import type { KnowledgeEdgeData, KnowledgeNodeData } from '../../../../features/knowledge-graph/types';

export const aiExpandedDatabaseNodes: KnowledgeNodeData[] = [
  {"id":"data-drift-ai","labelJa":"データドリフト","labelVi":"Data drift","labelEn":"Data Drift","category":"database","level":"topic","importance":"high","summaryVi":"Data drift là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"データドリフトはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: データドリフト dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：データドリフトの目的、具体例、似た概念との違い、注意点を問われます。","examples":["入力分布","変化"],"keywords":["入力分布","変化","データドリフト","Data Drift"],"prerequisites":["ai-monitoring"],"related":[]},
  {"id":"vector-database-ai","labelJa":"ベクトルデータベース","labelVi":"Vector database","labelEn":"Vector Database","category":"database","level":"topic","importance":"medium","summaryVi":"Vector database là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"ベクトルデータベースはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: ベクトルデータベース dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：ベクトルデータベースの目的、具体例、似た概念との違い、注意点を問われます。","examples":["ベクトル","検索"],"keywords":["ベクトル","検索","ベクトルデータベース","Vector Database"],"prerequisites":["rag"],"related":[]},
  {"id":"feature-engineering-ai","labelJa":"特徴量エンジニアリング","labelVi":"Feature engineering","labelEn":"Feature Engineering","category":"database","level":"topic","importance":"high","summaryVi":"Feature engineering là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"特徴量エンジニアリングはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 特徴量エンジニアリング dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：特徴量エンジニアリングの目的、具体例、似た概念との違い、注意点を問われます。","examples":["特徴量","変換"],"keywords":["特徴量","変換","特徴量エンジニアリング","Feature Engineering"],"prerequisites":["data-preprocessing-ai"],"related":[]},
  {"id":"normalization-ai-data","labelJa":"正規化","labelVi":"Chuẩn hóa dữ liệu","labelEn":"Normalization","category":"database","level":"topic","importance":"high","summaryVi":"Chuẩn hóa dữ liệu là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"正規化はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 正規化 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：正規化の目的、具体例、似た概念との違い、注意点を問われます。","examples":["スケール","正規化"],"keywords":["スケール","正規化","正規化","Normalization"],"prerequisites":["data-preprocessing-ai"],"related":[]},
  {"id":"missing-value-ai","labelJa":"欠損値処理","labelVi":"Xử lý thiếu dữ liệu","labelEn":"Missing Value Handling","category":"database","level":"topic","importance":"high","summaryVi":"Xử lý thiếu dữ liệu là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"欠損値処理はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 欠損値処理 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：欠損値処理の目的、具体例、似た概念との違い、注意点を問われます。","examples":["欠損","補完"],"keywords":["欠損","補完","欠損値処理","Missing Value Handling"],"prerequisites":["data-preprocessing-ai"],"related":[]},
  {"id":"label-encoding-ai","labelJa":"ラベルエンコーディング","labelVi":"Label encoding","labelEn":"Label Encoding","category":"database","level":"topic","importance":"medium","summaryVi":"Label encoding là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"ラベルエンコーディングはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: ラベルエンコーディング dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：ラベルエンコーディングの目的、具体例、似た概念との違い、注意点を問われます。","examples":["カテゴリ","数値化"],"keywords":["カテゴリ","数値化","ラベルエンコーディング","Label Encoding"],"prerequisites":["feature-engineering-ai"],"related":[]},
  {"id":"one-hot-ai","labelJa":"One-hotエンコーディング","labelVi":"One-hot encoding","labelEn":"One-hot Encoding","category":"database","level":"topic","importance":"medium","summaryVi":"One-hot encoding là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"One-hotエンコーディングはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: One-hotエンコーディング dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：One-hotエンコーディングの目的、具体例、似た概念との違い、注意点を問われます。","examples":["カテゴリ","ダミー変数"],"keywords":["カテゴリ","ダミー変数","One-hotエンコーディング","One-hot Encoding"],"prerequisites":["feature-engineering-ai"],"related":[]},
  {"id":"data-split-ai","labelJa":"データ分割","labelVi":"Chia dữ liệu","labelEn":"Data Split","category":"database","level":"topic","importance":"high","summaryVi":"Chia dữ liệu là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"データ分割はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: データ分割 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：データ分割の目的、具体例、似た概念との違い、注意点を問われます。","examples":["訓練","検証"],"keywords":["訓練","検証","テスト","データ分割","Data Split"],"prerequisites":["training-test-data"],"related":[]},
  {"id":"validation-data-ai","labelJa":"検証データ","labelVi":"Validation data","labelEn":"Validation Data","category":"database","level":"topic","importance":"high","summaryVi":"Validation data là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"検証データはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 検証データ dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：検証データの目的、具体例、似た概念との違い、注意点を問われます。","examples":["検証","チューニング"],"keywords":["検証","チューニング","検証データ","Validation Data"],"prerequisites":["training-test-data"],"related":[]},
  {"id":"test-data-leakage-ai","labelJa":"データリーク","labelVi":"Data leakage","labelEn":"Data Leakage","category":"database","level":"topic","importance":"high","summaryVi":"Data leakage là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"データリークはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: データリーク dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：データリークの目的、具体例、似た概念との違い、注意点を問われます。","examples":["リーク","評価"],"keywords":["リーク","評価","データリーク","Data Leakage"],"prerequisites":["training-test-data"],"related":[]},
];

export const aiExpandedDatabaseEdges: KnowledgeEdgeData[] = [
  {"id":"edge-rag-vector-database-ai","source":"rag","target":"vector-database-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-data-preprocessing-ai-feature-engineering-ai","source":"data-preprocessing-ai","target":"feature-engineering-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-data-preprocessing-ai-normalization-ai-data","source":"data-preprocessing-ai","target":"normalization-ai-data","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-data-preprocessing-ai-missing-value-ai","source":"data-preprocessing-ai","target":"missing-value-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-feature-engineering-ai-label-encoding-ai","source":"feature-engineering-ai","target":"label-encoding-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-feature-engineering-ai-one-hot-ai","source":"feature-engineering-ai","target":"one-hot-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-training-test-data-data-split-ai","source":"training-test-data","target":"data-split-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-training-test-data-validation-data-ai","source":"training-test-data","target":"validation-data-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-training-test-data-test-data-leakage-ai","source":"training-test-data","target":"test-data-leakage-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
];
