import type { KnowledgeEdgeData, KnowledgeNodeData } from '../../../../features/knowledge-graph/types';

export const aiExpandedManagementNodes: KnowledgeNodeData[] = [
  {"id":"ai-vendor-management","labelJa":"ベンダ管理","labelVi":"Quản lý vendor AI","labelEn":"Vendor Management","category":"management","level":"topic","importance":"medium","summaryVi":"Quản lý vendor AI là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"ベンダ管理はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: ベンダ管理 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：ベンダ管理の目的、具体例、似た概念との違い、注意点を問われます。","examples":["ベンダ","委託"],"keywords":["ベンダ","委託","ベンダ管理","Vendor Management"],"prerequisites":["ai-project-flow"],"related":[]},
  {"id":"ai-contract-ai","labelJa":"AI契約","labelVi":"Hợp đồng AI","labelEn":"AI Contract","category":"management","level":"topic","importance":"medium","summaryVi":"Hợp đồng AI là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"AI契約はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: AI契約 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：AI契約の目的、具体例、似た概念との違い、注意点を問われます。","examples":["契約","責任"],"keywords":["契約","責任","AI契約","AI Contract"],"prerequisites":["copyright-ai"],"related":[]},
  {"id":"ai-guideline-company","labelJa":"社内AI利用ルール","labelVi":"Quy định dùng AI nội bộ","labelEn":"Company AI Policy","category":"management","level":"topic","importance":"high","summaryVi":"Quy định dùng AI nội bộ là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"社内AI利用ルールはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 社内AI利用ルール dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：社内AI利用ルールの目的、具体例、似た概念との違い、注意点を問われます。","examples":["社内ルール","禁止事項"],"keywords":["社内ルール","禁止事項","社内AI利用ルール","Company AI Policy"],"prerequisites":["ai-governance"],"related":[]},
  {"id":"ai-literacy-training","labelJa":"AIリテラシー教育","labelVi":"Đào tạo AI literacy","labelEn":"AI Literacy Training","category":"management","level":"topic","importance":"medium","summaryVi":"Đào tạo AI literacy là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"AIリテラシー教育はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: AIリテラシー教育 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：AIリテラシー教育の目的、具体例、似た概念との違い、注意点を問われます。","examples":["教育","研修"],"keywords":["教育","研修","AIリテラシー教育","AI Literacy Training"],"prerequisites":["ai-literacy"],"related":[]},
  {"id":"ai-quality-assurance","labelJa":"AI品質保証","labelVi":"QA cho AI","labelEn":"AI Quality Assurance","category":"management","level":"topic","importance":"high","summaryVi":"QA cho AI là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"AI品質保証はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: AI品質保証 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：AI品質保証の目的、具体例、似た概念との違い、注意点を問われます。","examples":["品質","テスト"],"keywords":["品質","テスト","AI品質保証","AI Quality Assurance"],"prerequisites":["ai-project-flow"],"related":[]},
];

export const aiExpandedManagementEdges: KnowledgeEdgeData[] = [
  {"id":"edge-ai-project-flow-ai-vendor-management","source":"ai-project-flow","target":"ai-vendor-management","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-copyright-ai-ai-contract-ai","source":"copyright-ai","target":"ai-contract-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-ai-governance-ai-guideline-company","source":"ai-governance","target":"ai-guideline-company","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-ai-literacy-ai-literacy-training","source":"ai-literacy","target":"ai-literacy-training","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-ai-project-flow-ai-quality-assurance","source":"ai-project-flow","target":"ai-quality-assurance","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
];
