import type { KnowledgeEdgeData, KnowledgeNodeData } from '../../../../features/knowledge-graph/types';

export const aiExpandedTechnologyNodes: KnowledgeNodeData[] = [
  {"id":"gpu-ai","labelJa":"GPU","labelVi":"GPU","labelEn":"GPU","category":"technology","level":"topic","importance":"medium","summaryVi":"GPU là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"GPUはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: GPU dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：GPUの目的、具体例、似た概念との違い、注意点を問われます。","examples":["並列処理","高速化"],"keywords":["並列処理","高速化","GPU","GPU"],"prerequisites":["deep-learning-ai"],"related":[]},
  {"id":"cloud-gpu-ai","labelJa":"クラウドGPU","labelVi":"Cloud GPU","labelEn":"Cloud GPU","category":"technology","level":"topic","importance":"medium","summaryVi":"Cloud GPU là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"クラウドGPUはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: クラウドGPU dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：クラウドGPUの目的、具体例、似た概念との違い、注意点を問われます。","examples":["クラウド","GPU"],"keywords":["クラウド","GPU","クラウドGPU","Cloud GPU"],"prerequisites":["gpu-ai"],"related":[]},
  {"id":"edge-device-ai","labelJa":"エッジデバイス","labelVi":"Thiết bị edge","labelEn":"Edge Device","category":"technology","level":"topic","importance":"medium","summaryVi":"Thiết bị edge là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"エッジデバイスはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: エッジデバイス dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：エッジデバイスの目的、具体例、似た概念との違い、注意点を問われます。","examples":["端末","推論"],"keywords":["端末","推論","エッジデバイス","Edge Device"],"prerequisites":["edge-ai"],"related":[]},
  {"id":"on-device-ai","labelJa":"オンデバイスAI","labelVi":"AI trên thiết bị","labelEn":"On-device AI","category":"technology","level":"topic","importance":"medium","summaryVi":"AI trên thiết bị là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"オンデバイスAIはAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: オンデバイスAI dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：オンデバイスAIの目的、具体例、似た概念との違い、注意点を問われます。","examples":["端末内","プライバシー"],"keywords":["端末内","プライバシー","オンデバイスAI","On-device AI"],"prerequisites":["edge-ai"],"related":[]},
  {"id":"ai-energy-consumption","labelJa":"AIの電力消費","labelVi":"Điện năng AI","labelEn":"AI Energy Consumption","category":"technology","level":"topic","importance":"medium","summaryVi":"Điện năng AI là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"AIの電力消費はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: AIの電力消費 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：AIの電力消費の目的、具体例、似た概念との違い、注意点を問われます。","examples":["電力","CO2"],"keywords":["電力","CO2","AIの電力消費","AI Energy Consumption"],"prerequisites":["ai-risk-management"],"related":[]},
  {"id":"ai-environmental-impact","labelJa":"環境負荷","labelVi":"Tác động môi trường","labelEn":"Environmental Impact","category":"technology","level":"topic","importance":"medium","summaryVi":"Tác động môi trường là khái niệm cần nắm trong AI Passport. Hãy học theo ba điểm: định nghĩa, ví dụ thực tế và rủi ro khi áp dụng.","summaryJa":"環境負荷はAIパスポートで押さえるべき重要概念です。定義、具体例、利用時の注意点をセットで理解します。","examPointVi":"Hay hỏi: 環境負荷 dùng để làm gì, ví dụ đúng là gì, khác gì với khái niệm gần giống, và cần chú ý rủi ro nào.","examPointJa":"頻出ポイント：環境負荷の目的、具体例、似た概念との違い、注意点を問われます。","examples":["CO2","水資源"],"keywords":["CO2","水資源","環境負荷","Environmental Impact"],"prerequisites":["ai-energy-consumption"],"related":[]},
];

export const aiExpandedTechnologyEdges: KnowledgeEdgeData[] = [
  {"id":"edge-deep-learning-ai-gpu-ai","source":"deep-learning-ai","target":"gpu-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-gpu-ai-cloud-gpu-ai","source":"gpu-ai","target":"cloud-gpu-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-edge-ai-edge-device-ai","source":"edge-ai","target":"edge-device-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-edge-ai-on-device-ai","source":"edge-ai","target":"on-device-ai","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-ai-risk-management-ai-energy-consumption","source":"ai-risk-management","target":"ai-energy-consumption","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
  {"id":"edge-ai-energy-consumption-ai-environmental-impact","source":"ai-energy-consumption","target":"ai-environmental-impact","relation":"related_to","labelVi":"liên quan","labelJa":"関連"},
];
