import type { KnowledgeNodeData } from '../features/knowledge-graph/types';
import type { CourseId } from './types';
import { v105ManualChapters, type V105ChapterGroup, type V105ManualChapter } from './v105ManualChapterPack';

export const v106ManualChapterExtensions: V105ManualChapter[] = [
  {
    id: 'v106-python-file-pathlib',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['file', 'pathlib', 'json', 'csv', 'read', 'write', 'with open', 'filesystem'],
    titleVi: 'Python File Handling: đọc ghi file bằng pathlib và context manager',
    subtitleVi: 'Học file không phải chỉ là open(). Mục tiêu là biết dữ liệu nằm ở đâu, đọc kiểu gì, xử lý lỗi ra sao và không làm hỏng file gốc.',
    whyItMattersVi: 'Trong project thật, dữ liệu thường đến từ file CSV, JSON, log hoặc config. Nếu không hiểu đường dẫn, encoding, context manager và kiểm tra lỗi, chương trình chạy được ở máy bạn nhưng hỏng khi đưa cho người khác.',
    conceptVi: ['Pathlib giúp làm việc với đường dẫn như object thay vì nối chuỗi bằng dấu /. Điều này giảm lỗi khác nhau giữa Windows, macOS và Linux.', 'Context manager with ... as ... đảm bảo file được đóng đúng cách dù code bên trong có lỗi.', 'Khi đọc file text, hãy nghĩ tới encoding. Với tiếng Việt hoặc tiếng Nhật, utf-8 thường là lựa chọn an toàn.', 'Không nên ghi đè file gốc ngay lập tức. Hãy parse, validate, rồi mới ghi ra file mới hoặc backup.'],
    storyVi: 'Ví dụ đời thường: bạn nhận một bảng chi tiêu từ bạn bè. Trước khi sửa file gốc, bạn photo ra bản nháp, kiểm tra từng dòng, rồi mới tổng hợp kết quả.',
    deepExampleTitleVi: 'Ví dụ viết tay: đọc JSON config và tạo output an toàn',
    deepExampleBody: 'from pathlib import Path\nimport json\n\nconfig_path = Path("config.json")\n\nif not config_path.exists():\n    raise FileNotFoundError("config.json is missing")\n\nraw_text = config_path.read_text(encoding="utf-8")\nconfig = json.loads(raw_text)\n\napp_name = config.get("app_name", "Local App")\nmax_items = int(config.get("max_items", 10))\n\nsummary = f"{app_name}: max_items={max_items}"\nPath("summary.txt").write_text(summary, encoding="utf-8")\nprint(summary)',
    walkthroughVi: ['Tạo Path object để mô tả file config.json, chưa đọc file ngay.', 'exists() kiểm tra file có thật không. Nếu thiếu, báo lỗi rõ thay vì lỗi mơ hồ ở bước sau.', 'read_text(encoding="utf-8") đọc toàn bộ text, phù hợp config nhỏ.', 'json.loads đổi text JSON thành dict Python.', 'get dùng default để app không crash khi thiếu key không quá quan trọng.', 'write_text ghi summary ra file mới, không phá config gốc.'],
    exerciseVi: 'Tạo file data.json gồm {"name":"Long","level":3}. Viết code đọc file và in ra Name: Long, Level: 3.',
    expectedOutputVi: 'Name: Long\nLevel: 3',
    miniQuizVi: 'Vì sao nên dùng pathlib thay vì tự nối path bằng chuỗi?',
    miniQuizAnswerVi: 'Vì pathlib hiểu đường dẫn theo hệ điều hành, code dễ đọc hơn và giảm lỗi separator như / hoặc \\.',
    mistakesVi: ['Ghi đè file gốc khi chưa validate dữ liệu.', 'Quên encoding khiến tiếng Việt/Nhật bị lỗi ký tự.', 'Bắt mọi exception rồi im lặng làm mất nguyên nhân thật.'],
    studyChecklistVi: ['Dùng Path để tạo đường dẫn.', 'Đọc JSON bằng json.loads hoặc json.load.', 'Biết khi nào cần kiểm tra file tồn tại.', 'Không ghi đè dữ liệu gốc khi chưa chắc logic đúng.'],
  },
  {
    id: 'v106-python-error-exception',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['exception', 'error', 'raise', 'try', 'except', 'traceback', 'validation'],
    titleVi: 'Python Error Handling: lỗi là tín hiệu để bảo vệ logic, không phải thứ cần che giấu',
    subtitleVi: 'Mục tiêu là biết lỗi nào nên chặn, lỗi nào nên cho fail rõ, và viết message đủ dễ hiểu để debug.',
    whyItMattersVi: 'Backend, CLI và code lab đều cần xử lý input xấu. Nếu chỉ dùng try/except chung chung, bạn sẽ che mất lỗi thật và rất khó sửa bug.',
    conceptVi: ['Exception cho biết chương trình gặp trạng thái không hợp lệ. Nó tốt hơn trả về None mơ hồ nếu lỗi cần được xử lý ngay.', 'raise dùng khi bạn phát hiện dữ liệu sai và muốn dừng logic trước khi state bị hỏng.', 'try/except nên đặt ở boundary: nơi nhận input từ user, file, API. Không nên bọc toàn bộ chương trình bằng except Exception rồi bỏ qua.', 'Message lỗi nên nói điều kiện nào sai, ví dụ amount must be positive, thay vì chỉ ghi error.'],
    storyVi: 'Ví dụ đời thường: nếu thẻ ATM nhập số tiền âm, máy không tự đoán ý bạn. Nó dừng giao dịch và báo lý do rõ ràng.',
    deepExampleTitleVi: 'Ví dụ viết tay: validate amount trước khi cộng tiền',
    deepExampleBody: 'def add_balance(balance: int, amount: int) -> int:\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    return balance + amount\n\ntry:\n    new_balance = add_balance(1000, -200)\n    print(new_balance)\nexcept ValueError as error:\n    print(f"Invalid input: {error}")',
    walkthroughVi: ['Function add_balance có contract: amount phải dương.', 'Nếu amount <= 0, raise ValueError để dừng sớm.', 'try nằm ở nơi gọi function, vì đây là boundary có thể hiển thị lỗi cho user.', 'except ValueError chỉ bắt lỗi mình dự đoán, không nuốt mọi lỗi khác.', 'Output giải thích input sai, không làm balance bị đổi sai.'],
    exerciseVi: 'Viết hàm parse_age(text). Nếu text không phải số nguyên hoặc nhỏ hơn 0 thì raise ValueError với message dễ hiểu.',
    expectedOutputVi: 'parse_age("20") -> 20\nparse_age("abc") -> ValueError: age must be a number',
    miniQuizVi: 'Vì sao không nên viết except Exception: pass?',
    miniQuizAnswerVi: 'Vì nó nuốt lỗi thật, chương trình có thể tiếp tục với dữ liệu sai và làm bug khó tìm hơn.',
    mistakesVi: ['Dùng exception cho flow bình thường quá nhiều.', 'Bắt lỗi quá rộng và không log.', 'Message lỗi không nói rõ input nào sai.'],
    studyChecklistVi: ['Biết raise ValueError khi input sai.', 'Biết đặt try/except ở boundary.', 'Không nuốt exception im lặng.', 'Viết message lỗi có ý nghĩa.'],
  },
  {
    id: 'v106-python-testing-pytest',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['pytest', 'test', 'fixture', 'tmp_path', 'assert', 'unit test'],
    titleVi: 'Python Testing: test là cách mô tả hành vi đúng bằng ví dụ chạy được',
    subtitleVi: 'Học pytest để biến expected output thành kiểm chứng tự động, thay vì chỉ nhìn bằng mắt.',
    whyItMattersVi: 'Khi project nhiều file và function, bạn không thể bấm thử từng case thủ công. Test giúp đảm bảo sửa code hôm nay không làm hỏng chức năng hôm qua.',
    conceptVi: ['Một test tốt gồm input, hành động và expected result rõ ràng.', 'assert là câu nói: tôi kỳ vọng điều này đúng. Nếu sai, pytest chỉ ra case bị fail.', 'Fixture giúp chuẩn bị dữ liệu dùng lại, ví dụ file tạm bằng tmp_path.', 'Test nên bao gồm happy path và edge case: dữ liệu rỗng, số 0, input sai, duplicate.'],
    storyVi: 'Ví dụ đời thường: công thức nấu ăn không chỉ ghi nguyên liệu, mà còn có tiêu chí món đạt: bánh chín, không cháy, vị đúng.',
    deepExampleTitleVi: 'Ví dụ viết tay: test hàm đếm item',
    deepExampleBody: 'def count_items(items):\n    result = {}\n    for item in items:\n        result[item] = result.get(item, 0) + 1\n    return result\n\n\ndef test_count_items_normal():\n    assert count_items(["pen", "book", "pen"]) == {"pen": 2, "book": 1}\n\n\ndef test_count_items_empty():\n    assert count_items([]) == {}',
    walkthroughVi: ['Hàm count_items không print mà return dict, nên dễ test.', 'Test normal kiểm tra case có duplicate.', 'Test empty kiểm tra input rỗng không crash.', 'Nếu sửa nhầm logic, assert sẽ fail và chỉ ra expected khác actual.', 'Tên test nên nói hành vi đang kiểm tra.'],
    exerciseVi: 'Viết test cho hàm total(numbers) với case [1,2,3], [], và [-1,1].',
    expectedOutputVi: '3 tests pass: total([1,2,3]) == 6, total([]) == 0, total([-1,1]) == 0',
    miniQuizVi: 'Vì sao function nên return thay vì chỉ print nếu muốn test tốt?',
    miniQuizAnswerVi: 'Vì return cho test so sánh giá trị trực tiếp; print chỉ là hiển thị và khó kiểm chứng tự động.',
    mistakesVi: ['Chỉ test một case đẹp.', 'Test phụ thuộc thứ tự ngẫu nhiên không cần thiết.', 'Viết test sau khi code lỗi nhưng không mô tả expected rõ.'],
    studyChecklistVi: ['Viết được assert đơn giản.', 'Biết test edge case rỗng.', 'Biết dùng tmp_path cho file test.', 'Biết tên test mô tả hành vi.'],
  },
  {
    id: 'v106-python-logging',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['logging', 'log', 'debug', 'info', 'warning', 'error'],
    titleVi: 'Python Logging: log là nhật ký giúp hiểu chương trình đã đi qua đâu',
    subtitleVi: 'Mục tiêu là biết dùng logging thay vì print lung tung, đặc biệt ở boundary như file, API và job batch.',
    whyItMattersVi: 'Print phù hợp học nhanh, nhưng project thật cần level, timestamp và message có ngữ cảnh. Logging giúp debug lỗi production mà không phải đoán.',
    conceptVi: ['DEBUG dùng cho chi tiết khi phát triển, INFO cho sự kiện bình thường, WARNING cho điều bất thường nhưng chưa hỏng, ERROR cho lỗi cần chú ý.', 'Log nên đặt ở boundary: bắt đầu job, đọc file, gọi API, validate fail, ghi output.', 'Không log dữ liệu nhạy cảm như password, token, thông tin cá nhân.', 'Message log tốt có action và context, ví dụ failed to parse row 17, không chỉ ghi fail.'],
    storyVi: 'Ví dụ đời thường: log giống camera hành trình. Khi có sự cố, bạn xem lại thời điểm, vị trí và hành động trước đó.',
    deepExampleTitleVi: 'Ví dụ viết tay: log khi parse từng dòng CSV',
    deepExampleBody: 'import logging\n\nlogging.basicConfig(level=logging.INFO)\nlogger = logging.getLogger(__name__)\n\ndef parse_score(text: str) -> int:\n    logger.debug("parse_score input=%s", text)\n    try:\n        score = int(text)\n    except ValueError:\n        logger.warning("invalid score text=%s", text)\n        return 0\n    logger.info("parsed score=%s", score)\n    return score\n\nprint(parse_score("80"))\nprint(parse_score("abc"))',
    walkthroughVi: ['basicConfig đặt level tối thiểu để hiển thị log.', 'parse_score log debug input nhưng debug không hiện nếu level INFO.', 'int("abc") gây ValueError nên warning xuất hiện.', 'Function chọn trả 0 cho input lỗi theo policy đã định.', 'Log giúp biết vì sao output là 0.'],
    exerciseVi: 'Thêm logging cho hàm đọc file: log INFO khi bắt đầu đọc, WARNING khi file rỗng, ERROR khi thiếu file.',
    expectedOutputVi: 'INFO reading file data.csv\nWARNING empty file data.csv\nERROR missing file data.csv',
    miniQuizVi: 'Khi nào dùng WARNING thay vì ERROR?',
    miniQuizAnswerVi: 'WARNING khi có dấu hiệu bất thường nhưng chương trình vẫn xử lý được; ERROR khi thao tác chính thất bại hoặc cần can thiệp.',
    mistakesVi: ['Log quá nhiều dữ liệu nhạy cảm.', 'Dùng print trong service layer rồi quên xóa.', 'Message log không có context nên không debug được.'],
    studyChecklistVi: ['Phân biệt DEBUG/INFO/WARNING/ERROR.', 'Đặt log ở boundary.', 'Không log password/token.', 'Viết message có context.'],
  },
  {
    id: 'v106-python-fastapi-di',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['dependency', 'depends', 'service', 'repository', 'fastapi testing', 'dependency injection'],
    titleVi: 'FastAPI Dependency Injection: tách route khỏi service để dễ test và dễ thay đổi',
    subtitleVi: 'Mục tiêu là hiểu Depends không phải cú pháp lạ, mà là cách đưa dependency vào route một cách có kiểm soát.',
    whyItMattersVi: 'Nếu route vừa validate, vừa xử lý logic, vừa truy cập database, code sẽ khó test. Dependency injection giúp thay service thật bằng fake service trong test.',
    conceptVi: ['Route nên mỏng: nhận request, gọi service, trả response.', 'Service chứa logic nghiệp vụ, ví dụ tạo todo, tính grade, kiểm tra quyền.', 'Depends cung cấp service cho route. Trong test, có thể override dependency để không cần database thật.', 'Thiết kế local-only tốt vẫn nên theo pattern này để sau này chuyển thành backend thật không phải viết lại từ đầu.'],
    storyVi: 'Ví dụ đời thường: quầy lễ tân không tự sửa máy lạnh. Họ nhận yêu cầu, gọi bộ phận kỹ thuật, rồi trả kết quả cho khách.',
    deepExampleTitleVi: 'Ví dụ viết tay: route mỏng gọi service',
    deepExampleBody: 'from fastapi import Depends, FastAPI\n\napp = FastAPI()\n\nclass TodoService:\n    def create(self, title: str) -> dict:\n        return {"id": 1, "title": title, "done": False}\n\ndef get_todo_service():\n    return TodoService()\n\n@app.post("/todos")\ndef create_todo(title: str, service: TodoService = Depends(get_todo_service)):\n    return service.create(title)',
    walkthroughVi: ['TodoService chứa logic tạo todo.', 'get_todo_service là provider dependency.', 'Route nhận title và service từ Depends.', 'Route không biết service lưu ở memory hay database.', 'Test có thể thay get_todo_service bằng fake service.'],
    exerciseVi: 'Viết service GradeService có method grade(score), rồi route /grade gọi service đó qua Depends.',
    expectedOutputVi: 'POST /grade?score=80 -> {"grade":"A","passed":true}',
    miniQuizVi: 'Lợi ích lớn nhất của dependency injection trong test là gì?',
    miniQuizAnswerVi: 'Có thể thay dependency thật bằng fake/mock, nên test route không phụ thuộc database hoặc API ngoài.',
    mistakesVi: ['Để route chứa toàn bộ logic.', 'Tạo database connection trực tiếp trong từng route.', 'Không biết cách override dependency khi test.'],
    studyChecklistVi: ['Tách route và service.', 'Biết Depends cung cấp dependency.', 'Biết fake service cho test.', 'Giữ route mỏng và dễ đọc.'],
  },
  {
    id: 'v106-python-fastapi-schema',
    courseId: 'python',
    group: 'python-foundation' as V105ChapterGroup,
    match: ['fastapi', 'pydantic', 'schema', 'request', 'response', 'validation', 'api'],
    titleVi: 'FastAPI Schema: request và response contract giúp API dễ test và ít mơ hồ',
    subtitleVi: 'Mục tiêu là hiểu API không chỉ là route, mà là hợp đồng dữ liệu giữa client và server.',
    whyItMattersVi: 'Khi API nhận dữ liệu thiếu field hoặc sai kiểu, nếu không có schema rõ ràng, bug sẽ chạy sâu vào service và khó debug. FastAPI + Pydantic giúp chặn lỗi ngay ở cửa vào.',
    conceptVi: ['Request schema mô tả client được gửi gì. Response schema mô tả server trả gì.', 'Validation nên xảy ra trước khi logic nghiệp vụ chạy. Dữ liệu sai không nên đi vào service layer.', 'HTTP status code phải nói đúng ý nghĩa: 200 thành công, 404 không tìm thấy, 422 input sai, 500 lỗi server.', 'API tốt cần ví dụ request/response để người khác dùng không phải đoán.'],
    storyVi: 'Ví dụ đời thường: gọi món ở nhà hàng phải theo menu. Nếu bạn gọi món không có trong menu, nhân viên báo ngay thay vì đưa yêu cầu sai vào bếp.',
    deepExampleTitleVi: 'Ví dụ viết tay: grade endpoint có schema rõ',
    deepExampleBody: 'from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\napp = FastAPI()\n\nclass GradeRequest(BaseModel):\n    score: int = Field(ge=0, le=100)\n\nclass GradeResponse(BaseModel):\n    grade: str\n    passed: bool\n\n@app.post("/grade", response_model=GradeResponse)\ndef grade(payload: GradeRequest):\n    if payload.score >= 70:\n        return GradeResponse(grade="A", passed=True)\n    return GradeResponse(grade="Retry", passed=False)',
    walkthroughVi: ['Client gửi JSON có score.', 'Field(ge=0, le=100) chặn score âm hoặc quá 100 trước khi vào function.', 'Function chỉ xử lý dữ liệu đã hợp lệ.', 'response_model giúp output luôn có grade và passed.', 'Test API có thể kiểm tra cả status code lẫn response body.'],
    exerciseVi: 'Thiết kế endpoint POST /todos nhận title string không rỗng và trả về id, title, done=false.',
    expectedOutputVi: 'Request: {"title":"learn FastAPI"}\nResponse: {"id":1,"title":"learn FastAPI","done":false}',
    miniQuizVi: 'Vì sao schema giúp giảm bug?',
    miniQuizAnswerVi: 'Vì nó chặn dữ liệu sai ở boundary và làm contract request/response rõ ràng cho cả client lẫn test.',
    mistakesVi: ['Không validate input rồi service phải xử lý quá nhiều case bẩn.', 'Trả response tùy tiện lúc có field, lúc thiếu field.', 'Dùng status code 200 cho cả lỗi.'],
    studyChecklistVi: ['Viết được request model.', 'Viết được response model.', 'Biết dùng status code đúng.', 'Có ví dụ request/response rõ.'],
  },
  {
    id: 'v106-python-typing-dataclass',
    courseId: 'python',
    group: 'python-oop' as V105ChapterGroup,
    match: ['typing', 'type hint', 'dataclass', 'typedDict', 'model', '__post_init__'],
    titleVi: 'Python Typing + Dataclass: làm dữ liệu rõ nghĩa trước khi logic phức tạp',
    subtitleVi: 'Mục tiêu là dùng type hint và dataclass để người đọc hiểu object có field gì, rule gì, và lỗi có thể xuất hiện ở đâu.',
    whyItMattersVi: 'Trong project lớn, dict trôi nổi làm code khó đọc: không biết key nào bắt buộc, value kiểu gì. Dataclass giúp gom dữ liệu thành object có tên và có thể kiểm tra invariant.',
    conceptVi: ['Type hint không làm Python thành ngôn ngữ compile cứng, nhưng giúp IDE, test và người đọc phát hiện sai sớm.', 'Dataclass giảm boilerplate khi tạo object chỉ chứa data nhưng vẫn cho phép thêm validation trong __post_init__.', 'TypedDict phù hợp khi dữ liệu vẫn là dict JSON nhưng muốn mô tả key rõ hơn.', 'Tên type tốt là tài liệu sống cho code.'],
    storyVi: 'Ví dụ đời thường: form đăng ký có tên trường rõ ràng. Nếu chỉ đưa túi giấy chứa giấy tờ lộn xộn, người xử lý sẽ không biết thiếu gì.',
    deepExampleTitleVi: 'Ví dụ viết tay: dataclass giữ rule score 0..100',
    deepExampleBody: 'from dataclasses import dataclass\n\n@dataclass\nclass StudentScore:\n    name: str\n    score: int\n\n    def __post_init__(self):\n        if not 0 <= self.score <= 100:\n            raise ValueError("score must be 0..100")\n\n    @property\n    def passed(self) -> bool:\n        return self.score >= 70\n\nitem = StudentScore("Long", 82)\nprint(item.name, item.passed)',
    walkthroughVi: ['@dataclass tự tạo __init__ dễ đọc.', 'name và score có type hint để người đọc hiểu field.', '__post_init__ chạy sau khi object được tạo để kiểm tra rule.', 'passed là property tính từ score, không cần lưu trùng state.', 'Nếu score=120, object bị chặn ngay.'],
    exerciseVi: 'Tạo dataclass Product(name, price). Kiểm tra price không âm và property tax_included = price * 1.1.',
    expectedOutputVi: 'Product("book", 1000).tax_included -> 1100.0',
    miniQuizVi: 'Vì sao không nên lưu passed như field riêng nếu nó tính được từ score?',
    miniQuizAnswerVi: 'Vì state trùng dễ lệch. Nếu score đổi mà passed không đổi theo, object bị mâu thuẫn.',
    mistakesVi: ['Dùng Any cho mọi thứ làm mất lợi ích type hint.', 'Lưu state có thể tính được dẫn tới lệch dữ liệu.', 'Quên validation trong dataclass có invariant.'],
    studyChecklistVi: ['Biết viết dataclass.', 'Biết dùng __post_init__.', 'Biết khi nào dùng property.', 'Không lạm dụng dict trôi nổi.'],
  },
  {
    id: 'v106-python-algo-sliding-prefix',
    courseId: 'python',
    group: 'python-algorithm' as V105ChapterGroup,
    match: ['sliding', 'window', 'prefix', 'two pointers', 'array', 'sum', 'algorithm'],
    titleVi: 'Python Algorithm: sliding window và prefix sum giúp tránh loop lồng nhau',
    subtitleVi: 'Mục tiêu là nhận ra bài nào có thể dùng tổng tích lũy hoặc cửa sổ trượt để giảm O(n²) xuống O(n).',
    whyItMattersVi: 'Trong phỏng vấn và code lab, nhiều bài list không khó ở cú pháp mà khó ở cách tránh duyệt lại dữ liệu quá nhiều lần.',
    conceptVi: ['Prefix sum lưu tổng từ đầu đến vị trí i, giúp tính tổng đoạn nhanh.', 'Sliding window giữ một đoạn liên tục và cập nhật khi cửa sổ dịch sang phải.', 'Two pointers dùng hai chỉ số để quản lý biên trái/phải thay vì tạo list con liên tục.', 'Trace biến left, right, current_sum quan trọng hơn nhớ công thức.'],
    storyVi: 'Ví dụ đời thường: khi tính tổng tiền 3 ngày liên tiếp, bạn không cần cộng lại từ đầu mỗi lần; bỏ ngày cũ ra và thêm ngày mới vào.',
    deepExampleTitleVi: 'Ví dụ viết tay: max sum của 3 phần tử liên tiếp',
    deepExampleBody: 'numbers = [2, 1, 5, 1, 3, 2]\nk = 3\n\ncurrent = sum(numbers[:k])\nbest = current\n\nfor right in range(k, len(numbers)):\n    left = right - k\n    current = current - numbers[left] + numbers[right]\n    best = max(best, current)\n\nprint(best)',
    walkthroughVi: ['current ban đầu là tổng [2,1,5] = 8.', 'right=3: bỏ numbers[0]=2, thêm numbers[3]=1, current=7.', 'right=4: bỏ 1, thêm 3, current=9, best=9.', 'right=5: bỏ 5, thêm 2, current=6.', 'Output best=9 vì đoạn [5,1,3] lớn nhất.'],
    exerciseVi: 'Viết hàm max_pair_sum(numbers) tìm tổng lớn nhất của 2 phần tử liên tiếp bằng sliding window.',
    expectedOutputVi: 'max_pair_sum([4,1,7,2]) -> 9',
    miniQuizVi: 'Sliding window áp dụng cho loại đoạn nào?',
    miniQuizAnswerVi: 'Thường áp dụng cho đoạn liên tiếp trong list/string, nơi cửa sổ có thể dịch từng bước.',
    mistakesVi: ['Tạo slice mới trong loop khiến tốn chi phí.', 'Quên cập nhật best sau khi current đổi.', 'Nhầm left = right - k + 1 trong công thức bỏ phần tử.'],
    studyChecklistVi: ['Trace được left/right/current.', 'Biết khi nào dùng prefix sum.', 'Biết window cho đoạn liên tiếp.', 'Giảm được loop lồng nhau không cần thiết.'],
  },
  {
    id: 'v106-python-algo-dp',
    courseId: 'python',
    group: 'python-algorithm' as V105ChapterGroup,
    match: ['dp', 'dynamic programming', 'recursion', 'memo', 'table', 'minimum cost'],
    titleVi: 'Python Algorithm: Dynamic Programming là nhớ kết quả con để không tính lại',
    subtitleVi: 'Mục tiêu là hiểu DP bằng bảng trạng thái, không học thuộc công thức.',
    whyItMattersVi: 'DP xuất hiện trong 科目B nâng cao và phỏng vấn. Người mới thường sợ DP vì nhìn công thức, nhưng thực chất DP là hỏi: bài lớn được ghép từ bài nhỏ nào?',
    conceptVi: ['State là ý nghĩa của một ô trong bảng, ví dụ dp[i] là chi phí nhỏ nhất để tới bậc i.', 'Transition là cách tính state mới từ state cũ.', 'Base case là điểm bắt đầu không cần tính thêm.', 'Trace bảng từng dòng giúp phát hiện sai index.'],
    storyVi: 'Ví dụ đời thường: muốn biết đường rẻ nhất tới ga số 5, bạn có thể dùng kết quả rẻ nhất tới ga 3 và 4 thay vì thử lại mọi tuyến từ đầu.',
    deepExampleTitleVi: 'Ví dụ viết tay: climb stairs số cách leo cầu thang',
    deepExampleBody: 'n = 5\ndp = [0] * (n + 1)\ndp[0] = 1\ndp[1] = 1\n\nfor i in range(2, n + 1):\n    dp[i] = dp[i - 1] + dp[i - 2]\n\nprint(dp)\nprint(dp[n])',
    walkthroughVi: ['dp[0]=1 nghĩa là có một cách đứng ở điểm xuất phát.', 'dp[1]=1 nghĩa là có một cách lên bậc 1.', 'dp[2]=dp[1]+dp[0]=2 vì có thể từ bậc 1 lên 1 bước hoặc từ bậc 0 lên 2 bước.', 'Tiếp tục điền bảng tới dp[5].', 'Output dp[5]=8.'],
    exerciseVi: 'Viết DP tính số cách leo n=4 nếu mỗi lần leo 1 hoặc 2 bậc.',
    expectedOutputVi: 'dp = [1, 1, 2, 3, 5]\nanswer = 5',
    miniQuizVi: 'Trong DP, state quan trọng nhất cần viết rõ là gì?',
    miniQuizAnswerVi: 'Ý nghĩa của dp[i]. Nếu không biết dp[i] nghĩa là gì, công thức chỉ là học vẹt.',
    mistakesVi: ['Học công thức nhưng không biết state.', 'Sai base case.', 'Sai index khi truy cập i-1 hoặc i-2.'],
    studyChecklistVi: ['Định nghĩa được dp[i].', 'Viết được base case.', 'Trace bảng nhỏ bằng tay.', 'Giải thích được transition.'],
  },
  {
    id: 'v106-fe-dp-table',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['dp', 'dynamic programming', 'table', '科目b', 'minimum', 'cost'],
    titleVi: '基本情報 科目B: DP table không đáng sợ nếu định nghĩa rõ từng ô',
    subtitleVi: 'Mục tiêu là đọc DP như điền bảng, không đoán công thức.',
    whyItMattersVi: '科目B có thể ra pseudo-code về bảng DP. Nếu không biết state và transition, bạn sẽ bị rối bởi vòng lặp và index.',
    conceptVi: ['Trước khi trace, hãy viết câu: T[i] nghĩa là gì.', 'Base case thường là giá trị ban đầu trước vòng lặp.', 'Transition là dòng cập nhật T[i] từ các ô trước đó.', 'Khi đề hỏi kết quả cuối, thường cần xem ô cuối bảng sau tất cả update.'],
    storyVi: 'Ví dụ đời thường: tìm chi phí rẻ nhất tới từng trạm. Muốn tới trạm i, bạn chỉ cần biết chi phí rẻ nhất tới các trạm gần trước đó.',
    deepExampleTitleVi: 'Pseudo-code viết tay: min cost climb',
    deepExampleBody: 'cost = [10, 15, 20]\ndp[0] = 0\ndp[1] = 0\nfor i = 2 to 3\n  dp[i] = min(dp[i-1] + cost[i-1], dp[i-2] + cost[i-2])\nendfor\nprint dp[3]',
    walkthroughVi: ['dp[0]=0 và dp[1]=0 là base vì có thể bắt đầu ở bậc 0 hoặc 1.', 'i=2: min(dp1+cost1=15, dp0+cost0=10) => 10.', 'i=3: min(dp2+cost2=30, dp1+cost1=15) => 15.', 'Kết quả dp[3]=15.', 'Nếu nhầm index cost 0-based/1-based sẽ ra đáp án sai.'],
    exerciseVi: 'Trace cost=[1,100,1,1] và tính dp[4].',
    expectedOutputVi: 'dp[4] = 2',
    miniQuizVi: 'Tại sao phải viết ý nghĩa dp[i] trước khi tính?',
    miniQuizAnswerVi: 'Vì nếu không biết dp[i] đại diện cho gì, bạn không thể kiểm tra transition đúng hay sai.',
    mistakesVi: ['Nhầm index mảng cost.', 'Quên base case.', 'Chọn min/max sai theo yêu cầu đề.'],
    studyChecklistVi: ['Viết được ý nghĩa state.', 'Trace được bảng nhỏ.', 'Kiểm tra index trước khi chọn đáp án.', 'Không đoán công thức.'],
  },
  {
    id: 'v106-fe-sql-join',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['sql', 'join', 'left join', 'inner join', 'where', 'group by'],
    titleVi: '基本情報 SQL: JOIN phải đọc theo bảng gốc, điều kiện nối và điều kiện lọc',
    subtitleVi: 'Mục tiêu là không còn nhầm LEFT JOIN với INNER JOIN, và biết WHERE có thể làm mất hàng NULL.',
    whyItMattersVi: 'FE hay hỏi SQL bằng bảng nhỏ. Nhiều bạn biết cú pháp nhưng sai vì không vẽ kết quả trung gian sau JOIN.',
    conceptVi: ['INNER JOIN chỉ giữ dòng nối được ở cả hai bảng.', 'LEFT JOIN giữ toàn bộ bảng bên trái, nếu không có dòng bên phải thì cột bên phải là NULL.', 'WHERE chạy sau JOIN nên điều kiện trên bảng phải có thể loại mất dòng NULL.', 'GROUP BY gom dòng sau khi JOIN/WHERE đã xử lý.'],
    storyVi: 'Ví dụ đời thường: danh sách nhân viên là bảng trái. LEFT JOIN đơn nghỉ phép giúp vẫn thấy nhân viên chưa có đơn nào.',
    deepExampleTitleVi: 'SQL viết tay: hiện cả nhân viên chưa có request',
    deepExampleBody: 'SELECT e.name, COUNT(r.id) AS request_count\nFROM employee e\nLEFT JOIN request r ON e.id = r.employee_id\nGROUP BY e.name;',
    walkthroughVi: ['FROM employee tạo tập nhân viên gốc.', 'LEFT JOIN request giữ cả nhân viên không có request.', 'COUNT(r.id) không đếm NULL nên người không có request ra 0.', 'GROUP BY e.name gom theo từng nhân viên.', 'Nếu thêm WHERE r.status = "open", nhân viên không có request có thể biến mất.'],
    exerciseVi: 'Có bảng student và score. Viết SQL để hiện cả student chưa có score với score_count = 0.',
    expectedOutputVi: 'SELECT s.name, COUNT(sc.id) FROM student s LEFT JOIN score sc ON s.id=sc.student_id GROUP BY s.name;',
    miniQuizVi: 'Vì sao WHERE r.id IS NOT NULL làm LEFT JOIN giống INNER JOIN hơn?',
    miniQuizAnswerVi: 'Vì nó loại các dòng bên phải NULL, tức là loại các bản ghi không nối được.',
    mistakesVi: ['Không vẽ kết quả sau JOIN.', 'Dùng WHERE trên bảng phải làm mất dòng NULL.', 'COUNT(*) và COUNT(right.id) bị nhầm.'],
    studyChecklistVi: ['Phân biệt INNER/LEFT JOIN.', 'Biết thứ tự FROM/JOIN/WHERE/GROUP.', 'Biết COUNT(NULL) không được tính.', 'Trace SQL bằng bảng nhỏ.'],
  },
  {
    id: 'v106-fe-network-subnet',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['subnet', 'cidr', 'network', 'ip', 'host', '/24', '/27'],
    titleVi: '基本情報 Network: subnet là chia địa chỉ bằng số bit, không phải học mẹo rời rạc',
    subtitleVi: 'Mục tiêu là hiểu prefix /27 nghĩa là còn bao nhiêu bit host và vì sao phải trừ network/broadcast.',
    whyItMattersVi: 'Subnet là chủ đề dễ mất điểm vì chỉ cần nhầm một bit là host count sai. FE thường hỏi số host usable hoặc network range.',
    conceptVi: ['IPv4 có 32 bit. Prefix /27 nghĩa là 27 bit dành cho network, còn 5 bit cho host.', 'Số địa chỉ trong subnet là 2^host_bits.', 'Usable host thường trừ 2: network address và broadcast address.', 'Block size giúp tìm range: /27 có 32 địa chỉ mỗi block.'],
    storyVi: 'Ví dụ đời thường: một tòa nhà có nhiều tầng. Prefix là phần xác định tòa/tầng, host bits là số phòng trong tầng đó.',
    deepExampleTitleVi: 'Trace viết tay: /27 host count',
    deepExampleBody: 'prefix = 27\nhost_bits = 32 - prefix\naddresses = 2 ** host_bits\nusable = addresses - 2\nprint(usable)',
    walkthroughVi: ['host_bits = 5.', 'addresses = 2^5 = 32.', 'Trừ network address và broadcast address.', 'usable = 30.', 'Nếu đề hỏi tổng địa chỉ, đáp án là 32; nếu hỏi usable host, đáp án là 30.'],
    exerciseVi: 'Tính usable host của /26 và /28.',
    expectedOutputVi: '/26 -> 62 usable\n/28 -> 14 usable',
    miniQuizVi: 'Vì sao /27 không phải 27 host?',
    miniQuizAnswerVi: 'Vì 27 là số bit network, không phải số host. Host bits là 32 - 27 = 5.',
    mistakesVi: ['Nhầm prefix với số host.', 'Quên trừ 2 khi hỏi usable.', 'Không phân biệt total addresses và usable hosts.'],
    studyChecklistVi: ['Tính được host_bits.', 'Tính được 2^host_bits.', 'Biết khi nào trừ 2.', 'Không nhầm prefix với host count.'],
  },
  {
    id: 'v106-fe-security-log',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['security', 'log', 'incident', 'audit', '403', 'privilege', 'malware'],
    titleVi: '基本情報 Security: đọc log theo actor, action, time, result, impact',
    subtitleVi: 'Mục tiêu là xử lý câu security tình huống bằng timeline thay vì đọc cảm tính.',
    whyItMattersVi: 'FE thích hỏi log đăng nhập, quyền truy cập, malware, incident response. Nếu không đọc theo timeline, bạn dễ chọn đáp án nghe có vẻ an toàn nhưng sai thứ tự xử lý.',
    conceptVi: ['Actor là ai thực hiện hành động: user, admin, service account, attacker.', 'Action là làm gì: login, change password, access admin API, download file.', 'Result là thành công hay thất bại: 200, 403, 500, denied, success.', 'Impact là dữ liệu/quyền/hệ thống nào bị ảnh hưởng.'],
    storyVi: 'Ví dụ đời thường: camera an ninh phải xem ai vào, vào lúc nào, mở cửa nào, có lấy gì không; không thể chỉ nhìn một frame.',
    deepExampleTitleVi: 'Case viết tay: privilege escalation',
    deepExampleBody: '09:00 userA GET /admin -> 403\n09:01 userA GET /admin/users -> 403\n09:03 adminToken issued from unknown IP\n09:04 settings changed -> success\n09:05 many files exported',
    walkthroughVi: ['403 liên tục cho thấy userA thử quyền admin nhưng bị chặn.', 'adminToken từ unknown IP là điểm bất thường lớn.', 'settings changed success sau token mới cho thấy khả năng token bị chiếm hoặc cấp sai.', 'files exported là impact cần kiểm tra dữ liệu rò rỉ.', 'Bước đầu nên khóa token/session liên quan và giữ log để điều tra.'],
    exerciseVi: 'Đọc timeline trên và nêu 3 thông tin cần báo cáo incident.',
    expectedOutputVi: 'Actor/session liên quan, thời điểm token admin được cấp, dữ liệu hoặc setting bị ảnh hưởng.',
    miniQuizVi: 'Trong incident, vì sao không nên xóa log ngay để dọn hệ thống?',
    miniQuizAnswerVi: 'Vì log là bằng chứng điều tra nguyên nhân, phạm vi ảnh hưởng và báo cáo sau sự cố.',
    mistakesVi: ['Chỉ nhìn event cuối mà bỏ qua chuỗi trước đó.', 'Reset hệ thống trước khi giữ bằng chứng.', 'Không phân biệt failed access và successful change.'],
    studyChecklistVi: ['Đọc log theo timeline.', 'Tách actor/action/result/impact.', 'Biết ưu tiên cô lập và giữ bằng chứng.', 'Không chọn đáp án cảm tính.'],
  },
  {
    id: 'v106-fe-auth-access',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['authentication', 'authorization', 'access control', 'least privilege', 'auth'],
    titleVi: '基本情報 Security: authentication khác authorization',
    subtitleVi: 'Mục tiêu là không nhầm đăng nhập thành được phép làm mọi thứ.',
    whyItMattersVi: 'Câu FE thường hỏi xác thực, phân quyền, least privilege, MFA. Nhầm hai khái niệm này là lỗi cơ bản nhưng rất hay gặp.',
    conceptVi: ['Authentication là xác minh bạn là ai: password, MFA, certificate, biometric.', 'Authorization là kiểm tra bạn được phép làm gì sau khi đã xác thực.', 'Least privilege nghĩa là chỉ cấp quyền tối thiểu cần cho công việc.', 'Access control tốt cần role, policy, log và review định kỳ.'],
    storyVi: 'Ví dụ đời thường: thẻ nhân viên chứng minh bạn thuộc công ty, nhưng không có nghĩa bạn được vào phòng server.',
    deepExampleTitleVi: 'Case viết tay: employee portal',
    deepExampleBody: 'Login success: user=staff01\nRole: sales\nAction: view_customer_list -> allowed\nAction: export_all_customers -> denied\nAction: change_admin_setting -> denied',
    walkthroughVi: ['Login success là authentication thành công.', 'Role sales quyết định authorization.', 'view_customer_list được phép theo role.', 'export_all_customers bị denied vì vượt quyền.', 'change_admin_setting denied là least privilege đúng.'],
    exerciseVi: 'Thiết kế rule quyền cho hệ thống todo có user thường và admin.',
    expectedOutputVi: 'User thường: xem/sửa todo của mình. Admin: xem audit và quản lý user. Cả hai đều cần login; quyền khác nhau.',
    miniQuizVi: 'MFA thuộc authentication hay authorization?',
    miniQuizAnswerVi: 'MFA thuộc authentication vì nó xác minh danh tính mạnh hơn khi đăng nhập.',
    mistakesVi: ['Cho rằng login xong là được làm mọi thứ.', 'Cấp quyền admin cho user thường để tiện.', 'Không review quyền cũ khi nhân viên đổi vị trí.'],
    studyChecklistVi: ['Phân biệt authentication/authorization.', 'Nêu được ví dụ least privilege.', 'Biết MFA thuộc xác thực.', 'Biết cần audit quyền.'],
  },
  {
    id: 'v106-fe-http-dns',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['dns', 'http', 'https', 'tcp', 'tls', 'web', 'network'],
    titleVi: '基本情報 Network: từ URL tới HTTPS response diễn ra nhiều bước',
    subtitleVi: 'Mục tiêu là hiểu web request bằng chuỗi DNS → TCP/TLS → HTTP, để làm câu network không học vẹt.',
    whyItMattersVi: 'FE có thể hỏi DNS, HTTPS, certificate, port, cache. Nếu hiểu flow, bạn sẽ suy luận được lỗi nằm ở đâu.',
    conceptVi: ['DNS đổi domain thành IP. Nếu DNS sai, browser không biết server ở đâu.', 'TCP tạo kết nối tin cậy giữa client và server. HTTPS thường chạy trên TCP port 443.', 'TLS mã hóa và xác thực server bằng certificate.', 'HTTP request/response là lớp nội dung: method, path, status code, header, body.'],
    storyVi: 'Ví dụ đời thường: muốn gửi thư, bạn cần tra địa chỉ nhà, đi đường tới đó, xác minh đúng người nhận, rồi mới đưa nội dung thư.',
    deepExampleTitleVi: 'Flow viết tay: mở https://example.com/login',
    deepExampleBody: '1. Browser checks DNS cache\n2. DNS resolves example.com -> IP\n3. Browser opens TCP connection to IP:443\n4. TLS handshake verifies certificate\n5. Browser sends HTTP GET /login\n6. Server returns 200 with HTML',
    walkthroughVi: ['DNS cache có thể tránh query lặp lại.', 'Nếu DNS fail thì chưa tới bước TCP.', 'TLS fail có thể do certificate hết hạn hoặc domain không khớp.', 'HTTP 404 nghĩa là tới server rồi nhưng path không có.', 'HTTP 500 nghĩa là server xử lý lỗi.'],
    exerciseVi: 'Phân biệt lỗi DNS fail, TLS certificate error, HTTP 404 bằng một câu ngắn mỗi loại.',
    expectedOutputVi: 'DNS fail: không tìm được IP. TLS error: không xác minh/mã hóa an toàn. 404: server chạy nhưng không có path.',
    miniQuizVi: 'HTTPS mã hóa ở bước nào?',
    miniQuizAnswerVi: 'Ở bước TLS, trước khi gửi HTTP content qua kết nối an toàn.',
    mistakesVi: ['Nghĩ 404 là lỗi mạng vật lý.', 'Nhầm DNS với HTTP.', 'Không biết HTTPS dùng TLS để mã hóa.'],
    studyChecklistVi: ['Nêu được DNS làm gì.', 'Nêu được TLS làm gì.', 'Phân biệt 404 và DNS fail.', 'Biết port 443 cho HTTPS.'],
  },
  {
    id: 'v106-fe-graph-bfs',
    courseId: 'fundamental-info',
    group: 'fe-kamoku-b' as V105ChapterGroup,
    match: ['graph', 'bfs', 'queue', 'shortest path', 'node', 'edge'],
    titleVi: '基本情報 科目B: BFS dùng queue để đi theo từng lớp',
    subtitleVi: 'Mục tiêu là trace graph bằng queue, visited và distance thay vì nhìn hình rồi đoán.',
    whyItMattersVi: 'BFS thường dùng để tìm đường ngắn nhất trên graph không trọng số. 科目B có thể hỏi trạng thái queue sau vài bước.',
    conceptVi: ['Queue là FIFO: vào trước ra trước. Vì vậy BFS xử lý node theo lớp khoảng cách.', 'visited giúp không thêm lại node đã gặp, tránh vòng lặp vô hạn.', 'distance[next] = distance[current] + 1 khi lần đầu gặp next.', 'Thứ tự neighbor trong đề ảnh hưởng queue nếu đề cho thứ tự duyệt.'],
    storyVi: 'Ví dụ đời thường: tìm bạn của bạn trên mạng xã hội. Trước hết xem bạn trực tiếp, rồi bạn của bạn, rồi lớp tiếp theo.',
    deepExampleTitleVi: 'Pseudo-code viết tay: BFS distance',
    deepExampleBody: 'queue = [A]\nvisited = {A}\ndistance[A] = 0\nwhile queue not empty:\n  current = pop_front(queue)\n  for next in neighbors[current]:\n    if next not in visited:\n      visited.add(next)\n      distance[next] = distance[current] + 1\n      push_back(queue, next)',
    walkthroughVi: ['Bắt đầu A có distance 0.', 'pop_front lấy node cũ nhất trong queue.', 'Neighbor chưa visited được thêm vào cuối queue.', 'distance tăng thêm 1 từ current.', 'Vì queue FIFO, node distance 1 xử lý trước distance 2.'],
    exerciseVi: 'Graph A-B, A-C, B-D, C-D. Trace BFS từ A và ghi distance D.',
    expectedOutputVi: 'distance[D] = 2',
    miniQuizVi: 'Vì sao BFS tìm shortest path trên graph không trọng số?',
    miniQuizAnswerVi: 'Vì nó duyệt theo từng lớp khoảng cách, lần đầu gặp node là đường ít cạnh nhất.',
    mistakesVi: ['Dùng stack thay queue làm thành DFS.', 'Quên visited khiến lặp vô hạn.', 'Cập nhật distance cho node đã visited làm sai shortest path.'],
    studyChecklistVi: ['Trace được queue.', 'Biết visited để tránh lặp.', 'Tính được distance.', 'Phân biệt BFS và DFS.'],
  },
  {
    id: 'v106-ai-ethics-privacy',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['privacy', 'personal data', 'ethics', '個人情報', 'pii', 'consent'],
    titleVi: 'AI Passport Case Study: privacy không phải checkbox, mà là thiết kế dữ liệu tối thiểu',
    subtitleVi: 'Mục tiêu là hiểu dữ liệu cá nhân cần được giảm, bảo vệ và dùng đúng mục đích ngay từ thiết kế.',
    whyItMattersVi: 'AI Passport thường hỏi privacy, consent, anonymization và governance. Nếu chỉ nói “bảo mật dữ liệu” chung chung sẽ không đủ.',
    conceptVi: ['Dữ liệu cá nhân là thông tin nhận diện trực tiếp hoặc gián tiếp một người.', 'Data minimization nghĩa là chỉ thu thập dữ liệu thật sự cần cho mục tiêu đã nêu.', 'Purpose limitation nghĩa là không dùng dữ liệu cho mục đích mới nếu chưa có căn cứ phù hợp.', 'Ẩn danh/pseudonymization giảm rủi ro nhưng không phải lúc nào cũng loại bỏ hoàn toàn khả năng tái nhận diện.'],
    storyVi: 'Ví dụ đời thường: cửa hàng cần số điện thoại để giao hàng, nhưng không cần biết bệnh sử của khách. Thu thập càng nhiều không đồng nghĩa càng tốt.',
    deepExampleTitleVi: 'Case viết tay: AI phân tích phản hồi khách hàng',
    deepExampleBody: 'Goal: phân loại phản hồi tích cực/tiêu cực\nRaw data: tên, email, nội dung phản hồi, số điện thoại\nSafer design:\n- Remove name/email/phone before model training\n- Keep customer_id only in protected system\n- Use aggregated dashboard\n- Limit access to raw data\n- Define retention period',
    walkthroughVi: ['Mục tiêu chỉ cần nội dung phản hồi, không cần tên/email để train sentiment.', 'Loại bỏ PII trước training giảm rủi ro lộ dữ liệu.', 'customer_id nếu cần đối chiếu phải giữ ở hệ thống bảo vệ riêng.', 'Dashboard tổng hợp giảm quyền truy cập raw data.', 'Retention period tránh giữ dữ liệu mãi mãi.'],
    exerciseVi: 'Thiết kế privacy checklist cho chatbot nội bộ dùng tài liệu nhân sự.',
    expectedOutputVi: 'Không gửi PII không cần thiết, phân quyền tài liệu, log truy cập, retention, human review cho câu hỏi nhạy cảm.',
    miniQuizVi: 'Data minimization nghĩa là gì?',
    miniQuizAnswerVi: 'Chỉ thu thập và xử lý dữ liệu cần thiết cho mục tiêu cụ thể, không gom thêm vì “có thể dùng sau”.',
    mistakesVi: ['Thu thập dữ liệu tối đa vì nghĩ AI cần càng nhiều càng tốt.', 'Ẩn danh sơ sài nhưng vẫn có thể tái nhận diện.', 'Dùng dữ liệu cho mục đích mới mà không kiểm tra policy.'],
    studyChecklistVi: ['Nêu được PII là gì.', 'Giải thích data minimization.', 'Biết purpose limitation.', 'Thiết kế được checklist privacy.'],
  },
  {
    id: 'v106-ai-bias-fairness',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['bias', 'fairness', 'discrimination', 'dataset', '偏り'],
    titleVi: 'AI Passport Case Study: bias xuất hiện khi dữ liệu, mục tiêu hoặc cách dùng bị lệch',
    subtitleVi: 'Mục tiêu là hiểu fairness bằng case cụ thể, không chỉ nhớ định nghĩa thiên lệch.',
    whyItMattersVi: 'AI dùng trong tuyển dụng, tín dụng, y tế có thể ảnh hưởng con người. Bias không xử lý sẽ tạo quyết định không công bằng và rủi ro pháp lý.',
    conceptVi: ['Bias có thể đến từ dữ liệu lịch sử vốn đã lệch.', 'Metric tổng thể cao có thể che giấu nhóm nhỏ bị sai nhiều.', 'Fairness cần đo theo nhóm liên quan, không chỉ accuracy toàn bộ.', 'Human review và appeal process giúp giảm tác hại khi model sai.'],
    storyVi: 'Ví dụ đời thường: nếu chỉ học từ lịch sử tuyển người của một phòng từng ưu tiên một nhóm nhất định, AI có thể lặp lại thói quen cũ.',
    deepExampleTitleVi: 'Case viết tay: AI sàng lọc CV',
    deepExampleBody: 'Goal: rank CV for interview\nRisk:\n- Training data from past hires may reflect old bias\n- Gap year or school name may become proxy\n- Accuracy overall looks high but subgroup recall is low\nMitigation:\n- Remove sensitive/proxy features when possible\n- Evaluate by subgroup\n- Add human review\n- Keep explanation and appeal path',
    walkthroughVi: ['Dữ liệu past hires không trung lập nếu quy trình cũ đã thiên lệch.', 'Feature tưởng vô hại có thể là proxy cho nhóm nhạy cảm.', 'Cần xem metric theo subgroup, ví dụ recall từng nhóm.', 'AI chỉ nên hỗ trợ shortlist, không tự động loại ứng viên rủi ro cao.', 'Appeal path cho phép con người sửa quyết định sai.'],
    exerciseVi: 'Nêu 4 bước kiểm tra bias cho model chấm điểm hồ sơ vay.',
    expectedOutputVi: 'Kiểm tra dữ liệu lịch sử, metric theo subgroup, feature proxy, human review/appeal.',
    miniQuizVi: 'Vì sao accuracy chung 90% chưa đủ để kết luận model công bằng?',
    miniQuizAnswerVi: 'Vì model có thể rất tốt ở nhóm lớn nhưng sai nhiều ở nhóm nhỏ hoặc nhóm bị ảnh hưởng.',
    mistakesVi: ['Chỉ nhìn metric tổng thể.', 'Không nhận ra proxy feature.', 'Dùng AI tự động loại người trong quyết định nhạy cảm.'],
    studyChecklistVi: ['Giải thích được nguồn bias.', 'Biết đo metric theo subgroup.', 'Nêu được proxy feature.', 'Biết cần human review.'],
  },
  {
    id: 'v106-ai-law-copyright',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['copyright', 'law', 'license', 'ai act', 'compliance', '著作権'],
    titleVi: 'AI Passport Case Study: bản quyền và compliance phải kiểm tra trước khi dùng GenAI trong doanh nghiệp',
    subtitleVi: 'Mục tiêu là hiểu rủi ro pháp lý quanh dữ liệu huấn luyện, input prompt và output được tạo.',
    whyItMattersVi: 'AI Passport có thể hỏi luật, bản quyền, trách nhiệm giải trình và sử dụng AI an toàn. Doanh nghiệp không thể chỉ copy output AI vào sản phẩm.',
    conceptVi: ['Input có thể chứa tài liệu nội bộ hoặc dữ liệu khách hàng, cần kiểm tra quyền đưa vào công cụ AI.', 'Output GenAI có thể giống nội dung có bản quyền hoặc chứa thông tin sai.', 'License của dữ liệu, model, thư viện và asset cần được kiểm tra khi dùng thương mại.', 'Compliance là quy trình: policy, approval, logging, review, documentation.'],
    storyVi: 'Ví dụ đời thường: dùng ảnh tìm trên mạng làm poster công ty không tự động hợp pháp. Với GenAI, output đẹp cũng không tự động an toàn.',
    deepExampleTitleVi: 'Case viết tay: tạo nội dung marketing bằng GenAI',
    deepExampleBody: 'Scenario:\n- Marketing team asks LLM to write product copy\n- Prompt includes unreleased product specs\n- Output mentions competitor claim without source\nSafe process:\n1. Do not input confidential specs into public tool\n2. Use approved enterprise AI workspace\n3. Check factual claims\n4. Review copyright/style similarity\n5. Keep approval log',
    walkthroughVi: ['Thông số sản phẩm chưa công bố là confidential, không nên đưa vào tool không được duyệt.', 'Enterprise workspace có policy và logging tốt hơn.', 'Claim về đối thủ cần nguồn, nếu không có thể gây rủi ro pháp lý.', 'Output cần người review trước khi publish.', 'Log giúp chứng minh quy trình kiểm soát.'],
    exerciseVi: 'Viết checklist 5 điểm trước khi publish bài viết do GenAI hỗ trợ.',
    expectedOutputVi: 'Kiểm tra dữ liệu input, quyền sử dụng, factual claim, bản quyền/style similarity, approval log.',
    miniQuizVi: 'Output do AI tạo có luôn miễn bản quyền và an toàn để dùng thương mại không?',
    miniQuizAnswerVi: 'Không. Vẫn cần kiểm tra license, similarity, factual accuracy và policy nội bộ.',
    mistakesVi: ['Đưa tài liệu mật vào public AI.', 'Tin output vì văn phong chuyên nghiệp.', 'Không lưu dấu vết approval.'],
    studyChecklistVi: ['Biết phân biệt input risk và output risk.', 'Nêu được copyright/license check.', 'Biết cần factual review.', 'Hiểu compliance là quy trình.'],
  },
  {
    id: 'v106-ai-governance-monitoring',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['governance', 'monitoring', 'audit', 'model drift', 'policy', 'risk management'],
    titleVi: 'AI Passport Case Study: AI governance là vòng đời kiểm soát, không phải tài liệu một lần',
    subtitleVi: 'Mục tiêu là hiểu sau khi deploy AI vẫn phải monitor, audit, cập nhật và xử lý incident.',
    whyItMattersVi: 'Model có thể xuống chất lượng khi dữ liệu thực tế thay đổi. Governance giúp doanh nghiệp biết ai chịu trách nhiệm và khi nào cần can thiệp.',
    conceptVi: ['AI governance gồm policy, role, approval, monitoring, incident response và audit trail.', 'Model drift xảy ra khi dữ liệu thực tế khác dữ liệu huấn luyện, làm performance giảm.', 'Monitoring cần theo dõi chất lượng, lỗi, khiếu nại, bias và security signal.', 'Owner rõ ràng giúp quyết định rollback, retrain hoặc tạm dừng hệ thống.'],
    storyVi: 'Ví dụ đời thường: thang máy không chỉ kiểm định lúc lắp đặt; nó cần bảo trì định kỳ, log sự cố và người chịu trách nhiệm.',
    deepExampleTitleVi: 'Case viết tay: model dự báo nhu cầu hàng hóa',
    deepExampleBody: 'Before launch:\n- Define KPI: forecast error < 10%\n- Assign owner: supply chain team\n- Approve data source\nAfter launch:\n- Monitor weekly error\n- Alert if error > 15% for 2 weeks\n- Review seasonal drift\n- Retrain with approved data\n- Keep change log',
    walkthroughVi: ['KPI định nghĩa model tốt hay không bằng số đo cụ thể.', 'Owner chịu trách nhiệm khi alert xảy ra.', 'Weekly monitoring phát hiện drift sớm.', 'Retrain phải dùng dữ liệu được duyệt, không tùy tiện.', 'Change log giúp audit vì sao model thay đổi.'],
    exerciseVi: 'Thiết kế governance plan cho chatbot CSKH dùng GenAI.',
    expectedOutputVi: 'Owner, allowed data, quality metric, hallucination report, escalation path, review log, rollback/disable plan.',
    miniQuizVi: 'Model drift là gì?',
    miniQuizAnswerVi: 'Là hiện tượng dữ liệu thực tế thay đổi so với dữ liệu huấn luyện khiến model giảm chất lượng.',
    mistakesVi: ['Deploy xong không monitor.', 'Không có owner rõ ràng.', 'Retrain bằng dữ liệu chưa kiểm tra.'],
    studyChecklistVi: ['Nêu được thành phần governance.', 'Hiểu model drift.', 'Biết cần owner và KPI.', 'Thiết kế được alert/rollback.'],
  },
  {
    id: 'v106-ai-business-kpi',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['business', 'kpi', 'roi', 'use case', 'strategy', 'dx'],
    titleVi: 'AI Passport Case Study: use case AI tốt bắt đầu từ vấn đề kinh doanh, không bắt đầu từ model',
    subtitleVi: 'Mục tiêu là biết chọn bài toán AI có KPI rõ, dữ liệu phù hợp và rủi ro kiểm soát được.',
    whyItMattersVi: 'AI Passport thường hỏi ứng dụng AI trong doanh nghiệp. Câu trả lời tốt không phải “dùng AI cho hiện đại”, mà là problem → data → action → KPI → risk.',
    conceptVi: ['Problem phải cụ thể: giảm thời gian xử lý ticket, dự báo tồn kho, phát hiện lỗi sản phẩm.', 'Data phải có sẵn, hợp pháp, đủ chất lượng và liên quan tới problem.', 'Output AI phải dẫn tới action rõ ràng, nếu không chỉ là dashboard đẹp.', 'KPI đo business impact: thời gian, chi phí, chất lượng, doanh thu, satisfaction.'],
    storyVi: 'Ví dụ đời thường: mua máy chạy bộ không làm bạn khỏe nếu không có mục tiêu, lịch tập và cách đo tiến bộ.',
    deepExampleTitleVi: 'Case viết tay: AI phân loại ticket hỗ trợ',
    deepExampleBody: 'Problem: support team mất thời gian phân loại ticket\nData: historical tickets with labels\nAI output: category and priority\nAction: route ticket to correct team\nKPI:\n- reduce first response time by 20%\n- improve routing accuracy to 90%\nRisk:\n- wrong route for urgent ticket\n- privacy in ticket text',
    walkthroughVi: ['Problem là phân loại ticket, không phải “dùng AI”.', 'Historical tickets có label giúp train/evaluate.', 'Output phải gắn với action routing.', 'KPI đo thời gian và accuracy.', 'Risk urgent ticket cần fallback/human review.'],
    exerciseVi: 'Chọn một use case AI cho cửa hàng nhỏ và viết problem, data, output, action, KPI.',
    expectedOutputVi: 'Ví dụ: forecast demand. Data: sales history. Output: expected sales. Action: adjust stock. KPI: reduce stockout by 15%.',
    miniQuizVi: 'Vì sao không nên bắt đầu dự án AI bằng câu hỏi “dùng model nào”?',
    miniQuizAnswerVi: 'Vì model chỉ là công cụ. Trước hết cần xác định vấn đề, dữ liệu, hành động và KPI.',
    mistakesVi: ['Use case mơ hồ không đo được.', 'Có output nhưng không có action.', 'Bỏ qua rủi ro vận hành.'],
    studyChecklistVi: ['Viết được problem rõ.', 'Nối data-output-action.', 'Đặt KPI đo được.', 'Nêu risk và fallback.'],
  },
  {
    id: 'v106-ai-data-quality',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['data quality', 'label', 'missing', 'noise', 'dataset', 'preprocessing'],
    titleVi: 'AI Passport Case Study: dữ liệu xấu làm AI xấu, dù model hiện đại đến đâu',
    subtitleVi: 'Mục tiêu là hiểu quality issue như missing, noise, label sai, leakage và imbalance bằng ví dụ dễ nhớ.',
    whyItMattersVi: 'Trong AI project, nhiều lỗi đến từ dữ liệu hơn thuật toán. AI Passport hay hỏi preprocessing, evaluation và rủi ro dữ liệu.',
    conceptVi: ['Missing value là dữ liệu thiếu, cần quyết định bỏ, điền hoặc thu thập lại.', 'Noise là dữ liệu sai/lẫn, ví dụ typo, sensor lỗi, record trùng.', 'Label sai làm model học sai mục tiêu.', 'Data leakage xảy ra khi dữ liệu train chứa thông tin mà khi dự đoán thật không có.'],
    storyVi: 'Ví dụ đời thường: nếu thầy đưa đáp án lẫn vào đề ôn, học sinh làm điểm cao khi ôn nhưng thi thật không còn đáp án nên rớt.',
    deepExampleTitleVi: 'Case viết tay: dự đoán khách hủy dịch vụ',
    deepExampleBody: 'Dataset columns:\n- customer_age\n- monthly_fee\n- complaint_count\n- cancel_date\n- label_churn\nProblem:\n- cancel_date appears only after churn happens\n- some complaint_count missing\n- labels from old system are inconsistent\nFix:\n- remove leakage column cancel_date\n- define missing value policy\n- audit labels\n- split train/test by time',
    walkthroughVi: ['cancel_date là leakage vì khi dự đoán trước hủy thì chưa biết ngày hủy.', 'Missing complaint_count cần policy rõ: unknown, 0 hay cần bổ sung.', 'Label inconsistent làm model học sai.', 'Split by time giúp test giống thực tế hơn.', 'Data audit trước model giúp tránh kết quả ảo.'],
    exerciseVi: 'Nêu 4 bước kiểm tra data quality trước khi train model dự báo nghỉ việc.',
    expectedOutputVi: 'Check missing, duplicate/noise, label definition, leakage, train/test split.',
    miniQuizVi: 'Data leakage nguy hiểm vì sao?',
    miniQuizAnswerVi: 'Vì model nhìn thấy thông tin không có trong thực tế, nên điểm test ảo cao nhưng deploy sẽ fail.',
    mistakesVi: ['Tập trung model mà bỏ qua data audit.', 'Điền missing value tùy tiện.', 'Không kiểm tra leakage.'],
    studyChecklistVi: ['Phân biệt missing/noise/label sai.', 'Giải thích leakage.', 'Biết audit label.', 'Biết split theo thời gian khi cần.'],
  },
  {
    id: 'v106-ai-human-in-loop',
    courseId: 'ai-passport',
    group: 'ai-case-study' as V105ChapterGroup,
    match: ['human in the loop', 'review', 'automation', 'decision', 'risk'],
    titleVi: 'AI Passport Case Study: human-in-the-loop dùng cho quyết định rủi ro cao',
    subtitleVi: 'Mục tiêu là hiểu khi nào AI được tự động hóa, khi nào cần người kiểm tra trước khi hành động.',
    whyItMattersVi: 'Không phải use case nào cũng nên cho AI tự quyết. Với y tế, tài chính, tuyển dụng, pháp lý, sai một lần có thể ảnh hưởng con người.',
    conceptVi: ['Human-in-the-loop nghĩa là con người review, approve hoặc can thiệp vào quyết định AI.', 'Mức automation phụ thuộc rủi ro: low risk có thể tự động, high risk cần approval.', 'AI nên đưa confidence, reason, evidence để người review hiểu vì sao gợi ý được tạo.', 'Process cần ghi log quyết định cuối cùng do ai approve.'],
    storyVi: 'Ví dụ đời thường: GPS gợi ý đường đi, nhưng tài xế vẫn quyết định có rẽ vào đường nhỏ nguy hiểm hay không.',
    deepExampleTitleVi: 'Case viết tay: AI gợi ý từ chối khoản vay',
    deepExampleBody: 'AI output:\n- risk_score: high\n- reason: unstable income, late payments\nSafe workflow:\n1. AI suggests review_needed\n2. Human officer checks documents\n3. Customer can provide additional evidence\n4. Final decision is logged\n5. Model feedback is collected',
    walkthroughVi: ['AI không tự động từ chối ngay vì ảnh hưởng tài chính của khách.', 'Human officer kiểm tra tài liệu bổ sung.', 'Appeal/additional evidence giúp giảm sai sót.', 'Log quyết định phục vụ audit.', 'Feedback giúp cải thiện model.'],
    exerciseVi: 'Thiết kế workflow human-in-the-loop cho AI chấm CV.',
    expectedOutputVi: 'AI shortlist + reason, recruiter review, candidate appeal if rejected, log decision, monitor fairness.',
    miniQuizVi: 'Khi nào human-in-the-loop đặc biệt cần thiết?',
    miniQuizAnswerVi: 'Khi quyết định có rủi ro cao, ảnh hưởng quyền lợi con người hoặc có yêu cầu giải trình.',
    mistakesVi: ['Tự động hóa toàn bộ vì AI nhanh.', 'Không cung cấp reason/evidence cho người review.', 'Không log ai ra quyết định cuối.'],
    studyChecklistVi: ['Biết định nghĩa HITL.', 'Phân loại risk theo use case.', 'Thiết kế review/appeal.', 'Nêu được audit log.'],
  }
];

export const v106ManualChapters: V105ManualChapter[] = [
  ...v106ManualChapterExtensions,
  ...v105ManualChapters,
];

const textOf = (node: KnowledgeNodeData) => `${node.id} ${node.labelVi} ${node.labelEn} ${node.labelJa} ${node.keywords.join(' ')}`.toLowerCase();

export function findV106ManualChapter(courseId: CourseId, node: KnowledgeNodeData): V105ManualChapter | undefined {
  const haystack = textOf(node);
  const candidates = v106ManualChapters.filter((chapter) => chapter.courseId === courseId);
  return candidates.find((chapter) => chapter.match.some((key) => haystack.includes(key.toLowerCase()))) ?? candidates[0];
}

export function v106ChaptersForCourse(courseId: CourseId): V105ManualChapter[] {
  return v106ManualChapters.filter((chapter) => chapter.courseId === courseId);
}
