import type { KnowledgeNodeData } from '../../features/knowledge-graph/types';
type Level='root'|'major'|'topic'|'detail'; type Importance='high'|'medium'|'low';
const n=(id:string,vi:string,en:string,level:Level,importance:Importance='high',prerequisites:string[]=[]):KnowledgeNodeData=>({
  id,labelJa:en,labelVi:vi,labelEn:en,category:'software',level,importance,
  summaryVi:`${vi}: lệnh/khái niệm terminal cần biết để làm việc với dự án thật.`,
  summaryJa:`${en} はterminal作業で重要なコマンド/概念です。`,
  examPointVi:`Cần hiểu ${vi} dùng để làm gì, option thường gặp và lỗi nguy hiểm.`,
  examPointJa:`${en} の用途、よく使うoption、注意点を確認します。`,
  examples:[],keywords:[vi,en],prerequisites,related:[],
});

export const linuxNodes=[
  n('linux','Linux / Terminal tổng quan','Linux / Terminal','root','high',[]),
  n('shell','Shell','Shell','major','high',['linux']),
  n('terminal','Terminal','Terminal','topic','high',['shell']),
  n('pwd','pwd','pwd','topic','high',['terminal']),
  n('ls','ls','ls','topic','high',['terminal']),
  n('cd','cd','cd','topic','high',['terminal']),
  n('path','Path','Path','topic','high',['terminal']),
  n('mkdir','mkdir','mkdir','topic','high',['path']),
  n('touch','touch','touch','topic','medium',['path']),
  n('cp','cp','cp','topic','high',['path']),
  n('mv','mv','mv','topic','high',['path']),
  n('rm','rm','rm','topic','high',['path']),
  n('cat','cat','cat','topic','medium',['path']),
  n('less','less','less','topic','medium',['cat']),
  n('head-tail','head / tail','head tail','topic','medium',['cat']),
  n('grep','grep','grep','major','high',['cat']),
  n('find','find','find','major','high',['path']),
  n('pipe','Pipe |','Pipe','topic','high',['grep']),
  n('redirect','Redirect > >>','Redirect','topic','high',['pipe']),
  n('chmod','chmod','chmod','major','high',['path']),
  n('permission','Permission','Permission','topic','high',['chmod']),
  n('chown','chown','chown','topic','medium',['permission']),
  n('ps','ps','ps','topic','high',['linux']),
  n('top','top','top','topic','medium',['ps']),
  n('kill','kill','kill','topic','high',['ps']),
  n('systemctl','systemctl','systemctl','major','high',['linux']),
  n('journalctl','journalctl','journalctl','topic','medium',['systemctl']),
  n('ssh','ssh','ssh','major','high',['linux']),
  n('scp','scp','scp','topic','medium',['ssh']),
  n('tar','tar','tar','topic','medium',['linux']),
  n('curl','curl','curl','topic','high',['linux']),
  n('wget','wget','wget','topic','medium',['curl']),
  n('env','Environment Variables','Environment Variables','topic','high',['shell']),
  n('which','which','which','topic','medium',['shell']),
  n('sudo','sudo','sudo','topic','high',['permission']),
  n('apt','apt','apt','topic','medium',['linux']),
  n('docker','Docker CLI','Docker','major','high',['linux']),
  n('docker-ps','docker ps','docker ps','topic','high',['docker']),
  n('docker-logs','docker logs','docker logs','topic','medium',['docker']),
  n('docker-compose','docker compose','docker compose','topic','high',['docker']),
  n('git','Git CLI','Git','major','high',['linux']),
  n('git-status','git status','git status','topic','high',['git']),
  n('git-branch','git branch','git branch','topic','medium',['git']),
  n('git-commit','git commit','git commit','topic','high',['git']),
  n('git-pull-push','git pull/push','git pull push','topic','high',['git']),
];
