import type { Importance, KnowledgeCategory, NodeLevel } from '../../features/knowledge-graph/types';

export interface FundamentalInfoCatalogItem {
  id: string;
  labelJa: string;
  labelVi: string;
  labelEn: string;
  category: KnowledgeCategory;
  level: NodeLevel;
  importance: Importance;
  phase: string;
  prerequisites: string[];
  definitionVi: string;
  definitionJa: string;
  whyImportantVi: string;
  whyImportantJa: string;
  examPatternsVi: string[];
  examPatternsJa: string[];
  commonMistakesVi: string[];
  commonMistakesJa: string[];
  memoryTipVi: string;
  memoryTipJa: string;
  examples: string[];
  keywords: string[];
}

interface FundamentalInfoTopicRow {
  id: string;
  labelJa: string;
  labelVi: string;
  labelEn: string;
  category: KnowledgeCategory;
  level: NodeLevel;
  importance: Importance;
  phase: string;
  prerequisites: string[];
  focusVi: string;
  focusJa: string;
  examExample: string;
  keywords: string[];
}

export const fundamentalInfoTopicRows: FundamentalInfoTopicRow[] = [
  {
    id: 'fundamental-info',
    labelJa: '基本情報技術者 総論',
    labelVi: '基本情報技術者 総論',
    labelEn: 'Fundamental Information Technology Engineer',
    category: 'technology',
    level: 'root',
    importance: 'high',
    phase: 'overview',
    focusVi: 'toàn cảnh kỳ thi, cách học 科目A/科目B và cách nối thuật ngữ với bài toán xử lý thực tế',
    focusJa: '科目A/科目Bの全体像、学習順序、用語を処理問題につなげる考え方',
    examExample: 'Chọn cách học FE đúng: đọc kiến thức rộng, luyện trace thuật toán và giải thích lựa chọn sai',
    prerequisites: [],
    keywords: ['基本情報', '科目A', '科目B', 'CBT'],
  },
  {
    id: 'fe-theory',
    labelJa: '基礎理論・数学',
    labelVi: '基礎理論 / Math',
    labelEn: '基礎理論 / Math',
    category: 'technology',
    level: 'major',
    importance: 'high',
    phase: 'theory',
    focusVi: 'Nắm cách tính, logic, biểu diễn dữ liệu và xác suất trước khi học thuật toán.',
    focusJa: '基礎理論・数学の全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: '基礎理論 / Mathの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['基礎理論・数学', '基礎理論 / Math', 'FE'],
  },
  {
    id: 'fe-algorithm',
    labelJa: 'アルゴリズム・データ構造',
    labelVi: 'Algorithm / Data Structure',
    labelEn: 'Algorithm / Data Structure',
    category: 'technology',
    level: 'major',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'Đọc pseudo-code, trace biến, hiểu cấu trúc dữ liệu và độ phức tạp.',
    focusJa: 'アルゴリズム・データ構造の全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Algorithm / Data Structureの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['アルゴリズム・データ構造', 'Algorithm / Data Structure', 'FE'],
  },
  {
    id: 'fe-computer',
    labelJa: 'コンピュータ・ソフトウェア',
    labelVi: 'Computer / Software',
    labelEn: 'Computer / Software',
    category: 'technology',
    level: 'major',
    importance: 'high',
    phase: 'computer',
    focusVi: 'Hiểu phần cứng, hệ điều hành, cloud và nền lập trình.',
    focusJa: 'コンピュータ・ソフトウェアの全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Computer / Softwareの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['コンピュータ・ソフトウェア', 'Computer / Software', 'FE'],
  },
  {
    id: 'fe-database',
    labelJa: 'データベース',
    labelVi: 'Database',
    labelEn: 'Database',
    category: 'database',
    level: 'major',
    importance: 'high',
    phase: 'database',
    focusVi: 'Thiết kế ER, chuẩn hóa, SQL, transaction và tối ưu truy vấn.',
    focusJa: 'データベースの全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Databaseの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['データベース', 'Database', 'FE'],
  },
  {
    id: 'fe-network-security',
    labelJa: 'ネットワーク・セキュリティ',
    labelVi: 'Network / Security',
    labelEn: 'Network / Security',
    category: 'security',
    level: 'major',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'Nắm TCP/IP, subnet, web, mã hóa, xác thực và đối sách rủi ro.',
    focusJa: 'ネットワーク・セキュリティの全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Network / Securityの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['ネットワーク・セキュリティ', 'Network / Security', 'FE'],
  },
  {
    id: 'fe-development',
    labelJa: '開発・マネジメント',
    labelVi: 'Development / Management',
    labelEn: 'Development / Management',
    category: 'management',
    level: 'major',
    importance: 'high',
    phase: 'development',
    focusVi: 'Hiểu quy trình phát triển, testing, PM, service và vận hành.',
    focusJa: '開発・マネジメントの全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Development / Managementの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['開発・マネジメント', 'Development / Management', 'FE'],
  },
  {
    id: 'fe-strategy',
    labelJa: 'ストラテジ・法務',
    labelVi: 'Strategy / Law',
    labelEn: 'Strategy / Law',
    category: 'business',
    level: 'major',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'Đọc được câu hỏi kinh doanh, luật, kế toán và quản trị doanh nghiệp.',
    focusJa: 'ストラテジ・法務の全体像を整理し、用語と計算・判断問題をつなげます。',
    examExample: 'Strategy / Lawの代表問題を分野別に分類する',
    prerequisites: ['fundamental-info'],
    keywords: ['ストラテジ・法務', 'Strategy / Law', 'FE'],
  },
  {
    id: 'binary-number',
    labelJa: '2進数・基数変換',
    labelVi: 'Nhị phân và đổi cơ số',
    labelEn: 'Binary / Radix Conversion',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'theory',
    focusVi: 'đổi giữa 2/10/16, hiểu bit/byte, số bit biểu diễn trạng thái',
    focusJa: '2進数・10進数・16進数、bit/byte、状態数を表すbit数を理解します',
    examExample: '101101₂ を10進数に変換する',
    prerequisites: ['fe-theory'],
    keywords: ['2進数', '16進数', 'bit', 'byte'],
  },
  {
    id: 'complement-number',
    labelJa: '補数表現',
    labelVi: 'Biểu diễn số âm bằng bù',
    labelEn: 'Complement Number',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'theory',
    focusVi: 'biểu diễn số âm bằng bù 1/bù 2 và đọc overflow',
    focusJa: '負数を1の補数・2の補数で表し、桁あふれを判断します',
    examExample: '8 bit 2の補数で -5 を表す',
    prerequisites: ['binary-number'],
    keywords: ['2の補数', '負数', 'overflow'],
  },
  {
    id: 'fixed-floating-point',
    labelJa: '固定小数点・浮動小数点',
    labelVi: 'Số cố định và số chấm động',
    labelEn: 'Fixed / Floating Point',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'hiểu sai số làm tròn và cách số thực được biểu diễn',
    focusJa: '固定小数点と浮動小数点の表現、丸め誤差を理解します',
    examExample: '浮動小数点の丸め誤差を選ぶ',
    prerequisites: ['binary-number'],
    keywords: ['浮動小数点', '丸め誤差', '仮数', '指数'],
  },
  {
    id: 'boolean-logic',
    labelJa: '論理演算',
    labelVi: 'Logic Boolean',
    labelEn: 'Boolean Logic',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'theory',
    focusVi: 'AND/OR/NOT/XOR, bảng chân trị và điều kiện trong chương trình',
    focusJa: 'AND/OR/NOT/XOR、真理値表、条件分岐への応用を理解します',
    examExample: 'A AND NOT B の真理値を求める',
    prerequisites: ['fe-theory'],
    keywords: ['AND', 'OR', 'NOT', 'XOR', '真理値表'],
  },
  {
    id: 'set-logic',
    labelJa: '集合とベン図',
    labelVi: 'Tập hợp và biểu đồ Venn',
    labelEn: 'Sets / Venn Diagram',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'hợp, giao, phần bù và đọc điều kiện lọc dữ liệu',
    focusJa: '和集合・積集合・補集合とデータ抽出条件を理解します',
    examExample: '条件に合う件数をベン図で求める',
    prerequisites: ['boolean-logic'],
    keywords: ['集合', 'ベン図', '和集合', '積集合'],
  },
  {
    id: 'probability-statistics',
    labelJa: '確率・統計',
    labelVi: 'Xác suất và thống kê',
    labelEn: 'Probability / Statistics',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'theory',
    focusVi: 'tính xác suất, kỳ vọng, trung bình, phương sai, độ lệch chuẩn',
    focusJa: '確率、期待値、平均、分散、標準偏差を計算します',
    examExample: '故障率から期待値を求める',
    prerequisites: ['fe-theory'],
    keywords: ['確率', '期待値', '平均', '分散'],
  },
  {
    id: 'permutation-combination',
    labelJa: '順列・組合せ',
    labelVi: 'Hoán vị và tổ hợp',
    labelEn: 'Permutation / Combination',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'phân biệt xếp thứ tự và chọn nhóm không xét thứ tự',
    focusJa: '順序を考える順列と、順序を考えない組合せを区別します',
    examExample: '5人から3人を選ぶ場合の数',
    prerequisites: ['probability-statistics'],
    keywords: ['順列', '組合せ', '場合の数'],
  },
  {
    id: 'information-entropy',
    labelJa: '情報量・エントロピー',
    labelVi: 'Lượng tin và entropy',
    labelEn: 'Information Entropy',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'hiểu thông tin, mã hóa và nén dữ liệu ở mức khái niệm',
    focusJa: '情報量・エントロピーと符号化・圧縮の考え方を理解します',
    examExample: '出現確率が低い記号ほど情報量が大きい',
    prerequisites: ['probability-statistics'],
    keywords: ['情報量', 'エントロピー', '符号化'],
  },
  {
    id: 'coding-error-detection',
    labelJa: '誤り検出・訂正',
    labelVi: 'Phát hiện và sửa lỗi',
    labelEn: 'Error Detection / Correction',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'theory',
    focusVi: 'parity, checksum, CRC, Hamming code và giới hạn phát hiện lỗi',
    focusJa: 'パリティ、チェックサム、CRC、ハミング符号の役割を理解します',
    examExample: '偶数パリティで誤りを検出する',
    prerequisites: ['binary-number'],
    keywords: ['パリティ', 'CRC', 'ハミング符号'],
  },
  {
    id: 'data-compression',
    labelJa: 'データ圧縮',
    labelVi: 'Nén dữ liệu',
    labelEn: 'Data Compression',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'lossless/lossy, run-length, Huffman và ảnh/âm thanh/video',
    focusJa: '可逆圧縮・非可逆圧縮、ランレングス、ハフマン符号を理解します',
    examExample: '画像圧縮で非可逆を選ぶ',
    prerequisites: ['information-entropy'],
    keywords: ['可逆圧縮', '非可逆圧縮', 'Huffman'],
  },
  {
    id: 'automata-formal-language',
    labelJa: 'オートマトン・形式言語',
    labelVi: 'Automata và ngôn ngữ hình thức',
    labelEn: 'Automata / Formal Language',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'trạng thái, chuyển trạng thái và nhận dạng chuỗi theo luật',
    focusJa: '状態、状態遷移、文字列を受理する仕組みを理解します',
    examExample: '有限オートマトンの受理状態を追う',
    prerequisites: ['fe-theory'],
    keywords: ['オートマトン', '状態遷移', '形式言語'],
  },
  {
    id: 'logical-circuit',
    labelJa: '論理回路',
    labelVi: 'Mạch logic',
    labelEn: 'Logical Circuit',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'theory',
    focusVi: 'cổng logic, biểu thức logic và bảng chân trị của mạch',
    focusJa: '論理ゲート、論理式、回路の真理値表を理解します',
    examExample: 'NANDだけでNOTを作る',
    prerequisites: ['boolean-logic'],
    keywords: ['論理回路', 'NAND', 'NOR', '真理値表'],
  },
  {
    id: 'matrix-vector',
    labelJa: '行列・ベクトル',
    labelVi: 'Ma trận và vector',
    labelEn: 'Matrix / Vector',
    category: 'technology',
    level: 'detail',
    importance: 'low',
    phase: 'theory',
    focusVi: 'đọc bảng số, phép nhân ma trận đơn giản và ứng dụng trong xử lý dữ liệu',
    focusJa: '行列・ベクトルの基本計算とデータ処理での利用を理解します',
    examExample: '2x2行列の積を計算する',
    prerequisites: ['fe-theory'],
    keywords: ['行列', 'ベクトル', '線形代数'],
  },
  {
    id: 'graph-theory',
    labelJa: 'グラフ理論',
    labelVi: 'Lý thuyết đồ thị',
    labelEn: 'Graph Theory',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'đỉnh/cạnh, đường đi, cây, trọng số và ứng dụng trong network/path',
    focusJa: '頂点・辺・経路・木・重み付きグラフを理解します',
    examExample: '最短経路の候補を選ぶ',
    prerequisites: ['fe-theory'],
    keywords: ['グラフ', '頂点', '辺', '経路'],
  },
  {
    id: 'queueing-basic',
    labelJa: '待ち行列',
    labelVi: 'Hàng đợi cơ bản',
    labelEn: 'Queueing Theory',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'theory',
    focusVi: 'thời gian chờ, tốc độ đến/xử lý và tắc nghẽn hệ thống',
    focusJa: '到着率・処理率・待ち時間とシステム混雑を理解します',
    examExample: '処理能力不足で待ち行列が伸びる理由を選ぶ',
    prerequisites: ['probability-statistics'],
    keywords: ['待ち行列', '到着率', '処理率'],
  },
  {
    id: 'algo',
    labelJa: 'アルゴリズム総論',
    labelVi: 'Algorithm tổng luận',
    labelEn: 'Algorithm Overview',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'khái niệm thuật toán, input/output, tính đúng đắn, hiệu quả và cách đọc bài 科目B',
    focusJa: 'アルゴリズムの入力・出力・正しさ・効率、科目Bの読み方を理解します',
    examExample: 'Chọn thuật toán phù hợp và trace kết quả của một đoạn pseudo-code ngắn',
    prerequisites: ['fe-algorithm'],
    keywords: ['アルゴリズム', '擬似言語', '計算量', 'トレース'],
  },
  {
    id: 'algorithm-basic',
    labelJa: 'アルゴリズム基礎',
    labelVi: 'Nền tảng thuật toán',
    labelEn: 'Algorithm Basics',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'chia bài toán thành input, xử lý, output và điều kiện dừng',
    focusJa: '入力・処理・出力・終了条件でアルゴリズムを読む力を固めます',
    examExample: '処理手順の正しい順序を選ぶ',
    prerequisites: ['fe-algorithm'],
    keywords: ['アルゴリズム', '入力', '出力'],
  },
  {
    id: 'flowchart',
    labelJa: 'フローチャート',
    labelVi: 'Flowchart',
    labelEn: 'Flowchart',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'đọc ký hiệu xử lý, điều kiện, lặp và luồng nhánh',
    focusJa: '処理・判断・繰返しの記号と流れを読みます',
    examExample: '判断記号の分岐先を追う',
    prerequisites: ['algorithm-basic'],
    keywords: ['フローチャート', '判断', '繰返し'],
  },
  {
    id: 'pseudo-code',
    labelJa: '擬似言語',
    labelVi: 'Pseudo-code FE',
    labelEn: 'Pseudo-code',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'đọc cú pháp giả, gán biến, vòng lặp và mảng theo kiểu 科目B',
    focusJa: '擬似言語の代入、ループ、配列を科目B形式で読みます',
    examExample: '配列Aの最大値を求める処理を追う',
    prerequisites: ['algorithm-basic'],
    keywords: ['擬似言語', '代入', '配列', 'ループ'],
  },
  {
    id: 'trace-table',
    labelJa: 'トレース表',
    labelVi: 'Bảng trace biến',
    labelEn: 'Trace Table',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'ghi từng bước giá trị biến để tránh nhầm vòng lặp',
    focusJa: '変数の値を1行ずつ表にしてループを追います',
    examExample: 'i,sum,A[i] の変化を書く',
    prerequisites: ['pseudo-code'],
    keywords: ['トレース', '変数', 'ループ'],
  },
  {
    id: 'complexity',
    labelJa: '計算量',
    labelVi: 'Độ phức tạp',
    labelEn: 'Complexity',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'Big-O, số vòng lặp và so sánh O(n), O(n log n), O(n²)',
    focusJa: 'Big-O、ループ回数、O(n)、O(n log n)、O(n²)を比較します',
    examExample: '二重ループの計算量を選ぶ',
    prerequisites: ['algorithm-basic'],
    keywords: ['計算量', 'Big-O', 'O(n²)'],
  },
  {
    id: 'array',
    labelJa: '配列',
    labelVi: 'Mảng',
    labelEn: 'Array',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'index, duyệt mảng, cập nhật phần tử và lỗi lệch chỉ số',
    focusJa: '添字、配列走査、要素更新、添字ずれを理解します',
    examExample: 'A[1]からA[n]まで合計する',
    prerequisites: ['pseudo-code'],
    keywords: ['配列', '添字', '走査'],
  },
  {
    id: 'two-dimensional-array',
    labelJa: '二次元配列',
    labelVi: 'Mảng hai chiều',
    labelEn: '2D Array',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'hàng/cột, bảng, ma trận và vòng lặp lồng nhau',
    focusJa: '行・列・表形式データと二重ループを理解します',
    examExample: '表の全セルを走査する順序を選ぶ',
    prerequisites: ['array'],
    keywords: ['二次元配列', '行', '列'],
  },
  {
    id: 'linked-list',
    labelJa: '連結リスト',
    labelVi: 'Danh sách liên kết',
    labelEn: 'Linked List',
    category: 'technology',
    level: 'topic',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'node, pointer, chèn/xóa và khác với array',
    focusJa: 'ノード、ポインタ、挿入・削除、配列との違いを理解します',
    examExample: '途中に要素を挿入する手順を選ぶ',
    prerequisites: ['fe-algorithm'],
    keywords: ['連結リスト', 'ポインタ', '挿入', '削除'],
  },
  {
    id: 'stack',
    labelJa: 'スタック',
    labelVi: 'Stack',
    labelEn: 'Stack',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'LIFO, push/pop, call stack và undo',
    focusJa: 'LIFO、push/pop、呼出しスタック、undoを理解します',
    examExample: 'push順とpop結果を求める',
    prerequisites: ['fe-algorithm'],
    keywords: ['スタック', 'LIFO', 'push', 'pop'],
  },
  {
    id: 'queue',
    labelJa: 'キュー',
    labelVi: 'Queue',
    labelEn: 'Queue',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'FIFO, enqueue/dequeue, buffer và scheduling',
    focusJa: 'FIFO、enqueue/dequeue、バッファ、スケジューリングを理解します',
    examExample: 'enqueue/dequeue後の先頭を求める',
    prerequisites: ['fe-algorithm'],
    keywords: ['キュー', 'FIFO', 'enqueue', 'dequeue'],
  },
  {
    id: 'deque',
    labelJa: 'デック',
    labelVi: 'Deque',
    labelEn: 'Deque',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'hai đầu thêm/xóa và trường hợp dùng trong thuật toán',
    focusJa: '両端で挿入・削除できるデータ構造を理解します',
    examExample: '両端キューを使う場面を選ぶ',
    prerequisites: ['queue'],
    keywords: ['デック', '両端キュー'],
  },
  {
    id: 'tree',
    labelJa: '木構造',
    labelVi: 'Cây',
    labelEn: 'Tree',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'root, leaf, depth, traversal và cây nhị phân',
    focusJa: '根、葉、深さ、走査、二分木を理解します',
    examExample: '木の深さと葉の数を読む',
    prerequisites: ['fe-algorithm'],
    keywords: ['木構造', '根', '葉', '深さ'],
  },
  {
    id: 'binary-search-tree',
    labelJa: '二分探索木',
    labelVi: 'Cây tìm kiếm nhị phân',
    labelEn: 'Binary Search Tree',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'quy tắc trái nhỏ/phải lớn, search/insert và traversal',
    focusJa: '左が小さく右が大きい探索木の検索・挿入を理解します',
    examExample: '値を探索するとき通るノードを選ぶ',
    prerequisites: ['tree'],
    keywords: ['二分探索木', '探索', '挿入'],
  },
  {
    id: 'heap-priority-queue',
    labelJa: 'ヒープ・優先度付きキュー',
    labelVi: 'Heap và priority queue',
    labelEn: 'Heap / Priority Queue',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'heap property, lấy min/max và dùng trong scheduling/sort',
    focusJa: 'ヒープ条件、最小・最大取り出し、優先度付きキューを理解します',
    examExample: '最小ヒープから取り出す値を選ぶ',
    prerequisites: ['tree'],
    keywords: ['ヒープ', '優先度付きキュー'],
  },
  {
    id: 'hash-table',
    labelJa: 'ハッシュ表',
    labelVi: 'Hash table',
    labelEn: 'Hash Table',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'hash function, collision, chaining/open addressing',
    focusJa: 'ハッシュ関数、衝突、チェイン法、オープンアドレス法を理解します',
    examExample: '衝突時の処理方法を選ぶ',
    prerequisites: ['fe-algorithm'],
    keywords: ['ハッシュ表', 'ハッシュ関数', '衝突'],
  },
  {
    id: 'linear-search',
    labelJa: '線形探索',
    labelVi: 'Tìm kiếm tuyến tính',
    labelEn: 'Linear Search',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'duyệt từ đầu đến cuối và tính số lần so sánh',
    focusJa: '先頭から順に調べる探索と比較回数を理解します',
    examExample: '最悪時の比較回数を求める',
    prerequisites: ['array'],
    keywords: ['線形探索', '逐次探索'],
  },
  {
    id: 'binary-search',
    labelJa: '二分探索',
    labelVi: 'Tìm kiếm nhị phân',
    labelEn: 'Binary Search',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'điều kiện mảng đã sort, cập nhật low/high/mid',
    focusJa: '整列済み配列、low/high/midの更新を理解します',
    examExample: '探索範囲が半分になる回数を求める',
    prerequisites: ['array'],
    keywords: ['二分探索', 'low', 'high', 'mid'],
  },
  {
    id: 'bubble-sort',
    labelJa: 'バブルソート',
    labelVi: 'Bubble sort',
    labelEn: 'Bubble Sort',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'đổi chỗ phần tử kề nhau và tính vòng lặp',
    focusJa: '隣接する要素を比較して交換し、各パス後の配列状態とループ回数を理解します',
    examExample: '1パス後の配列を選ぶ',
    prerequisites: ['array'],
    keywords: ['バブルソート', '交換'],
  },
  {
    id: 'selection-sort',
    labelJa: '選択ソート',
    labelVi: 'Selection sort',
    labelEn: 'Selection Sort',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'tìm min/max rồi đưa về vị trí đúng',
    focusJa: '最小値・最大値を選んで配置する手順を理解します',
    examExample: '最初の交換後の配列を選ぶ',
    prerequisites: ['array'],
    keywords: ['選択ソート', '最小値'],
  },
  {
    id: 'insertion-sort',
    labelJa: '挿入ソート',
    labelVi: 'Insertion sort',
    labelEn: 'Insertion Sort',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'chèn phần tử vào vùng đã sắp xếp',
    focusJa: '整列済み部分へ要素を挿入する手順を理解します',
    examExample: '途中状態の配列を読む',
    prerequisites: ['array'],
    keywords: ['挿入ソート', '整列済み部分'],
  },
  {
    id: 'quick-sort',
    labelJa: 'クイックソート',
    labelVi: 'Quick sort',
    labelEn: 'Quick Sort',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'pivot, partition và trường hợp xấu',
    focusJa: 'ピボット、分割、最悪計算量を理解します',
    examExample: 'pivotで左右に分ける結果を選ぶ',
    prerequisites: ['array'],
    keywords: ['クイックソート', 'pivot', 'partition'],
  },
  {
    id: 'merge-sort',
    labelJa: 'マージソート',
    labelVi: 'Merge sort',
    labelEn: 'Merge Sort',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'chia để trị và merge hai dãy đã sort',
    focusJa: '分割統治と整列済み列の併合を理解します',
    examExample: '2つの整列済み配列を併合する',
    prerequisites: ['array'],
    keywords: ['マージソート', '分割統治'],
  },
  {
    id: 'recursion',
    labelJa: '再帰',
    labelVi: 'Đệ quy',
    labelEn: 'Recursion',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'điều kiện dừng, stack call và trace kết quả trả về',
    focusJa: '終了条件、呼出しスタック、戻り値を追います',
    examExample: '階乗の再帰呼出し回数を数える',
    prerequisites: ['pseudo-code'],
    keywords: ['再帰', '終了条件', '呼出し'],
  },
  {
    id: 'dynamic-programming',
    labelJa: '動的計画法',
    labelVi: 'Quy hoạch động',
    labelEn: 'Dynamic Programming',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'lưu kết quả con để tránh tính lặp',
    focusJa: '部分問題の結果を保存して再計算を減らします',
    examExample: 'フィボナッチをメモ化で計算する',
    prerequisites: ['recursion'],
    keywords: ['動的計画法', 'メモ化', '部分問題'],
  },
  {
    id: 'greedy-algorithm',
    labelJa: '貪欲法',
    labelVi: 'Thuật toán tham lam',
    labelEn: 'Greedy Algorithm',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'mỗi bước chọn phương án tốt nhất cục bộ và rủi ro không tối ưu toàn cục',
    focusJa: '各ステップで局所最適を選ぶ考え方と限界を理解します',
    examExample: '硬貨問題で貪欲法が使えるか判断する',
    prerequisites: ['algorithm-basic'],
    keywords: ['貪欲法', '局所最適'],
  },
  {
    id: 'debugging-algorithm',
    labelJa: 'デバッグ・境界値',
    labelVi: 'Debug thuật toán và biên',
    labelEn: 'Debugging / Boundary',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'algorithm',
    focusVi: 'kiểm tra off-by-one, null/empty, first/last element',
    focusJa: '境界値、空データ、先頭・末尾、off-by-oneを確認します',
    examExample: 'for文の終了条件が1回多いか判断する',
    prerequisites: ['pseudo-code'],
    keywords: ['デバッグ', '境界値', 'off-by-one'],
  },
  {
    id: 'computer-system',
    labelJa: 'コンピュータシステム',
    labelVi: 'Hệ thống máy tính',
    labelEn: 'Computer System',
    category: 'technology',
    level: 'major',
    importance: 'high',
    phase: 'computer',
    focusVi: 'CPU, memory, storage, OS và thiết bị I/O phối hợp xử lý',
    focusJa: 'CPU、メモリ、ストレージ、OS、I/Oの役割を整理します',
    examExample: 'CPUと主記憶の関係を選ぶ',
    prerequisites: ['fe-computer'],
    keywords: ['CPU', 'メモリ', 'OS', 'I/O'],
  },
  {
    id: 'cpu',
    labelJa: 'CPU・命令実行',
    labelVi: 'CPU và chu kỳ lệnh',
    labelEn: 'CPU / Instruction Cycle',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'ALU, control unit, register, fetch-decode-execute',
    focusJa: 'ALU、制御装置、レジスタ、命令サイクルを理解します',
    examExample: '命令実行順序を選ぶ',
    prerequisites: ['computer-system'],
    keywords: ['CPU', 'ALU', 'レジスタ', '命令'],
  },
  {
    id: 'performance-mips',
    labelJa: '性能指標・MIPS',
    labelVi: 'Chỉ số hiệu năng',
    labelEn: 'Performance Metrics',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'MIPS, CPI, clock, throughput, response time',
    focusJa: 'MIPS、CPI、クロック、スループット、応答時間を理解します',
    examExample: 'クロックとCPIから実行時間を求める',
    prerequisites: ['cpu'],
    keywords: ['MIPS', 'CPI', 'クロック'],
  },
  {
    id: 'memory-cache',
    labelJa: 'メモリ・キャッシュ',
    labelVi: 'Memory và cache',
    labelEn: 'Memory / Cache',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'RAM, cache hit/miss, locality và tầng nhớ',
    focusJa: 'RAM、キャッシュヒット/ミス、局所性、記憶階層を理解します',
    examExample: '平均アクセス時間を計算する',
    prerequisites: ['computer-system'],
    keywords: ['キャッシュ', 'RAM', '局所性'],
  },
  {
    id: 'storage-raid',
    labelJa: '補助記憶・RAID',
    labelVi: 'Storage và RAID',
    labelEn: 'Storage / RAID',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'computer',
    focusVi: 'SSD/HDD, backup, RAID0/1/5 và redundancy',
    focusJa: 'SSD/HDD、バックアップ、RAID0/1/5、冗長性を理解します',
    examExample: 'RAID1とRAID5の違いを選ぶ',
    prerequisites: ['computer-system'],
    keywords: ['RAID', 'SSD', 'HDD', '冗長化'],
  },
  {
    id: 'operating-system',
    labelJa: 'OS・プロセス管理',
    labelVi: 'OS và process',
    labelEn: 'Operating System',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'process, thread, scheduling, interrupt và resource management',
    focusJa: 'プロセス、スレッド、スケジューリング、割込みを理解します',
    examExample: 'ラウンドロビンの順序を読む',
    prerequisites: ['computer-system'],
    keywords: ['OS', 'プロセス', 'スレッド', '割込み'],
  },
  {
    id: 'deadlock',
    labelJa: 'デッドロック',
    labelVi: 'Deadlock',
    labelEn: 'Deadlock',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'computer',
    focusVi: 'tài nguyên bị giữ chéo, điều kiện phát sinh và cách phòng tránh',
    focusJa: '資源待ちの循環、発生条件、予防策を理解します',
    examExample: 'デッドロック発生条件を選ぶ',
    prerequisites: ['operating-system'],
    keywords: ['デッドロック', '排他制御', '資源'],
  },
  {
    id: 'file-system',
    labelJa: 'ファイルシステム',
    labelVi: 'File system',
    labelEn: 'File System',
    category: 'technology',
    level: 'topic',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'directory, path, permission, backup và file allocation',
    focusJa: 'ディレクトリ、パス、アクセス権、ファイル配置を理解します',
    examExample: '絶対パスと相対パスを区別する',
    prerequisites: ['operating-system'],
    keywords: ['ファイル', 'ディレクトリ', 'パス'],
  },
  {
    id: 'virtual-memory',
    labelJa: '仮想記憶',
    labelVi: 'Bộ nhớ ảo',
    labelEn: 'Virtual Memory',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'computer',
    focusVi: 'paging, page fault, swapping và thrashing',
    focusJa: 'ページング、ページフォルト、スワッピング、スラッシングを理解します',
    examExample: 'ページフォルトが多い原因を選ぶ',
    prerequisites: ['memory-cache'],
    keywords: ['仮想記憶', 'ページング', 'スラッシング'],
  },
  {
    id: 'virtualization-cloud',
    labelJa: '仮想化・クラウド',
    labelVi: 'Virtualization và cloud',
    labelEn: 'Virtualization / Cloud',
    category: 'technology',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'VM/container, IaaS/PaaS/SaaS và scale',
    focusJa: 'VM、コンテナ、IaaS/PaaS/SaaS、スケールを理解します',
    examExample: 'IaaSとPaaSの責任範囲を選ぶ',
    prerequisites: ['computer-system'],
    keywords: ['仮想化', 'クラウド', 'IaaS', 'PaaS', 'SaaS'],
  },
  {
    id: 'container-docker',
    labelJa: 'コンテナ',
    labelVi: 'Container',
    labelEn: 'Container',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'container chia sẻ kernel, nhẹ hơn VM nhưng cần quản lý image',
    focusJa: 'コンテナはカーネルを共有し、VMより軽量だがイメージ管理が必要です',
    examExample: 'VMとコンテナの違いを選ぶ',
    prerequisites: ['virtualization-cloud'],
    keywords: ['コンテナ', 'Docker', 'イメージ'],
  },
  {
    id: 'distributed-system',
    labelJa: '分散システム',
    labelVi: 'Hệ thống phân tán',
    labelEn: 'Distributed System',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'scale-out, replication, consistency và fault tolerance',
    focusJa: 'スケールアウト、複製、一貫性、耐障害性を理解します',
    examExample: '負荷分散の目的を選ぶ',
    prerequisites: ['virtualization-cloud'],
    keywords: ['分散', '複製', '耐障害性'],
  },
  {
    id: 'programming',
    labelJa: 'プログラミング基礎',
    labelVi: 'Nền tảng lập trình',
    labelEn: 'Programming Basics',
    category: 'software',
    level: 'major',
    importance: 'high',
    phase: 'computer',
    focusVi: 'biến, kiểu dữ liệu, điều kiện, vòng lặp, hàm và debug',
    focusJa: '変数、型、条件分岐、ループ、関数、デバッグを理解します',
    examExample: '変数の値の変化を追う',
    prerequisites: ['fe-computer'],
    keywords: ['プログラミング', '変数', '関数'],
  },
  {
    id: 'variable-type',
    labelJa: '変数・データ型',
    labelVi: 'Biến và kiểu dữ liệu',
    labelEn: 'Variables / Types',
    category: 'software',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'int, string, boolean, array và ép kiểu',
    focusJa: 'int、string、boolean、array、型変換を理解します',
    examExample: '文字列と数値の加算結果を考える',
    prerequisites: ['programming'],
    keywords: ['変数', 'データ型', '型変換'],
  },
  {
    id: 'control-flow',
    labelJa: '条件分岐・繰返し',
    labelVi: 'Điều kiện và vòng lặp',
    labelEn: 'Control Flow',
    category: 'software',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'if, switch, for, while, break/continue',
    focusJa: 'if、switch、for、while、break/continueを理解します',
    examExample: 'while文が何回実行されるか数える',
    prerequisites: ['programming'],
    keywords: ['if', 'for', 'while', 'break'],
  },
  {
    id: 'function-procedure',
    labelJa: '関数・手続',
    labelVi: 'Hàm và thủ tục',
    labelEn: 'Function / Procedure',
    category: 'software',
    level: 'topic',
    importance: 'high',
    phase: 'computer',
    focusVi: 'parameter, return, scope và side effect',
    focusJa: '引数、戻り値、スコープ、副作用を理解します',
    examExample: '値渡しと参照渡しを区別する',
    prerequisites: ['programming'],
    keywords: ['関数', '引数', '戻り値', 'スコープ'],
  },
  {
    id: 'object-oriented',
    labelJa: 'オブジェクト指向',
    labelVi: 'Lập trình hướng đối tượng',
    labelEn: 'Object-Oriented Programming',
    category: 'software',
    level: 'topic',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'class, object, encapsulation, inheritance, polymorphism',
    focusJa: 'クラス、オブジェクト、カプセル化、継承、多態性を理解します',
    examExample: '継承と委譲の違いを選ぶ',
    prerequisites: ['programming'],
    keywords: ['OOP', 'クラス', '継承', '多態性'],
  },
  {
    id: 'api-json',
    labelJa: 'API・JSON',
    labelVi: 'API và JSON',
    labelEn: 'API / JSON',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'request/response, endpoint, JSON và status code',
    focusJa: 'リクエスト/レスポンス、エンドポイント、JSON、ステータスコードを理解します',
    examExample: 'REST APIの応答を読む',
    prerequisites: ['programming'],
    keywords: ['API', 'JSON', 'REST', 'HTTP'],
  },
  {
    id: 'testing-debugging',
    labelJa: '単体テスト・デバッグ',
    labelVi: 'Unit test và debug',
    labelEn: 'Testing / Debugging',
    category: 'software',
    level: 'detail',
    importance: 'high',
    phase: 'computer',
    focusVi: 'bộ kiểm tra, expected/actual, boundary, regression',
    focusJa: 'テストケース、期待値/実測値、境界値、回帰テストを理解します',
    examExample: '境界値テストケースを選ぶ',
    prerequisites: ['programming'],
    keywords: ['単体テスト', 'デバッグ', '境界値'],
  },
  {
    id: 'database-fe',
    labelJa: 'データベース総論',
    labelVi: 'Tổng quan database',
    labelEn: 'Database Overview',
    category: 'database',
    level: 'major',
    importance: 'high',
    phase: 'database',
    focusVi: 'data model, DBMS, schema, table và relationship',
    focusJa: 'データモデル、DBMS、スキーマ、表、関連を理解します',
    examExample: 'DBMSの役割を選ぶ',
    prerequisites: ['fe-database'],
    keywords: ['DBMS', 'スキーマ', '表'],
  },
  {
    id: 'er-model',
    labelJa: 'ERモデル',
    labelVi: 'ER model',
    labelEn: 'ER Model',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: 'entity, attribute, relationship, cardinality',
    focusJa: 'エンティティ、属性、関連、多重度を理解します',
    examExample: '1対多の関係をER図で読む',
    prerequisites: ['database-fe'],
    keywords: ['ER図', 'エンティティ', '関連'],
  },
  {
    id: 'relational-model',
    labelJa: '関係モデル',
    labelVi: 'Mô hình quan hệ',
    labelEn: 'Relational Model',
    category: 'database',
    level: 'detail',
    importance: 'high',
    phase: 'database',
    focusVi: 'table, tuple, attribute, primary key, foreign key',
    focusJa: '表、タプル、属性、主キー、外部キーを理解します',
    examExample: '主キーと外部キーを選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['関係モデル', '主キー', '外部キー'],
  },
  {
    id: 'normalization-fe',
    labelJa: '正規化',
    labelVi: 'Chuẩn hóa',
    labelEn: 'Normalization',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: '1NF/2NF/3NF, phụ thuộc hàm và tránh dư thừa',
    focusJa: '1NF/2NF/3NF、関数従属性、冗長性を理解します',
    examExample: '第3正規形への分解を選ぶ',
    prerequisites: ['relational-model'],
    keywords: ['正規化', '関数従属性', '3NF'],
  },
  {
    id: 'sql-select',
    labelJa: 'SELECT・WHERE',
    labelVi: 'SQL SELECT/WHERE',
    labelEn: 'SQL SELECT',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: 'SELECT, WHERE, ORDER BY và điều kiện lọc',
    focusJa: 'SELECT、WHERE、ORDER BY、抽出条件を理解します',
    examExample: '条件に合う行を抽出するSQLを選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['SELECT', 'WHERE', 'ORDER BY'],
  },
  {
    id: 'sql-join',
    labelJa: 'JOIN',
    labelVi: 'SQL JOIN',
    labelEn: 'SQL JOIN',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: 'INNER/LEFT JOIN, khóa liên kết và kết quả bảng',
    focusJa: 'INNER/LEFT JOIN、結合キー、結果表を理解します',
    examExample: '社員表と部署表を結合する',
    prerequisites: ['sql-select'],
    keywords: ['JOIN', 'INNER JOIN', 'LEFT JOIN'],
  },
  {
    id: 'sql-aggregate',
    labelJa: 'GROUP BY・HAVING',
    labelVi: 'GROUP BY và HAVING',
    labelEn: 'SQL Aggregate',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: 'COUNT/SUM/AVG, GROUP BY, HAVING vs WHERE',
    focusJa: 'COUNT/SUM/AVG、GROUP BY、HAVINGとWHEREの違いを理解します',
    examExample: '部署ごとの平均給与を求める',
    prerequisites: ['sql-select'],
    keywords: ['GROUP BY', 'HAVING', 'COUNT', 'AVG'],
  },
  {
    id: 'sql-subquery',
    labelJa: '副問合せ',
    labelVi: 'Subquery',
    labelEn: 'SQL Subquery',
    category: 'database',
    level: 'detail',
    importance: 'medium',
    phase: 'database',
    focusVi: 'subquery trong WHERE/FROM và đọc kết quả trung gian',
    focusJa: 'WHERE/FROM内の副問合せと中間結果を理解します',
    examExample: '平均以上の得点者を抽出する',
    prerequisites: ['sql-select'],
    keywords: ['副問合せ', 'サブクエリ'],
  },
  {
    id: 'transaction-fe',
    labelJa: 'トランザクション・ACID',
    labelVi: 'Transaction và ACID',
    labelEn: 'Transaction / ACID',
    category: 'database',
    level: 'topic',
    importance: 'high',
    phase: 'database',
    focusVi: 'atomicity, consistency, isolation, durability, commit/rollback',
    focusJa: 'ACID、commit/rollback、分離性を理解します',
    examExample: '送金処理でrollbackする場面を選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['トランザクション', 'ACID', 'commit', 'rollback'],
  },
  {
    id: 'lock-isolation',
    labelJa: 'ロック・分離レベル',
    labelVi: 'Lock và isolation',
    labelEn: 'Lock / Isolation',
    category: 'database',
    level: 'detail',
    importance: 'high',
    phase: 'database',
    focusVi: 'shared/exclusive lock, dirty read, non-repeatable read',
    focusJa: '共有/排他ロック、ダーティリード、反復不能読み取りを理解します',
    examExample: '排他ロックが必要な場面を選ぶ',
    prerequisites: ['transaction-fe'],
    keywords: ['ロック', '排他制御', '分離レベル'],
  },
  {
    id: 'index-db',
    labelJa: 'インデックス',
    labelVi: 'Index database',
    labelEn: 'Database Index',
    category: 'database',
    level: 'topic',
    importance: 'medium',
    phase: 'database',
    focusVi: 'index giúp search nhanh nhưng tốn cập nhật/storage',
    focusJa: '検索を高速化するが更新・容量コストがあることを理解します',
    examExample: '索引が有効な列を選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['インデックス', '索引', '検索'],
  },
  {
    id: 'view-db',
    labelJa: 'ビュー',
    labelVi: 'View database',
    labelEn: 'Database View',
    category: 'database',
    level: 'detail',
    importance: 'medium',
    phase: 'database',
    focusVi: 'view là bảng ảo để che giấu/đơn giản hóa truy vấn',
    focusJa: 'ビューは仮想表で、隠蔽・簡略化に使います',
    examExample: '利用者ごとに列を隠す',
    prerequisites: ['database-fe'],
    keywords: ['ビュー', '仮想表'],
  },
  {
    id: 'backup-recovery-db',
    labelJa: 'DBバックアップ・リカバリ',
    labelVi: 'Backup và recovery DB',
    labelEn: 'DB Backup / Recovery',
    category: 'database',
    level: 'detail',
    importance: 'high',
    phase: 'database',
    focusVi: 'full/incremental backup, log, recovery point',
    focusJa: 'フル/差分バックアップ、ログ、復旧時点を理解します',
    examExample: '障害後にログで復旧する',
    prerequisites: ['transaction-fe'],
    keywords: ['バックアップ', 'リカバリ', 'ログ'],
  },
  {
    id: 'data-warehouse',
    labelJa: 'データウェアハウス',
    labelVi: 'Data warehouse',
    labelEn: 'Data Warehouse',
    category: 'database',
    level: 'detail',
    importance: 'medium',
    phase: 'database',
    focusVi: 'DWH/ETL/OLAP dùng cho phân tích, khác OLTP',
    focusJa: 'DWH、ETL、OLAPとOLTPの違いを理解します',
    examExample: '売上分析にDWHを使う理由を選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['DWH', 'ETL', 'OLAP', 'OLTP'],
  },
  {
    id: 'network-fe',
    labelJa: 'ネットワーク総論',
    labelVi: 'Tổng quan network',
    labelEn: 'Network Overview',
    category: 'network',
    level: 'major',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'mạng truyền dữ liệu bằng protocol, địa chỉ, route và port',
    focusJa: 'プロトコル、アドレス、経路、ポートで通信を理解します',
    examExample: '通信に必要な要素を選ぶ',
    prerequisites: ['fe-network-security'],
    keywords: ['ネットワーク', 'プロトコル', 'ポート'],
  },
  {
    id: 'osi-tcpip',
    labelJa: 'OSI参照モデル・TCP/IP',
    labelVi: 'OSI và TCP/IP',
    labelEn: 'OSI / TCP-IP',
    category: 'network',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: '7 layer OSI, TCP/IP stack và vai trò từng tầng',
    focusJa: 'OSI 7層とTCP/IP階層、各層の役割を理解します',
    examExample: 'HTTPがどの層に近いか選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['OSI', 'TCP/IP', 'Layer'],
  },
  {
    id: 'ip-subnet',
    labelJa: 'IPアドレス・サブネット',
    labelVi: 'IP và subnet',
    labelEn: 'IP / Subnet',
    category: 'network',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'IPv4, subnet mask, CIDR, network/host bits',
    focusJa: 'IPv4、サブネットマスク、CIDR、network/host bitsを理解します',
    examExample: '/26 のホスト数を求める',
    prerequisites: ['network-fe'],
    keywords: ['IP', 'サブネット', 'CIDR'],
  },
  {
    id: 'routing',
    labelJa: 'ルーティング',
    labelVi: 'Routing',
    labelEn: 'Routing',
    category: 'network',
    level: 'detail',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'default gateway, routing table, static/dynamic routing',
    focusJa: 'デフォルトゲートウェイ、ルーティング表、静的/動的経路を理解します',
    examExample: '異なるネットワークへの経路を選ぶ',
    prerequisites: ['ip-subnet'],
    keywords: ['ルーティング', 'gateway', 'route'],
  },
  {
    id: 'tcp-udp',
    labelJa: 'TCP・UDP',
    labelVi: 'TCP và UDP',
    labelEn: 'TCP / UDP',
    category: 'network',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'TCP tin cậy/connection, UDP nhanh/không đảm bảo',
    focusJa: 'TCPの信頼性とUDPの軽量性を比較します',
    examExample: 'DNSでUDPが使われやすい理由を選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['TCP', 'UDP', 'コネクション'],
  },
  {
    id: 'dns-fe',
    labelJa: 'DNS',
    labelVi: 'DNS',
    labelEn: 'DNS',
    category: 'network',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'domain to IP, recursive/authoritative, record A/CNAME/MX',
    focusJa: 'ドメイン名をIPへ変換し、A/CNAME/MXレコードを理解します',
    examExample: '名前解決の流れを選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['DNS', 'Aレコード', 'CNAME', 'MX'],
  },
  {
    id: 'http-https',
    labelJa: 'HTTP・HTTPS',
    labelVi: 'HTTP và HTTPS',
    labelEn: 'HTTP / HTTPS',
    category: 'network',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'method, status code, cookie/session, TLS',
    focusJa: 'メソッド、ステータスコード、cookie/session、TLSを理解します',
    examExample: 'HTTPSが守る内容を選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['HTTP', 'HTTPS', 'TLS', 'cookie'],
  },
  {
    id: 'email-protocol',
    labelJa: 'メールプロトコル',
    labelVi: 'Email protocol',
    labelEn: 'Email Protocol',
    category: 'network',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'SMTP, POP3, IMAP và cơ chế gửi/nhận mail',
    focusJa: 'SMTP、POP3、IMAP、メール送受信を理解します',
    examExample: '送信に使うプロトコルを選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['SMTP', 'POP3', 'IMAP'],
  },
  {
    id: 'wireless-network',
    labelJa: '無線LAN',
    labelVi: 'Wi-Fi/Wireless',
    labelEn: 'Wireless Network',
    category: 'network',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'SSID, WPA2/3, interference và security',
    focusJa: 'SSID、WPA2/3、干渉、セキュリティを理解します',
    examExample: '安全な無線LAN設定を選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['無線LAN', 'SSID', 'WPA3'],
  },
  {
    id: 'load-balancer',
    labelJa: 'ロードバランサ',
    labelVi: 'Load balancer',
    labelEn: 'Load Balancer',
    category: 'network',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'phân phối request, health check, availability',
    focusJa: '要求分散、ヘルスチェック、可用性を理解します',
    examExample: 'Webサーバ増設時に使う装置を選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['ロードバランサ', '負荷分散'],
  },
  {
    id: 'security-fe',
    labelJa: '情報セキュリティ総論',
    labelVi: 'Tổng quan security',
    labelEn: 'Security Overview',
    category: 'security',
    level: 'major',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'CIA, risk, controls, threat/vulnerability/asset',
    focusJa: 'CIA、リスク、対策、脅威・脆弱性・資産を理解します',
    examExample: '脅威と脆弱性を区別する',
    prerequisites: ['fe-network-security'],
    keywords: ['情報セキュリティ', 'CIA', 'リスク'],
  },
  {
    id: 'cia-fe',
    labelJa: 'CIA',
    labelVi: 'CIA bảo mật',
    labelEn: 'CIA',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'confidentiality, integrity, availability và ví dụ kiểm soát',
    focusJa: '機密性・完全性・可用性と対策例を理解します',
    examExample: '改ざん対策は完全性に対応する',
    prerequisites: ['security-fe'],
    keywords: ['機密性', '完全性', '可用性'],
  },
  {
    id: 'cryptography',
    labelJa: '暗号技術',
    labelVi: 'Mã hóa',
    labelEn: 'Cryptography',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'symmetric/asymmetric, hash, digital signature, certificate',
    focusJa: '共通鍵/公開鍵、ハッシュ、電子署名、証明書を理解します',
    examExample: '電子署名の役割を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['暗号', '共通鍵', '公開鍵', 'ハッシュ'],
  },
  {
    id: 'pki-certificate',
    labelJa: 'PKI・電子証明書',
    labelVi: 'PKI và certificate',
    labelEn: 'PKI / Certificate',
    category: 'security',
    level: 'detail',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'CA, certificate chain, public key trust',
    focusJa: 'CA、証明書チェーン、公開鍵の信頼を理解します',
    examExample: '証明書で確認できることを選ぶ',
    prerequisites: ['cryptography'],
    keywords: ['PKI', 'CA', '証明書'],
  },
  {
    id: 'authentication-authorization',
    labelJa: '認証・認可',
    labelVi: 'Authentication và authorization',
    labelEn: 'Authentication / Authorization',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'xác minh danh tính vs cấp quyền truy cập',
    focusJa: '本人確認の認証と権限付与の認可を区別します',
    examExample: 'ログイン後に権限を確認する処理を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['認証', '認可', '権限'],
  },
  {
    id: 'mfa-password',
    labelJa: '多要素認証・パスワード',
    labelVi: 'MFA và password',
    labelEn: 'MFA / Password',
    category: 'security',
    level: 'detail',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'password policy, MFA factors, brute force và phishing',
    focusJa: 'パスワード方針、多要素、総当たり、フィッシングを理解します',
    examExample: 'MFAの要素を選ぶ',
    prerequisites: ['authentication-authorization'],
    keywords: ['MFA', 'パスワード', 'フィッシング'],
  },
  {
    id: 'access-control',
    labelJa: 'アクセス制御',
    labelVi: 'Access control',
    labelEn: 'Access Control',
    category: 'security',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'least privilege, ACL, RBAC và privilege management',
    focusJa: '最小権限、ACL、RBAC、権限管理を理解します',
    examExample: '職務変更時に権限を見直す',
    prerequisites: ['authentication-authorization'],
    keywords: ['アクセス制御', '最小権限', 'RBAC'],
  },
  {
    id: 'malware',
    labelJa: 'マルウェア',
    labelVi: 'Malware',
    labelEn: 'Malware',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'virus, worm, trojan, ransomware và countermeasure',
    focusJa: 'ウイルス、ワーム、トロイ、ランサムウェアと対策を理解します',
    examExample: 'ランサムウェア対策を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['マルウェア', 'ランサムウェア', 'ウイルス'],
  },
  {
    id: 'web-security',
    labelJa: 'Webセキュリティ',
    labelVi: 'Bảo mật web',
    labelEn: 'Web Security',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'XSS, SQL injection, CSRF và input validation',
    focusJa: 'XSS、SQLインジェクション、CSRF、入力検証を理解します',
    examExample: 'SQL injection対策を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['XSS', 'SQLインジェクション', 'CSRF'],
  },
  {
    id: 'firewall-waf',
    labelJa: 'ファイアウォール・WAF',
    labelVi: 'Firewall và WAF',
    labelEn: 'Firewall / WAF',
    category: 'security',
    level: 'detail',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'packet filter, stateful firewall, WAF bảo vệ HTTP app',
    focusJa: 'パケットフィルタ、ステートフル、WAFを理解します',
    examExample: 'WAFが防ぐ攻撃を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['ファイアウォール', 'WAF', 'パケットフィルタ'],
  },
  {
    id: 'ids-ips',
    labelJa: 'IDS・IPS',
    labelVi: 'IDS và IPS',
    labelEn: 'IDS / IPS',
    category: 'security',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'detect vs prevent, signature/anomaly detection',
    focusJa: '検知するIDSと防御するIPS、シグネチャ/異常検知を理解します',
    examExample: 'IDSとIPSの違いを選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['IDS', 'IPS', '侵入検知'],
  },
  {
    id: 'risk-backup',
    labelJa: 'リスク管理・バックアップ',
    labelVi: 'Risk và backup',
    labelEn: 'Risk / Backup',
    category: 'security',
    level: 'topic',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'risk analysis, backup strategy, RPO/RTO',
    focusJa: 'リスク分析、バックアップ戦略、RPO/RTOを理解します',
    examExample: 'RTOが短いシステムの対策を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['リスク', 'バックアップ', 'RPO', 'RTO'],
  },
  {
    id: 'log-monitoring',
    labelJa: 'ログ監視',
    labelVi: 'Log monitoring',
    labelEn: 'Log Monitoring',
    category: 'security',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'audit log, event monitoring, incident detection',
    focusJa: '監査ログ、イベント監視、インシデント検知を理解します',
    examExample: '不正アクセス調査でログを見る',
    prerequisites: ['security-fe'],
    keywords: ['ログ', '監視', '監査'],
  },
  {
    id: 'system-dev',
    labelJa: 'システム開発総論',
    labelVi: 'Tổng quan phát triển hệ thống',
    labelEn: 'System Development',
    category: 'management',
    level: 'major',
    importance: 'high',
    phase: 'development',
    focusVi: 'SDLC từ requirement đến operation, waterfall/agile',
    focusJa: '要求定義から運用までのSDLC、waterfall/agileを理解します',
    examExample: '工程の順序を選ぶ',
    prerequisites: ['fe-development'],
    keywords: ['SDLC', '開発工程', 'waterfall'],
  },
  {
    id: 'requirement-fe',
    labelJa: '要件定義',
    labelVi: 'Requirement definition',
    labelEn: 'Requirement Definition',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'functional/non-functional requirements và stakeholder agreement',
    focusJa: '機能要件・非機能要件、利害関係者合意を理解します',
    examExample: '性能要件が非機能要件であることを選ぶ',
    prerequisites: ['system-dev'],
    keywords: ['要件定義', '機能要件', '非機能要件'],
  },
  {
    id: 'basic-design',
    labelJa: '基本設計',
    labelVi: 'Basic design',
    labelEn: 'Basic Design',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'external design, screen/API/data design from user view',
    focusJa: '外部設計、画面/API/データ設計を利用者視点で理解します',
    examExample: '基本設計で決める内容を選ぶ',
    prerequisites: ['requirement-fe'],
    keywords: ['基本設計', '外部設計'],
  },
  {
    id: 'detailed-design',
    labelJa: '詳細設計',
    labelVi: 'Detailed design',
    labelEn: 'Detailed Design',
    category: 'management',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'module/internal design, logic, interface detail',
    focusJa: 'モジュール内部、処理ロジック、インタフェース詳細を理解します',
    examExample: '詳細設計に含まれる内容を選ぶ',
    prerequisites: ['basic-design'],
    keywords: ['詳細設計', '内部設計'],
  },
  {
    id: 'coding-standards',
    labelJa: 'コーディング規約',
    labelVi: 'Coding standards',
    labelEn: 'Coding Standards',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'naming, formatting, reviewability and defect prevention',
    focusJa: '命名、整形、レビュー容易性、欠陥防止を理解します',
    examExample: '規約を守る目的を選ぶ',
    prerequisites: ['programming'],
    keywords: ['コーディング規約', 'レビュー'],
  },
  {
    id: 'test-fe',
    labelJa: 'テスト工程',
    labelVi: 'Testing process',
    labelEn: 'Testing Process',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'unit, integration, system, acceptance test and V-model',
    focusJa: '単体・結合・システム・受入テスト、V字モデルを理解します',
    examExample: '結合テストの目的を選ぶ',
    prerequisites: ['system-dev'],
    keywords: ['テスト', '単体テスト', '結合テスト', 'V字モデル'],
  },
  {
    id: 'test-design',
    labelJa: 'テスト技法',
    labelVi: 'Test design techniques',
    labelEn: 'Test Design',
    category: 'management',
    level: 'detail',
    importance: 'high',
    phase: 'development',
    focusVi: 'equivalence partitioning, boundary value, decision table',
    focusJa: '同値分割、境界値、デシジョンテーブルを理解します',
    examExample: '境界値分析のケースを選ぶ',
    prerequisites: ['test-fe'],
    keywords: ['同値分割', '境界値', 'デシジョンテーブル'],
  },
  {
    id: 'version-control',
    labelJa: 'バージョン管理',
    labelVi: 'Version control',
    labelEn: 'Version Control',
    category: 'software',
    level: 'topic',
    importance: 'medium',
    phase: 'development',
    focusVi: 'commit, branch, merge, conflict and release tag',
    focusJa: 'commit、branch、merge、conflict、release tagを理解します',
    examExample: 'merge conflict時の対応を選ぶ',
    prerequisites: ['system-dev'],
    keywords: ['Git', 'branch', 'merge', 'commit'],
  },
  {
    id: 'agile-scrum',
    labelJa: 'アジャイル・スクラム',
    labelVi: 'Agile/Scrum',
    labelEn: 'Agile / Scrum',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'sprint, backlog, review, retrospective, product owner',
    focusJa: 'sprint、backlog、review、retrospective、product ownerを理解します',
    examExample: 'スクラムマスターの役割を選ぶ',
    prerequisites: ['system-dev'],
    keywords: ['アジャイル', 'スクラム', 'スプリント'],
  },
  {
    id: 'project-mgmt-fe',
    labelJa: 'プロジェクトマネジメント',
    labelVi: 'Project management',
    labelEn: 'Project Management',
    category: 'management',
    level: 'major',
    importance: 'high',
    phase: 'development',
    focusVi: 'scope, cost, schedule, quality, risk and stakeholder',
    focusJa: 'スコープ、コスト、スケジュール、品質、リスク、ステークホルダを理解します',
    examExample: '三大制約とスコープ変更時の影響を選ぶ',
    prerequisites: ['fe-development'],
    keywords: ['PM', 'スコープ', 'コスト', '品質'],
  },
  {
    id: 'wbs',
    labelJa: 'WBS',
    labelVi: 'WBS',
    labelEn: 'WBS',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'break work into tasks, estimate, assign and track',
    focusJa: '作業を分解し、見積り、担当、進捗管理につなげます',
    examExample: 'WBSの目的を選ぶ',
    prerequisites: ['project-mgmt-fe'],
    keywords: ['WBS', '作業分解'],
  },
  {
    id: 'critical-path',
    labelJa: 'クリティカルパス',
    labelVi: 'Critical path',
    labelEn: 'Critical Path',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'longest path, float/slack and project duration',
    focusJa: '最長経路、余裕時間、プロジェクト期間を理解します',
    examExample: 'アローダイアグラムで最長経路を選ぶ',
    prerequisites: ['project-mgmt-fe'],
    keywords: ['クリティカルパス', '余裕時間'],
  },
  {
    id: 'earned-value',
    labelJa: 'EVM',
    labelVi: 'Earned Value Management',
    labelEn: 'EVM',
    category: 'management',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'PV, EV, AC, SPI, CPI and project health',
    focusJa: 'PV、EV、AC、SPI、CPIで進捗とコストを判断します',
    examExample: 'CPIが1未満の意味を選ぶ',
    prerequisites: ['project-mgmt-fe'],
    keywords: ['EVM', 'PV', 'EV', 'AC', 'CPI', 'SPI'],
  },
  {
    id: 'quality-management',
    labelJa: '品質管理',
    labelVi: 'Quality management',
    labelEn: 'Quality Management',
    category: 'management',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'quality plan, review, metrics and defect management',
    focusJa: '品質計画、レビュー、メトリクス、欠陥管理を理解します',
    examExample: 'レビューの目的を選ぶ',
    prerequisites: ['project-mgmt-fe'],
    keywords: ['品質管理', 'レビュー', '欠陥'],
  },
  {
    id: 'service-mgmt-fe',
    labelJa: 'サービスマネジメント',
    labelVi: 'Service management',
    labelEn: 'Service Management',
    category: 'management',
    level: 'major',
    importance: 'high',
    phase: 'development',
    focusVi: 'ITIL, incident/problem/change, service desk',
    focusJa: 'ITIL、incident/problem/change、service deskを理解します',
    examExample: 'incidentとproblemを区別する',
    prerequisites: ['fe-development'],
    keywords: ['ITIL', 'インシデント', '問題管理'],
  },
  {
    id: 'sla',
    labelJa: 'SLA',
    labelVi: 'SLA',
    labelEn: 'SLA',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'service level, availability, response time and penalties',
    focusJa: 'サービスレベル、可用性、応答時間、ペナルティを理解します',
    examExample: 'SLAに含める指標を選ぶ',
    prerequisites: ['service-mgmt-fe'],
    keywords: ['SLA', '可用性', '応答時間'],
  },
  {
    id: 'bcp',
    labelJa: 'BCP・DR',
    labelVi: 'BCP và DR',
    labelEn: 'BCP / DR',
    category: 'management',
    level: 'topic',
    importance: 'high',
    phase: 'development',
    focusVi: 'business continuity, disaster recovery, RTO/RPO',
    focusJa: '事業継続、災害復旧、RTO/RPOを理解します',
    examExample: 'RTOとRPOの違いを選ぶ',
    prerequisites: ['service-mgmt-fe'],
    keywords: ['BCP', 'DR', 'RTO', 'RPO'],
  },
  {
    id: 'it-governance',
    labelJa: 'ITガバナンス',
    labelVi: 'IT governance',
    labelEn: 'IT Governance',
    category: 'management',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'align IT with business, control and accountability',
    focusJa: 'ITを経営目標に合わせ、統制と説明責任を担保します',
    examExample: 'ITガバナンスの目的を選ぶ',
    prerequisites: ['service-mgmt-fe'],
    keywords: ['ITガバナンス', '統制'],
  },
  {
    id: 'strategy-fe',
    labelJa: '経営戦略',
    labelVi: 'Chiến lược kinh doanh',
    labelEn: 'Business Strategy',
    category: 'business',
    level: 'major',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'strategy frameworks, competition and IT investment',
    focusJa: '経営戦略、競争、IT投資の考え方を理解します',
    examExample: 'SWOT分析の使い方を選ぶ',
    prerequisites: ['fe-strategy'],
    keywords: ['経営戦略', 'SWOT', '競争'],
  },
  {
    id: 'swot',
    labelJa: 'SWOT分析',
    labelVi: 'SWOT',
    labelEn: 'SWOT',
    category: 'business',
    level: 'topic',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'strength/weakness/opportunity/threat and internal/external factors',
    focusJa: '強み・弱み・機会・脅威と内部/外部要因を区別します',
    examExample: '機会が外部環境であることを選ぶ',
    prerequisites: ['strategy-fe'],
    keywords: ['SWOT', '強み', '機会'],
  },
  {
    id: 'kpi-kgi',
    labelJa: 'KPI・KGI',
    labelVi: 'KPI và KGI',
    labelEn: 'KPI / KGI',
    category: 'business',
    level: 'topic',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'KGI là mục tiêu cuối, KPI là chỉ số trung gian đo tiến độ',
    focusJa: 'KGIは最終目標、KPIは進捗指標として理解します',
    examExample: '売上目標とCVR指標を区別する',
    prerequisites: ['strategy-fe'],
    keywords: ['KPI', 'KGI', '指標'],
  },
  {
    id: 'bsc',
    labelJa: 'バランススコアカード',
    labelVi: 'Balanced Scorecard',
    labelEn: 'Balanced Scorecard',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'financial/customer/process/learning perspectives',
    focusJa: '財務・顧客・業務プロセス・学習成長の視点を理解します',
    examExample: 'BSCの4視点を選ぶ',
    prerequisites: ['strategy-fe'],
    keywords: ['BSC', '財務', '顧客'],
  },
  {
    id: 'marketing-basic',
    labelJa: 'マーケティング基礎',
    labelVi: 'Marketing cơ bản',
    labelEn: 'Marketing Basics',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'STP, 4P, customer segmentation and positioning',
    focusJa: 'STP、4P、セグメント、ポジショニングを理解します',
    examExample: '4Pに含まれる要素を選ぶ',
    prerequisites: ['strategy-fe'],
    keywords: ['STP', '4P', 'セグメント'],
  },
  {
    id: 'accounting-fe',
    labelJa: '会計・財務',
    labelVi: 'Kế toán và tài chính',
    labelEn: 'Accounting / Finance',
    category: 'business',
    level: 'topic',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'profit/loss, balance sheet, cash flow and break-even',
    focusJa: '損益、貸借、キャッシュフロー、損益分岐点を理解します',
    examExample: '損益分岐点売上高を求める',
    prerequisites: ['fe-strategy'],
    keywords: ['会計', '財務', '損益分岐点'],
  },
  {
    id: 'depreciation',
    labelJa: '減価償却',
    labelVi: 'Khấu hao',
    labelEn: 'Depreciation',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'allocate asset cost over useful life; straight-line/declining balance',
    focusJa: '固定資産の取得原価を耐用年数に配分します',
    examExample: '定額法の償却費を求める',
    prerequisites: ['accounting-fe'],
    keywords: ['減価償却', '定額法'],
  },
  {
    id: 'break-even',
    labelJa: '損益分岐点',
    labelVi: 'Điểm hòa vốn',
    labelEn: 'Break-even Point',
    category: 'business',
    level: 'detail',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'fixed cost, variable cost, contribution margin',
    focusJa: '固定費、変動費、限界利益で損益分岐点を求めます',
    examExample: '固定費と変動費から損益分岐点を計算する',
    prerequisites: ['accounting-fe'],
    keywords: ['損益分岐点', '固定費', '変動費'],
  },
  {
    id: 'law-fe',
    labelJa: '法務・コンプライアンス',
    labelVi: 'Luật và compliance',
    labelEn: 'Law / Compliance',
    category: 'business',
    level: 'topic',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'copyright, personal information, contract and compliance',
    focusJa: '著作権、個人情報、契約、コンプライアンスを理解します',
    examExample: '個人情報保護の目的を選ぶ',
    prerequisites: ['fe-strategy'],
    keywords: ['法務', 'コンプライアンス', '著作権'],
  },
  {
    id: 'intellectual-property',
    labelJa: '知的財産権',
    labelVi: 'Sở hữu trí tuệ',
    labelEn: 'Intellectual Property',
    category: 'business',
    level: 'detail',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'copyright, patent, trademark, trade secret',
    focusJa: '著作権、特許権、商標権、営業秘密を区別します',
    examExample: 'ソフトウェアの著作権を選ぶ',
    prerequisites: ['law-fe'],
    keywords: ['知的財産', '著作権', '特許', '商標'],
  },
  {
    id: 'personal-info-law',
    labelJa: '個人情報保護',
    labelVi: 'Bảo vệ thông tin cá nhân',
    labelEn: 'Personal Information Protection',
    category: 'security',
    level: 'detail',
    importance: 'high',
    phase: 'strategy',
    focusVi: 'personal data handling, consent, purpose and leakage response',
    focusJa: '個人情報の取扱い、同意、利用目的、漏えい対応を理解します',
    examExample: '利用目的の通知が必要な場面を選ぶ',
    prerequisites: ['law-fe'],
    keywords: ['個人情報', 'プライバシー', '同意'],
  },
  {
    id: 'standardization',
    labelJa: '標準化',
    labelVi: 'Tiêu chuẩn hóa',
    labelEn: 'Standardization',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'ISO/JIS, standard benefits and interoperability',
    focusJa: 'ISO/JIS、標準化の利点、相互運用性を理解します',
    examExample: '標準化のメリットを選ぶ',
    prerequisites: ['strategy-fe'],
    keywords: ['ISO', 'JIS', '標準化'],
  },
  {
    id: 'bit-operation',
    labelJa: 'ビット演算',
    labelVi: 'Phép toán bit',
    labelEn: 'Bit Operation',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'shift, mask, AND/OR để bật/tắt bit',
    focusJa: 'シフト、マスク、AND/ORでbitを操作します',
    examExample: 'マスクで特定bitを取り出す',
    prerequisites: ['binary-number'],
    keywords: ['ビット演算', 'シフト', 'マスク'],
  },
  {
    id: 'string-processing',
    labelJa: '文字列処理',
    labelVi: 'Xử lý chuỗi',
    labelEn: 'String Processing',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'length, substring, search, replace và loop theo ký tự',
    focusJa: '文字列長、部分文字列、検索、置換、文字ごとのループを理解します',
    examExample: '文字列中の文字数を数える',
    prerequisites: ['pseudo-code'],
    keywords: ['文字列', 'substring', '検索'],
  },
  {
    id: 'file-processing-algorithm',
    labelJa: 'ファイル処理アルゴリズム',
    labelVi: 'Thuật toán xử lý file',
    labelEn: 'File Processing Algorithm',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'read line, EOF, parse record and accumulate',
    focusJa: '行読込み、EOF、レコード解析、集計を理解します',
    examExample: 'EOFまで合計を求める',
    prerequisites: ['pseudo-code'],
    keywords: ['ファイル処理', 'EOF', 'レコード'],
  },
  {
    id: 'state-transition',
    labelJa: '状態遷移',
    labelVi: 'State transition',
    labelEn: 'State Transition',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'algorithm',
    focusVi: 'state machine, event, transition table and diagram',
    focusJa: '状態機械、イベント、遷移表、遷移図を理解します',
    examExample: '入力列後の状態を選ぶ',
    prerequisites: ['automata-formal-language'],
    keywords: ['状態遷移', '状態機械'],
  },
  {
    id: 'compiler-interpreter',
    labelJa: 'コンパイラ・インタプリタ',
    labelVi: 'Compiler và interpreter',
    labelEn: 'Compiler / Interpreter',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'compile trước vs chạy từng dòng; error timing and portability',
    focusJa: '事前翻訳と逐次実行、エラー検出タイミングを理解します',
    examExample: 'コンパイラ方式の特徴を選ぶ',
    prerequisites: ['programming'],
    keywords: ['コンパイラ', 'インタプリタ'],
  },
  {
    id: 'middleware',
    labelJa: 'ミドルウェア',
    labelVi: 'Middleware',
    labelEn: 'Middleware',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'DBMS, web/app server, message queue as common services',
    focusJa: 'DBMS、Web/APサーバ、MQなど共通機能を提供します',
    examExample: 'ミドルウェアの例を選ぶ',
    prerequisites: ['computer-system'],
    keywords: ['ミドルウェア', 'APサーバ', 'MQ'],
  },
  {
    id: 'availability-reliability',
    labelJa: '可用性・信頼性',
    labelVi: 'Availability và reliability',
    labelEn: 'Availability / Reliability',
    category: 'technology',
    level: 'detail',
    importance: 'high',
    phase: 'computer',
    focusVi: 'MTBF, MTTR, availability formula and redundancy',
    focusJa: 'MTBF、MTTR、稼働率、冗長化を理解します',
    examExample: '稼働率を計算する',
    prerequisites: ['distributed-system'],
    keywords: ['可用性', '信頼性', 'MTBF', 'MTTR'],
  },
  {
    id: 'fault-tolerance',
    labelJa: 'フォールトトレランス',
    labelVi: 'Fault tolerance',
    labelEn: 'Fault Tolerance',
    category: 'technology',
    level: 'detail',
    importance: 'medium',
    phase: 'computer',
    focusVi: 'failover, redundancy, graceful degradation',
    focusJa: 'フェイルオーバ、冗長化、縮退運転を理解します',
    examExample: '障害時に継続する仕組みを選ぶ',
    prerequisites: ['availability-reliability'],
    keywords: ['フォールトトレランス', 'フェイルオーバ'],
  },
  {
    id: 'db-security',
    labelJa: 'データベースセキュリティ',
    labelVi: 'Database security',
    labelEn: 'Database Security',
    category: 'database',
    level: 'detail',
    importance: 'high',
    phase: 'database',
    focusVi: 'privilege, view, encryption, audit log and masking',
    focusJa: '権限、ビュー、暗号化、監査ログ、マスキングを理解します',
    examExample: '給与列を隠す方法を選ぶ',
    prerequisites: ['database-fe'],
    keywords: ['DBセキュリティ', '権限', 'マスキング'],
  },
  {
    id: 'data-modeling-cardinality',
    labelJa: '多重度',
    labelVi: 'Cardinality',
    labelEn: 'Cardinality',
    category: 'database',
    level: 'detail',
    importance: 'high',
    phase: 'database',
    focusVi: 'one-to-one, one-to-many, many-to-many and bridge table',
    focusJa: '1対1、1対多、多対多、中間表を理解します',
    examExample: '多対多を中間表で表す',
    prerequisites: ['er-model'],
    keywords: ['多重度', '1対多', '多対多'],
  },
  {
    id: 'vpn',
    labelJa: 'VPN',
    labelVi: 'VPN',
    labelEn: 'VPN',
    category: 'network',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'encrypted tunnel for remote access/site-to-site',
    focusJa: '暗号化トンネルでリモートアクセスや拠点間通信を守ります',
    examExample: 'VPNの目的を選ぶ',
    prerequisites: ['network-fe'],
    keywords: ['VPN', 'トンネル', 'リモートアクセス'],
  },
  {
    id: 'zero-trust',
    labelJa: 'ゼロトラスト',
    labelVi: 'Zero Trust',
    labelEn: 'Zero Trust',
    category: 'security',
    level: 'detail',
    importance: 'medium',
    phase: 'network-security',
    focusVi: 'never trust, always verify, device/user/context checks',
    focusJa: '常に検証し、端末・利用者・状況を確認します',
    examExample: 'ゼロトラストの考え方を選ぶ',
    prerequisites: ['access-control'],
    keywords: ['ゼロトラスト', '検証', '最小権限'],
  },
  {
    id: 'incident-response',
    labelJa: 'インシデント対応',
    labelVi: 'Incident response',
    labelEn: 'Incident Response',
    category: 'security',
    level: 'detail',
    importance: 'high',
    phase: 'network-security',
    focusVi: 'detect, contain, eradicate, recover and lessons learned',
    focusJa: '検知、封じ込め、根絶、復旧、再発防止を理解します',
    examExample: 'マルウェア発見後の初動を選ぶ',
    prerequisites: ['security-fe'],
    keywords: ['インシデント', '封じ込め', '復旧'],
  },
  {
    id: 'devops-cicd',
    labelJa: 'DevOps・CI/CD',
    labelVi: 'DevOps và CI/CD',
    labelEn: 'DevOps / CI-CD',
    category: 'software',
    level: 'detail',
    importance: 'medium',
    phase: 'development',
    focusVi: 'automate build/test/deploy and shorten feedback loop',
    focusJa: 'build/test/deployを自動化し、フィードバックを短縮します',
    examExample: 'CIの目的を選ぶ',
    prerequisites: ['system-dev'],
    keywords: ['DevOps', 'CI/CD', '自動化'],
  },
  {
    id: 'ui-ux-basic',
    labelJa: 'UI/UX基礎',
    labelVi: 'UI/UX cơ bản',
    labelEn: 'UI / UX Basics',
    category: 'software',
    level: 'detail',
    importance: 'low',
    phase: 'development',
    focusVi: 'usability, accessibility, error prevention and user flow',
    focusJa: '使いやすさ、アクセシビリティ、誤操作防止、導線を理解します',
    examExample: '入力フォームの改善策を選ぶ',
    prerequisites: ['basic-design'],
    keywords: ['UI', 'UX', 'ユーザビリティ'],
  },
  {
    id: 'roi-investment',
    labelJa: '投資評価・ROI',
    labelVi: 'Đánh giá đầu tư ROI',
    labelEn: 'ROI / Investment',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'ROI, payback period and cost-benefit for IT investment',
    focusJa: 'ROI、回収期間、費用対効果でIT投資を評価します',
    examExample: 'ROIの計算式を選ぶ',
    prerequisites: ['accounting-fe'],
    keywords: ['ROI', '投資評価', '費用対効果'],
  },
  {
    id: 'outsourcing',
    labelJa: 'アウトソーシング',
    labelVi: 'Outsourcing',
    labelEn: 'Outsourcing',
    category: 'business',
    level: 'detail',
    importance: 'medium',
    phase: 'strategy',
    focusVi: 'external vendor, contract, SLA and risk of dependency',
    focusJa: '外部委託、契約、SLA、依存リスクを理解します',
    examExample: '外部委託の注意点を選ぶ',
    prerequisites: ['strategy-fe'],
    keywords: ['アウトソーシング', 'SLA', '委託'],
  },
];

const keywordText = (item: FundamentalInfoTopicRow): string => item.keywords.slice(0, 4).join(' / ');

const makeCatalogItem = (item: FundamentalInfoTopicRow): FundamentalInfoCatalogItem => ({
  ...item,
  definitionVi: `${item.labelVi} là chủ đề thuộc 基本情報 cần học theo hướng hiểu cơ chế, biết dùng trong bài tính hoặc tình huống hệ thống. Trọng tâm của bài này là ${item.focusVi}. Người mới nên bắt đầu bằng cách tự trả lời ba câu: khái niệm này dùng để làm gì, dữ kiện đề cho là gì, và đáp án đúng phải thỏa điều kiện nào. Từ khóa cần bám: ${keywordText(item)}.`,
  definitionJa: `${item.labelJa} は基本情報技術者試験で重要なテーマです。単なる用語暗記ではなく、仕組み・利用場面・計算または判断の流れとして理解します。このlessonでは ${item.focusJa}。重要語は ${keywordText(item)} です。`,
  whyImportantVi: `Trong 基本情報, ${item.labelVi} thường liên kết trực tiếp với câu hỏi 科目A và cũng xuất hiện gián tiếp trong 科目B khi phải đọc pseudo-code, bảng, mạng, SQL hoặc tình huống vận hành. Học kỹ bài này giúp bạn không chọn đáp án theo cảm giác. Khi gặp đề, hãy tách thành: dữ kiện đầu vào, quy tắc/công thức áp dụng, kết quả trung gian, rồi mới chọn đáp án. Ví dụ hay gặp: ${item.examExample}.`,
  whyImportantJa: `基本情報では ${item.labelJa} が科目Aの知識問題だけでなく、科目Bの処理読解やシステム判断にもつながります。問題文のキーワードだけで選ばず、入力条件、適用する規則、途中結果、最終判断の順に確認することが大切です。代表例: ${item.examExample}。`,
  examPatternsVi: [
    `Dạng 1: hỏi định nghĩa hoặc vai trò của ${item.labelVi}; cần chọn mô tả đúng nhất theo ngữ cảnh, không chọn đáp án chỉ có từ khóa giống trong đề.`,
    `Dạng 2: cho ví dụ nhỏ như “${item.examExample}” rồi yêu cầu tính kết quả, chọn bước xử lý tiếp theo hoặc xác định nguyên nhân đúng.`,
    `Dạng 3: so sánh ${item.labelVi} với khái niệm gần giống; hãy lập bảng khác nhau về mục đích, dữ liệu đầu vào, kết quả và rủi ro.`,
    `Dạng 4: áp dụng vào tình huống vận hành hoặc phát triển hệ thống; cần đọc câu hỏi theo chuỗi nguyên nhân → cơ chế → biện pháp.`,
    `Dạng 5: câu tiếng Nhật dài; hãy gạch chân chủ ngữ, điều kiện phủ định, số liệu và từ như 最も適切 / 誤っている trước khi chọn đáp án.`,
  ],
  examPatternsJa: [
    `形式1: ${item.labelJa} の定義・役割を問う。キーワード一致だけでなく、文脈に合う説明を選びます。`,
    `形式2: 「${item.examExample}」のような小さな例から、計算結果・次の処理・原因を判断します。`,
    `形式3: 似た用語との比較問題。目的、入力、結果、注意点を表にして区別します。`,
    `形式4: 開発・運用・セキュリティの場面で、原因 → 仕組み → 対策の順に考えます。`,
    `形式5: 長い日本語問題では、条件、否定表現、数値、最も適切/誤っているを先に確認します。`,
  ],
  commonMistakesVi: [
    `Chỉ nhớ tên ${item.labelVi} nhưng không giải thích được bằng ví dụ hoặc không biết khi nào dùng trong hệ thống thật.`,
    `Không viết bảng trace/bảng so sánh khi có số liệu, điều kiện, vòng lặp, SQL hoặc luồng xử lý nên dễ lệch một bước.`,
    `Nhầm với khái niệm gần giống vì chỉ nhìn từ khóa; đặc biệt cần so sánh mục đích, đầu vào và kết quả của từng lựa chọn.`,
    `Bỏ qua từ phủ định trong tiếng Nhật như ない, 誤っている, 適切でない hoặc đọc thiếu điều kiện “nếu/chỉ khi”.`,
    `Chọn đáp án nghe có vẻ chuyên môn nhưng không giải quyết đúng yêu cầu đề bài hoặc không phù hợp với ràng buộc đã cho.`,
  ],
  commonMistakesJa: [
    `${item.labelJa} の名称だけを覚えて、例や利用場面を説明できない。`,
    `数値・条件・ループ・SQL・通信の流れがあるのに、表や図を書かず頭だけで解こうとする。`,
    `似た用語をキーワードだけで判断し、目的・入力・結果・リスクの違いを確認しない。`,
    `ない、誤っている、適切でない、ただし、最も適切などの条件を読み落とす。`,
    `専門用語らしい選択肢を選ぶが、問題の制約や目的に合っていない。`,
  ],
  memoryTipVi: `${item.labelVi}: nhớ theo 4 bước “định nghĩa → ví dụ → bẫy → cách giải”. Khi ôn nhanh, hãy tự tạo một câu hỏi mini với từ khóa ${keywordText(item)} và giải thích lại bằng tiếng Việt trong 30 giây.`,
  memoryTipJa: `${item.labelJa} は「定義 → 例 → ひっかけ → 解き方」で覚えます。復習時は ${keywordText(item)} を使って30秒で説明できるか確認します。`,
  examples: [item.examExample, ...item.keywords.slice(0, 3)],
  keywords: item.keywords,
});

export const fundamentalInfoCatalog: FundamentalInfoCatalogItem[] = fundamentalInfoTopicRows.map(makeCatalogItem);
