import { fundamentalInfoV79RKamokuBMasteryScenarios } from './v79rKamokuBMastery';
import { fundamentalInfoV81RMixedMockMiniSet } from './v81rMixedMockMiniSet';
import { fundamentalInfoV85RTraceBank } from './v85rKamokuBTraceBank';
import { fundamentalInfoV90RMockMiniSet } from './v90rMockMiniSet';

export type FundamentalScenarioKind = 'japanese-scenario' | 'long-trace' | 'sql-step';

export interface FundamentalScenarioChoice {
  ja: string;
  vi: string;
  whyVi: string;
  whyJa: string;
}

export interface FundamentalExamScenario {
  id: string;
  kind: FundamentalScenarioKind;
  titleJa: string;
  titleVi: string;
  domain: 'algorithm' | 'database' | 'network' | 'security' | 'management' | 'strategy';
  difficulty: 'standard' | 'hard';
  relatedNodeIds: string[];
  passageJa: string;
  passageVi: string;
  questionJa: string;
  questionVi: string;
  code?: string;
  table?: string;
  traceSteps?: { step: string; variables: string; noteJa: string; noteVi: string }[];
  sqlSteps?: { step: string; result: string; noteJa: string; noteVi: string }[];
  choices: FundamentalScenarioChoice[];
  answerIndex: number;
  trapJa: string;
  trapVi: string;
  examTipJa: string;
  examTipVi: string;
}

const scenario = (item: FundamentalExamScenario) => item;

export const fundamentalInfoExamScenarios: FundamentalExamScenario[] = [
  scenario({
    id: 'v61-ja-appropriate-availability', kind: 'japanese-scenario', domain: 'security', difficulty: 'standard', relatedNodeIds: ['cia-fe', 'availability-reliability', 'bcp'],
    titleJa: '「最も適切」な可用性対策', titleVi: 'Chọn biện pháp availability phù hợp nhất',
    passageJa: 'あるWebサービスでは，災害時にも利用者が重要な機能を継続して利用できることを重視している。情報セキュリティの三要素のうち，可用性を高める対策として最も適切なものを選べ。',
    passageVi: 'Một web service muốn người dùng vẫn dùng được chức năng quan trọng khi có sự cố hoặc thiên tai. Hãy chọn biện pháp phù hợp nhất để tăng availability trong CIA.',
    questionJa: '可用性を高める対策として最も適切なものはどれか。', questionVi: 'Biện pháp nào phù hợp nhất để tăng availability?',
    choices: [
      { ja: '入力値を暗号化して保存する', vi: 'Mã hóa input khi lưu', whyVi: 'Mã hóa chủ yếu liên quan confidentiality, không trực tiếp tăng khả năng dùng liên tục.', whyJa: '暗号化は主に機密性に関係します。' },
      { ja: '冗長構成とバックアップサイトを用意する', vi: 'Chuẩn bị redundant system và backup site', whyVi: 'Đúng. Redundancy/backup site giúp dịch vụ tiếp tục hoạt động khi một phần hỏng.', whyJa: '正解。冗長化や予備サイトは障害時の継続利用に有効です。' },
      { ja: '利用者ごとにアクセス権限を細かく設定する', vi: 'Thiết lập quyền truy cập chi tiết', whyVi: 'Access control thuộc authorization/confidentiality.', whyJa: 'アクセス制御は認可・機密性寄りです。' },
      { ja: 'データの改ざん検知用ハッシュ値を保存する', vi: 'Lưu hash để phát hiện sửa đổi', whyVi: 'Hash phát hiện integrity violation, không phải availability chính.', whyJa: 'ハッシュは完全性の確認に使います。' },
    ], answerIndex: 1,
    trapJa: '「最も適切」は、全部よさそうでも設問の観点に最も直接対応するものを選ぶ。',
    trapVi: 'Bẫy “phù hợp nhất”: nhiều đáp án đều tốt cho security, nhưng phải bám đúng availability.',
    examTipJa: '可用性＝使いたい時に使える。冗長化、バックアップ、フェールオーバを連想する。',
    examTipVi: 'Availability = dùng được khi cần. Nhớ redundancy, backup, failover.',
  }),
  scenario({
    id: 'v61-ja-incorrect-sql-injection', kind: 'japanese-scenario', domain: 'security', difficulty: 'hard', relatedNodeIds: ['web-security', 'db-security', 'sql-select'],
    titleJa: '「誤っている」SQLインジェクション対策', titleVi: 'Chọn phát biểu sai về SQL injection',
    passageJa: 'Webアプリケーションで検索画面を実装する。SQLインジェクション対策としての記述のうち，誤っているものを選べ。',
    passageVi: 'Một web app có màn hình tìm kiếm. Chọn phát biểu sai về biện pháp chống SQL injection.',
    questionJa: 'SQLインジェクション対策として誤っているものはどれか。', questionVi: 'Đâu là phát biểu sai?',
    choices: [
      { ja: 'プレースホルダを用いたSQL文を使用する', vi: 'Dùng nội dung nháp/prepared statement', whyVi: 'Đúng là biện pháp tốt.', whyJa: 'これは有効な対策です。' },
      { ja: '入力値の形式や長さを検査する', vi: 'Kiểm tra format và độ dài input', whyVi: 'Đúng, input validation giúp giảm rủi ro.', whyJa: '入力検査は有効です。' },
      { ja: 'エラーメッセージにSQL文をそのまま表示する', vi: 'Hiển thị nguyên câu SQL trong error message', whyVi: 'Sai. Lộ SQL giúp attacker hiểu cấu trúc hệ thống.', whyJa: '正解。SQL文を表示すると攻撃者に情報を与えます。' },
      { ja: 'DBアカウントの権限を必要最小限にする', vi: 'Giới hạn quyền DB account tối thiểu', whyVi: 'Đúng, least privilege giảm thiệt hại.', whyJa: '最小権限は有効です。' },
    ], answerIndex: 2,
    trapJa: '「誤っている」を見落とすと、有効な対策を選んでしまう。', trapVi: 'Bẫy là chữ “sai/誤っている”; đừng chọn biện pháp đúng.',
    examTipJa: '設問末尾の「正しい」「誤っている」「最も」を必ず丸で囲む。', examTipVi: 'Khi đọc đề Nhật, khoanh từ cuối câu: đúng/sai/phù hợp nhất.',
  }),
  scenario({
    id: 'v61-ja-less-than-bep', kind: 'japanese-scenario', domain: 'strategy', difficulty: 'standard', relatedNodeIds: ['break-even', 'accounting-fe', 'roi-investment'],
    titleJa: '「以上・未満」損益分岐点', titleVi: 'Bẫy 以上/未満 trong break-even',
    passageJa: '固定費が100万円，製品1個当たりの販売価格が5,000円，変動費が3,000円である。利益が0以上となる販売数量として最も適切なものを選べ。',
    passageVi: 'Fixed cost 1,000,000 yen, price/unit 5,000 yen, variable cost/unit 3,000 yen. Chọn số lượng bán phù hợp để profit >= 0.',
    questionJa: '利益が0以上となる販売数量はどれか。', questionVi: 'Cần bán bao nhiêu sản phẩm để lợi nhuận >= 0?',
    choices: [
      { ja: '200個', vi: '200', whyVi: 'Contribution margin = 2000, 200*2000=400000 chưa đủ fixed cost.', whyJa: '限界利益は2000円なので200個では不足です。' },
      { ja: '400個', vi: '400', whyVi: '400*2000=800000, vẫn âm.', whyJa: '800000円なので固定費に届きません。' },
      { ja: '500個', vi: '500', whyVi: '500*2000=1,000,000, profit = 0 nên đạt 0以上.', whyJa: '正解。利益0なので「0以上」に含まれます。' },
      { ja: '501個未満はすべて不可', vi: 'Dưới 501 đều không đạt', whyVi: 'Sai vì 500 đã bằng 0 và “以上” bao gồm bằng.', whyJa: '500個は0以上に含まれるので誤りです。' },
    ], answerIndex: 2,
    trapJa: '以上は「等しい」を含み、未満は含まない。', trapVi: '以上 bao gồm bằng; 未満 không bao gồm bằng.',
    examTipJa: '損益分岐点＝固定費÷（販売価格−変動費）。境界値の含む/含まないに注意。', examTipVi: 'Break-even = fixed cost / contribution margin; chú ý dấu >=, >, <.',
  }),
  scenario({
    id: 'v61-ja-er-cardinality', kind: 'japanese-scenario', domain: 'database', difficulty: 'standard', relatedNodeIds: ['er-model', 'data-modeling-cardinality', 'relational-model'],
    titleJa: 'ER図の多重度', titleVi: 'Cardinality trong ER diagram',
    passageJa: '社員は一つの部門に所属し，部門には複数の社員が所属できる。この関係をER図で表すとき，社員と部門の多重度として最も適切なものはどれか。',
    passageVi: 'Một nhân viên thuộc một phòng ban, một phòng ban có nhiều nhân viên. Chọn cardinality phù hợp giữa Employee và Department.',
    questionJa: '社員と部門の関係はどれか。', questionVi: 'Quan hệ Employee-Department là gì?',
    choices: [
      { ja: '社員:部門 = 多対多', vi: 'Many-to-many', whyVi: 'Sai vì mỗi employee chỉ thuộc một department.', whyJa: '社員は一つの部門だけなので多対多ではありません。' },
      { ja: '社員:部門 = 多対一', vi: 'Many-to-one', whyVi: 'Đúng: nhiều employees thuộc một department.', whyJa: '正解。複数社員が一つの部門に所属します。' },
      { ja: '社員:部門 = 一対一', vi: 'One-to-one', whyVi: 'Sai vì một department có nhiều employee.', whyJa: '部門に複数社員が所属できるので違います。' },
      { ja: '社員:部門 = 一対多', vi: 'One-to-many theo chiều Employee→Department', whyVi: 'Nếu xét Employee→Department thì không đúng; một employee không có nhiều departments.', whyJa: '社員から部門を見ると一対多ではありません。' },
    ], answerIndex: 1,
    trapJa: 'どちら側から読むかで一対多/多対一の表現が変わる。', trapVi: 'Bẫy là chiều đọc: Employee → Department khác Department → Employee.',
    examTipJa: '日本語文を「1件のAに対してBはいくつ？」で読み替える。', examTipVi: 'Đọc lại: “một A có bao nhiêu B?” để tránh nhầm chiều.',
  }),
  scenario({
    id: 'v61-trace-nested-loop', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['trace-table', 'two-dimensional-array', 'complexity'],
    titleJa: '二重ループの累計トレース', titleVi: 'Trace vòng lặp lồng nhau',
    passageJa: '次の疑似言語で，変数 count の最終値を求める。i と j の範囲に注意する。',
    passageVi: 'Tìm giá trị cuối của count trong pseudo-code. Chú ý phạm vi của i và j.',
    questionJa: 'count の最終値はどれか。', questionVi: 'Giá trị cuối của count là gì?',
    code: 'count ← 0\nfor i ← 1 to 3\n  for j ← 1 to i\n    count ← count + 1\n  endfor\nendfor',
    traceSteps: [
      { step: 'i=1', variables: 'j=1 / count=1', noteJa: '内側ループは1回', noteVi: 'Inner loop chạy 1 lần' },
      { step: 'i=2', variables: 'j=1,2 / count=3', noteJa: '2回加算', noteVi: 'Cộng thêm 2 lần' },
      { step: 'i=3', variables: 'j=1,2,3 / count=6', noteJa: '3回加算', noteVi: 'Cộng thêm 3 lần' },
    ],
    choices: [
      { ja: '3', vi: '3', whyVi: 'Chỉ đếm số vòng outer, bỏ mất inner.', whyJa: '外側だけを数えています。' },
      { ja: '6', vi: '6', whyVi: 'Đúng: 1+2+3 = 6.', whyJa: '正解。1+2+3=6です。' },
      { ja: '9', vi: '9', whyVi: 'Nhầm mỗi i đều chạy 3 lần.', whyJa: '常に3回と誤解しています。' },
      { ja: '12', vi: '12', whyVi: 'Sai do cộng vượt phạm vi.', whyJa: '範囲外まで数えています。' },
    ], answerIndex: 1,
    trapJa: '内側ループの終了値が i で変化する。', trapVi: 'Bẫy là giới hạn inner loop thay đổi theo i.',
    examTipJa: '科目Bは表を書いて、各 i で内側が何回動くかを数える。', examTipVi: '科目B: lập bảng từng i, đừng tính nhẩm.',
  }),
  scenario({
    id: 'v61-trace-binary-search-full', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['binary-search', 'array', 'trace-table'],
    titleJa: '二分探索の完全トレース', titleVi: 'Trace binary search đầy đủ',
    passageJa: '昇順配列 A=[3,7,9,14,18,22,30] から 18 を探索する。添字は1始まりとする。',
    passageVi: 'Tìm 18 trong A=[3,7,9,14,18,22,30], index bắt đầu từ 1.',
    questionJa: '18 が見つかるときの mid の列はどれか。', questionVi: 'Chuỗi mid đến khi tìm thấy 18 là gì?',
    code: 'low ← 1, high ← 7\nwhile low <= high\n  mid ← floor((low + high) / 2)\n  compare A[mid] with 18',
    traceSteps: [
      { step: '1', variables: 'low=1 high=7 mid=4 A[4]=14', noteJa: '14<18なので右側へ', noteVi: '14 < 18 nên đi nửa phải' },
      { step: '2', variables: 'low=5 high=7 mid=6 A[6]=22', noteJa: '22>18なので左側へ', noteVi: '22 > 18 nên đi nửa trái' },
      { step: '3', variables: 'low=5 high=5 mid=5 A[5]=18', noteJa: '発見', noteVi: 'Tìm thấy' },
    ],
    choices: [
      { ja: '4 → 5', vi: '4 → 5', whyVi: 'Thiếu bước mid=6.', whyJa: 'mid=6 の比較が抜けています。' },
      { ja: '4 → 6 → 5', vi: '4 → 6 → 5', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '3 → 5', vi: '3 → 5', whyVi: 'mid đầu không phải 3.', whyJa: '最初の mid は4です。' },
      { ja: '5', vi: '5', whyVi: 'Không nhảy thẳng đến vị trí target.', whyJa: 'いきなり5にはなりません。' },
    ], answerIndex: 1,
    trapJa: 'mid の丸めと low/high 更新を一つずつ追う。', trapVi: 'Chú ý floor và cập nhật low/high từng bước.',
    examTipJa: '二分探索は「整列済み」「mid」「範囲更新」の3点が頻出。', examTipVi: 'Binary search: sorted array, mid, update range.',
  }),
  scenario({
    id: 'v61-sql-three-table-join', kind: 'sql-step', domain: 'database', difficulty: 'hard', relatedNodeIds: ['sql-join', 'sql-aggregate', 'sql-subquery'],
    titleJa: '3表JOINと集計', titleVi: 'JOIN 3 bảng và aggregate',
    passageJa: '顧客，注文，注文明細の3表から，顧客ごとの売上合計を求める。JOIN条件とGROUP BYに注意する。',
    passageVi: 'Tính tổng doanh thu theo khách hàng từ Customers, Orders, OrderItems. Chú ý JOIN condition và GROUP BY.',
    questionJa: '顧客ごとの売上合計を求めるSQLとして最も適切なものはどれか。', questionVi: 'SQL nào phù hợp nhất để tính tổng doanh thu theo khách hàng?',
    table: 'Customers(id, name)\nOrders(id, customer_id)\nOrderItems(order_id, price, qty)',
    sqlSteps: [
      { step: '1 JOIN', result: 'Customers.id = Orders.customer_id', noteJa: '顧客と注文を結合', noteVi: 'Nối customer với order' },
      { step: '2 JOIN', result: 'Orders.id = OrderItems.order_id', noteJa: '注文と明細を結合', noteVi: 'Nối order với items' },
      { step: '3 GROUP', result: 'GROUP BY Customers.id, Customers.name', noteJa: '顧客ごとに集計', noteVi: 'Gom theo từng customer' },
    ],
    choices: [
      { ja: 'SELECT name, SUM(price*qty) FROM Customers JOIN Orders ON Customers.id=Orders.customer_id JOIN OrderItems ON Orders.id=OrderItems.order_id GROUP BY Customers.id, name;', vi: 'SELECT name, SUM(price*qty) ... JOIN đúng ... GROUP BY Customers.id, name;', whyVi: 'Đúng: nối đủ 3 bảng và group theo customer.', whyJa: '正解。3表を正しく結合し顧客ごとに集計します。' },
      { ja: 'SELECT name, price*qty FROM Customers, OrderItems;', vi: 'SELECT name, price*qty FROM Customers, OrderItems;', whyVi: 'Sai vì cartesian product, thiếu JOIN condition.', whyJa: '結合条件がなく直積になります。' },
      { ja: 'SELECT name, SUM(price*qty) FROM Customers GROUP BY order_id;', vi: 'SELECT name, SUM(price*qty) FROM Customers GROUP BY order_id;', whyVi: 'Sai vì thiếu Orders/OrderItems.', whyJa: '必要な表がありません。' },
      { ja: 'SELECT SUM(name) FROM Orders;', vi: 'SELECT SUM(name) FROM Orders;', whyVi: 'Sai kiểu dữ liệu và thiếu doanh thu.', whyJa: 'name は集計対象ではありません。' },
    ], answerIndex: 0,
    trapJa: 'JOIN条件が一つでも抜けると件数が増えて集計が誤る。', trapVi: 'Thiếu một JOIN condition sẽ làm nhân dòng và tổng sai.',
    examTipJa: 'SQL問題は「必要な表 → 結合キー → 集計単位」の順で読む。', examTipVi: 'Đọc SQL theo thứ tự: bảng cần dùng → khóa nối → đơn vị group.',
  }),
  scenario({
    id: 'v61-sql-transaction-rollback', kind: 'sql-step', domain: 'database', difficulty: 'standard', relatedNodeIds: ['transaction-fe', 'lock-isolation', 'backup-recovery-db'],
    titleJa: 'トランザクションとROLLBACK', titleVi: 'Transaction và ROLLBACK',
    passageJa: '口座Aから口座Bへ送金する処理で，途中でエラーが発生した。ACIDの原子性を満たすための処理を選ぶ。',
    passageVi: 'Chuyển tiền từ account A sang B, xảy ra lỗi giữa chừng. Chọn xử lý để đảm bảo atomicity trong ACID.',
    questionJa: '原子性を満たす処理として最も適切なものはどれか。', questionVi: 'Xử lý nào phù hợp nhất để đảm bảo atomicity?',
    sqlSteps: [
      { step: 'BEGIN', result: 'start transaction', noteJa: '一連の処理を開始', noteVi: 'Bắt đầu transaction' },
      { step: 'UPDATE A', result: 'Aから減額', noteJa: '片方だけ成功すると不整合', noteVi: 'Nếu chỉ trừ A thì dữ liệu sai' },
      { step: 'ERROR', result: 'ROLLBACK', noteJa: '全体を取り消す', noteVi: 'Hủy toàn bộ' },
    ],
    choices: [
      { ja: '途中まで成功した処理をCOMMITする', vi: 'COMMIT phần đã thành công', whyVi: 'Sai vì sẽ mất tiền ở A nhưng B chưa nhận.', whyJa: '不整合になります。' },
      { ja: 'ROLLBACKして処理前の状態に戻す', vi: 'ROLLBACK về trạng thái trước giao dịch', whyVi: 'Đúng. Atomicity = all or nothing.', whyJa: '正解。原子性は all or nothing です。' },
      { ja: 'SELECT文だけ再実行する', vi: 'Chỉ chạy lại SELECT', whyVi: 'Không khôi phục dữ liệu.', whyJa: 'データは戻りません。' },
      { ja: 'インデックスを削除する', vi: 'Xóa index', whyVi: 'Không liên quan atomicity.', whyJa: '原子性とは関係ありません。' },
    ], answerIndex: 1,
    trapJa: '一部成功を許さないのが原子性。', trapVi: 'Atomicity không cho phép thành công một nửa.',
    examTipJa: '送金・在庫更新・予約処理は transaction/rollback を連想する。', examTipVi: 'Gặp chuyển tiền/tồn kho/booking → nghĩ transaction/rollback.',
  }),

  scenario({
    id: 'v62-ja-incorrect-dns-cache', kind: 'japanese-scenario', domain: 'network', difficulty: 'standard', relatedNodeIds: ['dns-fe', 'http-https', 'network-fe'],
    titleJa: '「誤っている」DNSキャッシュ', titleVi: 'Chọn phát biểu sai về DNS cache',
    passageJa: '利用者がWebサイトにアクセスするとき，ドメイン名をIPアドレスに対応付ける仕組みを利用する。DNSとキャッシュに関する記述のうち，誤っているものを選べ。',
    passageVi: 'Khi truy cập website, domain name được phân giải sang IP address. Chọn phát biểu sai về DNS và cache.',
    questionJa: 'DNSキャッシュに関する説明として誤っているものはどれか。', questionVi: 'Phát biểu nào sai về DNS cache?',
    choices: [
      { ja: 'キャッシュにより同じ名前解決を高速化できる', vi: 'Cache giúp phân giải lại nhanh hơn', whyVi: 'Đúng. Cache giảm thời gian hỏi DNS server.', whyJa: 'これは正しい説明です。' },
      { ja: 'TTLが切れると再度問い合わせが必要になる', vi: 'Khi TTL hết hạn cần hỏi lại', whyVi: 'Đúng. TTL quyết định thời gian cache hợp lệ.', whyJa: 'TTL満了後は再問い合わせします。' },
      { ja: 'DNSはHTTPの暗号化そのものである', vi: 'DNS chính là cơ chế mã hóa HTTP', whyVi: 'Sai. DNS phân giải tên; HTTPS/TLS mới mã hóa nội dung HTTP.', whyJa: '正解。DNSは名前解決であり暗号化そのものではありません。' },
      { ja: 'DNS障害時は名前で接続できないことがある', vi: 'DNS lỗi có thể không truy cập được bằng tên miền', whyVi: 'Đúng.', whyJa: '正しい説明です。' },
    ], answerIndex: 2,
    trapJa: 'DNS・HTTP・HTTPSを混同しない。', trapVi: 'Đừng nhầm DNS với HTTPS/TLS.',
    examTipJa: 'DNS＝名前解決，HTTPS＝通信の暗号化。役割で切り分ける。', examTipVi: 'DNS = name resolution; HTTPS = encrypted communication.',
  }),
  scenario({
    id: 'v62-ja-most-appropriate-tls', kind: 'japanese-scenario', domain: 'security', difficulty: 'standard', relatedNodeIds: ['http-https', 'cryptography', 'pki-certificate'],
    titleJa: 'HTTPSで最も適切な説明', titleVi: 'Giải thích phù hợp nhất về HTTPS',
    passageJa: '社外からWebシステムを利用する。通信内容の盗聴や改ざんを防ぐためにHTTPSを利用する理由として最も適切なものを選べ。',
    passageVi: 'Một hệ thống web được truy cập từ bên ngoài. Chọn lý do phù hợp nhất để dùng HTTPS nhằm tránh nghe lén/sửa đổi.',
    questionJa: 'HTTPSの説明として最も適切なものはどれか。', questionVi: 'Giải thích nào phù hợp nhất về HTTPS?',
    choices: [
      { ja: '通信をTLSで暗号化し，サーバ証明書で相手を確認できる', vi: 'Mã hóa bằng TLS và kiểm tra server bằng certificate', whyVi: 'Đúng. HTTPS = HTTP over TLS.', whyJa: '正解。HTTPSはTLSと証明書を利用します。' },
      { ja: 'IPアドレスを自動的に割り当てる', vi: 'Tự cấp IP address', whyVi: 'Đó là DHCP, không phải HTTPS.', whyJa: 'DHCPの説明です。' },
      { ja: 'ファイルを圧縮して転送する', vi: 'Nén file để truyền', whyVi: 'Không phải ý chính của HTTPS.', whyJa: 'HTTPSの主目的ではありません。' },
      { ja: 'ドメイン名をIPアドレスに変換する', vi: 'Đổi domain sang IP', whyVi: 'Đó là DNS.', whyJa: 'DNSの説明です。' },
    ], answerIndex: 0,
    trapJa: 'HTTPSを「速くする仕組み」と誤解しない。', trapVi: 'Đừng hiểu HTTPS là cơ chế tăng tốc.',
    examTipJa: 'HTTPS問題は「暗号化」「証明書」「改ざん検知」を探す。', examTipVi: 'Gặp HTTPS: nhớ encryption, certificate, integrity.',
  }),
  scenario({
    id: 'v62-ja-subnet-usable-hosts', kind: 'japanese-scenario', domain: 'network', difficulty: 'hard', relatedNodeIds: ['ip-subnet', 'routing', 'network-fe'],
    titleJa: 'CIDRの利用可能ホスト数', titleVi: 'Số host usable trong CIDR',
    passageJa: 'IPv4ネットワーク 192.168.10.0/27 において，通常利用可能なホストアドレス数として最も適切なものを選べ。',
    passageVi: 'Trong mạng IPv4 192.168.10.0/27, chọn số host address usable thông thường.',
    questionJa: '利用可能なホスト数はどれか。', questionVi: 'Số host usable là bao nhiêu?',
    choices: [
      { ja: '30', vi: '30', whyVi: 'Đúng. Host bits = 5, total 32, usable = 32-2.', whyJa: '正解。2^5-2=30です。' },
      { ja: '32', vi: '32', whyVi: 'Sai vì tính cả network và broadcast.', whyJa: 'ネットワークアドレスとブロードキャストを含めています。' },
      { ja: '27', vi: '27', whyVi: 'Nhầm prefix với host count.', whyJa: 'プレフィックス長とホスト数を混同しています。' },
      { ja: '64', vi: '64', whyVi: 'Đó là /26 total addresses.', whyJa: '/26の総数に近い値です。' },
    ], answerIndex: 0,
    trapJa: '/27 はホスト部5ビット。利用可能数は通常2を引く。', trapVi: '/27 còn 5 host bits, usable thường trừ 2.',
    examTipJa: 'IPv4 host数＝2^(32-prefix)-2 をまず書く。', examTipVi: 'IPv4 usable = 2^(32-prefix)-2.',
  }),
  scenario({
    id: 'v62-ja-firewall-waf', kind: 'japanese-scenario', domain: 'security', difficulty: 'standard', relatedNodeIds: ['firewall-waf', 'web-security', 'ids-ips'],
    titleJa: 'WAFとファイアウォールの違い', titleVi: 'Khác nhau giữa WAF và firewall',
    passageJa: 'WebアプリケーションへのSQLインジェクションやXSSなど，HTTPリクエストの内容に基づく攻撃を検知・遮断したい。最も適切な対策はどれか。',
    passageVi: 'Muốn phát hiện/chặn tấn công dựa trên nội dung HTTP request như SQL injection/XSS. Chọn biện pháp phù hợp nhất.',
    questionJa: '最も適切な対策はどれか。', questionVi: 'Biện pháp phù hợp nhất là gì?',
    choices: [
      { ja: 'WAFを導入する', vi: 'Dùng WAF', whyVi: 'Đúng. WAF kiểm tra tầng application/HTTP.', whyJa: '正解。WAFはWebアプリ層の攻撃を扱います。' },
      { ja: 'ルータの経路表だけを変更する', vi: 'Chỉ đổi routing table', whyVi: 'Không kiểm tra nội dung HTTP.', whyJa: 'HTTP内容は検査しません。' },
      { ja: 'DNSキャッシュを延長する', vi: 'Kéo dài DNS cache', whyVi: 'Không chặn SQLi/XSS.', whyJa: '攻撃対策になりません。' },
      { ja: 'RAID1を構成する', vi: 'Cấu hình RAID1', whyVi: 'RAID là redundancy storage, không phải web attack protection.', whyJa: '可用性寄りの対策です。' },
    ], answerIndex: 0,
    trapJa: 'ネットワーク層のFWとアプリ層のWAFを区別する。', trapVi: 'Phân biệt firewall network layer và WAF application layer.',
    examTipJa: 'SQLi/XSS/HTTPヘッダが出たらWAFを疑う。', examTipVi: 'Gặp SQLi/XSS/HTTP request → WAF.',
  }),
  scenario({
    id: 'v62-ja-incorrect-sla', kind: 'japanese-scenario', domain: 'management', difficulty: 'standard', relatedNodeIds: ['sla', 'service-mgmt-fe', 'availability-reliability'],
    titleJa: '「誤っている」SLA', titleVi: 'Chọn phát biểu sai về SLA',
    passageJa: 'クラウドサービスの利用にあたり，サービス提供者と利用者の間でサービス品質の目標値を取り決める。SLAに関する記述のうち誤っているものを選べ。',
    passageVi: 'Khi dùng cloud service, provider và user thỏa thuận chỉ tiêu chất lượng dịch vụ. Chọn phát biểu sai về SLA.',
    questionJa: 'SLAの説明として誤っているものはどれか。', questionVi: 'Phát biểu nào sai về SLA?',
    choices: [
      { ja: '稼働率や応答時間などの目標を定めることがある', vi: 'Có thể quy định uptime/response time', whyVi: 'Đúng.', whyJa: '正しい説明です。' },
      { ja: 'サービス提供者と利用者の合意である', vi: 'Là thỏa thuận giữa provider và user', whyVi: 'Đúng.', whyJa: '正しい説明です。' },
      { ja: 'ソースコードの著作権を自動的に移転する契約である', vi: 'Là hợp đồng tự động chuyển bản quyền source code', whyVi: 'Sai. SLA không phải hợp đồng chuyển copyright.', whyJa: '正解。SLAはサービス品質の合意です。' },
      { ja: '未達時の対応を定めることがある', vi: 'Có thể quy định xử lý khi không đạt', whyVi: 'Đúng.', whyJa: '正しい説明です。' },
    ], answerIndex: 2,
    trapJa: 'SLAは品質目標であって知的財産権の契約ではない。', trapVi: 'SLA là chất lượng dịch vụ, không phải IP/copyright.',
    examTipJa: 'SLA＝Service Level Agreement。稼働率・応答時間・復旧時間を連想する。', examTipVi: 'SLA = uptime, response time, recovery time.',
  }),
  scenario({
    id: 'v62-ja-critical-path', kind: 'japanese-scenario', domain: 'management', difficulty: 'hard', relatedNodeIds: ['critical-path', 'wbs', 'project-mgmt-fe'],
    titleJa: 'クリティカルパスの読み取り', titleVi: 'Đọc critical path',
    passageJa: '作業Aは3日，Bは2日，Cは4日である。Aの後にB，Aの後にCを並行して実施し，BとCの両方が終わるとDを開始できる。全体期間に影響する作業として最も適切なものを選べ。',
    passageVi: 'A mất 3 ngày. Sau A, B mất 2 ngày và C mất 4 ngày chạy song song; D bắt đầu khi cả B và C xong. Chọn công việc ảnh hưởng đến thời gian toàn bộ nhất.',
    questionJa: 'クリティカルパス上の作業はどれか。', questionVi: 'Công việc nằm trên critical path là gì?',
    choices: [
      { ja: 'AとB', vi: 'A và B', whyVi: 'A+B=5, ngắn hơn A+C=7.', whyJa: 'A+Bは5日で最長ではありません。' },
      { ja: 'AとC', vi: 'A và C', whyVi: 'Đúng. A+C=7 dài hơn A+B=5.', whyJa: '正解。最長経路はA+Cです。' },
      { ja: 'Bだけ', vi: 'Chỉ B', whyVi: 'B không phải đường dài nhất.', whyJa: 'Bだけでは全体期間を表せません。' },
      { ja: 'Cだけ', vi: 'Chỉ C', whyVi: 'C cần sau A, nên thiếu A.', whyJa: 'Cの前にAが必要です。' },
    ], answerIndex: 1,
    trapJa: '並行作業は合計せず，長い方が全体を支配する。', trapVi: 'Các việc song song không cộng hết; nhánh dài hơn chi phối.',
    examTipJa: 'PERTは依存関係を書き，開始から終了までの最長経路を探す。', examTipVi: 'PERT/critical path: vẽ phụ thuộc, tìm path dài nhất.',
  }),
  scenario({
    id: 'v62-ja-evm-cpi', kind: 'japanese-scenario', domain: 'management', difficulty: 'hard', relatedNodeIds: ['earned-value', 'project-mgmt-fe', 'quality-management'],
    titleJa: 'EVMのCPI', titleVi: 'Chỉ số CPI trong EVM',
    passageJa: 'ある時点で，EVが80万円，ACが100万円である。コスト効率を表すCPIとして最も適切なものを選べ。',
    passageVi: 'Tại một thời điểm, EV = 800,000 yen, AC = 1,000,000 yen. Chọn CPI phù hợp.',
    questionJa: 'CPIはどれか。', questionVi: 'CPI bằng bao nhiêu?',
    choices: [
      { ja: '0.8', vi: '0.8', whyVi: 'Đúng. CPI = EV / AC = 0.8.', whyJa: '正解。CPI=EV/AC=0.8です。' },
      { ja: '1.25', vi: '1.25', whyVi: 'Đây là AC/EV, ngược công thức.', whyJa: '式が逆です。' },
      { ja: '20万円', vi: '200,000 yen', whyVi: 'Đó là chênh lệch chi phí, không phải CPI.', whyJa: '差額でありCPIではありません。' },
      { ja: '180万円', vi: '1,800,000 yen', whyVi: 'Cộng EV+AC không có ý nghĩa CPI.', whyJa: '加算ではありません。' },
    ], answerIndex: 0,
    trapJa: 'CPIは比率。1未満ならコスト効率が悪い。', trapVi: 'CPI là ratio; <1 là tốn chi phí hơn kế hoạch.',
    examTipJa: 'EVMは SPI=EV/PV, CPI=EV/AC とセットで覚える。', examTipVi: 'Nhớ SPI=EV/PV, CPI=EV/AC.',
  }),
  scenario({
    id: 'v62-ja-roi', kind: 'japanese-scenario', domain: 'strategy', difficulty: 'standard', relatedNodeIds: ['roi-investment', 'accounting-fe', 'strategy-fe'],
    titleJa: 'ROIの計算', titleVi: 'Tính ROI',
    passageJa: '投資額が200万円，年間効果額が50万円である。単純なROIとして最も適切なものを選べ。',
    passageVi: 'Investment cost = 2,000,000 yen, annual benefit = 500,000 yen. Chọn ROI đơn giản phù hợp.',
    questionJa: 'ROIはどれか。', questionVi: 'ROI là bao nhiêu?',
    choices: [
      { ja: '25%', vi: '25%', whyVi: 'Đúng. 500,000 / 2,000,000 = 0.25.', whyJa: '正解。50万÷200万=25%です。' },
      { ja: '4%', vi: '4%', whyVi: 'Nhầm đảo công thức.', whyJa: '式が逆です。' },
      { ja: '150万円', vi: '1,500,000 yen', whyVi: 'Đây là chênh lệch, không phải ROI %.', whyJa: '比率ではありません。' },
      { ja: '250%', vi: '250%', whyVi: 'Sai dấu thập phân.', whyJa: '桁を誤っています。' },
    ], answerIndex: 0,
    trapJa: 'ROIは効果÷投資額。単位が％になる。', trapVi: 'ROI = benefit / investment, thường biểu diễn %.',
    examTipJa: '投資対効果は「得た効果 ÷ 投資額」。', examTipVi: 'ROI: hiệu quả thu được / tiền đầu tư.',
  }),
  scenario({
    id: 'v62-ja-personal-information', kind: 'japanese-scenario', domain: 'strategy', difficulty: 'standard', relatedNodeIds: ['personal-info-law', 'law-fe', 'security-fe'],
    titleJa: '個人情報保護の適切な扱い', titleVi: 'Xử lý phù hợp dữ liệu cá nhân',
    passageJa: '顧客の氏名，住所，購買履歴を分析に利用する。個人情報保護の観点から最も適切な対応を選べ。',
    passageVi: 'Dùng tên, địa chỉ, lịch sử mua hàng của khách để phân tích. Chọn cách xử lý phù hợp nhất về bảo vệ thông tin cá nhân.',
    questionJa: '最も適切な対応はどれか。', questionVi: 'Cách xử lý phù hợp nhất là gì?',
    choices: [
      { ja: '利用目的を明確にし，必要な範囲で扱う', vi: 'Làm rõ mục đích sử dụng và chỉ xử lý trong phạm vi cần thiết', whyVi: 'Đúng. Purpose limitation/minimization là cốt lõi.', whyJa: '正解。利用目的と必要範囲が重要です。' },
      { ja: '便利なので全社員が自由に閲覧できるようにする', vi: 'Cho toàn bộ nhân viên xem tự do vì tiện', whyVi: 'Sai, vi phạm least privilege.', whyJa: 'アクセス制御が不適切です。' },
      { ja: '分析後も無期限に保存する', vi: 'Lưu vô thời hạn sau phân tích', whyVi: 'Không phù hợp nếu không có mục đích cần thiết.', whyJa: '必要性がない長期保存は不適切です。' },
      { ja: '本人に関係なく第三者へ販売する', vi: 'Bán cho bên thứ ba không liên quan người dùng', whyVi: 'Rủi ro pháp lý lớn.', whyJa: '適切ではありません。' },
    ], answerIndex: 0,
    trapJa: '個人情報は「便利だから」ではなく目的・同意・最小限で考える。', trapVi: 'Dữ liệu cá nhân phải theo purpose, consent, minimum necessary.',
    examTipJa: '個人情報問題は利用目的，安全管理，第三者提供を確認する。', examTipVi: 'Personal info: purpose, safeguards, third-party sharing.',
  }),
  scenario({
    id: 'v62-trace-recursion-factorial', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['recursion', 'trace-table', 'function-procedure'],
    titleJa: '再帰呼出しの戻り値トレース', titleVi: 'Trace recursion factorial',
    passageJa: '次の再帰関数 f(n) の戻り値を求める。基底条件と戻りながらの掛け算に注意する。',
    passageVi: 'Tìm giá trị trả về của hàm đệ quy f(n). Chú ý base case và phép nhân khi return.',
    questionJa: 'f(4) の戻り値はどれか。', questionVi: 'f(4) trả về bao nhiêu?',
    code: `function f(n)
  if n = 1 return 1
  return n * f(n - 1)
end`,
    traceSteps: [
      { step: 'call', variables: 'f(4)=4*f(3)', noteJa: 'まだ計算せず深く呼ぶ', noteVi: 'Chưa tính, gọi sâu xuống' },
      { step: 'base', variables: 'f(1)=1', noteJa: '基底条件で停止', noteVi: 'Dừng tại base case' },
      { step: 'return', variables: '2*1=2, 3*2=6, 4*6=24', noteJa: '戻りながら掛ける', noteVi: 'Nhân khi quay ngược stack' },
    ],
    choices: [
      { ja: '4', vi: '4', whyVi: 'Chỉ lấy n ban đầu.', whyJa: '最初のnだけを見ています。' },
      { ja: '10', vi: '10', whyVi: 'Đây giống tổng 1+2+3+4.', whyJa: '加算と誤解しています。' },
      { ja: '24', vi: '24', whyVi: 'Đúng. 4*3*2*1.', whyJa: '正解。4!=24です。' },
      { ja: '無限ループ', vi: 'Vòng lặp vô hạn', whyVi: 'Có base case n=1 nên không vô hạn.', whyJa: '基底条件があります。' },
    ], answerIndex: 2,
    trapJa: '再帰は呼び出し時ではなく戻る時にも計算が進む。', trapVi: 'Recursion tính tiếp khi call stack quay lại.',
    examTipJa: '基底条件・引数の変化・戻り値の3列で表を書く。', examTipVi: 'Lập bảng: base case, argument change, return value.',
  }),
  scenario({
    id: 'v62-trace-insertion-sort', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['insertion-sort', 'array', 'trace-table'],
    titleJa: '挿入ソート1パスのトレース', titleVi: 'Trace insertion sort',
    passageJa: '配列 [5,2,4,1] を挿入ソートで昇順に並べる。2回目の挿入処理後の配列を選ぶ。',
    passageVi: 'Sắp xếp [5,2,4,1] tăng dần bằng insertion sort. Chọn mảng sau lần insert thứ 2.',
    questionJa: '2回目の挿入処理後の配列はどれか。', questionVi: 'Sau lần insert thứ 2, mảng là gì?',
    code: `for i ← 2 to n
  key ← A[i]
  sorted partへ挿入`,
    traceSteps: [
      { step: '1st', variables: '[2,5,4,1]', noteJa: '2を5の前へ挿入', noteVi: 'Chèn 2 trước 5' },
      { step: '2nd', variables: '[2,4,5,1]', noteJa: '4を2と5の間へ挿入', noteVi: 'Chèn 4 giữa 2 và 5' },
    ],
    choices: [
      { ja: '[2,4,5,1]', vi: '[2,4,5,1]', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '[1,2,4,5]', vi: '[1,2,4,5]', whyVi: 'Đây là kết quả cuối, không phải sau lần 2.', whyJa: '最終結果です。' },
      { ja: '[2,5,4,1]', vi: '[2,5,4,1]', whyVi: 'Mới sau lần 1.', whyJa: '1回目の状態です。' },
      { ja: '[5,2,4,1]', vi: '[5,2,4,1]', whyVi: 'Chưa sắp xếp.', whyJa: '初期状態です。' },
    ], answerIndex: 0,
    trapJa: '「何回目の処理後」かを見落とすと最終結果を選ぶ。', trapVi: 'Bẫy là hỏi “sau lần thứ mấy”, không phải kết quả cuối.',
    examTipJa: 'ソート問題は各パス後の配列を書き出す。', examTipVi: 'Sort trace: ghi mảng sau từng pass.',
  }),
  scenario({
    id: 'v62-trace-queue-stack', kind: 'long-trace', domain: 'algorithm', difficulty: 'standard', relatedNodeIds: ['stack', 'queue', 'trace-table'],
    titleJa: 'スタックとキューの出力順', titleVi: 'Thứ tự output của stack và queue',
    passageJa: '1,2,3を順にデータ構造へ入れる。スタックとキューから全て取り出したときの順序を比較する。',
    passageVi: 'Đưa 1,2,3 vào cấu trúc dữ liệu theo thứ tự. So sánh thứ tự lấy ra từ stack và queue.',
    questionJa: 'スタックの出力順として正しいものはどれか。', questionVi: 'Thứ tự output của stack là gì?',
    code: `push/enqueue 1,2,3
pop/dequeue until empty`,
    traceSteps: [
      { step: 'input', variables: '1 → 2 → 3', noteJa: '同じ順で入れる', noteVi: 'Đưa vào cùng thứ tự' },
      { step: 'stack', variables: '3 → 2 → 1', noteJa: '後入れ先出し', noteVi: 'LIFO' },
      { step: 'queue', variables: '1 → 2 → 3', noteJa: '先入れ先出し', noteVi: 'FIFO' },
    ],
    choices: [
      { ja: '3,2,1', vi: '3,2,1', whyVi: 'Đúng. Stack là LIFO.', whyJa: '正解。スタックはLIFOです。' },
      { ja: '1,2,3', vi: '1,2,3', whyVi: 'Đây là queue FIFO.', whyJa: 'キューの順序です。' },
      { ja: '2,1,3', vi: '2,1,3', whyVi: 'Không theo LIFO/FIFO cơ bản.', whyJa: '基本動作と一致しません。' },
      { ja: '1,3,2', vi: '1,3,2', whyVi: 'Không đúng.', whyJa: '正しくありません。' },
    ], answerIndex: 0,
    trapJa: 'スタック=LIFO，キュー=FIFOを入出力順で確認する。', trapVi: 'Stack=LIFO, queue=FIFO; kiểm theo thứ tự vào/ra.',
    examTipJa: '図を描き，最後に入ったもの・最初に入ったものを丸で囲む。', examTipVi: 'Vẽ hình, khoanh phần tử vào cuối/đầu.',
  }),
  scenario({
    id: 'v62-trace-quick-sort-partition', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['quick-sort', 'array', 'trace-table'],
    titleJa: 'クイックソートの分割', titleVi: 'Partition trong quicksort',
    passageJa: '配列 [4,1,3,2] で pivot を4とし，pivot未満の要素を左に集める単純な分割を行う。分割後の考え方として最も適切なものを選べ。',
    passageVi: 'Với [4,1,3,2], chọn pivot=4 và đưa phần tử nhỏ hơn pivot sang trái. Chọn cách hiểu phù hợp nhất sau partition.',
    questionJa: '分割後に確実に言えることはどれか。', questionVi: 'Sau partition chắc chắn nói được gì?',
    code: `pivot ← 4
left: elements < pivot
right: elements >= pivot`,
    traceSteps: [
      { step: 'scan', variables: '1,3,2 < 4', noteJa: '全てpivot未満', noteVi: 'Tất cả nhỏ hơn pivot' },
      { step: 'partition', variables: '[1,3,2] | [4]', noteJa: '左右に分割', noteVi: 'Chia thành trái/phải' },
    ],
    choices: [
      { ja: '左側は必ず完全に整列済みである', vi: 'Bên trái chắc chắn đã sort hoàn toàn', whyVi: 'Sai. Partition chưa đảm bảo left sorted.', whyJa: '分割だけでは整列しません。' },
      { ja: 'pivotより小さい要素が左側に集まる', vi: 'Các phần tử nhỏ hơn pivot nằm bên trái', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '計算量は常にO(1)である', vi: 'Độ phức tạp luôn O(1)', whyVi: 'Sai.', whyJa: '誤りです。' },
      { ja: 'pivotは必ず最小値である', vi: 'Pivot chắc chắn là min', whyVi: 'Sai, pivot ở đây là max.', whyJa: 'この例では最大値です。' },
    ], answerIndex: 1,
    trapJa: 'partitionは「左右に分ける」だけで、各側の整列は再帰処理。', trapVi: 'Partition chỉ chia trái/phải; sort từng bên là bước sau.',
    examTipJa: 'クイックソートは pivot・分割・再帰を分けて読む。', examTipVi: 'Quicksort: pivot, partition, recursion.',
  }),
  scenario({
    id: 'v62-sql-left-join-null', kind: 'sql-step', domain: 'database', difficulty: 'hard', relatedNodeIds: ['sql-join', 'relational-model', 'view-db'],
    titleJa: 'LEFT JOINとNULL', titleVi: 'LEFT JOIN và NULL',
    passageJa: '顧客表と注文表をLEFT JOINし，注文がない顧客も一覧に出したい。NULLの扱いに注意する。',
    passageVi: 'LEFT JOIN Customers và Orders để vẫn hiện khách chưa có order. Chú ý NULL.',
    questionJa: '注文がない顧客も表示するSQLとして最も適切なものはどれか。', questionVi: 'SQL nào vẫn hiện khách chưa có order?',
    table: `Customers(id,name): (1,Ana),(2,Bob)
Orders(id,customer_id): (10,1)`,
    sqlSteps: [
      { step: 'FROM', result: 'Customers LEFT JOIN Orders', noteJa: '左表の顧客を残す', noteVi: 'Giữ tất cả Customers' },
      { step: 'ON', result: 'Customers.id = Orders.customer_id', noteJa: '注文がなければOrders側はNULL', noteVi: 'Không có order thì cột Orders là NULL' },
      { step: 'result', result: 'Ana=10, Bob=NULL', noteJa: 'Bobも表示される', noteVi: 'Bob vẫn xuất hiện' },
    ],
    choices: [
      { ja: 'SELECT name, Orders.id FROM Customers LEFT JOIN Orders ON Customers.id=Orders.customer_id;', vi: 'SELECT name, Orders.id FROM Customers LEFT JOIN Orders ON Customers.id=Orders.customer_id;', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'SELECT name FROM Orders INNER JOIN Customers ON ...;', vi: 'INNER JOIN từ Orders', whyVi: 'INNER JOIN sẽ loại khách chưa order.', whyJa: '注文なし顧客は消えます。' },
      { ja: 'SELECT name FROM Customers WHERE Orders.id IS NOT NULL;', vi: 'WHERE Orders.id IS NOT NULL', whyVi: 'Điều kiện này loại NULL, mất khách chưa order.', whyJa: 'NULL行を除外します。' },
      { ja: 'SELECT COUNT(*) FROM Orders;', vi: 'COUNT Orders', whyVi: 'Không liệt kê customer.', whyJa: '顧客一覧ではありません。' },
    ], answerIndex: 0,
    trapJa: 'LEFT JOIN後にWHEREで右表の列を絞るとINNER JOINのようになることがある。', trapVi: 'Sau LEFT JOIN, WHERE trên bảng phải có thể biến thành INNER-like.',
    examTipJa: '「ないものも出す」ならLEFT JOINとNULLを確認。', examTipVi: 'Muốn hiện cả “không có” → LEFT JOIN + NULL.',
  }),
  scenario({
    id: 'v62-sql-subquery-max', kind: 'sql-step', domain: 'database', difficulty: 'hard', relatedNodeIds: ['sql-subquery', 'sql-aggregate', 'sql-select'],
    titleJa: 'サブクエリで最大値を選ぶ', titleVi: 'Subquery chọn giá trị lớn nhất',
    passageJa: '売上表から売上金額が最大の行を取得したい。集計関数とサブクエリの使い方に注意する。',
    passageVi: 'Muốn lấy dòng có amount lớn nhất từ Sales. Chú ý aggregate và subquery.',
    questionJa: '最大売上の行を取得するSQLとして最も適切なものはどれか。', questionVi: 'SQL nào lấy dòng có amount lớn nhất?',
    table: 'Sales(id, amount): (1,100), (2,250), (3,180)',
    sqlSteps: [
      { step: 'subquery', result: 'SELECT MAX(amount) FROM Sales = 250', noteJa: '最大値を先に求める', noteVi: 'Tính max trước' },
      { step: 'outer', result: 'WHERE amount = 250', noteJa: '該当行を取得', noteVi: 'Lấy dòng có amount bằng max' },
    ],
    choices: [
      { ja: 'SELECT * FROM Sales WHERE amount = (SELECT MAX(amount) FROM Sales);', vi: 'SELECT * FROM Sales WHERE amount = (SELECT MAX(amount) FROM Sales);', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'SELECT * FROM Sales WHERE amount = MAX(amount);', vi: 'WHERE amount = MAX(amount)', whyVi: 'Aggregate không dùng trực tiếp như vậy trong WHERE.', whyJa: 'WHEREで直接MAXは使えません。' },
      { ja: 'SELECT MIN(amount) FROM Sales;', vi: 'SELECT MIN(amount)', whyVi: 'Lấy min, không phải max row.', whyJa: '最小値です。' },
      { ja: 'SELECT * FROM Sales GROUP BY id HAVING amount;', vi: 'GROUP BY id HAVING amount', whyVi: 'Không có điều kiện max rõ ràng.', whyJa: '最大条件ではありません。' },
    ], answerIndex: 0,
    trapJa: '最大値そのものと最大値を持つ行は違う。', trapVi: 'Max value và row có max value là hai việc khác nhau.',
    examTipJa: '「最大の行」ならサブクエリやORDER BY LIMITを考える。', examTipVi: '“Row with max” → subquery hoặc ORDER BY LIMIT.',
  }),
  scenario({
    id: 'v62-sql-normalization-update', kind: 'sql-step', domain: 'database', difficulty: 'standard', relatedNodeIds: ['normalization-fe', 'er-model', 'relational-model'],
    titleJa: '正規化と更新異常', titleVi: 'Normalization và update anomaly',
    passageJa: '受注明細表に商品名と商品単価を何度も重複して保存している。商品名の変更時に複数行の修正漏れが起きる。',
    passageVi: 'Order detail lưu trùng product name/unit price nhiều lần. Khi đổi tên sản phẩm dễ sót update nhiều dòng.',
    questionJa: 'この問題を減らす設計として最も適切なものはどれか。', questionVi: 'Thiết kế nào phù hợp nhất để giảm vấn đề này?',
    table: 'OrderDetail(order_id, product_id, product_name, unit_price, qty)',
    sqlSteps: [
      { step: 'problem', result: 'product_name repeated', noteJa: '同じ商品情報が重複', noteVi: 'Thông tin sản phẩm bị lặp' },
      { step: 'normalize', result: 'Product(product_id, product_name, unit_price)', noteJa: '商品表へ分離', noteVi: 'Tách Product table' },
    ],
    choices: [
      { ja: '商品表を分離し，商品IDで参照する', vi: 'Tách Product table và tham chiếu bằng product_id', whyVi: 'Đúng.', whyJa: '正解。更新異常を減らせます。' },
      { ja: '商品名をさらに各行へコピーする', vi: 'Copy thêm product name vào nhiều dòng', whyVi: 'Làm tăng redundancy.', whyJa: '重複が増えます。' },
      { ja: '全ての列を文字列型にする', vi: 'Đổi mọi cột thành string', whyVi: 'Không giải quyết normalization.', whyJa: '正規化とは関係ありません。' },
      { ja: '主キーを削除する', vi: 'Xóa primary key', whyVi: 'Làm dữ liệu tệ hơn.', whyJa: '識別が困難になります。' },
    ], answerIndex: 0,
    trapJa: '重複データは更新異常・挿入異常・削除異常につながる。', trapVi: 'Dữ liệu lặp gây update/insert/delete anomaly.',
    examTipJa: '「同じ情報が何度も出る」なら正規化を疑う。', examTipVi: 'Thấy dữ liệu lặp → nghĩ normalization.',
  }),
  scenario({
    id: 'v62-sql-index-range', kind: 'sql-step', domain: 'database', difficulty: 'standard', relatedNodeIds: ['index-db', 'sql-select', 'performance-mips'],
    titleJa: 'インデックスが効きやすい条件', titleVi: 'Điều kiện dễ dùng index',
    passageJa: '社員表の employee_no にインデックスがある。検索性能を改善しやすい条件として最も適切なものを選ぶ。',
    passageVi: 'Employee table có index trên employee_no. Chọn điều kiện dễ cải thiện performance nhất.',
    questionJa: 'インデックスが効きやすい検索条件はどれか。', questionVi: 'Điều kiện nào dễ tận dụng index?',
    table: 'Employee(employee_no indexed, name, department)',
    sqlSteps: [
      { step: 'index key', result: 'employee_no', noteJa: '索引列を直接使う', noteVi: 'Dùng trực tiếp cột index' },
      { step: 'predicate', result: 'employee_no = 1001', noteJa: '等価検索は効きやすい', noteVi: 'Equality search thường tận dụng index tốt' },
    ],
    choices: [
      { ja: 'WHERE employee_no = 1001', vi: 'WHERE employee_no = 1001', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'WHERE name LIKE "%田%"', vi: 'WHERE name LIKE "%田%"', whyVi: 'Không dùng cột indexed và wildcard đầu khó tối ưu.', whyJa: '索引列ではなく先頭ワイルドカードです。' },
      { ja: 'WHERE employee_no + 1 = 1002', vi: 'WHERE employee_no + 1 = 1002', whyVi: 'Function/expression trên cột có thể cản index.', whyJa: '列に演算をかけると効きにくい場合があります。' },
      { ja: 'WHERE department IS NOT NULL', vi: 'WHERE department IS NOT NULL', whyVi: 'Không phải index column ở đề.', whyJa: '対象索引列ではありません。' },
    ], answerIndex: 0,
    trapJa: '索引列に関数や演算をかけると効きにくい。', trapVi: 'Không nên bọc cột index bằng function/expression nếu muốn dùng index.',
    examTipJa: 'インデックス問題は「どの列に索引があるか」を最初に確認。', examTipVi: 'Index: xem index nằm trên cột nào trước.',
  }),
  scenario({
    id: 'v63-kamoku-b-array-second-max', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['array', 'trace-table', 'debugging-algorithm'],
    titleJa: '科目B難問：2番目に大きい値の更新', titleVi: '科目B khó: tìm giá trị lớn thứ hai',
    passageJa: '配列を1回だけ走査して最大値 max1 と2番目に大きい値 max2 を更新する。初期値と更新順に注意する。',
    passageVi: 'Quét array một lần để cập nhật max1 và max2. Chú ý giá trị ban đầu và thứ tự cập nhật.',
    questionJa: 'A=[4,9,2,9,7] の処理後，max2 の値はどれか。', questionVi: 'Sau khi xử lý A=[4,9,2,9,7], max2 là bao nhiêu?',
    code: 'max1 ← -∞, max2 ← -∞\nfor x in A\n  if x > max1 then\n    max2 ← max1\n    max1 ← x\n  else if x < max1 and x > max2 then\n    max2 ← x\n  endif\nendfor',
    traceSteps: [
      { step: 'x=4', variables: 'max1=4 max2=-∞', noteJa: '最初の値は最大値へ', noteVi: 'Giá trị đầu vào max1' },
      { step: 'x=9', variables: 'max1=9 max2=4', noteJa: '旧max1をmax2へ退避', noteVi: 'Đẩy max1 cũ xuống max2' },
      { step: 'x=2', variables: 'max1=9 max2=4', noteJa: 'max2より小さいので無視', noteVi: '2 nhỏ hơn max2 nên bỏ qua' },
      { step: 'x=9', variables: 'max1=9 max2=4', noteJa: 'x < max1 ではないので重複最大は数えない', noteVi: '9 bằng max1 nên không tính là second distinct max' },
      { step: 'x=7', variables: 'max1=9 max2=7', noteJa: '4より大きく9未満なのでmax2更新', noteVi: '7 nằm giữa max2 và max1' },
    ],
    choices: [
      { ja: '4', vi: '4', whyVi: 'Sai vì bỏ qua bước x=7 cập nhật max2.', whyJa: 'x=7でmax2が更新される点を見落としています。' },
      { ja: '7', vi: '7', whyVi: 'Đúng. max2 là giá trị lớn thứ hai khác max1.', whyJa: '正解。最大値9とは異なる2番目の値は7です。' },
      { ja: '9', vi: '9', whyVi: 'Sai nếu đề yêu cầu second distinct maximum do điều kiện x < max1.', whyJa: 'x < max1 条件があるので重複9はmax2になりません。' },
      { ja: '-∞', vi: '-∞', whyVi: 'Sai vì array có đủ giá trị cập nhật.', whyJa: '途中で更新されています。' },
    ], answerIndex: 1,
    trapJa: '重複最大値を2番目と数えるかは条件式で判断する。', trapVi: 'Có tính giá trị trùng max là second hay không phải đọc điều kiện.',
    examTipJa: '科目Bでは「更新順」と「else if条件」を表にして追う。', examTipVi: '科目B: lập bảng update order và điều kiện else-if.',
  }),
  scenario({
    id: 'v63-kamoku-b-off-by-one-loop', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['control-flow', 'trace-table', 'debugging-algorithm'],
    titleJa: '科目B難問：境界値とループ回数', titleVi: '科目B khó: boundary và số lần lặp',
    passageJa: 'ループ条件が「i < n」か「i <= n」かで結果が変わる。境界値を丁寧に追う。',
    passageVi: 'Kết quả thay đổi tùy điều kiện i < n hay i <= n. Cần trace boundary cẩn thận.',
    questionJa: 'n=5 のとき，sum の最終値はどれか。', questionVi: 'Với n=5, giá trị cuối của sum là gì?',
    code: 'i ← 1\nsum ← 0\nwhile i < n\n  sum ← sum + i\n  i ← i + 1\nendwhile',
    traceSteps: [
      { step: '1', variables: 'i=1 sum=1', noteJa: '1を加算後 i=2', noteVi: 'Cộng 1 rồi i=2' },
      { step: '2', variables: 'i=2 sum=3', noteJa: '2を加算', noteVi: 'Cộng 2' },
      { step: '3', variables: 'i=3 sum=6', noteJa: '3を加算', noteVi: 'Cộng 3' },
      { step: '4', variables: 'i=4 sum=10', noteJa: '4を加算後 i=5', noteVi: 'Cộng 4 rồi i=5' },
      { step: 'stop', variables: 'i=5, i<n is false', noteJa: '5は加算しない', noteVi: 'Không cộng 5' },
    ],
    choices: [
      { ja: '10', vi: '10', whyVi: 'Đúng: 1+2+3+4.', whyJa: '正解。i < n なので4までです。' },
      { ja: '15', vi: '15', whyVi: 'Sai do nhầm thành i <= n.', whyJa: 'i <= n と読み違えています。' },
      { ja: '5', vi: '5', whyVi: 'Sai do đếm số vòng thay vì sum.', whyJa: '回数と合計を混同しています。' },
      { ja: '0', vi: '0', whyVi: 'Sai vì loop vẫn chạy khi i=1.', whyJa: 'i=1では条件が真です。' },
    ], answerIndex: 0,
    trapJa: '未満は境界値を含まない。', trapVi: '未満 / < không bao gồm boundary.',
    examTipJa: '境界値問題は最後の1回を必ず確認する。', examTipVi: 'Boundary: luôn kiểm tra vòng cuối có chạy hay không.',
  }),
  scenario({
    id: 'v63-kamoku-b-recursive-fibonacci', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['recursion', 'trace-table', 'complexity'],
    titleJa: '科目B難問：再帰 Fibonacci の呼出し木', titleVi: '科目B khó: cây gọi recursion Fibonacci',
    passageJa: '単純再帰の Fibonacci は同じ値を何度も計算する。戻り値だけでなく呼出し回数も問われやすい。',
    passageVi: 'Fibonacci đệ quy đơn giản tính lặp nhiều lần. Đề hay hỏi cả return value và số lần gọi.',
    questionJa: 'fib(4) の戻り値はどれか。', questionVi: 'fib(4) trả về giá trị nào?',
    code: 'function fib(n)\n  if n <= 1 return n\n  return fib(n-1) + fib(n-2)\nend',
    traceSteps: [
      { step: 'fib(4)', variables: 'fib(3)+fib(2)', noteJa: '二つに分岐', noteVi: 'Tách thành 2 nhánh' },
      { step: 'fib(3)', variables: 'fib(2)+fib(1)', noteJa: 'fib(2)を再度計算', noteVi: 'fib(2) bị tính lại' },
      { step: 'fib(2)', variables: 'fib(1)+fib(0)=1', noteJa: '基底条件へ', noteVi: 'Về base case' },
      { step: 'result', variables: 'fib(4)=2+1=3', noteJa: '戻り値を足す', noteVi: 'Cộng return values' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Sai, đó là fib(3).', whyJa: 'fib(3)の値です。' },
      { ja: '3', vi: '3', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '4', vi: '4', whyVi: 'Sai do nhầm fib(n)=n.', whyJa: 'fib(n)=nではありません。' },
      { ja: '5', vi: '5', whyVi: 'Đó là fib(5).', whyJa: 'fib(5)の値です。' },
    ], answerIndex: 1,
    trapJa: '再帰は基底条件と戻り値の足し合わせを分けて追う。', trapVi: 'Recursion: tách base case và phép cộng return.',
    examTipJa: '科目Bの再帰は小さいnで呼出し木を書く。', examTipVi: 'Với recursion, vẽ call tree cho n nhỏ.',
  }),
  scenario({
    id: 'v63-kamoku-b-euclid-gcd', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['algorithm-basic', 'recursion', 'trace-table'],
    titleJa: '科目B難問：ユークリッド互除法', titleVi: '科目B khó: Euclid GCD',
    passageJa: '剰余を使って最大公約数を求める。a,b の入替えを1行ずつ追う。',
    passageVi: 'Dùng phần dư để tìm GCD. Trace từng lần đổi a,b.',
    questionJa: 'gcd(48,18) の戻り値はどれか。', questionVi: 'gcd(48,18) trả về bao nhiêu?',
    code: 'while b ≠ 0\n  r ← a mod b\n  a ← b\n  b ← r\nendwhile\nreturn a',
    traceSteps: [
      { step: '1', variables: 'a=48 b=18 r=12 → a=18 b=12', noteJa: '48 mod 18 = 12', noteVi: '48 mod 18 = 12' },
      { step: '2', variables: 'a=18 b=12 r=6 → a=12 b=6', noteJa: '18 mod 12 = 6', noteVi: '18 mod 12 = 6' },
      { step: '3', variables: 'a=12 b=6 r=0 → a=6 b=0', noteJa: '終了条件へ', noteVi: 'Đạt điều kiện dừng' },
    ],
    choices: [
      { ja: '0', vi: '0', whyVi: 'Sai: b=0 là điều kiện dừng, return a.', whyJa: '0は終了時のbであり戻り値ではありません。' },
      { ja: '6', vi: '6', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '12', vi: '12', whyVi: 'Sai do dừng quá sớm.', whyJa: '途中で止めています。' },
      { ja: '18', vi: '18', whyVi: 'Sai, chưa trace đủ.', whyJa: '最初のbで止めてはいけません。' },
    ], answerIndex: 1,
    trapJa: 'return b ではなく return a かを確認する。', trapVi: 'Đọc kỹ return a hay return b.',
    examTipJa: '剰余が0になった直後のaが答え。', examTipVi: 'Khi remainder thành 0, a hiện tại là GCD.',
  }),
  scenario({
    id: 'v63-kamoku-b-rpn-stack', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['stack', 'trace-table', 'pseudo-code'],
    titleJa: '科目B難問：逆ポーランド記法とスタック', titleVi: '科目B khó: RPN và stack',
    passageJa: '逆ポーランド記法では数値をpushし，演算子で2つpopして計算結果をpushする。popの順序に注意する。',
    passageVi: 'Trong Reverse Polish Notation, push số, gặp toán tử thì pop 2 giá trị và push kết quả. Chú ý thứ tự pop.',
    questionJa: '式「3 4 2 * +」の結果はどれか。', questionVi: 'Biểu thức “3 4 2 * +” có kết quả nào?',
    code: 'token: 3 4 2 * +\nnumber -> push\noperator -> pop right, pop left, push(left op right)',
    traceSteps: [
      { step: '3', variables: 'stack=[3]', noteJa: '3をpush', noteVi: 'push 3' },
      { step: '4', variables: 'stack=[3,4]', noteJa: '4をpush', noteVi: 'push 4' },
      { step: '2', variables: 'stack=[3,4,2]', noteJa: '2をpush', noteVi: 'push 2' },
      { step: '*', variables: '4*2=8 stack=[3,8]', noteJa: '右2, 左4', noteVi: 'right=2, left=4' },
      { step: '+', variables: '3+8=11', noteJa: '結果11', noteVi: 'result 11' },
    ],
    choices: [
      { ja: '10', vi: '10', whyVi: 'Sai do tính 3+4 trước.', whyJa: '先に3+4を計算しています。' },
      { ja: '11', vi: '11', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '14', vi: '14', whyVi: 'Sai do nhầm thứ tự/toán tử.', whyJa: '演算順が違います。' },
      { ja: '24', vi: '24', whyVi: 'Sai do nhân tất cả.', whyJa: '全て掛けていません。' },
    ], answerIndex: 1,
    trapJa: 'スタックはLIFO。演算子では右オペランドを先にpopする。', trapVi: 'Stack là LIFO; pop right operand trước.',
    examTipJa: 'RPNは必ずスタックの中身を書き出す。', examTipVi: 'RPN: luôn viết trạng thái stack.',
  }),
  scenario({
    id: 'v63-kamoku-b-circular-queue', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['queue', 'array', 'trace-table'],
    titleJa: '科目B難問：循環キュー', titleVi: '科目B khó: circular queue',
    passageJa: '配列サイズ5の循環キューで rear/front を mod 5 で更新する。空き1個を残す実装に注意する。',
    passageVi: 'Circular queue size 5 cập nhật rear/front theo mod 5. Chú ý implementation để trống 1 ô.',
    questionJa: 'front=0, rear=0 から enqueue A,B,C, dequeue, enqueue D を行った後の front,rear はどれか。', questionVi: 'Từ front=0,rear=0, sau enqueue A,B,C, dequeue, enqueue D thì front,rear là gì?',
    code: 'enqueue: Q[rear] ← x; rear ← (rear+1) mod 5\ndequeue: x ← Q[front]; front ← (front+1) mod 5',
    traceSteps: [
      { step: 'enq A', variables: 'front=0 rear=1', noteJa: 'rearだけ進む', noteVi: 'rear tăng' },
      { step: 'enq B', variables: 'front=0 rear=2', noteJa: 'Bを格納', noteVi: 'store B' },
      { step: 'enq C', variables: 'front=0 rear=3', noteJa: 'Cを格納', noteVi: 'store C' },
      { step: 'deq', variables: 'front=1 rear=3', noteJa: 'Aを取り出しfront進む', noteVi: 'remove A, front tăng' },
      { step: 'enq D', variables: 'front=1 rear=4', noteJa: 'Dを格納', noteVi: 'store D' },
    ],
    choices: [
      { ja: 'front=0, rear=4', vi: 'front=0, rear=4', whyVi: 'Sai vì dequeue làm front tăng.', whyJa: 'dequeueでfrontが進みます。' },
      { ja: 'front=1, rear=4', vi: 'front=1, rear=4', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'front=1, rear=3', vi: 'front=1, rear=3', whyVi: 'Sai vì quên enqueue D.', whyJa: '最後のenqueue Dを忘れています。' },
      { ja: 'front=4, rear=1', vi: 'front=4, rear=1', whyVi: 'Sai do mod chưa xảy ra ở chuỗi thao tác này.', whyJa: 'この操作列ではまだ折返しません。' },
    ], answerIndex: 1,
    trapJa: 'enqueueはrear，dequeueはfrontを動かす。', trapVi: 'enqueue di chuyển rear; dequeue di chuyển front.',
    examTipJa: '循環キューは表にfront/rearだけを書いて追う。', examTipVi: 'Circular queue: trace front/rear qua từng thao tác.',
  }),
  scenario({
    id: 'v63-kamoku-b-quicksort-partition', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['quick-sort', 'array', 'trace-table'],
    titleJa: '科目B難問：クイックソート partition', titleVi: '科目B khó: partition trong quicksort',
    passageJa: '先頭要素をpivotとして，pivot未満を左へ移すpartitionを追う。swapのタイミングに注意する。',
    passageVi: 'Dùng phần tử đầu làm pivot, đưa phần tử nhỏ hơn pivot sang trái. Chú ý thời điểm swap.',
    questionJa: 'A=[5,2,8,1,6] でpivot=5のpartition後，pivotの位置はどこか。添字は1始まり。', questionVi: 'Với A=[5,2,8,1,6], pivot=5 sau partition nằm ở vị trí nào? Index bắt đầu từ 1.',
    code: 'pivot ← A[1]\ni ← 2\nfor j ← 2 to 5\n  if A[j] < pivot then swap A[i],A[j]; i←i+1\nendfor\nswap A[1],A[i-1]',
    traceSteps: [
      { step: 'j=2', variables: '2<5 swap self, i=3', noteJa: '2は左側', noteVi: '2 sang trái' },
      { step: 'j=3', variables: '8<5 false, i=3', noteJa: '8は右側', noteVi: '8 ở phải' },
      { step: 'j=4', variables: '1<5 swap A[3],A[4] => [5,2,1,8,6], i=4', noteJa: '1を左へ', noteVi: 'đưa 1 sang trái' },
      { step: 'final', variables: 'swap A[1],A[3] => [1,2,5,8,6]', noteJa: 'pivot位置=3', noteVi: 'pivot position=3' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Sai vì có hai phần tử nhỏ hơn pivot: 2 và 1.', whyJa: 'pivot未満が2個あります。' },
      { ja: '3', vi: '3', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '4', vi: '4', whyVi: 'Sai do tính cả 8 hoặc i sau increment.', whyJa: 'iの値とpivot位置を混同しています。' },
      { ja: '5', vi: '5', whyVi: 'Sai.', whyJa: '末尾ではありません。' },
    ], answerIndex: 1,
    trapJa: '最終swapは i ではなく i-1 と行う。', trapVi: 'Swap cuối với i-1, không phải i.',
    examTipJa: 'partitionは「pivot未満の個数+1」がpivot位置になることが多い。', examTipVi: 'Partition: pivot position thường = số phần tử nhỏ hơn pivot + 1.',
  }),
  scenario({
    id: 'v63-kamoku-b-insertion-sort-shifts', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['insertion-sort', 'array', 'trace-table'],
    titleJa: '科目B難問：挿入ソートの移動回数', titleVi: '科目B khó: số lần dịch trong insertion sort',
    passageJa: '挿入ソートで key より大きい要素を右へずらす回数を数える。比較回数ではなく移動回数を問う。',
    passageVi: 'Đếm số lần dịch phần tử lớn hơn key sang phải trong insertion sort. Đề hỏi shifts, không phải comparisons.',
    questionJa: 'A=[4,3,2] を昇順に挿入ソートするとき，右シフトの総回数はどれか。', questionVi: 'Sắp xếp A=[4,3,2] tăng dần bằng insertion sort, tổng số right-shift là bao nhiêu?',
    code: 'for i ← 2 to n\n  key ← A[i]\n  j ← i-1\n  while j>=1 and A[j]>key\n    A[j+1] ← A[j]\n    j ← j-1\n  endwhile\n  A[j+1] ← key\nendfor',
    traceSteps: [
      { step: 'i=2 key=3', variables: '4 shifts right once', noteJa: '1回シフト', noteVi: '1 shift' },
      { step: 'after i=2', variables: '[3,4,2]', noteJa: '3を先頭へ', noteVi: 'insert 3' },
      { step: 'i=3 key=2', variables: '4 shifts, 3 shifts', noteJa: '2回シフト', noteVi: '2 shifts' },
      { step: 'total', variables: '1+2=3', noteJa: '合計3', noteVi: 'total 3' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Sai, chỉ tính vòng thứ hai.', whyJa: '最後の回だけ数えています。' },
      { ja: '3', vi: '3', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '4', vi: '4', whyVi: 'Sai do nhầm comparison với shift.', whyJa: '比較回数と混同しています。' },
      { ja: '6', vi: '6', whyVi: 'Sai, đó là đếm quá mức.', whyJa: '過剰に数えています。' },
    ], answerIndex: 1,
    trapJa: '比較回数・交換回数・移動回数は別物。', trapVi: 'Comparison, swap, shift là các khái niệm khác nhau.',
    examTipJa: '問題文の「何回」を必ず特定する。', examTipVi: 'Luôn xác định đề hỏi số lần gì.',
  }),
  scenario({
    id: 'v63-kamoku-b-merge-count', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['merge-sort', 'array', 'trace-table'],
    titleJa: '科目B難問：マージ処理の出力順', titleVi: '科目B khó: thứ tự output khi merge',
    passageJa: '整列済みの二つの配列をマージする。各先頭要素を比較し，小さい方を出力する。',
    passageVi: 'Merge hai mảng đã sort. So sánh phần tử đầu và output phần tử nhỏ hơn.',
    questionJa: 'L=[1,4,7], R=[2,3,8] をマージしたとき，4番目に出力される値はどれか。', questionVi: 'Merge L=[1,4,7], R=[2,3,8], giá trị output thứ 4 là gì?',
    code: 'while L and R are not empty\n  output smaller head\nthen output remaining values',
    traceSteps: [
      { step: '1', variables: 'compare 1 and 2 -> output 1', noteJa: 'Lを進める', noteVi: 'advance L' },
      { step: '2', variables: 'compare 4 and 2 -> output 2', noteJa: 'Rを進める', noteVi: 'advance R' },
      { step: '3', variables: 'compare 4 and 3 -> output 3', noteJa: 'Rを進める', noteVi: 'advance R' },
      { step: '4', variables: 'compare 4 and 8 -> output 4', noteJa: '4番目は4', noteVi: '4th is 4' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Sai, đó là output thứ 2.', whyJa: '2番目です。' },
      { ja: '3', vi: '3', whyVi: 'Sai, đó là output thứ 3.', whyJa: '3番目です。' },
      { ja: '4', vi: '4', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '7', vi: '7', whyVi: 'Sai.', whyJa: 'まだ出力されません。' },
    ], answerIndex: 2,
    trapJa: '二つの配列の添字を別々に進める。', trapVi: 'Hai index của hai mảng tiến độc lập.',
    examTipJa: 'マージは出力列を書いていくと安全。', examTipVi: 'Merge: viết dãy output từng bước.',
  }),
  scenario({
    id: 'v63-kamoku-b-dp-coin-change', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['dynamic-programming', 'array', 'trace-table'],
    titleJa: '科目B難問：動的計画法の最小枚数', titleVi: '科目B khó: DP số coin tối thiểu',
    passageJa: '金額を作る最小枚数を dp 配列で求める。直前の状態から更新する。',
    passageVi: 'Tìm số coin tối thiểu bằng mảng dp. Cập nhật từ trạng thái trước.',
    questionJa: '硬貨 {1,3,4} で金額6を作る最小枚数はどれか。', questionVi: 'Với coin {1,3,4}, số coin ít nhất để tạo amount 6 là bao nhiêu?',
    code: 'dp[0]=0\nfor amount 1..6\n  dp[amount]=min(dp[amount-c]+1) for c in coins if amount>=c',
    traceSteps: [
      { step: 'dp[1]', variables: '1', noteJa: '1', noteVi: '1 coin' },
      { step: 'dp[3]', variables: '1', noteJa: '3', noteVi: 'coin 3' },
      { step: 'dp[4]', variables: '1', noteJa: '4', noteVi: 'coin 4' },
      { step: 'dp[6]', variables: 'min(dp[5]+1, dp[3]+1, dp[2]+1)=2', noteJa: '3+3が最小', noteVi: '3+3 là tối ưu' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Đúng: 3+3.', whyJa: '正解。3+3です。' },
      { ja: '3', vi: '3', whyVi: 'Sai, 4+1+1 dùng 3 coin nhưng không tối ưu.', whyJa: '4+1+1は3枚ですが最小ではありません。' },
      { ja: '4', vi: '4', whyVi: 'Sai.', whyJa: 'さらに多いです。' },
      { ja: '6', vi: '6', whyVi: 'Sai, dùng toàn coin 1.', whyJa: '1円硬貨だけの場合です。' },
    ], answerIndex: 0,
    trapJa: '貪欲に大きい硬貨から選ぶだけではない。', trapVi: 'Không phải lúc nào greedy chọn coin lớn nhất cũng đủ.',
    examTipJa: 'DPは「小さい問題の答えを使う」と読む。', examTipVi: 'DP = dùng đáp án bài toán nhỏ hơn.',
  }),
  scenario({
    id: 'v63-kamoku-b-bfs-queue', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['graph-theory', 'queue', 'trace-table'],
    titleJa: '科目B難問：BFSとキュー', titleVi: '科目B khó: BFS và queue',
    passageJa: '幅優先探索ではキューを使う。隣接頂点は番号の小さい順に追加する。',
    passageVi: 'BFS dùng queue. Thêm neighbor theo thứ tự số nhỏ đến lớn.',
    questionJa: '辺 A-B, A-C, B-D, C-E のグラフで A からBFSすると訪問順はどれか。', questionVi: 'Graph có cạnh A-B, A-C, B-D, C-E. BFS từ A có thứ tự thăm nào?',
    code: 'enqueue A\nwhile queue not empty\n  v ← dequeue\n  visit v\n  enqueue unvisited neighbors in alphabetical order',
    traceSteps: [
      { step: 'start', variables: 'queue=[A]', noteJa: 'Aから開始', noteVi: 'start A' },
      { step: 'visit A', variables: 'queue=[B,C]', noteJa: 'B,Cを追加', noteVi: 'enqueue B,C' },
      { step: 'visit B', variables: 'queue=[C,D]', noteJa: 'Dを追加', noteVi: 'enqueue D' },
      { step: 'visit C', variables: 'queue=[D,E]', noteJa: 'Eを追加', noteVi: 'enqueue E' },
      { step: 'finish', variables: 'A,B,C,D,E', noteJa: '幅優先順', noteVi: 'BFS order' },
    ],
    choices: [
      { ja: 'A,B,C,D,E', vi: 'A,B,C,D,E', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'A,B,D,C,E', vi: 'A,B,D,C,E', whyVi: 'Đó giống DFS đi sâu trước.', whyJa: '深さ優先に近い順です。' },
      { ja: 'A,C,E,B,D', vi: 'A,C,E,B,D', whyVi: 'Sai do thứ tự neighbor.', whyJa: '隣接頂点の順序が違います。' },
      { ja: 'A,D,E,B,C', vi: 'A,D,E,B,C', whyVi: 'Không thể thăm D/E trước B/C.', whyJa: 'D/EはAの直接隣接ではありません。' },
    ], answerIndex: 0,
    trapJa: 'BFSはキュー，DFSはスタック/再帰。', trapVi: 'BFS dùng queue; DFS dùng stack/recursion.',
    examTipJa: '探索問題はデータ構造を先に確認する。', examTipVi: 'Search: xác định data structure trước.',
  }),
  scenario({
    id: 'v63-kamoku-b-hash-linear-probing', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['hash-table', 'array', 'trace-table'],
    titleJa: '科目B難問：ハッシュ表の線形探索法', titleVi: '科目B khó: hash table linear probing',
    passageJa: 'ハッシュ値が衝突したら次の空き位置を順に探す。表サイズは7，h(k)=k mod 7。',
    passageVi: 'Khi hash collision, tìm ô trống tiếp theo. Table size 7, h(k)=k mod 7.',
    questionJa: '10,17,24 を順に挿入したとき，24の格納位置はどれか。', questionVi: 'Chèn 10,17,24 theo thứ tự. 24 nằm ở index nào?',
    code: 'index ← key mod 7\nif occupied, try (index+1) mod 7 until empty',
    traceSteps: [
      { step: '10', variables: '10 mod 7 = 3 -> slot3', noteJa: '空き', noteVi: 'empty' },
      { step: '17', variables: '17 mod 7 = 3 occupied -> slot4', noteJa: '1つ進む', noteVi: 'move one slot' },
      { step: '24', variables: '24 mod 7 = 3 occupied, slot4 occupied -> slot5', noteJa: 'さらに進む', noteVi: 'continue probing' },
    ],
    choices: [
      { ja: '3', vi: '3', whyVi: 'Sai vì slot 3 đã có 10.', whyJa: 'slot3は使用済みです。' },
      { ja: '4', vi: '4', whyVi: 'Sai vì slot 4 đã có 17.', whyJa: 'slot4も使用済みです。' },
      { ja: '5', vi: '5', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '6', vi: '6', whyVi: 'Sai, probe dừng ở slot 5.', whyJa: 'slot5で空きが見つかります。' },
    ], answerIndex: 2,
    trapJa: '衝突後も同じハッシュ値に戻らず，次の空きを探す。', trapVi: 'Sau collision, probe đến ô trống tiếp theo.',
    examTipJa: 'ハッシュ問題は表サイズとmodを必ず確認。', examTipVi: 'Hash: luôn xem table size và mod.',
  }),
  scenario({
    id: 'v63-kamoku-b-heap-insert', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['heap-priority-queue', 'array', 'trace-table'],
    titleJa: '科目B難問：最小ヒープへの挿入', titleVi: '科目B khó: insert vào min-heap',
    passageJa: '最小ヒープに値を末尾へ追加し，親より小さい間は交換して上へ移動する。',
    passageVi: 'Insert vào cuối min-heap, nếu nhỏ hơn parent thì swap lên.',
    questionJa: 'ヒープ [3,5,8,9,6] に 4 を挿入した後の配列はどれか。', questionVi: 'Sau khi insert 4 vào heap [3,5,8,9,6], array là gì?',
    code: 'append 4 at index6\nwhile child < parent: swap',
    traceSteps: [
      { step: 'append', variables: '[3,5,8,9,6,4]', noteJa: '末尾へ追加', noteVi: 'append cuối' },
      { step: 'parent', variables: 'index6 parent index3 value8', noteJa: '4<8なので交換', noteVi: '4<8 swap' },
      { step: 'after swap', variables: '[3,5,4,9,6,8]', noteJa: '親index1 value3とは交換しない', noteVi: 'parent 3 nhỏ hơn 4 nên dừng' },
    ],
    choices: [
      { ja: '[3,5,4,9,6,8]', vi: '[3,5,4,9,6,8]', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '[4,3,8,9,6,5]', vi: '[4,3,8,9,6,5]', whyVi: 'Sai vì 4 không swap với root 3.', whyJa: '4は3より大きいので根にはなりません。' },
      { ja: '[3,4,8,9,6,5]', vi: '[3,4,8,9,6,5]', whyVi: 'Sai do chọn nhầm parent index.', whyJa: 'index6の親はindex3です。' },
      { ja: '[3,5,8,9,6,4]', vi: '[3,5,8,9,6,4]', whyVi: 'Sai vì chưa heapify up.', whyJa: '上方向の交換が必要です。' },
    ], answerIndex: 0,
    trapJa: '配列ヒープの親は floor(i/2)（1始まり）。', trapVi: 'Heap array 1-indexed: parent = floor(i/2).',
    examTipJa: 'ヒープは木として描くと親子関係を間違えにくい。', examTipVi: 'Vẽ heap như cây để tránh nhầm parent.',
  }),
  scenario({
    id: 'v63-kamoku-b-matrix-diagonal', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['two-dimensional-array', 'array', 'trace-table'],
    titleJa: '科目B難問：二次元配列の対角線', titleVi: '科目B khó: đường chéo ma trận',
    passageJa: '3×3行列の主対角線と副対角線を足す。中央要素を二重に足さない条件に注意する。',
    passageVi: 'Cộng main diagonal và anti-diagonal của ma trận 3x3. Chú ý không cộng tâm hai lần.',
    questionJa: 'M=[[1,2,3],[4,5,6],[7,8,9]] の対角線和はどれか。', questionVi: 'Diagonal sum của M=[[1,2,3],[4,5,6],[7,8,9]] là bao nhiêu?',
    code: 'sum ← 0\nfor i ← 1 to 3\n  sum ← sum + M[i][i]\n  if i ≠ 4-i then sum ← sum + M[i][4-i]\nendfor',
    traceSteps: [
      { step: 'i=1', variables: 'add 1 and 3 -> sum=4', noteJa: '両方加算', noteVi: 'cộng 1 và 3' },
      { step: 'i=2', variables: 'add 5 only -> sum=9', noteJa: '中央は1回だけ', noteVi: 'center chỉ cộng 1 lần' },
      { step: 'i=3', variables: 'add 9 and 7 -> sum=25', noteJa: '両方加算', noteVi: 'cộng 9 và 7' },
    ],
    choices: [
      { ja: '20', vi: '20', whyVi: 'Sai, thiếu một đường chéo.', whyJa: '片方の対角線だけです。' },
      { ja: '25', vi: '25', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '30', vi: '30', whyVi: 'Sai do cộng center 5 hai lần.', whyJa: '中央5を二重加算しています。' },
      { ja: '45', vi: '45', whyVi: 'Sai, đó là tổng toàn matrix.', whyJa: '全要素の合計です。' },
    ], answerIndex: 1,
    trapJa: '奇数サイズの中央要素は二重に数えない。', trapVi: 'Ma trận kích thước lẻ: tâm không cộng hai lần.',
    examTipJa: '二次元配列は添字式を書き換えて確認する。', examTipVi: '2D array: kiểm tra công thức index.',
  }),
  scenario({
    id: 'v63-kamoku-b-bitmask-parity', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['binary-number', 'boolean-logic', 'trace-table'],
    titleJa: '科目B難問：ビット演算と偶奇判定', titleVi: '科目B khó: bit operation và parity',
    passageJa: '整数xの最下位ビットを x AND 1 で調べる。偶数なら0，奇数なら1になる。',
    passageVi: 'Kiểm tra bit thấp nhất bằng x AND 1. Số chẵn ra 0, số lẻ ra 1.',
    questionJa: 'x=13 のとき，x AND 1 の値はどれか。', questionVi: 'Với x=13, x AND 1 bằng bao nhiêu?',
    code: '13 = 1101₂\n1  = 0001₂\nAND bit by bit',
    traceSteps: [
      { step: 'binary', variables: '13=1101', noteJa: '2進数へ変換', noteVi: 'đổi sang binary' },
      { step: 'mask', variables: '0001', noteJa: '最下位ビットだけ見る', noteVi: 'mask bit thấp nhất' },
      { step: 'AND', variables: '1101 AND 0001 = 0001', noteJa: '結果1', noteVi: 'result 1' },
    ],
    choices: [
      { ja: '0', vi: '0', whyVi: 'Sai, 13 là số lẻ.', whyJa: '13は奇数です。' },
      { ja: '1', vi: '1', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '12', vi: '12', whyVi: 'Sai, đó là 13 AND 12 có thể khác.', whyJa: '1とのANDではありません。' },
      { ja: '13', vi: '13', whyVi: 'Sai do nhầm AND với OR/giữ nguyên.', whyJa: 'AND 1では最下位ビットだけ残ります。' },
    ], answerIndex: 1,
    trapJa: 'AND 1 は値全体ではなく最下位ビットだけを残す。', trapVi: 'AND 1 chỉ giữ bit thấp nhất.',
    examTipJa: 'ビット問題は必ず2進数で縦にそろえる。', examTipVi: 'Bitwise: luôn viết binary thẳng cột.',
  }),
  scenario({
    id: 'v63-kamoku-b-debug-infinite-loop', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['debugging-algorithm', 'control-flow', 'trace-table'],
    titleJa: '科目B難問：無限ループの原因', titleVi: '科目B khó: nguyên nhân vòng lặp vô hạn',
    passageJa: 'while文の中で条件に関係する変数が更新されないと無限ループになる。',
    passageVi: 'Nếu biến liên quan đến điều kiện while không được cập nhật, vòng lặp có thể vô hạn.',
    questionJa: '次の疑似コードが停止しない主な原因はどれか。', questionVi: 'Nguyên nhân chính khiến pseudo-code sau không dừng là gì?',
    code: 'i ← 1\nwhile i <= 5\n  sum ← sum + i\nendwhile',
    traceSteps: [
      { step: 'init', variables: 'i=1', noteJa: '条件は真', noteVi: 'condition true' },
      { step: 'loop1', variables: 'sum updated, i still 1', noteJa: 'iが変わらない', noteVi: 'i không đổi' },
      { step: 'loop2', variables: 'i<=5 remains true', noteJa: '条件がずっと真', noteVi: 'condition mãi true' },
    ],
    choices: [
      { ja: 'sumを初期化していないことだけが原因', vi: 'Chỉ do sum chưa init', whyVi: 'sum chưa init cũng là lỗi, nhưng nguyên nhân không dừng là i không update.', whyJa: 'sum初期化も問題ですが停止しない主因はi未更新です。' },
      { ja: 'iを更新していない', vi: 'Không cập nhật i', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '条件が i < 5 でない', vi: 'Điều kiện không phải i < 5', whyVi: 'Dù i<5 cũng vô hạn nếu i không update.', whyJa: 'iが更新されなければ同じです。' },
      { ja: 'whileではなくforを使うべき', vi: 'Phải dùng for thay while', whyVi: 'Không bắt buộc; while đúng nếu cập nhật biến.', whyJa: 'whileでも正しく書けます。' },
    ], answerIndex: 1,
    trapJa: '停止条件に近づく更新があるか確認する。', trapVi: 'Kiểm tra có update làm tiến về điều kiện dừng không.',
    examTipJa: 'デバッグ問題は「初期化・条件・更新」を三点セットで見る。', examTipVi: 'Debug loop: xem init, condition, update.',
  }),
  scenario({
    id: 'v63-kamoku-b-sentinel-linear-search', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['linear-search', 'array', 'trace-table'],
    titleJa: '科目B難問：番兵法の線形探索', titleVi: '科目B khó: linear search với sentinel',
    passageJa: '番兵法では配列末尾に探索値を置き，ループ内の範囲判定を省く。元の範囲内で見つかったかを最後に判定する。',
    passageVi: 'Sentinel search đặt target ở cuối để bỏ kiểm tra biên trong loop. Cuối cùng kiểm tra vị trí tìm thấy có nằm trong mảng gốc không.',
    questionJa: 'A=[4,8,2], target=5 のとき，番兵を追加した後に停止する添字はどれか。添字は1始まりで，番兵は4番目。', questionVi: 'A=[4,8,2], target=5. Sau thêm sentinel ở vị trí 4, loop dừng ở index nào?',
    code: 'A[n+1] ← target\ni ← 1\nwhile A[i] ≠ target\n  i ← i + 1\nendwhile',
    traceSteps: [
      { step: 'i=1', variables: 'A[1]=4 != 5', noteJa: '進む', noteVi: 'advance' },
      { step: 'i=2', variables: 'A[2]=8 != 5', noteJa: '進む', noteVi: 'advance' },
      { step: 'i=3', variables: 'A[3]=2 != 5', noteJa: '進む', noteVi: 'advance' },
      { step: 'i=4', variables: 'A[4]=5 sentinel', noteJa: '番兵で停止', noteVi: 'stop at sentinel' },
    ],
    choices: [
      { ja: '1', vi: '1', whyVi: 'Sai.', whyJa: '最初の要素では一致しません。' },
      { ja: '3', vi: '3', whyVi: 'Sai, A[3]=2.', whyJa: 'A[3]は2です。' },
      { ja: '4', vi: '4', whyVi: 'Đúng: dừng ở sentinel.', whyJa: '正解。番兵の位置で停止します。' },
      { ja: '停止しない', vi: 'Không dừng', whyVi: 'Sai vì sentinel đảm bảo dừng.', whyJa: '番兵により必ず停止します。' },
    ], answerIndex: 2,
    trapJa: '停止した位置がn+1なら，元の配列には存在しない。', trapVi: 'Nếu dừng ở n+1 thì target không có trong mảng gốc.',
    examTipJa: '番兵法は「高速化」と「最後の存在判定」がセット。', examTipVi: 'Sentinel: tối ưu loop nhưng cần check existence cuối.',
  }),
  scenario({
    id: 'v63-kamoku-b-selection-sort-swap-count', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['selection-sort', 'array', 'trace-table'],
    titleJa: '科目B難問：選択ソートの交換回数', titleVi: '科目B khó: số swap trong selection sort',
    passageJa: '選択ソートは未整列部分の最小値を探し，先頭と交換する。交換しない実装もあるので条件に注意する。',
    passageVi: 'Selection sort tìm min trong phần chưa sort và swap với đầu. Chú ý implementation có thể không swap nếu min đã ở đầu.',
    questionJa: 'A=[2,1,3] を昇順に選択ソートする。minIndexがiと異なる時だけ交換すると，交換回数はどれか。', questionVi: 'Selection sort A=[2,1,3] tăng dần. Chỉ swap khi minIndex khác i. Số swap là bao nhiêu?',
    code: 'for i ← 1 to n-1\n  minIndex ← i\n  for j ← i+1 to n\n    if A[j] < A[minIndex] then minIndex ← j\n  endfor\n  if minIndex ≠ i then swap A[i],A[minIndex]\nendfor',
    traceSteps: [
      { step: 'i=1', variables: 'minIndex=2 value=1 -> swap [1,2,3]', noteJa: '1回交換', noteVi: '1 swap' },
      { step: 'i=2', variables: 'minIndex=2', noteJa: '既に最小なので交換なし', noteVi: 'already min, no swap' },
    ],
    choices: [
      { ja: '0', vi: '0', whyVi: 'Sai, i=1 cần swap.', whyJa: '最初に交換します。' },
      { ja: '1', vi: '1', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '2', vi: '2', whyVi: 'Sai do tưởng mỗi vòng đều swap.', whyJa: 'minIndex=iの場合は交換しません。' },
      { ja: '3', vi: '3', whyVi: 'Sai.', whyJa: '過剰です。' },
    ], answerIndex: 1,
    trapJa: '「必ず交換」か「異なる時だけ交換」か実装を読む。', trapVi: 'Đọc implementation: always swap hay chỉ swap khi khác.',
    examTipJa: 'ソート問題は配列状態と交換回数を分けて記録する。', examTipVi: 'Sort: ghi trạng thái array và số swap riêng.',
  }),
  scenario({
    id: 'v63-kamoku-b-bubble-sort-pass', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['bubble-sort', 'array', 'trace-table'],
    titleJa: '科目B難問：バブルソート1パス後', titleVi: '科目B khó: sau 1 pass bubble sort',
    passageJa: '隣同士を比較し，大きい方を右へ送る。1パス後に最大値が末尾へ移動する。',
    passageVi: 'So sánh cặp liền kề, đưa giá trị lớn hơn sang phải. Sau 1 pass, max về cuối.',
    questionJa: 'A=[3,1,4,2] を昇順バブルソートで1パス実行した後の配列はどれか。', questionVi: 'A=[3,1,4,2], sau 1 pass bubble sort tăng dần là gì?',
    code: 'for j ← 1 to n-1\n  if A[j] > A[j+1] then swap\nendfor',
    traceSteps: [
      { step: 'j=1', variables: '[1,3,4,2]', noteJa: '3と1を交換', noteVi: 'swap 3 và 1' },
      { step: 'j=2', variables: '[1,3,4,2]', noteJa: '3<4 交換なし', noteVi: 'no swap' },
      { step: 'j=3', variables: '[1,3,2,4]', noteJa: '4と2を交換', noteVi: 'swap 4 và 2' },
    ],
    choices: [
      { ja: '[1,2,3,4]', vi: '[1,2,3,4]', whyVi: 'Sai, đó là sort hoàn toàn, không phải 1 pass.', whyJa: '完全ソート後です。' },
      { ja: '[1,3,2,4]', vi: '[1,3,2,4]', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '[3,1,2,4]', vi: '[3,1,2,4]', whyVi: 'Sai vì quên swap đầu.', whyJa: '最初の交換を忘れています。' },
      { ja: '[1,4,3,2]', vi: '[1,4,3,2]', whyVi: 'Sai.', whyJa: '隣接比較の結果ではありません。' },
    ], answerIndex: 1,
    trapJa: '1パスと全体完了を混同しない。', trapVi: 'Đừng nhầm 1 pass với sort hoàn tất.',
    examTipJa: 'バブルソートはパスごとに末尾が確定する。', examTipVi: 'Bubble sort: mỗi pass cố định phần tử cuối.',
  }),

  ...fundamentalInfoV79RKamokuBMasteryScenarios,
  ...fundamentalInfoV81RMixedMockMiniSet,
];

export const getFundamentalScenariosByKind = (kind: FundamentalScenarioKind) => fundamentalInfoExamScenarios.filter((item) => item.kind === kind);

fundamentalInfoExamScenarios.push(...fundamentalInfoV85RTraceBank);
fundamentalInfoExamScenarios.push(...fundamentalInfoV90RMockMiniSet);
