import type { FundamentalExamScenario } from './examScenarios';

export const fundamentalInfoV79RKamokuBMasteryScenarios: FundamentalExamScenario[] = [
  {
    id: 'v79r-kamoku-b-dp-table-path-count', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['dynamic-programming', 'array', 'trace-table'],
    titleJa: 'V79R 科目B：DP表の更新順', titleVi: 'V79R 科目B: thứ tự cập nhật bảng DP',
    passageJa: '階段を1段または2段ずつ上がる。ways[i] は i 段目までの上がり方の数で、ways[0]=1, ways[1]=1 とする。',
    passageVi: 'Leo cầu thang mỗi lần 1 hoặc 2 bậc. ways[i] là số cách đến bậc i, ways[0]=1, ways[1]=1.',
    questionJa: 'n=5 のとき ways[2] から ways[5] までの値の列はどれか。', questionVi: 'Với n=5, dãy giá trị ways[2] đến ways[5] là gì?',
    code: 'ways[0] ← 1\nways[1] ← 1\nfor i ← 2 to n\n  ways[i] ← ways[i-1] + ways[i-2]\nendfor',
    traceSteps: [
      { step: 'i=2', variables: 'ways[2]=2', noteJa: 'ways[1]+ways[0]=1+1', noteVi: 'ways[1]+ways[0]=1+1' },
      { step: 'i=3', variables: 'ways[3]=3', noteJa: '2+1', noteVi: '2+1' },
      { step: 'i=4', variables: 'ways[4]=5', noteJa: '3+2', noteVi: '3+2' },
      { step: 'i=5', variables: 'ways[5]=8', noteJa: '5+3', noteVi: '5+3' },
    ],
    choices: [
      { ja: '1,2,3,5', vi: '1,2,3,5', whyVi: 'Sai vì ways[2] phải là 2.', whyJa: 'ways[2] は2です。' },
      { ja: '2,3,5,8', vi: '2,3,5,8', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '2,4,6,8', vi: '2,4,6,8', whyVi: 'Sai do cộng tuyến tính.', whyJa: '単純な等差ではありません。' },
      { ja: '1,1,2,3', vi: '1,1,2,3', whyVi: 'Sai vì đang liệt kê từ ways[0].', whyJa: 'ways[0] からの列になっています。' },
    ], answerIndex: 1,
    trapJa: '初期値と「どの添字から問われているか」を分けて読む。', trapVi: 'Tách rõ giá trị khởi tạo và index đang được hỏi.',
    examTipJa: 'DP問題は「意味・初期値・漸化式・更新順」の4点を表にする。', examTipVi: 'DP: ghi meaning, initial values, recurrence, update order.',
  },
  {
    id: 'v79r-kamoku-b-queue-bfs-distance', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['queue', 'graph-theory', 'trace-table'],
    titleJa: 'V79R 科目B：キューによるBFS距離', titleVi: 'V79R 科目B: khoảng cách BFS bằng queue',
    passageJa: 'グラフの隣接リストは A:{B,C}, B:{D}, C:{D}, D:{}。AからBFSを行い、未訪問の頂点だけをenqueueする。',
    passageVi: 'Adjacency list: A:{B,C}, B:{D}, C:{D}, D:{}. BFS từ A, chỉ enqueue node chưa thăm.',
    questionJa: 'Dの距離が確定するまでのdequeue順はどれか。', questionVi: 'Thứ tự dequeue đến khi xác định khoảng cách của D là gì?',
    code: 'queue ← [A], dist[A] ← 0\nwhile queue not empty\n  v ← dequeue()\n  for each neighbor u of v\n    if u is unvisited then dist[u] ← dist[v]+1; enqueue(u)',
    traceSteps: [
      { step: '1', variables: 'dequeue A, enqueue B,C, dist=1', noteJa: 'Aの隣接を順に入れる', noteVi: 'enqueue neighbors of A' },
      { step: '2', variables: 'dequeue B, enqueue D, dist[D]=2', noteJa: 'Dの距離がここで確定', noteVi: 'D distance fixed here' },
      { step: '3', variables: 'queue contains C,D', noteJa: 'Dは既に訪問済み扱い', noteVi: 'D is already visited' },
    ],
    choices: [
      { ja: 'A → B', vi: 'A → B', whyVi: 'Đúng: khi xử lý B thì D được phát hiện với distance 2.', whyJa: '正解。B処理時にDが見つかります。' },
      { ja: 'A → C', vi: 'A → C', whyVi: 'Sai vì B được enqueue trước C.', whyJa: 'BがCより先にqueueに入ります。' },
      { ja: 'A → B → C → D', vi: 'A → B → C → D', whyVi: 'Đó là đến khi pop D, không phải khi distance được xác định.', whyJa: '距離確定ではなくDを取り出す順です。' },
      { ja: 'A → D', vi: 'A → D', whyVi: 'Sai vì D không kề trực tiếp A.', whyJa: 'DはAの直接隣接ではありません。' },
    ], answerIndex: 0,
    trapJa: 'BFSでは「発見時に距離確定」か「取り出し時に見る」か設問を確認する。', trapVi: 'BFS: đọc kỹ hỏi lúc phát hiện hay lúc dequeue.',
    examTipJa: 'キューの中身、visited、distを3列で追う。', examTipVi: 'Trace BFS bằng 3 cột: queue, visited, dist.',
  },
  {
    id: 'v79r-kamoku-b-recursion-stack-return', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['recursion', 'stack', 'trace-table'],
    titleJa: 'V79R 科目B：再帰呼出しスタック', titleVi: 'V79R 科目B: call stack đệ quy',
    passageJa: '関数 g(n) は n<=1 なら n を返し、それ以外は g(n-1)+g(n-2) を返す。短い入力で呼出し木を追う。',
    passageVi: 'Hàm g(n) trả n nếu n<=1, ngược lại trả g(n-1)+g(n-2). Trace cây gọi hàm nhỏ.',
    questionJa: 'g(4) の値はどれか。', questionVi: 'Giá trị g(4) là gì?',
    code: 'function g(n)\n  if n <= 1 then return n\n  return g(n-1) + g(n-2)\nendfunction',
    traceSteps: [
      { step: 'g(2)', variables: 'g(1)+g(0)=1', noteJa: '基本ケースに戻る', noteVi: 'returns from base cases' },
      { step: 'g(3)', variables: 'g(2)+g(1)=2', noteJa: '1+1', noteVi: '1+1' },
      { step: 'g(4)', variables: 'g(3)+g(2)=3', noteJa: '2+1', noteVi: '2+1' },
    ],
    choices: [
      { ja: '2', vi: '2', whyVi: 'Sai, đó là g(3).', whyJa: 'g(3)の値です。' },
      { ja: '3', vi: '3', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '4', vi: '4', whyVi: 'Sai do tưởng trả n.', whyJa: 'nをそのまま返すのは基本ケースだけです。' },
      { ja: '5', vi: '5', whyVi: 'Sai, đó là g(5).', whyJa: 'g(5)相当です。' },
    ], answerIndex: 1,
    trapJa: '同じ呼出しが重複するため、表にメモして再利用する。', trapVi: 'Call lặp lại nhiều lần; ghi bảng và tái sử dụng.',
    examTipJa: '再帰は「基本ケース」「戻り値」「重複呼出し」を先に確認する。', examTipVi: 'Recursion: base case, return value, repeated calls.',
  },
  {
    id: 'v79r-kamoku-b-stack-expression-eval', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['stack', 'array', 'trace-table'],
    titleJa: 'V79R 科目B：逆ポーランド記法とスタック', titleVi: 'V79R 科目B: Reverse Polish notation và stack',
    passageJa: '逆ポーランド記法 3 4 + 2 * を左から読み、数値はpush、演算子は2値をpopして計算結果をpushする。',
    passageVi: 'Đọc RPN 3 4 + 2 * từ trái sang phải; số thì push, toán tử thì pop 2 số rồi push kết quả.',
    questionJa: '最終的にスタックに残る値はどれか。', questionVi: 'Giá trị cuối cùng còn trong stack là gì?',
    code: 'tokens: 3 4 + 2 *\nnumber → push\noperator → b←pop(), a←pop(), push(a operator b)',
    traceSteps: [
      { step: '3,4', variables: 'stack=[3,4]', noteJa: '数値をpush', noteVi: 'push numbers' },
      { step: '+', variables: 'stack=[7]', noteJa: '3+4', noteVi: '3+4' },
      { step: '2', variables: 'stack=[7,2]', noteJa: '2をpush', noteVi: 'push 2' },
      { step: '*', variables: 'stack=[14]', noteJa: '7*2', noteVi: '7*2' },
    ],
    choices: [
      { ja: '10', vi: '10', whyVi: 'Sai vì nhân sau cùng.', whyJa: '最後に乗算します。' },
      { ja: '11', vi: '11', whyVi: 'Sai do tính 3+4+2.', whyJa: '加算だけではありません。' },
      { ja: '14', vi: '14', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: '24', vi: '24', whyVi: 'Sai do tính 3*(4+2).', whyJa: '演算順が違います。' },
    ], answerIndex: 2,
    trapJa: '演算子が来た時点で直前2つを使う。通常の中置記法に戻さない。', trapVi: 'Khi gặp operator, dùng đúng 2 phần tử trên đỉnh stack.',
    examTipJa: 'スタック問題は各token後のstack状態だけを書けば解ける。', examTipVi: 'Stack: ghi stack sau từng token là đủ.',
  },
  {
    id: 'v79r-kamoku-b-two-dimensional-array-scan', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['two-dimensional-array', 'array', 'trace-table'],
    titleJa: 'V79R 科目B：二次元配列の走査', titleVi: 'V79R 科目B: duyệt mảng 2 chiều',
    passageJa: '2行3列の配列を行優先で走査し、偶数だけを合計する。添字は1始まり。',
    passageVi: 'Duyệt mảng 2 hàng 3 cột theo row-major, chỉ cộng số chẵn. Index bắt đầu từ 1.',
    questionJa: 'sum の最終値はどれか。', questionVi: 'Giá trị cuối của sum là gì?',
    code: 'A = [[1,2,3],[4,5,6]]\nsum ← 0\nfor r ← 1 to 2\n  for c ← 1 to 3\n    if A[r][c] mod 2 = 0 then sum ← sum + A[r][c]',
    traceSteps: [
      { step: 'r=1', variables: 'add 2, sum=2', noteJa: '1行目の偶数は2', noteVi: 'row 1 even number is 2' },
      { step: 'r=2,c=1', variables: 'add 4, sum=6', noteJa: '4を加算', noteVi: 'add 4' },
      { step: 'r=2,c=3', variables: 'add 6, sum=12', noteJa: '6を加算', noteVi: 'add 6' },
    ],
    choices: [
      { ja: '6', vi: '6', whyVi: 'Sai, chỉ cộng 2+4.', whyJa: '6を足し忘れています。' },
      { ja: '9', vi: '9', whyVi: 'Sai, cộng số lẻ.', whyJa: '奇数を含めています。' },
      { ja: '12', vi: '12', whyVi: 'Đúng: 2+4+6.', whyJa: '正解。2+4+6です。' },
      { ja: '21', vi: '21', whyVi: 'Sai, đó là tổng tất cả phần tử.', whyJa: '全要素の合計です。' },
    ], answerIndex: 2,
    trapJa: '行・列の順序と条件分岐を同時に見る。', trapVi: 'Cần theo dõi cả thứ tự row/col và điều kiện if.',
    examTipJa: '二重ループは外側1回につき内側が何回動くかを先に数える。', examTipVi: 'Double loop: đếm inner loop chạy bao nhiêu lần cho mỗi outer loop.',
  },
  {
    id: 'v79r-kamoku-b-binary-search-not-found', kind: 'long-trace', domain: 'algorithm', difficulty: 'hard', relatedNodeIds: ['binary-search', 'array', 'trace-table'],
    titleJa: 'V79R 科目B：二分探索で見つからない場合', titleVi: 'V79R 科目B: binary search khi không tìm thấy',
    passageJa: '昇順配列 A=[2,5,8,12,20] から 7 を探す。low>high になったら未発見として終了する。',
    passageVi: 'Tìm 7 trong A=[2,5,8,12,20]. Khi low>high thì kết thúc không tìm thấy.',
    questionJa: '終了時の low, high と判定はどれか。', questionVi: 'low, high và kết luận khi kết thúc là gì?',
    code: 'low ← 1, high ← 5\nwhile low <= high\n  mid ← floor((low+high)/2)\n  if A[mid] < 7 then low ← mid+1 else high ← mid-1',
    traceSteps: [
      { step: '1', variables: 'low=1 high=5 mid=3 A[3]=8 -> high=2', noteJa: '8は大きい', noteVi: '8 is too large' },
      { step: '2', variables: 'low=1 high=2 mid=1 A[1]=2 -> low=2', noteJa: '2は小さい', noteVi: '2 is too small' },
      { step: '3', variables: 'low=2 high=2 mid=2 A[2]=5 -> low=3', noteJa: '5は小さい', noteVi: '5 is too small' },
      { step: 'end', variables: 'low=3 high=2 not found', noteJa: 'low>high', noteVi: 'low>high' },
    ],
    choices: [
      { ja: 'low=2, high=2, found', vi: 'low=2, high=2, found', whyVi: 'Sai, A[2]=5 không phải 7.', whyJa: 'A[2]は5です。' },
      { ja: 'low=3, high=2, not found', vi: 'low=3, high=2, not found', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'low=1, high=5, not found', vi: 'low=1, high=5, not found', whyVi: 'Sai, phạm vi đã được cập nhật.', whyJa: '範囲は更新されています。' },
      { ja: 'low=3, high=3, found', vi: 'low=3, high=3, found', whyVi: 'Sai, A[3]=8.', whyJa: 'A[3]は8です。' },
    ], answerIndex: 1,
    trapJa: '見つからない問題では終了条件 low>high を必ず書く。', trapVi: 'Không tìm thấy: luôn ghi điều kiện kết thúc low>high.',
    examTipJa: '二分探索はfound/not foundの両方を練習する。', examTipVi: 'Binary search cần luyện cả found và not found.',
  },
  {
    id: 'v79r-kamoku-b-sql-window-running-total', kind: 'sql-step', domain: 'database', difficulty: 'hard', relatedNodeIds: ['sql-aggregate', 'sql-select', 'database-fe'],
    titleJa: 'V79R 科目B寄りSQL：累計の読み取り', titleVi: 'V79R SQL FE: đọc running total',
    passageJa: '売上表 Sales(day, amount) から、日付順の累計を求める。集計対象と並び順を混同しない。',
    passageVi: 'Từ Sales(day, amount), tính tổng lũy kế theo ngày. Đừng nhầm aggregate với order.',
    questionJa: '日付順の累計として最も適切な式はどれか。', questionVi: 'Biểu thức nào phù hợp nhất để tính running total theo ngày?',
    table: 'Sales(day, amount)\n2026-01-01, 100\n2026-01-02, 50\n2026-01-03, 70',
    sqlSteps: [
      { step: 'ORDER', result: 'ORDER BY day', noteJa: '累計の順序', noteVi: 'order for running total' },
      { step: 'SUM', result: 'SUM(amount) OVER (...)', noteJa: '行を残したまま累計', noteVi: 'keep rows while computing total' },
      { step: 'RESULT', result: '100,150,220', noteJa: '日付順の累計', noteVi: 'running totals by day' },
    ],
    choices: [
      { ja: 'SUM(amount) OVER (ORDER BY day)', vi: 'SUM(amount) OVER (ORDER BY day)', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'SUM(day) OVER (ORDER BY amount)', vi: 'SUM(day) OVER (ORDER BY amount)', whyVi: 'Sai cột tính tổng và thứ tự đều sai.', whyJa: '集計対象と順序が違います。' },
      { ja: 'GROUP BY day HAVING amount > 0', vi: 'GROUP BY day HAVING amount > 0', whyVi: 'Sai vì không tạo lũy kế.', whyJa: '累計になりません。' },
      { ja: 'ORDER BY SUM(amount)', vi: 'ORDER BY SUM(amount)', whyVi: 'Sai vì chỉ sắp xếp aggregate.', whyJa: '累計ではありません。' },
    ], answerIndex: 0,
    trapJa: '累計は「何を合計するか」と「どの順で累積するか」を分ける。', trapVi: 'Running total: tách cột sum và thứ tự cộng dồn.',
    examTipJa: 'SQL読解では SELECT句の式を日本語で言い換える。', examTipVi: 'SQL: diễn giải SELECT expression thành tiếng người.',
  },
  {
    id: 'v79r-kamoku-b-security-log-trace', kind: 'japanese-scenario', domain: 'security', difficulty: 'hard', relatedNodeIds: ['log-monitoring', 'incident-response', 'web-security'],
    titleJa: 'V79R 午前/午後横断：ログから攻撃を読む', titleVi: 'V79R đọc log security kiểu FE',
    passageJa: 'Webサーバのログに、短時間で /login への失敗が同一IPから多数記録され、その後複数アカウントで成功ログが出た。最も疑わしい攻撃と初動対応を選べ。',
    passageVi: 'Log web server có nhiều login thất bại từ cùng IP trong thời gian ngắn, sau đó nhiều account login thành công. Chọn tấn công đáng nghi nhất và phản ứng ban đầu.',
    questionJa: '最も適切な判断はどれか。', questionVi: 'Nhận định phù hợp nhất là gì?',
    choices: [
      { ja: 'SQLインジェクションなのでDBを正規化する', vi: 'SQL injection nên normalize DB', whyVi: 'Sai, log mô tả thử đăng nhập hàng loạt.', whyJa: 'ログは大量ログイン試行を示します。' },
      { ja: 'ブルートフォース/パスワードリスト攻撃を疑い、IP制限・アカウント保護・ログ保全を行う', vi: 'Nghi brute force/password spraying; giới hạn IP, bảo vệ account, bảo toàn log', whyVi: 'Đúng.', whyJa: '正解。' },
      { ja: 'DNSキャッシュのTTLを短くする', vi: 'Giảm TTL DNS cache', whyVi: 'Không liên quan.', whyJa: '関係ありません。' },
      { ja: 'RAIDを追加して可用性だけを高める', vi: 'Thêm RAID để tăng availability', whyVi: 'Không phải phản ứng chính.', whyJa: '主対応ではありません。' },
    ], answerIndex: 1,
    trapJa: 'ログ問題は「何が何回・どこから・その後どうなったか」を読む。', trapVi: 'Đọc log theo: hành động gì, bao nhiêu lần, từ đâu, sau đó ra sao.',
    examTipJa: 'セキュリティは攻撃名よりも初動対応までセットで選ぶ。', examTipVi: 'Security FE: chọn cả attack type và initial response.',
  },
];
