import type { KnowledgeNodeData } from '../../features/knowledge-graph/types';
type Level = 'root' | 'major' | 'topic' | 'detail';
type Importance = 'high' | 'medium' | 'low';
const n = (id:string, vi:string, en:string, level:Level, importance:Importance='high', prerequisites:string[]=[]):KnowledgeNodeData => ({
  id, labelJa: en, labelVi: vi, labelEn: en, category:'database', level, importance,
  summaryVi:`${vi}: kiến thức SQL quan trọng để đọc, lọc, nối, tổng hợp, tối ưu và bảo vệ dữ liệu.`,
  summaryJa:`${en} はSQL学習で重要な概念です。`,
  examPointVi:`Cần hiểu vai trò của ${vi}, cú pháp thường dùng, thứ tự xử lý và lỗi dễ nhầm.`,
  examPointJa:`${en} の役割、構文、注意点を確認します。`,
  examples:[], keywords:[vi,en], prerequisites, related:[],
});

export const sqlNodes = [
  n('sql','SQL tổng quan','SQL','root','high',[]),
  n('rdbms','RDBMS','RDBMS','major','high',['sql']),
  n('database','Database','Database','topic','high',['rdbms']),
  n('schema','Schema','Schema','topic','medium',['database']),
  n('table','Table','Table','topic','high',['database']),
  n('row-column','Row / Column','Row / Column','topic','high',['table']),
  n('data-type','Data Types','Data Types','topic','high',['table']),
  n('constraint','Constraint','Constraint','topic','medium',['table']),
  n('primary-key','PRIMARY KEY','PRIMARY KEY','topic','high',['constraint']),
  n('foreign-key','FOREIGN KEY','FOREIGN KEY','topic','high',['primary-key']),
  n('unique','UNIQUE','UNIQUE','detail','medium',['constraint']),
  n('not-null','NOT NULL','NOT NULL','detail','medium',['constraint']),
  n('default','DEFAULT','DEFAULT','detail','low',['constraint']),
  n('select','SELECT','SELECT','major','high',['table']),
  n('select-list','SELECT list','SELECT list','detail','medium',['select']),
  n('alias','Alias','Alias','detail','medium',['select']),
  n('distinct','DISTINCT','DISTINCT','topic','high',['select']),
  n('where','WHERE','WHERE','topic','high',['select']),
  n('comparison-operators','Comparison Operators','Comparison Operators','topic','medium',['where']),
  n('logical-operators','AND / OR / NOT','AND / OR / NOT','topic','medium',['where']),
  n('like','LIKE','LIKE','topic','high',['where']),
  n('between','BETWEEN','BETWEEN','topic','medium',['where']),
  n('in-operator','IN','IN','topic','medium',['where']),
  n('is-null','IS NULL','IS NULL','topic','high',['where']),
  n('order-by','ORDER BY','ORDER BY','topic','high',['select']),
  n('limit','LIMIT','LIMIT','detail','medium',['select']),
  n('case-when','CASE WHEN','CASE WHEN','topic','medium',['select']),
  n('join','JOIN','JOIN','major','high',['foreign-key','select']),
  n('inner-join','INNER JOIN','INNER JOIN','topic','high',['join']),
  n('left-join','LEFT JOIN','LEFT JOIN','topic','high',['join']),
  n('right-join','RIGHT JOIN','RIGHT JOIN','detail','medium',['join']),
  n('full-join','FULL OUTER JOIN','FULL OUTER JOIN','detail','medium',['join']),
  n('cross-join','CROSS JOIN','CROSS JOIN','detail','low',['join']),
  n('self-join','SELF JOIN','SELF JOIN','topic','medium',['join']),
  n('join-condition','JOIN condition','JOIN condition','topic','high',['join']),
  n('many-to-many','Many-to-many','Many-to-many','topic','medium',['foreign-key']),
  n('group-by','GROUP BY','GROUP BY','major','high',['select']),
  n('aggregate-functions','Aggregate Functions','Aggregate Functions','topic','high',['group-by']),
  n('count','COUNT','COUNT','detail','high',['aggregate-functions']),
  n('sum-avg','SUM / AVG','SUM / AVG','detail','high',['aggregate-functions']),
  n('min-max','MIN / MAX','MIN / MAX','detail','medium',['aggregate-functions']),
  n('having','HAVING','HAVING','topic','high',['group-by']),
  n('grouping-error','Grouping Error','Grouping Error','topic','high',['group-by']),
  n('subquery','Subquery','Subquery','topic','medium',['select']),
  n('exists','EXISTS','EXISTS','topic','medium',['subquery']),
  n('union','UNION','UNION','topic','medium',['select']),
  n('cte','CTE / WITH','CTE / WITH','topic','medium',['subquery']),
  n('window-function','Window Function','Window Function','topic','medium',['group-by']),
  n('rank-row-number','RANK / ROW_NUMBER','RANK / ROW_NUMBER','detail','medium',['window-function']),
  n('insert','INSERT','INSERT','major','high',['table']),
  n('insert-select','INSERT SELECT','INSERT SELECT','detail','medium',['insert']),
  n('update','UPDATE','UPDATE','topic','high',['where']),
  n('delete','DELETE','DELETE','topic','high',['where']),
  n('truncate','TRUNCATE','TRUNCATE','detail','medium',['delete']),
  n('create-table','CREATE TABLE','CREATE TABLE','topic','medium',['table']),
  n('alter-table','ALTER TABLE','ALTER TABLE','detail','medium',['create-table']),
  n('drop-table','DROP TABLE','DROP TABLE','detail','medium',['create-table']),
  n('view','VIEW','VIEW','detail','low',['select']),
  n('index','INDEX','INDEX','major','high',['table']),
  n('composite-index','Composite Index','Composite Index','topic','medium',['index']),
  n('covering-index','Covering Index','Covering Index','detail','low',['index']),
  n('explain','EXPLAIN','EXPLAIN','topic','medium',['index']),
  n('query-plan','Query Plan','Query Plan','detail','medium',['explain']),
  n('normalization','Normalization','Normalization','topic','medium',['table']),
  n('first-normal-form','1NF','1NF','detail','medium',['normalization']),
  n('second-normal-form','2NF','2NF','detail','low',['normalization']),
  n('third-normal-form','3NF','3NF','detail','medium',['normalization']),
  n('denormalization','Denormalization','Denormalization','detail','low',['normalization']),
  n('transaction','TRANSACTION','TRANSACTION','major','high',['update','insert','delete']),
  n('commit-rollback','COMMIT / ROLLBACK','COMMIT / ROLLBACK','topic','high',['transaction']),
  n('acid','ACID','ACID','topic','high',['transaction']),
  n('isolation-level','Isolation Level','Isolation Level','topic','medium',['transaction']),
  n('deadlock','Deadlock','Deadlock','topic','medium',['transaction']),
  n('lock','Lock','Lock','detail','medium',['transaction']),
  n('sql-injection','SQL Injection','SQL Injection','major','high',['where']),
  n('parameterized-query','Parameterized Query','Parameterized Query','topic','high',['sql-injection']),
  n('input-validation-sql','Input Validation','Input Validation','topic','medium',['sql-injection']),
  n('least-privilege-sql','Least Privilege','Least Privilege','topic','medium',['sql-injection']),
  n('backup-restore','Backup / Restore','Backup / Restore','topic','medium',['database']),
  n('migration','Migration','Migration','topic','medium',['alter-table']),
  n('erd','ERD','ERD','topic','medium',['table']),
];
