import type { StudyPathPhase } from '../../features/knowledge-graph/data/studyPath';

export const sqlStudyPath: StudyPathPhase[] = [
  { id:'sql-path-1', titleVi:'Database nền tảng', titleJa:'Database Basic', goalVi:'Database, schema, table, keys, constraints.', goalJa:'Database, schema, table, keys, constraints.', nodeIds:['sql','rdbms','database','schema','table','row-column','data-type','constraint','primary-key','foreign-key','unique','not-null','default','erd'] },
  { id:'sql-path-2', titleVi:'SELECT và WHERE', titleJa:'SELECT and WHERE', goalVi:'SELECT, DISTINCT, WHERE, operators, ORDER BY, CASE.', goalJa:'SELECT, DISTINCT, WHERE, operators, ORDER BY, CASE.', nodeIds:['select','select-list','alias','distinct','where','comparison-operators','logical-operators','like','between','in-operator','is-null','order-by','limit','case-when'] },
  { id:'sql-path-3', titleVi:'JOIN', titleJa:'JOIN', goalVi:'INNER/LEFT/RIGHT/FULL, join condition, many-to-many.', goalJa:'INNER/LEFT/RIGHT/FULL, join condition, many-to-many.', nodeIds:['join','inner-join','left-join','right-join','full-join','cross-join','self-join','join-condition','many-to-many'] },
  { id:'sql-path-4', titleVi:'GROUP BY và truy vấn nâng cao', titleJa:'Aggregation and Advanced Query', goalVi:'Aggregate, HAVING, subquery, EXISTS, UNION, CTE, window function.', goalJa:'Aggregate, HAVING, subquery, EXISTS, UNION, CTE, window function.', nodeIds:['group-by','aggregate-functions','count','sum-avg','min-max','having','grouping-error','subquery','exists','union','cte','window-function','rank-row-number'] },
  { id:'sql-path-5', titleVi:'DML / DDL', titleJa:'DML and DDL', goalVi:'INSERT, UPDATE, DELETE, CREATE/ALTER/DROP, VIEW, migration.', goalJa:'INSERT, UPDATE, DELETE, CREATE/ALTER/DROP, VIEW, migration.', nodeIds:['insert','insert-select','update','delete','truncate','create-table','alter-table','drop-table','view','migration'] },
  { id:'sql-path-6', titleVi:'Index và thiết kế', titleJa:'Index and Design', goalVi:'Index, EXPLAIN, normalization, denormalization.', goalJa:'Index, EXPLAIN, normalization, denormalization.', nodeIds:['index','composite-index','covering-index','explain','query-plan','normalization','first-normal-form','second-normal-form','third-normal-form','denormalization'] },
  { id:'sql-path-7', titleVi:'Transaction', titleJa:'Transaction', goalVi:'ACID, commit/rollback, isolation, lock, deadlock.', goalJa:'ACID, commit/rollback, isolation, lock, deadlock.', nodeIds:['transaction','commit-rollback','acid','isolation-level','lock','deadlock'] },
  { id:'sql-path-8', titleVi:'Security / Operation', titleJa:'Security and Operation', goalVi:'SQL injection, parameterized query, least privilege, backup.', goalJa:'SQL injection, parameterized query, least privilege, backup.', nodeIds:['sql-injection','parameterized-query','input-validation-sql','least-privilege-sql','backup-restore'] },
];
