import type { QuizQuestion } from '../../../../features/knowledge-graph/data/quizQuestions';

export const aiQualityDatabaseQuiz: QuizQuestion[] = [
  {"id":"aiqp-011","domain":"database","nodeId":"data-preprocessing-ai","difficulty":"hard","questionVi":"Dữ liệu có nhiều ô trống trước khi train model. Hành động phù hợp nhất là gì?","questionJa":"学習データに欠損値が多い場合、適切な対応はどれですか。","options":["Bỏ qua hoàn toàn","Xử lý欠損値 bằng loại bỏ/bổ sung phù hợp","Dùng test data để lấp vào train","Tăng số layer của neural network"],"answerIndex":1,"explanationVi":"Cần xử lý missing values trong preprocessing.","explanationJa":"欠損値処理は前処理の重要作業です。"},
  {"id":"aiqp-012","domain":"database","nodeId":"training-test-data","difficulty":"hard","questionVi":"Điều nào gây đánh giá model không đáng tin?","questionJa":"モデル評価を信頼できなくする行為はどれですか。","options":["Chia train/test","Dùng test data để training","Dùng validation data để điều chỉnh","Đánh giá bằng metric phù hợp"],"answerIndex":1,"explanationVi":"Test data chỉ dùng để đánh giá, không dùng để train.","explanationJa":"テストデータを学習に使うと評価が不正確になります。"},
  {"id":"aiqp-extra-012","domain":"database","nodeId":"data-drift-ai","difficulty":"hard","questionVi":"データドリフト được hiểu đúng nhất là gì?","questionJa":"データドリフトの説明として最も適切なものはどれですか。","options":["Data drift là khái niệm liên quan đến 入力分布 / 変化","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"データドリフト cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 入力分布.","explanationJa":"データドリフトは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-039","domain":"database","nodeId":"vector-database-ai","difficulty":"standard","questionVi":"ベクトルデータベース được hiểu đúng nhất là gì?","questionJa":"ベクトルデータベースの説明として最も適切なものはどれですか。","options":["Vector database là khái niệm liên quan đến ベクトル / 検索","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"ベクトルデータベース cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với ベクトル.","explanationJa":"ベクトルデータベースは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-080","domain":"database","nodeId":"feature-engineering-ai","difficulty":"hard","questionVi":"特徴量エンジニアリング được hiểu đúng nhất là gì?","questionJa":"特徴量エンジニアリングの説明として最も適切なものはどれですか。","options":["Feature engineering là khái niệm liên quan đến 特徴量 / 変換","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"特徴量エンジニアリング cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 特徴量.","explanationJa":"特徴量エンジニアリングは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-081","domain":"database","nodeId":"normalization-ai-data","difficulty":"hard","questionVi":"正規化 được hiểu đúng nhất là gì?","questionJa":"正規化の説明として最も適切なものはどれですか。","options":["Chuẩn hóa dữ liệu là khái niệm liên quan đến スケール / 正規化","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"正規化 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với スケール.","explanationJa":"正規化は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-082","domain":"database","nodeId":"standardization-ai","difficulty":"standard","questionVi":"標準化 được hiểu đúng nhất là gì?","questionJa":"標準化の説明として最も適切なものはどれですか。","options":["Standardization là khái niệm liên quan đến 平均 / 分散","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"標準化 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 平均.","explanationJa":"標準化は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-083","domain":"database","nodeId":"missing-value-ai","difficulty":"hard","questionVi":"欠損値処理 được hiểu đúng nhất là gì?","questionJa":"欠損値処理の説明として最も適切なものはどれですか。","options":["Xử lý thiếu dữ liệu là khái niệm liên quan đến 欠損 / 補完","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"欠損値処理 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 欠損.","explanationJa":"欠損値処理は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-084","domain":"database","nodeId":"outlier-ai","difficulty":"standard","questionVi":"外れ値処理 được hiểu đúng nhất là gì?","questionJa":"外れ値処理の説明として最も適切なものはどれですか。","options":["Xử lý ngoại lệ là khái niệm liên quan đến 外れ値 / 異常値","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"外れ値処理 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 外れ値.","explanationJa":"外れ値処理は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-085","domain":"database","nodeId":"label-encoding-ai","difficulty":"standard","questionVi":"ラベルエンコーディング được hiểu đúng nhất là gì?","questionJa":"ラベルエンコーディングの説明として最も適切なものはどれですか。","options":["Label encoding là khái niệm liên quan đến カテゴリ / 数値化","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"ラベルエンコーディング cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với カテゴリ.","explanationJa":"ラベルエンコーディングは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-086","domain":"database","nodeId":"one-hot-ai","difficulty":"standard","questionVi":"One-hotエンコーディング được hiểu đúng nhất là gì?","questionJa":"One-hotエンコーディングの説明として最も適切なものはどれですか。","options":["One-hot encoding là khái niệm liên quan đến カテゴリ / ダミー変数","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"One-hotエンコーディング cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với カテゴリ.","explanationJa":"One-hotエンコーディングは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-087","domain":"database","nodeId":"data-split-ai","difficulty":"hard","questionVi":"データ分割 được hiểu đúng nhất là gì?","questionJa":"データ分割の説明として最も適切なものはどれですか。","options":["Chia dữ liệu là khái niệm liên quan đến 訓練 / 検証","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"データ分割 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 訓練.","explanationJa":"データ分割は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-088","domain":"database","nodeId":"validation-data-ai","difficulty":"hard","questionVi":"検証データ được hiểu đúng nhất là gì?","questionJa":"検証データの説明として最も適切なものはどれですか。","options":["Validation data là khái niệm liên quan đến 検証 / チューニング","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"検証データ cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 検証.","explanationJa":"検証データは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-089","domain":"database","nodeId":"test-data-leakage-ai","difficulty":"hard","questionVi":"データリーク được hiểu đúng nhất là gì?","questionJa":"データリークの説明として最も適切なものはどれですか。","options":["Data leakage là khái niệm liên quan đến リーク / 評価","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"データリーク cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với リーク.","explanationJa":"データリークは目的、具体例、注意点をセットで理解します。"},
];
