import type { QuizQuestion } from '../../../../features/knowledge-graph/data/quizQuestions';

export const aiQualityManagementQuiz: QuizQuestion[] = [
  {"id":"aiqp-029","domain":"management","nodeId":"ai-project-flow","difficulty":"standard","questionVi":"Thứ tự hợp lý khi bắt đầu dự án AI là gì?","questionJa":"AIプロジェクト開始時の適切な流れはどれですか。","options":["Chọn model trước, mục tiêu sau","Xác định vấn đề/mục tiêu → kiểm tra dữ liệu → model/evaluation","Deploy trước rồi tính rủi ro sau","Chỉ hỏi AI làm tất cả"],"answerIndex":1,"explanationVi":"Dự án AI bắt đầu từ problem/business goal và dữ liệu.","explanationJa":"AIプロジェクトは課題設定とデータ確認から始めます。"},
  {"id":"aiqp-extra-066","domain":"management","nodeId":"ai-vendor-management","difficulty":"standard","questionVi":"ベンダ管理 được hiểu đúng nhất là gì?","questionJa":"ベンダ管理の説明として最も適切なものはどれですか。","options":["Quản lý vendor AI là khái niệm liên quan đến ベンダ / 委託","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"ベンダ管理 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với ベンダ.","explanationJa":"ベンダ管理は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-067","domain":"management","nodeId":"ai-contract-ai","difficulty":"standard","questionVi":"AI契約 được hiểu đúng nhất là gì?","questionJa":"AI契約の説明として最も適切なものはどれですか。","options":["Hợp đồng AI là khái niệm liên quan đến 契約 / 責任","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"AI契約 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 契約.","explanationJa":"AI契約は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-068","domain":"management","nodeId":"ai-guideline-company","difficulty":"hard","questionVi":"社内AI利用ルール được hiểu đúng nhất là gì?","questionJa":"社内AI利用ルールの説明として最も適切なものはどれですか。","options":["Quy định dùng AI nội bộ là khái niệm liên quan đến 社内ルール / 禁止事項","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"社内AI利用ルール cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 社内ルール.","explanationJa":"社内AI利用ルールは目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-069","domain":"management","nodeId":"ai-literacy-training","difficulty":"standard","questionVi":"AIリテラシー教育 được hiểu đúng nhất là gì?","questionJa":"AIリテラシー教育の説明として最も適切なものはどれですか。","options":["Đào tạo AI literacy là khái niệm liên quan đến 教育 / 研修","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"AIリテラシー教育 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 教育.","explanationJa":"AIリテラシー教育は目的、具体例、注意点をセットで理解します。"},
  {"id":"aiqp-extra-070","domain":"management","nodeId":"ai-quality-assurance","difficulty":"hard","questionVi":"AI品質保証 được hiểu đúng nhất là gì?","questionJa":"AI品質保証の説明として最も適切なものはどれですか。","options":["QA cho AI là khái niệm liên quan đến 品質 / テスト","Đây là lệnh SQL để xóa bảng","Đây là giao thức cấp phát địa chỉ IP","Đây là phím tắt mở DevTools"],"answerIndex":0,"explanationVi":"AI品質保証 cần học theo mục đích, ví dụ và rủi ro. Trong đề, hãy chọn đáp án gắn với 品質.","explanationJa":"AI品質保証は目的、具体例、注意点をセットで理解します。"},
];
