import type { KnowledgeNodeData } from '../../features/knowledge-graph/types';
type Level = 'root' | 'major' | 'topic' | 'detail';
type Importance = 'high' | 'medium' | 'low';
const n = (id:string, vi:string, en:string, level:Level, importance:Importance='high', prerequisites:string[]=[]):KnowledgeNodeData => ({
  id, labelJa: en, labelVi: vi, labelEn: en, category:'software', level, importance,
  summaryVi: `${vi}: kiến thức Frontend cần hiểu để xây giao diện web dễ dùng, dễ bảo trì.`,
  summaryJa: `${en} はフロントエンド学習で重要な概念です。`,
  examPointVi: `Cần nắm vai trò của ${vi}, ví dụ sử dụng, lỗi dễ nhầm và liên hệ với UI thực tế.`,
  examPointJa: `${en} の役割、利用例、注意点を確認します。`,
  examples:[], keywords:[vi,en], prerequisites, related:[],
});

export const frontendNodes = [
  n('frontend','Frontend tổng quan','Frontend','root','high',[]),
  n('web-browser','Trình duyệt web','Web Browser','major','high',['frontend']),
  n('client-server','Client / Server','Client / Server','topic','high',['frontend']),
  n('http-basics','HTTP cơ bản','HTTP Basics','topic','high',['client-server']),
  n('html','HTML','HTML','major','high',['frontend']),
  n('html-document','HTML Document','HTML Document','topic','high',['html']),
  n('semantic-html','Semantic HTML','Semantic HTML','topic','high',['html']),
  n('html-head','Head / Meta','Head / Meta','detail','medium',['html-document']),
  n('html-links','Link / Anchor','Anchor Links','detail','medium',['html']),
  n('html-images','Image Tag','Image Tag','detail','medium',['html']),
  n('form-html','Form HTML','HTML Forms','topic','high',['html']),
  n('input-types','Input Types','Input Types','detail','medium',['form-html']),
  n('form-accessibility','Form Accessibility','Form Accessibility','detail','high',['form-html']),
  n('css','CSS','CSS','major','high',['html']),
  n('cascade','Cascade','CSS Cascade','topic','high',['css']),
  n('specificity','CSS Specificity','Specificity','topic','high',['cascade']),
  n('css-selectors','CSS Selectors','CSS Selectors','topic','high',['css']),
  n('box-model','Box Model','Box Model','topic','high',['css']),
  n('display','Display','Display','detail','medium',['box-model']),
  n('position','Position','CSS Position','topic','high',['css']),
  n('flexbox','Flexbox','Flexbox','topic','high',['css']),
  n('grid','CSS Grid','CSS Grid','topic','high',['css']),
  n('responsive','Responsive Design','Responsive Design','topic','high',['css']),
  n('media-query','Media Query','Media Query','detail','high',['responsive']),
  n('css-variables','CSS Variables','CSS Variables','topic','medium',['css']),
  n('animation','CSS Animation','CSS Animation','topic','medium',['css']),
  n('tailwind','Tailwind CSS','Tailwind CSS','topic','medium',['css']),
  n('javascript','JavaScript','JavaScript','major','high',['css']),
  n('variables','Variables','Variables','topic','high',['javascript']),
  n('data-types','Data Types','Data Types','topic','high',['javascript']),
  n('functions','Functions','Functions','topic','high',['javascript']),
  n('scope','Scope','Scope','topic','high',['functions']),
  n('array-methods','Array Methods','Array Methods','topic','high',['javascript']),
  n('object-basics','Object Basics','Objects','topic','high',['javascript']),
  n('destructuring','Destructuring','Destructuring','detail','medium',['object-basics']),
  n('modules','ES Modules','ES Modules','topic','high',['javascript']),
  n('dom','DOM','DOM','topic','high',['javascript']),
  n('event-handling','Event Handling','Event Handling','topic','high',['dom']),
  n('fetch-api','Fetch API','Fetch API','topic','high',['javascript']),
  n('promise','Promise','Promise','topic','high',['fetch-api']),
  n('async-await','Async/Await','Async/Await','topic','high',['promise']),
  n('error-handling-js','JS Error Handling','JS Error Handling','topic','medium',['async-await']),
  n('typescript','TypeScript','TypeScript','major','high',['javascript']),
  n('type-system','Type System','Type System','topic','high',['typescript']),
  n('interface-type','Interface / Type','Interface / Type','topic','high',['type-system']),
  n('generics','Generics','Generics','topic','medium',['typescript']),
  n('narrowing','Type Narrowing','Type Narrowing','topic','medium',['typescript']),
  n('react','React','React','major','high',['typescript']),
  n('component','Component','Component','topic','high',['react']),
  n('jsx','JSX','JSX','topic','high',['react']),
  n('props','Props','Props','topic','high',['component']),
  n('state','State','State','topic','high',['component']),
  n('hooks','Hooks','Hooks','topic','high',['state']),
  n('use-effect','useEffect','useEffect','topic','high',['hooks']),
  n('custom-hooks','Custom Hooks','Custom Hooks','topic','medium',['hooks']),
  n('conditional-render','Conditional Render','Conditional Rendering','detail','medium',['react']),
  n('list-render','List Render','List Rendering','detail','medium',['react']),
  n('controlled-form','Controlled Form','Controlled Form','topic','high',['state']),
  n('form-validation','Form Validation','Form Validation','topic','high',['controlled-form']),
  n('context','React Context','React Context','topic','medium',['react']),
  n('router','Router','Router','topic','medium',['react']),
  n('api','API kết nối backend','API Integration','major','high',['fetch-api','react']),
  n('rest-api','REST API','REST API','topic','high',['api']),
  n('json','JSON','JSON','topic','high',['api']),
  n('tanstack-query','TanStack Query','TanStack Query','topic','medium',['api']),
  n('loading-error-ui','Loading / Error UI','Loading / Error UI','topic','high',['api']),
  n('testing','Testing','Testing','major','high',['react']),
  n('unit-test','Unit Test','Unit Test','topic','medium',['testing']),
  n('vitest','Vitest','Vitest','topic','medium',['unit-test']),
  n('testing-library','Testing Library','Testing Library','topic','medium',['unit-test']),
  n('e2e-test','E2E Test','E2E Test','topic','medium',['testing']),
  n('playwright','Playwright','Playwright','topic','medium',['e2e-test']),
  n('quality','Code Quality','Code Quality','major','high',['typescript']),
  n('eslint','ESLint','ESLint','topic','medium',['quality']),
  n('prettier','Prettier','Prettier','topic','medium',['quality']),
  n('git-basic','Git Basic','Git Basic','topic','medium',['quality']),
  n('performance','Performance','Performance','major','high',['react']),
  n('web-vitals','Web Vitals','Web Vitals','topic','medium',['performance']),
  n('lazy-loading','Lazy Loading','Lazy Loading','topic','medium',['performance']),
  n('bundle-size','Bundle Size','Bundle Size','topic','medium',['performance']),
  n('accessibility','Accessibility','Accessibility','major','high',['semantic-html']),
  n('aria','ARIA','ARIA','topic','medium',['accessibility']),
  n('keyboard-nav','Keyboard Navigation','Keyboard Navigation','topic','high',['accessibility']),
  n('seo','SEO','SEO','topic','medium',['semantic-html']),
  n('deploy','Deploy web','Deploy','major','high',['testing','performance']),
  n('vite','Vite','Vite','topic','medium',['deploy']),
  n('env-vars','Environment Variables','Environment Variables','topic','medium',['deploy']),
  n('ci-cd','CI/CD','CI/CD','topic','medium',['deploy']),
  n('vercel','Vercel','Vercel','topic','low',['deploy']),
  n('project-profile-card','Project: Profile Card','Profile Card Project','detail','medium',['html','css']),
  n('project-todo','Project: Todo App','Todo App Project','detail','high',['react','state']),
  n('project-api-search','Project: API Search App','API Search Project','detail','high',['api','loading-error-ui']),
  n('project-dashboard','Project: Dashboard UI','Dashboard UI Project','detail','high',['react','performance']),
];
