import type { StudyPathPhase } from '../../features/knowledge-graph/data/studyPath';

export const frontendStudyPath: StudyPathPhase[] = [
  { id:'fe-path-1', titleVi:'Web nền tảng', titleJa:'Web Basic', goalVi:'Browser, HTTP, HTML, Semantic HTML, Forms.', goalJa:'Browser, HTTP, HTML, Semantic HTML, Forms.', nodeIds:['frontend','web-browser','client-server','http-basics','html','html-document','semantic-html','html-head','html-links','html-images','form-html','input-types','form-accessibility'] },
  { id:'fe-path-2', titleVi:'CSS layout', titleJa:'CSS Layout', goalVi:'Cascade, selector, box model, flexbox, grid, responsive.', goalJa:'Cascade, selector, box model, flexbox, grid, responsive.', nodeIds:['css','cascade','specificity','css-selectors','box-model','display','position','flexbox','grid','responsive','media-query','css-variables','animation','tailwind'] },
  { id:'fe-path-3', titleVi:'JavaScript nền tảng', titleJa:'JavaScript Basic', goalVi:'Variables, functions, arrays, objects, DOM, async.', goalJa:'Variables, functions, arrays, objects, DOM, async.', nodeIds:['javascript','variables','data-types','functions','scope','array-methods','object-basics','destructuring','modules','dom','event-handling','fetch-api','promise','async-await','error-handling-js'] },
  { id:'fe-path-4', titleVi:'TypeScript', titleJa:'TypeScript', goalVi:'Type system, interface/type, generics, narrowing.', goalJa:'Type system, interface/type, generics, narrowing.', nodeIds:['typescript','type-system','interface-type','generics','narrowing'] },
  { id:'fe-path-5', titleVi:'React căn bản', titleJa:'React Basic', goalVi:'Component, JSX, props, state, hooks.', goalJa:'Component, JSX, props, state, hooks.', nodeIds:['react','component','jsx','props','state','hooks','use-effect','custom-hooks','conditional-render','list-render'] },
  { id:'fe-path-6', titleVi:'React app thực tế', titleJa:'Real React App', goalVi:'Forms, validation, context, router, API, REST, JSON, loading/error UI.', goalJa:'Forms, validation, context, router, API, REST, JSON, loading/error UI.', nodeIds:['controlled-form','form-validation','context','router','api','rest-api','json','tanstack-query','loading-error-ui'] },
  { id:'fe-path-7', titleVi:'Quality / Test / Performance', titleJa:'Quality', goalVi:'Testing, code quality, performance, accessibility, SEO.', goalJa:'Testing, code quality, performance, accessibility, SEO.', nodeIds:['testing','unit-test','vitest','testing-library','e2e-test','playwright','quality','eslint','prettier','git-basic','performance','web-vitals','lazy-loading','bundle-size','accessibility','aria','keyboard-nav','seo'] },
  { id:'fe-path-8', titleVi:'Deploy và project', titleJa:'Deploy and Projects', goalVi:'Vite, env, CI/CD, deploy, projects.', goalJa:'Vite, env, CI/CD, deploy, projects.', nodeIds:['deploy','vite','env-vars','ci-cd','vercel','project-profile-card','project-todo','project-api-search','project-dashboard'] },
];
