import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';

export const aiPassportV52InfraLessons: LessonContent[] = [
  {
    nodeId: 'customer-churn-ai',
    shortDefinitionVi: 'Dự đoán rời bỏ là dùng AI ước lượng khách hàng nào có khả năng ngừng sử dụng dịch vụ, để công ty chăm sóc hoặc giữ chân đúng lúc.',
    shortDefinitionJa: '解約予測は、どの顧客がサービスをやめそうかをAIで推定し、適切なタイミングで維持施策を行うためのものです。',
    whyImportantVi: 'Đây là ví dụ tốt để phân biệt classification, marketing AI và business KPI. Output thường là rời bỏ/có-không hoặc xác suất rời bỏ.',
    whyImportantJa: '分類、マーケティングAI、業務KPIを結び付ける良い例です。出力は解約する/しない、または解約確率です。',
    examPatternsVi: ['Nhận diện đây thường là classification hoặc scoring.', 'Dữ liệu đầu vào: lịch sử mua, tần suất dùng, khiếu nại, thanh toán, phản hồi.', 'Hỏi hành động sau dự đoán: ưu đãi, chăm sóc, khảo sát, nhưng tránh làm phiền.'],
    examPatternsJa: ['多くの場合、分類またはスコアリング問題として扱う。', '入力データ：購買履歴、利用頻度、苦情、支払い、フィードバック。', '予測後の施策：特典、サポート、調査。ただし過度な連絡は避ける。'],
    commonMistakesVi: ['Chỉ dự đoán mà không thiết kế hành động kinh doanh sau đó.', 'Dùng dữ liệu nhạy cảm không cần thiết.', 'Đánh giá model bằng accuracy trong dữ liệu mất cân bằng mà không xem recall/precision.'],
    commonMistakesJa: ['予測だけして、その後の業務施策を設計しない。', '不要なセンシティブデータを使う。', '不均衡データで正解率だけを見て、再現率・適合率を見ない。'],
    memoryTipVi: 'Mẹo nhớ: Churn AI = ai sắp rời đi + vì sao + nên chăm sóc thế nào.',
    memoryTipJa: '覚え方：解約予測 = 誰がやめそうか、なぜか、どう対応するか。',
  },
  {
    nodeId: 'gpu-ai',
    shortDefinitionVi: 'GPU là bộ xử lý có rất nhiều lõi nhỏ, giỏi tính toán song song nên phù hợp cho huấn luyện và chạy mô hình AI/deep learning lớn.',
    shortDefinitionJa: 'GPUは多数の小さなコアで並列計算を得意とする処理装置で、大規模AI・深層学習の学習や推論に向いています。',
    whyImportantVi: 'AI Passport thường hỏi vì sao AI cần GPU. Câu trả lời không phải “GPU thông minh hơn CPU”, mà vì nhiều phép tính ma trận có thể chạy song song.',
    whyImportantJa: 'AIでGPUが使われる理由が問われます。GPUがCPUより賢いのではなく、多数の行列計算を並列処理できるからです。',
    examPatternsVi: ['Chọn GPU cho deep learning, image processing, large model training/inference.', 'Phân biệt CPU xử lý đa năng tuần tự mạnh, GPU xử lý song song mạnh.', 'Hỏi trade-off: chi phí, điện năng, nhiệt, cloud GPU.'],
    examPatternsJa: ['深層学習、画像処理、大規模モデルの学習・推論でGPUを選ぶ。', 'CPUは汎用処理、GPUは並列計算が得意。', 'コスト、電力、発熱、クラウドGPUのトレードオフ。'],
    commonMistakesVi: ['Nghĩ mọi AI đều bắt buộc cần GPU; mô hình nhỏ hoặc inference nhẹ có thể chạy CPU/edge.', 'Chỉ tính giá mua GPU mà quên điện, làm mát, vận hành.', 'Nhầm GPU với cloud; GPU có thể local hoặc cloud.'],
    commonMistakesJa: ['すべてのAIにGPUが必須だと思う。小規模推論はCPUやエッジでも可能。', 'GPU購入費だけ見て電力・冷却・運用費を忘れる。', 'GPUとクラウドを混同する。GPUはオンプレにもクラウドにもある。'],
    memoryTipVi: 'Mẹo nhớ: GPU = nhiều người cùng làm phép tính giống nhau, nên nhanh với ma trận AI.',
    memoryTipJa: '覚え方：GPU = 多人数で同じ種類の計算を同時に進める。AIの行列計算に強い。',
  },
  {
    nodeId: 'cloud-gpu-ai',
    shortDefinitionVi: 'Cloud GPU là thuê GPU trên cloud để huấn luyện hoặc chạy AI mà không cần tự mua máy chủ GPU, thường trả theo thời gian sử dụng.',
    shortDefinitionJa: 'クラウドGPUは、GPUサーバを自社購入せずクラウド上で借りてAI学習・推論に使う方法です。利用時間に応じて課金されます。',
    whyImportantVi: 'Cloud GPU phù hợp khi cần thử nhanh hoặc nhu cầu thay đổi. Nhưng cần quản lý chi phí, bảo mật dữ liệu và vị trí lưu trữ.',
    whyImportantJa: 'すばやい検証や需要変動に向きます。一方でコスト管理、データ保護、保存場所の確認が必要です。',
    examPatternsVi: ['Chọn cloud GPU cho PoC hoặc workload tăng giảm theo thời điểm.', 'So sánh với on-prem GPU: cloud linh hoạt, on-prem kiểm soát tốt nhưng đầu tư lớn.', 'Hỏi rủi ro: chi phí tăng, dữ liệu nhạy cảm, cấu hình quyền truy cập.'],
    examPatternsJa: ['PoCや変動するワークロードでクラウドGPUを選ぶ。', 'オンプレGPUとの比較：クラウドは柔軟、オンプレは管理しやすいが初期投資大。', 'リスク：費用増加、機密データ、アクセス権設定。'],
    commonMistakesVi: ['Bật GPU cloud rồi quên tắt, phát sinh chi phí lớn.', 'Đưa dữ liệu cá nhân lên cloud mà chưa kiểm tra quy định/hợp đồng.', 'Chọn GPU quá mạnh so với nhu cầu inference nhỏ.'],
    commonMistakesJa: ['クラウドGPUを起動したまま忘れて高額費用になる。', '契約・規制確認なしに個人情報をクラウドへ置く。', '小さな推論に過剰なGPUを選ぶ。'],
    memoryTipVi: 'Mẹo nhớ: Cloud GPU = thuê sức mạnh AI khi cần, nhưng phải nhớ kiểm soát tiền và dữ liệu.',
    memoryTipJa: '覚え方：クラウドGPU = 必要な時だけ借りるAI計算力。ただし費用とデータ管理。',
  },
  {
    nodeId: 'edge-device-ai',
    shortDefinitionVi: 'Thiết bị edge là thiết bị gần nơi dữ liệu phát sinh như camera, sensor, điện thoại, máy công nghiệp, có thể xử lý AI ngay tại chỗ.',
    shortDefinitionJa: 'エッジデバイスは、カメラ、センサ、スマホ、産業機械など、データ発生場所に近い端末でAI処理を行えるものです。',
    whyImportantVi: 'Edge AI giảm độ trễ, giảm gửi dữ liệu lên cloud và có thể hoạt động khi mạng yếu. AI Passport hay hỏi trong IoT, nhà máy, camera và mobile.',
    whyImportantJa: 'エッジAIは低遅延、クラウド送信量削減、通信不安定時の動作に有利です。IoT、工場、カメラ、モバイルで問われます。',
    examPatternsVi: ['Chọn edge khi cần phản ứng thời gian thực như phát hiện lỗi trên dây chuyền.', 'Hỏi lợi ích privacy: dữ liệu ảnh/âm thanh không cần gửi toàn bộ lên cloud.', 'Hỏi giới hạn: pin, bộ nhớ, tính toán yếu hơn cloud GPU.'],
    examPatternsJa: ['ライン上の欠陥検出などリアルタイム処理でエッジを選ぶ。', 'プライバシー利点：画像・音声を全てクラウド送信しない。', '制約：バッテリー、メモリ、計算能力はクラウドGPUより小さい。'],
    commonMistakesVi: ['Đưa bài toán cần phản ứng tức thời lên cloud xa gây trễ.', 'Quên cập nhật model trên nhiều thiết bị edge.', 'Nghĩ edge luôn an toàn; thiết bị tại hiện trường vẫn có thể bị đánh cắp/tấn công.'],
    commonMistakesJa: ['即時応答が必要なのに遠いクラウドで処理して遅延させる。', '多数のエッジ端末のモデル更新を忘れる。', 'エッジなら常に安全と思う。現場端末は盗難・攻撃リスクがある。'],
    memoryTipVi: 'Mẹo nhớ: Edge = xử lý gần nguồn dữ liệu. Gần hơn thì nhanh hơn và ít gửi dữ liệu hơn.',
    memoryTipJa: '覚え方：エッジ = データの近くで処理。近いほど速く、送信量も少ない。',
  },
  {
    nodeId: 'on-device-ai',
    shortDefinitionVi: 'On-device AI là AI chạy trực tiếp trên thiết bị người dùng như điện thoại, PC, camera hoặc thiết bị IoT thay vì gửi toàn bộ dữ liệu lên server.',
    shortDefinitionJa: 'オンデバイスAIは、スマホ、PC、カメラ、IoT端末など利用者の端末上でAIを実行し、全データをサーバへ送らない方法です。',
    whyImportantVi: 'Nó liên quan privacy, latency và offline. Đề hay hỏi vì sao nhận diện giọng nói/ảnh hoặc gợi ý bàn phím có thể chạy ngay trên máy.',
    whyImportantJa: 'プライバシー、低遅延、オフライン利用に関係します。音声・画像認識やキーボード予測が端末内で動く理由が問われます。',
    examPatternsVi: ['Chọn on-device khi muốn giảm gửi dữ liệu cá nhân lên cloud.', 'Hỏi lợi ích: phản hồi nhanh, dùng offline, giảm băng thông.', 'Hỏi giới hạn: model phải nhỏ, tiết kiệm pin, cập nhật khó hơn server.'],
    examPatternsJa: ['個人データをクラウド送信したくない場合にオンデバイスを選ぶ。', '利点：高速応答、オフライン利用、通信量削減。', '制約：モデル小型化、省電力、サーバより更新が難しい。'],
    commonMistakesVi: ['Nghĩ on-device nghĩa là không có rủi ro privacy; thiết bị vẫn cần bảo mật.', 'Chạy model quá lớn làm nóng máy/tốn pin.', 'Không có cơ chế cập nhật khi model cần sửa lỗi.'],
    commonMistakesJa: ['オンデバイスならプライバシーリスクがゼロだと思う。端末保護は必要。', '大きすぎるモデルで発熱・電池消費を招く。', 'モデル修正時の更新仕組みを用意しない。'],
    memoryTipVi: 'Mẹo nhớ: On-device = AI ở trong máy của bạn, nhanh và riêng tư hơn nhưng bị giới hạn tài nguyên.',
    memoryTipJa: '覚え方：オンデバイス = AIが端末内にいる。速くてプライバシーに有利だが資源制約あり。',
  },
  {
    nodeId: 'ai-energy-consumption',
    shortDefinitionVi: 'Điện năng AI là lượng năng lượng tiêu thụ khi huấn luyện, triển khai và vận hành mô hình AI, đặc biệt với GPU, data center và mô hình lớn.',
    shortDefinitionJa: 'AIの電力消費は、モデル学習・導入・運用で使われるエネルギー量です。特にGPU、データセンター、大規模モデルで問題になります。',
    whyImportantVi: 'AI Passport bắt đầu nhấn mạnh AI bền vững. Khi dùng AI, doanh nghiệp không chỉ tính accuracy mà còn tính chi phí điện, carbon và hiệu quả tài nguyên.',
    whyImportantJa: 'AIパスポートでは持続可能なAIも重視されます。精度だけでなく、電力コスト、CO2、資源効率も考えます。',
    examPatternsVi: ['Hỏi vì sao mô hình lớn tiêu thụ nhiều điện hơn.', 'Chọn biện pháp giảm tiêu thụ: model nhỏ hơn, tối ưu inference, batch, dùng khi cần.', 'So sánh cloud/data center/edge theo năng lượng và mục đích.'],
    examPatternsJa: ['大規模モデルが多くの電力を使う理由。', '削減策：小型モデル、推論最適化、バッチ処理、必要時のみ利用。', 'クラウド、データセンター、エッジの電力面比較。'],
    commonMistakesVi: ['Chỉ chọn model lớn nhất mà không xem nhiệm vụ có cần không.', 'Quên inference lặp lại hàng ngày cũng tốn điện, không chỉ training.', 'Không theo dõi chi phí GPU/cloud khi mở rộng dịch vụ.'],
    commonMistakesJa: ['必要性を見ずに最大モデルを選ぶ。', '学習だけでなく日々の推論も電力を使うことを忘れる。', 'サービス拡大時のGPU/クラウド費用を監視しない。'],
    memoryTipVi: 'Mẹo nhớ: AI càng lớn, chạy càng nhiều → điện càng tăng. Chọn đủ dùng là lựa chọn thông minh.',
    memoryTipJa: '覚え方：AIが大きく、利用回数が多いほど電力増。必要十分なモデルを選ぶ。',
  },
  {
    nodeId: 'ai-environmental-impact',
    shortDefinitionVi: 'Tác động môi trường của AI là ảnh hưởng từ điện năng, phát thải CO2, làm mát data center, phần cứng GPU và vòng đời thiết bị.',
    shortDefinitionJa: 'AIの環境影響は、電力使用、CO2排出、データセンター冷却、GPUなどハードウェア、機器ライフサイクルによる影響です。',
    whyImportantVi: 'Đề có thể hỏi sustainable AI hoặc green AI. Ý chính: AI tạo giá trị nhưng cần cân bằng giữa lợi ích, chi phí tài nguyên và tác động xã hội.',
    whyImportantJa: 'サステナブルAIやグリーンAIとして問われます。AIの価値と資源コスト・社会影響のバランスが重要です。',
    examPatternsVi: ['Chọn giải pháp giảm tác động: dùng model nhỏ, tái sử dụng model, tối ưu compute, chọn data center hiệu quả.', 'Hỏi carbon footprint của training/inference.', 'Liên hệ governance: đo lường, báo cáo, đặt tiêu chí bền vững.'],
    examPatternsJa: ['影響削減策：小型モデル、既存モデル再利用、計算最適化、効率的データセンター。', '学習・推論のカーボンフットプリント。', 'ガバナンス：測定、報告、持続可能性基準。'],
    commonMistakesVi: ['Nghĩ “AI là phần mềm” nên không có tác động môi trường.', 'Tối ưu accuracy rất nhỏ nhưng tăng compute rất lớn.', 'Không cân nhắc tái sử dụng mô hình hoặc chọn model nhỏ hơn.'],
    commonMistakesJa: ['AIはソフトウェアだから環境影響がないと思う。', 'わずかな精度向上のため計算量を大きく増やす。', 'モデル再利用や小型モデル選択を検討しない。'],
    memoryTipVi: 'Mẹo nhớ: Green AI = đạt mục tiêu bằng ít tài nguyên hơn, không phải cứ model lớn nhất.',
    memoryTipJa: '覚え方：グリーンAI = 目的を少ない資源で達成する。最大モデルが常に正解ではない。',
  },
  {
    nodeId: 'license-ai',
    shortDefinitionVi: 'Kiểm tra license là xác nhận quyền sử dụng dữ liệu, mã nguồn, model, ảnh, văn bản hoặc thư viện trước khi dùng trong sản phẩm AI.',
    shortDefinitionJa: 'ライセンス確認は、データ、コード、モデル、画像、文章、ライブラリをAI製品で利用する前に、利用条件を確認することです。',
    whyImportantVi: 'AI thường dùng nhiều nguồn bên ngoài. Nếu không kiểm tra license, doanh nghiệp có thể vi phạm bản quyền, điều khoản thương mại, nghĩa vụ ghi nguồn hoặc cấm tái phân phối.',
    whyImportantJa: 'AIでは外部資源を多く使います。ライセンス未確認だと著作権、商用利用条件、表示義務、再配布禁止に違反する可能性があります。',
    examPatternsVi: ['Hỏi có được dùng dữ liệu/mã nguồn/model open source cho mục đích thương mại không.', 'Chọn hành động đúng: kiểm tra license, điều khoản, nguồn gốc dữ liệu và nghĩa vụ ghi nhận.', 'Phân biệt miễn phí tải về với miễn phí dùng cho mọi mục đích.'],
    examPatternsJa: ['データ・コード・オープンソースモデルを商用利用できるか確認する問題。', '正しい対応：ライセンス、利用規約、データ由来、表示義務を確認。', '無料で入手できることと、自由に商用利用できることの違い。'],
    commonMistakesVi: ['Nghĩ “public trên internet” nghĩa là được dùng để train/bán sản phẩm.', 'Không lưu bằng chứng nguồn gốc và version license.', 'Dùng thư viện open source nhưng không tuân thủ nghĩa vụ notice/source disclosure nếu có.'],
    commonMistakesJa: ['インターネット公開 = 学習や商用利用が自由だと思う。', '入手元やライセンス版の証跡を残さない。', 'OSS利用時の表示義務やソース開示義務を確認しない。'],
    memoryTipVi: 'Mẹo nhớ: Trước khi dùng tài nguyên AI, hỏi 4 câu: nguồn ở đâu, license gì, dùng thương mại được không, có phải ghi nguồn không?',
    memoryTipJa: '覚え方：AI素材を使う前に、出所・ライセンス・商用可否・表示義務を確認する。',
  }
];
