import type { QuizQuestion } from '../../features/knowledge-graph/data/quizQuestions';

const q = (item: QuizQuestion) => item;

export const aiPassportQuizQuestions: QuizQuestion[] = [
  q({ id: 'aiq-relationship', domain: 'ai', nodeId: 'machine-learning-ai', difficulty: 'basic', questionVi: 'Quan hệ đúng giữa AI, Machine Learning và Deep Learning là gì?', questionJa: 'AI、機械学習、深層学習の関係として正しいものはどれですか。', options: ['AI ⊃ Machine Learning ⊃ Deep Learning', 'Deep Learning ⊃ AI ⊃ Machine Learning', 'Machine Learning không liên quan AI', 'AI chỉ là database'], answerIndex: 0, explanationVi: 'AI là khái niệm lớn; ML là một phần của AI; Deep Learning là một phần của ML.', explanationJa: 'AIの中に機械学習があり、機械学習の中に深層学習があります。' }),
  q({ id: 'aiq-supervised', domain: 'ai', nodeId: 'supervised-ai', difficulty: 'standard', questionVi: '教師あり学習 dùng loại dữ liệu nào?', questionJa: '教師あり学習で使うデータとして適切なものはどれですか。', options: ['Dữ liệu có nhãn/đáp án đúng', 'Dữ liệu hoàn toàn không có nhãn', 'Chỉ dữ liệu âm thanh', 'Không cần dữ liệu'], answerIndex: 0, explanationVi: 'Supervised learning học từ dữ liệu có label đúng.', explanationJa: '教師あり学習は正解ラベル付きデータを使います。' }),
  q({ id: 'aiq-unsupervised', domain: 'ai', nodeId: 'unsupervised-ai', difficulty: 'standard', questionVi: 'Ví dụ tiêu biểu của 教師なし学習 là gì?', questionJa: '教師なし学習の代表例として適切なものはどれですか。', options: ['Clustering', 'Login bằng MFA', 'DNS lookup', 'SQL SELECT'], answerIndex: 0, explanationVi: 'Unsupervised learning thường tìm nhóm/cấu trúc ẩn, ví dụ clustering.', explanationJa: '教師なし学習はラベルなしデータからグループを見つけるクラスタリングが代表例です。' }),
  q({ id: 'aiq-linear-logistic', domain: 'ai', nodeId: 'linear-regression-ai', difficulty: 'hard', questionVi: '線形回帰 và ロジスティック回帰 khác nhau thế nào?', questionJa: '線形回帰とロジスティック回帰の違いとして正しいものはどれですか。', options: ['線形回帰は数値予測、ロジスティック回帰は分類に使われることが多い', 'Cả hai chỉ dùng cho ảnh', '線形回帰 dùng cho phân loại, logistic dùng cho DNS', 'Không khác nhau'], answerIndex: 0, explanationVi: 'Linear regression dự đoán số liên tục; logistic regression thường dùng cho classification/xác suất.', explanationJa: '線形回帰は連続値予測、ロジスティック回帰は分類で使われることが多いです。' }),
  q({ id: 'aiq-overfit', domain: 'ai', nodeId: 'overfitting-ai', difficulty: 'hard', questionVi: '過学習 là gì?', questionJa: '過学習の説明として正しいものはどれですか。', options: ['Model khớp quá sát dữ liệu học và kém với dữ liệu mới', 'Model không học gì cả', 'Dữ liệu được mã hóa', 'Tăng tốc mạng'], answerIndex: 0, explanationVi: 'Overfitting làm model mất khả năng tổng quát hóa.', explanationJa: '過学習では学習データに適合しすぎ、未知データへの性能が低下します。' }),
  q({ id: 'aiq-test-train', domain: 'ai', nodeId: 'training-test-data', difficulty: 'hard', questionVi: 'Điều nào cần tránh khi đánh giá ML?', questionJa: '機械学習の評価で避けるべきことはどれですか。', options: ['Dùng test data để training', 'Chia dữ liệu train/test', 'Tiền xử lý dữ liệu', 'Đánh giá bằng chỉ số phù hợp'], answerIndex: 0, explanationVi: 'Test data phải dùng để đánh giá, không dùng để train.', explanationJa: 'テストデータを学習に使うと正しく評価できません。' }),
  q({ id: 'aiq-preprocess', domain: 'ai', nodeId: 'data-preprocessing-ai', difficulty: 'standard', questionVi: '前処理 gồm việc nào?', questionJa: '前処理に含まれる作業として適切なものはどれですか。', options: ['Xử lý dữ liệu thiếu và chuẩn hóa dữ liệu', 'Tắt màn hình', 'Đăng ký tên miền', 'Tạo mật khẩu Wi-Fi'], answerIndex: 0, explanationVi: 'Preprocessing gồm xử lý missing values, normalization, outlier, encoding.', explanationJa: '前処理には欠損値処理、正規化、外れ値対応などがあります。' }),
  q({ id: 'aiq-llm', domain: 'ai', nodeId: 'llm', difficulty: 'standard', questionVi: 'LLM chủ yếu xử lý loại dữ liệu nào?', questionJa: 'LLMが主に扱うデータとして適切なものはどれですか。', options: ['Ngôn ngữ tự nhiên / văn bản', 'Chỉ bảng SQL', 'Chỉ địa chỉ IP', 'Chỉ tín hiệu điện'], answerIndex: 0, explanationVi: 'LLM là Large Language Model, học và tạo ngôn ngữ tự nhiên.', explanationJa: 'LLMは大規模言語モデルで、自然言語を扱います。' }),
  q({ id: 'aiq-prompt', domain: 'ai', nodeId: 'prompt-engineering', difficulty: 'standard', questionVi: 'Prompt tốt nên có gì?', questionJa: '良いプロンプトに含めるべき要素として適切なものはどれですか。', options: ['Mục tiêu, bối cảnh, điều kiện, format output', 'Chỉ một từ bất kỳ', 'API key bí mật', 'Mật khẩu cá nhân'], answerIndex: 0, explanationVi: 'Prompt rõ giúp AI hiểu nhiệm vụ và trả lời đúng format.', explanationJa: '目的、文脈、条件、出力形式を明確にすると良い出力を得やすいです。' }),
  q({ id: 'aiq-hallucination', domain: 'ai', nodeId: 'hallucination', difficulty: 'hard', questionVi: 'Biện pháp phù hợp với hallucination là gì?', questionJa: 'ハルシネーションへの対策として適切なものはどれですか。', options: ['Kiểm chứng nguồn và human review', 'Tin toàn bộ output AI', 'Xóa toàn bộ dữ liệu', 'Tắt DNS'], answerIndex: 0, explanationVi: 'AI output cần được kiểm tra, đặc biệt khi dùng cho công việc quan trọng.', explanationJa: 'AI出力は重要な場面では出典確認や人間の確認が必要です。' }),
  q({ id: 'aiq-deepfake', domain: 'ai', nodeId: 'deepfake-ai', difficulty: 'standard', questionVi: 'Deepfake gây rủi ro chính nào?', questionJa: 'ディープフェイクのリスクとして適切なものはどれですか。', options: ['Giả mạo video/âm thanh gây lừa đảo hoặc tin giả', 'Tăng tốc CPU', 'Tạo khóa chính database', 'Cấp IP tự động'], answerIndex: 0, explanationVi: 'Deepfake có thể tạo nội dung giả giống thật.', explanationJa: 'ディープフェイクは本物のような偽動画・音声を作れます。' }),
  q({ id: 'aiq-privacy', domain: 'security', nodeId: 'personal-information-ai', difficulty: 'hard', questionVi: 'Khi dùng generative AI công cộng, điều nào cần tránh?', questionJa: '公開型の生成AIを使うとき避けるべきことはどれですか。', options: ['Nhập thông tin cá nhân hoặc bí mật công ty khi chưa được phép', 'Viết prompt rõ ràng', 'Kiểm tra kết quả', 'Hỏi định nghĩa thuật ngữ công khai'], answerIndex: 0, explanationVi: 'Thông tin cá nhân/bí mật có thể bị rò rỉ hoặc dùng không đúng mục đích.', explanationJa: '個人情報や機密情報の入力は漏えいリスクがあるため注意が必要です。' }),
  q({ id: 'aiq-bias', domain: 'security', nodeId: 'bias-fairness', difficulty: 'hard', questionVi: 'AI bias nghĩa là gì?', questionJa: 'AIのバイアスとして正しい説明はどれですか。', options: ['Dữ liệu hoặc mô hình thiên lệch gây kết quả không công bằng', 'AI luôn chạy nhanh hơn', 'Mã hóa dữ liệu bằng public key', 'Tự động backup'], answerIndex: 0, explanationVi: 'Bias có thể dẫn tới phân biệt đối xử hoặc kết quả sai cho một nhóm.', explanationJa: 'バイアスは不公平な結果や差別につながる可能性があります。' }),
  q({ id: 'aiq-xai', domain: 'security', nodeId: 'explainable-ai', difficulty: 'standard', questionVi: '説明可能AI quan trọng vì sao?', questionJa: '説明可能AIが重要な理由として適切なものはどれですか。', options: ['Giúp hiểu lý do AI đưa ra kết quả và tăng trách nhiệm giải trình', 'Giúp xóa hết dữ liệu', 'Luôn làm model chính xác 100%', 'Thay thế toàn bộ con người'], answerIndex: 0, explanationVi: 'Explainability giúp kiểm tra, tin cậy và chịu trách nhiệm trong quyết định AI.', explanationJa: '判断理由を説明できると、信頼性や説明責任を高められます。' }),
  q({ id: 'aiq-business-flow', domain: 'strategy', nodeId: 'ai-project-flow', difficulty: 'hard', questionVi: 'Bước đầu tiên nên làm trong dự án AI là gì?', questionJa: 'AIプロジェクトで最初に行うべきことはどれですか。', options: ['Xác định vấn đề/mục tiêu kinh doanh', 'Chọn model phức tạp nhất', 'Deploy ngay lên production', 'Xóa dữ liệu cũ'], answerIndex: 0, explanationVi: 'Dự án AI phải bắt đầu từ vấn đề và mục tiêu, sau đó mới xét dữ liệu/model.', explanationJa: 'AIプロジェクトは課題・目的の明確化から始めます。' }),
  q({ id: 'aiq-roi', domain: 'strategy', nodeId: 'roi-ai', difficulty: 'standard', questionVi: 'Vì sao cần xét 費用対効果 khi dùng AI?', questionJa: 'AI活用で費用対効果を考える理由として適切なものはどれですか。', options: ['AI không phải lúc nào cũng tạo giá trị lớn hơn chi phí và rủi ro', 'AI luôn miễn phí', 'AI chỉ dùng cho game', 'AI không cần dữ liệu'], answerIndex: 0, explanationVi: 'Cần so sánh chi phí triển khai/vận hành với hiệu quả thực tế.', explanationJa: '導入・運用コストに対して効果があるか確認する必要があります。' }),
];
