import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';

export const aiPassportV52MlLessons: LessonContent[] = [
  {
    nodeId: 'classification-ai',
    shortDefinitionVi: 'Classification là bài toán cho AI chọn một nhãn rời rạc cho dữ liệu, ví dụ email là spam/không spam, ảnh là chó/mèo, khách hàng thuộc nhóm rủi ro cao/thấp.',
    shortDefinitionJa: '分類は、データに対して離散的なラベルを選ぶ機械学習タスクです。例：迷惑メール/通常メール、犬/猫、高リスク/低リスク。',
    whyImportantVi: 'AI Passport hay hỏi phân biệt classification với regression. Chỉ cần nhớ: nếu đáp án là “loại/nhóm/nhãn” thì thường là classification; nếu đáp án là con số liên tục thì là regression.',
    whyImportantJa: 'AIパスポートでは分類と回帰の区別が頻出です。答えがカテゴリ・クラス・ラベルなら分類、連続的な数値なら回帰と考えます。',
    examPatternsVi: ['Nhận diện use case: phân loại ảnh, phát hiện spam, dự đoán khách hàng rời bỏ có/không.', 'Chọn mô hình/metric phù hợp cho nhãn rời rạc như accuracy, precision, recall, confusion matrix.', 'Phân biệt binary classification, multi-class classification và multi-label classification.'],
    examPatternsJa: ['画像分類、迷惑メール判定、解約する/しないなどのユースケース識別。', '正解率、適合率、再現率、混同行列など分類向け指標の選択。', '二値分類、多クラス分類、マルチラベル分類の違い。'],
    commonMistakesVi: ['Nhầm classification với regression khi đề có chữ “dự đoán”. Phải xem dự đoán ra nhãn hay số.', 'Chỉ nhìn accuracy mà bỏ qua dữ liệu mất cân bằng, ví dụ 99% không gian lận.', 'Nghĩ classification luôn chỉ có 2 lớp; thực tế có thể có nhiều lớp.'],
    commonMistakesJa: ['「予測」という言葉だけで回帰だと思う。出力がラベルか数値かを確認する。', '不均衡データで正解率だけを見る。例：ほとんどが不正でないデータ。', '分類は必ず2種類だけだと思う。多クラス分類もある。'],
    memoryTipVi: 'Mẹo nhớ: Classification = chọn “hộp/nhãn”. Spam hay không spam là chọn hộp, nên là classification.',
    memoryTipJa: '覚え方：分類 = ラベルの箱を選ぶ。迷惑メールか通常メールかは箱選びなので分類。',
  },
  {
    nodeId: 'regression-ai',
    shortDefinitionVi: 'Regression là bài toán AI dự đoán giá trị số liên tục, ví dụ doanh thu tháng sau, giá nhà, nhiệt độ, thời gian giao hàng hoặc lượng điện tiêu thụ.',
    shortDefinitionJa: '回帰は、売上、住宅価格、気温、配送時間、電力使用量のような連続値を予測する機械学習タスクです。',
    whyImportantVi: 'Đề thi thường đặt tình huống “dự đoán”. Người mới dễ nhầm vì classification cũng là dự đoán. Điểm quyết định là output: số liên tục thì regression.',
    whyImportantJa: '試験では「予測」という表現がよく出ます。分類も予測なので、出力が連続値かラベルかを見分けることが重要です。',
    examPatternsVi: ['Dự đoán số: doanh số, giá, nhu cầu, thời gian, nhiệt độ.', 'Chọn metric như MAE, MSE, RMSE thay vì accuracy.', 'Phân biệt linear regression với logistic regression: logistic thường dùng cho classification.'],
    examPatternsJa: ['売上、価格、需要、時間、温度などの数値予測。', '正解率ではなくMAE、MSE、RMSEなどの指標を選ぶ。', '線形回帰とロジスティック回帰の違い。ロジスティック回帰は分類で使われることが多い。'],
    commonMistakesVi: ['Thấy chữ regression trong logistic regression rồi nghĩ đó là regression số liên tục.', 'Dùng accuracy để đánh giá bài toán dự đoán giá tiền.', 'Quên kiểm tra đơn vị và phạm vi của số dự đoán.'],
    commonMistakesJa: ['ロジスティック回帰に「回帰」とあるので連続値予測だと思う。', '価格予測に正解率を使おうとする。', '予測値の単位や範囲の確認を忘れる。'],
    memoryTipVi: 'Mẹo nhớ: Regression = trả lời bằng “bao nhiêu?”. Bao nhiêu tiền, bao nhiêu ngày, bao nhiêu kWh.',
    memoryTipJa: '覚え方：回帰 = 「いくら・どれくらい」を答える。価格、日数、電力量など。',
  },
  {
    nodeId: 'supervised-ai',
    shortDefinitionVi: 'Học có giám sát là cách huấn luyện mô hình bằng dữ liệu đã có đáp án đúng, gọi là label. Ví dụ ảnh đã ghi “mèo”, giao dịch đã ghi “gian lận/không gian lận”.',
    shortDefinitionJa: '教師あり学習は、正解ラベル付きデータを使ってモデルを学習させる方法です。例：猫とラベル付けされた画像、不正/通常と付けられた取引。',
    whyImportantVi: 'Đây là nền tảng để hiểu classification và regression. AI Passport hay hỏi dữ liệu nào phù hợp với học có giám sát và vì sao cần train/test split.',
    whyImportantJa: '分類・回帰を理解する基礎です。AIパスポートでは、教師あり学習に適したデータや訓練/テスト分割がよく問われます。',
    examPatternsVi: ['Chọn supervised learning khi có dữ liệu đầu vào và đáp án mẫu.', 'Phân biệt classification/regression đều có thể thuộc supervised learning.', 'Hỏi vì sao không dùng test data để học: để đánh giá khách quan.'],
    examPatternsJa: ['入力データと正解ラベルがある場合に教師あり学習を選ぶ。', '分類も回帰も教師あり学習に含まれる場合がある。', 'テストデータを学習に使わない理由：客観的評価のため。'],
    commonMistakesVi: ['Nghĩ “giám sát” là con người ngồi theo dõi từng lần AI chạy; thực ra là có label khi học.', 'Nhầm dữ liệu chưa có nhãn với supervised learning.', 'Trộn train data và test data làm kết quả đánh giá quá đẹp nhưng không thật.'],
    commonMistakesJa: ['「教師あり」を人間が毎回監視することだと思う。実際は学習時に正解ラベルがあること。', 'ラベルなしデータを教師あり学習だと思う。', '訓練データとテストデータを混ぜて評価を甘くしてしまう。'],
    memoryTipVi: 'Mẹo nhớ: Supervised = học bằng “bài mẫu có đáp án”. Có đáp án thì mới so sánh và sửa sai được.',
    memoryTipJa: '覚え方：教師あり = 解答付き問題集で学ぶ。答えがあるから誤差を直せる。',
  },
  {
    nodeId: 'unsupervised-ai',
    shortDefinitionVi: 'Học không giám sát là cách cho mô hình tìm cấu trúc trong dữ liệu chưa có label, ví dụ gom nhóm khách hàng giống nhau hoặc tìm chủ đề trong văn bản.',
    shortDefinitionJa: '教師なし学習は、正解ラベルのないデータから構造やパターンを見つける方法です。例：顧客クラスタリング、文書トピック抽出。',
    whyImportantVi: 'AI Passport thường hỏi clustering, giảm chiều và khám phá dữ liệu. Người mới cần nhớ: không có đáp án đúng sẵn, mô hình tự tìm nhóm/quy luật.',
    whyImportantJa: 'クラスタリング、次元削減、データ探索がよく問われます。正解ラベルがなく、モデルが構造を見つける点が重要です。',
    examPatternsVi: ['Clustering khách hàng để phân nhóm marketing.', 'Giảm chiều dữ liệu để dễ trực quan hóa hoặc xử lý.', 'Phân biệt với supervised learning: không có label đúng/sai rõ ràng.'],
    examPatternsJa: ['マーケティングで顧客をクラスタに分ける。', '次元削減で可視化や処理をしやすくする。', '教師あり学習との違い：明確な正解ラベルがない。'],
    commonMistakesVi: ['Nghĩ unsupervised nghĩa là không cần con người đánh giá kết quả.', 'Gọi mọi bài toán phân nhóm là classification; nếu chưa có nhãn sẵn thì thường là clustering.', 'Tin rằng nhóm AI tạo ra luôn có ý nghĩa kinh doanh, trong khi cần kiểm tra lại.'],
    commonMistakesJa: ['教師なしなら人間の確認が不要だと思う。', 'グループ分けをすべて分類と呼ぶ。ラベルがなければクラスタリングの可能性が高い。', 'AIが作ったクラスタに必ず業務意味があると思う。確認が必要。'],
    memoryTipVi: 'Mẹo nhớ: Unsupervised = không có đáp án mẫu, AI tự “gom cụm” hoặc tìm hình dạng dữ liệu.',
    memoryTipJa: '覚え方：教師なし = 解答なしで、AIがまとまりや構造を探す。',
  },
  {
    nodeId: 'underfitting-ai',
    shortDefinitionVi: 'Underfitting là khi mô hình học quá đơn giản nên không nắm được quy luật dữ liệu. Kết quả thường kém cả trên training data và test data.',
    shortDefinitionJa: '学習不足は、モデルが単純すぎてデータの規則を十分に学べていない状態です。訓練データでもテストデータでも性能が低くなりやすいです。',
    whyImportantVi: 'Đề thi hay hỏi so sánh underfitting với overfitting. Underfitting là “chưa học đủ”; overfitting là “học vẹt training data”.',
    whyImportantJa: '過学習との比較が頻出です。学習不足は「十分に学べていない」、過学習は「訓練データに合わせすぎ」です。',
    examPatternsVi: ['Nhận diện dấu hiệu: train score thấp và test score thấp.', 'Chọn biện pháp: mô hình phức tạp hơn, thêm feature, học lâu hơn, giảm regularization quá mạnh.', 'Phân biệt với overfitting: overfitting train cao nhưng test thấp.'],
    examPatternsJa: ['兆候：訓練性能もテスト性能も低い。', '対策：モデルを複雑にする、特徴量を追加する、学習量を増やす、強すぎる正則化を弱める。', '過学習との違い：過学習は訓練性能が高くテスト性能が低い。'],
    commonMistakesVi: ['Thấy test thấp là kết luận overfitting ngay, nhưng cần xem train score.', 'Tăng regularization khi mô hình đã underfit làm tình hình xấu hơn.', 'Không kiểm tra chất lượng feature và dữ liệu đầu vào.'],
    commonMistakesJa: ['テスト性能が低いだけで過学習と決めつける。訓練性能も見る。', '学習不足なのに正則化を強めて悪化させる。', '特徴量や入力データ品質を確認しない。'],
    memoryTipVi: 'Mẹo nhớ: Underfitting = học chưa tới. Cả bài tập quen và bài mới đều làm sai.',
    memoryTipJa: '覚え方：学習不足 = まだ理解していない。練習問題も本番問題もできない。',
  },
  {
    nodeId: 'cnn-ai',
    shortDefinitionVi: 'CNN là mạng nơ-ron tích chập thường dùng cho ảnh. Nó học các đặc trưng như cạnh, hình dạng, hoa văn rồi ghép lại để nhận diện đối tượng.',
    shortDefinitionJa: 'CNNは画像処理でよく使われる畳み込みニューラルネットワークです。エッジ、形、模様などの特徴を段階的に学習します。',
    whyImportantVi: 'AI Passport không bắt bạn tính toán CNN sâu, nhưng cần biết CNN phù hợp với image recognition, defect detection, OCR và computer vision.',
    whyImportantJa: 'AIパスポートでは詳細計算より、CNNが画像認識、外観検査、OCR、コンピュータビジョンに向くことを理解します。',
    examPatternsVi: ['Chọn CNN cho bài toán ảnh: nhận diện vật thể, phân loại ảnh, phát hiện lỗi sản phẩm.', 'Phân biệt CNN với RNN/Transformer ở mức ứng dụng cơ bản.', 'Hiểu convolution giúp trích xuất đặc trưng cục bộ trong ảnh.'],
    examPatternsJa: ['物体認識、画像分類、製品欠陥検出など画像タスクでCNNを選ぶ。', 'RNNやTransformerとの基本的な用途の違い。', '畳み込みが画像の局所特徴を抽出すること。'],
    commonMistakesVi: ['Nghĩ CNN chỉ dùng cho camera an ninh; thực tế dùng rộng trong y tế, sản xuất, OCR.', 'Nhầm CNN với generative AI tạo ảnh.', 'Không phân biệt dữ liệu ảnh với dữ liệu chuỗi thời gian/ngôn ngữ.'],
    commonMistakesJa: ['CNNは監視カメラだけと思う。医療、製造、OCRでも使う。', 'CNNを画像生成AIそのものと混同する。', '画像データと時系列・言語データの違いを見ない。'],
    memoryTipVi: 'Mẹo nhớ: CNN = nhìn ảnh bằng nhiều “kính lọc” để bắt cạnh, góc, hình.',
    memoryTipJa: '覚え方：CNN = 複数のフィルタで画像の線・角・形を見る。',
  },
  {
    nodeId: 'computer-vision-ai',
    shortDefinitionVi: 'Computer Vision là lĩnh vực giúp máy tính hiểu hình ảnh hoặc video, ví dụ nhận diện khuôn mặt, kiểm tra lỗi sản phẩm, đọc biển số, phân tích ảnh y tế.',
    shortDefinitionJa: 'コンピュータビジョンは、画像や動画をコンピュータに理解させる分野です。顔認識、外観検査、ナンバー認識、医療画像分析など。',
    whyImportantVi: 'Đề AI Passport hay đưa use case doanh nghiệp. Bạn cần biết Computer Vision không chỉ là “xem ảnh”, mà gồm nhận diện, phát hiện, phân đoạn và OCR.',
    whyImportantJa: 'AIパスポートでは業務ユースケースで問われます。画像を見るだけでなく、認識、検出、セグメンテーション、OCRなどを含みます。',
    examPatternsVi: ['Chọn computer vision cho kiểm tra ngoại quan trong nhà máy.', 'Phân biệt image classification, object detection, segmentation, OCR.', 'Nhận diện rủi ro: quyền riêng tư, bias khuôn mặt, chất lượng camera/ánh sáng.'],
    examPatternsJa: ['工場の外観検査でコンピュータビジョンを選ぶ。', '画像分類、物体検出、セグメンテーション、OCRの違い。', 'プライバシー、顔認識バイアス、カメラ・照明品質のリスク。'],
    commonMistakesVi: ['Gọi mọi bài toán ảnh là OCR; OCR chỉ là đọc chữ trong ảnh.', 'Quên điều kiện ánh sáng/góc chụp ảnh hưởng chất lượng.', 'Bỏ qua privacy khi xử lý mặt người hoặc camera nơi công cộng.'],
    commonMistakesJa: ['画像処理をすべてOCRと呼ぶ。OCRは画像中の文字認識。', '照明や撮影角度が精度に影響することを忘れる。', '顔画像や公共カメラでのプライバシーを無視する。'],
    memoryTipVi: 'Mẹo nhớ: Computer Vision = AI cho “mắt”: nhìn, tìm, tách vùng, đọc chữ.',
    memoryTipJa: '覚え方：コンピュータビジョン = AIの目。見る、探す、領域を分ける、文字を読む。',
  },
  {
    nodeId: 'ocr-ai',
    shortDefinitionVi: 'OCR là công nghệ nhận dạng chữ trong ảnh hoặc tài liệu scan, biến chữ trên giấy/hình thành dữ liệu số có thể tìm kiếm và xử lý.',
    shortDefinitionJa: 'OCRは、画像やスキャン文書内の文字を認識し、検索・処理できるデジタルテキストに変換する技術です。',
    whyImportantVi: 'OCR rất hay gặp trong nghiệp vụ: nhập hóa đơn, đọc giấy tờ, số hóa form. Đề thường hỏi lợi ích, giới hạn và bước kiểm tra sau OCR.',
    whyImportantJa: '請求書入力、書類読み取り、フォーム電子化など業務でよく使われます。利点、限界、確認工程が問われます。',
    examPatternsVi: ['Chọn OCR để đọc văn bản từ ảnh/scan/PDF ảnh.', 'Kết hợp OCR với RPA để tự động nhập liệu.', 'Hỏi biện pháp nâng độ chính xác: ảnh rõ, layout ổn định, kiểm tra con người với trường quan trọng.'],
    examPatternsJa: ['画像・スキャン・画像PDFから文字を読む用途でOCRを選ぶ。', 'OCRとRPAを組み合わせて入力作業を自動化する。', '精度向上策：鮮明な画像、安定したレイアウト、重要項目の人手確認。'],
    commonMistakesVi: ['Nhầm OCR với NLP: OCR đọc chữ từ ảnh, NLP hiểu/ngôn ngữ sau khi đã có text.', 'Tin OCR đúng 100%, không cần kiểm tra hóa đơn hoặc giấy tờ quan trọng.', 'Quên dữ liệu cá nhân trong giấy tờ cần quản lý an toàn.'],
    commonMistakesJa: ['OCRとNLPを混同する。OCRは画像から文字化、NLPはテキスト理解。', 'OCRは100%正しいと思い重要書類を確認しない。', '書類中の個人情報管理を忘れる。'],
    memoryTipVi: 'Mẹo nhớ: OCR = Optical Character Recognition = nhìn ảnh rồi gõ lại chữ thành text.',
    memoryTipJa: '覚え方：OCR = 画像を見て文字をテキスト化する技術。',
  },
  {
    nodeId: 'semantic-search-ai',
    shortDefinitionVi: 'Tìm kiếm ngữ nghĩa là tìm theo ý nghĩa của câu hỏi, không chỉ khớp từ khóa. Ví dụ hỏi “cách giảm chi phí điện” vẫn tìm tài liệu nói về “tiết kiệm năng lượng”.',
    shortDefinitionJa: 'セマンティック検索は、単なるキーワード一致ではなく意味の近さで検索する方法です。「電気代を下げる」と「省エネ」を結び付けられます。',
    whyImportantVi: 'Generative AI/RAG thường dùng semantic search để lấy tài liệu liên quan trước khi trả lời. Đây là điểm quan trọng trong câu hỏi về chatbot doanh nghiệp.',
    whyImportantJa: '生成AIやRAGでは、回答前に関連文書を探すためセマンティック検索が使われます。企業チャットボットの文脈で重要です。',
    examPatternsVi: ['Phân biệt keyword search và semantic search.', 'Hiểu embedding/vector database dùng để biểu diễn ý nghĩa gần nhau.', 'Chọn semantic search khi người dùng hỏi tự nhiên, từ ngữ không giống tài liệu gốc.'],
    examPatternsJa: ['キーワード検索とセマンティック検索の違い。', '埋め込み・ベクトルDBで意味の近さを扱うこと。', '利用者の自然文と文書の表現が違う場合に有効。'],
    commonMistakesVi: ['Nghĩ semantic search luôn đúng; thực tế vẫn có thể lấy nhầm tài liệu gần nghĩa.', 'Bỏ qua quyền truy cập tài liệu khi search trong nội bộ công ty.', 'Nhầm semantic search với LLM tự tạo kiến thức mới.'],
    commonMistakesJa: ['セマンティック検索は必ず正しいと思う。意味が近いだけで誤取得もある。', '社内検索で文書アクセス権を無視する。', 'セマンティック検索をLLMが新知識を作ることと混同する。'],
    memoryTipVi: 'Mẹo nhớ: Keyword search tìm “chữ giống”; semantic search tìm “ý giống”.',
    memoryTipJa: '覚え方：キーワード検索は文字の一致、セマンティック検索は意味の一致。',
  },
  {
    nodeId: 'few-shot-ai',
    shortDefinitionVi: 'Few-shot là cách đưa vài ví dụ mẫu trong prompt để AI hiểu format hoặc kiểu trả lời mong muốn, ví dụ cho 2 email mẫu rồi yêu cầu viết email thứ ba cùng phong cách.',
    shortDefinitionJa: 'Few-shotは、プロンプト内に少数の例を示して、AIに望ましい形式や回答パターンを理解させる方法です。',
    whyImportantVi: 'AI Passport hay hỏi prompt engineering ở mức ứng dụng. Few-shot giúp giảm mơ hồ, nhưng không thay thế kiểm chứng kết quả.',
    whyImportantJa: 'AIパスポートではプロンプト設計の実務活用が問われます。Few-shotは曖昧さを減らしますが、結果確認は必要です。',
    examPatternsVi: ['Chọn few-shot khi muốn AI bắt chước định dạng, giọng văn hoặc cách phân loại.', 'Phân biệt zero-shot, one-shot, few-shot.', 'Hỏi rủi ro: ví dụ sai hoặc lệch sẽ làm AI học theo hướng sai.'],
    examPatternsJa: ['形式、文体、分類基準をAIに示したい場合にfew-shotを選ぶ。', 'zero-shot、one-shot、few-shotの違い。', '誤った例や偏った例を示すと回答も偏るリスク。'],
    commonMistakesVi: ['Cho ví dụ quá dài hoặc mâu thuẫn khiến AI khó hiểu.', 'Đưa thông tin cá nhân/nhạy cảm vào prompt mẫu.', 'Tin few-shot đảm bảo đúng tuyệt đối.'],
    commonMistakesJa: ['長すぎる例や矛盾した例を入れてAIを混乱させる。', '例の中に個人情報や機密情報を入れる。', 'few-shotなら必ず正しいと思う。'],
    memoryTipVi: 'Mẹo nhớ: Few-shot = “làm theo mấy mẫu này”. Mẫu tốt thì câu trả lời dễ đúng format hơn.',
    memoryTipJa: '覚え方：Few-shot = 「この例のように答えて」。良い例ほど形式が安定する。',
  },
  {
    nodeId: 'data-preprocessing-ai',
    shortDefinitionVi: 'Tiền xử lý dữ liệu là bước làm sạch, chuẩn hóa và biến đổi dữ liệu trước khi huấn luyện AI, ví dụ xử lý thiếu dữ liệu, bỏ trùng, mã hóa category, scale số.',
    shortDefinitionJa: 'データ前処理は、AI学習前にデータを整える工程です。欠損処理、重複削除、カテゴリ変換、数値スケーリングなどを含みます。',
    whyImportantVi: 'Đây là phần người mới hay xem nhẹ nhưng đề rất hay hỏi. Mô hình tốt vẫn sai nếu dữ liệu bẩn, lệch hoặc không thống nhất định dạng.',
    whyImportantJa: '初心者が軽視しがちですが頻出です。モデルが良くても、汚い・偏った・形式不統一のデータでは性能が落ちます。',
    examPatternsVi: ['Chọn xử lý missing value, outlier, duplicate, format ngày tháng.', 'Hiểu train/test split phải làm cẩn thận để tránh data leakage.', 'Chọn encoding/scaling phù hợp trước khi đưa vào mô hình.'],
    examPatternsJa: ['欠損値、外れ値、重複、日付形式の処理。', 'データリーケージを避けるため訓練/テスト分割を適切に行う。', 'モデル入力前のエンコーディングやスケーリング。'],
    commonMistakesVi: ['Xử lý toàn bộ dataset trước khi chia train/test gây leakage.', 'Xóa mọi dòng thiếu dữ liệu mà không xem ảnh hưởng bias.', 'Nghĩ preprocessing chỉ là việc kỹ thuật, không liên quan nghiệp vụ.'],
    commonMistakesJa: ['train/test分割前に全データで処理してリーケージを起こす。', '欠損行をすべて削除し、偏りの影響を見ない。', '前処理を技術作業だけと考え、業務意味を確認しない。'],
    memoryTipVi: 'Mẹo nhớ: Preprocessing = rửa nguyên liệu trước khi nấu. Dữ liệu bẩn thì món AI khó ngon.',
    memoryTipJa: '覚え方：前処理 = 料理前に材料を洗って整える。データが汚いとAIも失敗する。',
  }
];
