import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';
import type { QuizQuestion } from '../../features/knowledge-graph/data/quizQuestions';
import type { AiPassportGlossaryTerm } from './aiPassportGlossary';

const deep = (nodeId: string, titleVi: string, titleJa: string, purposeVi: string, purposeJa: string, memoryVi: string, memoryJa: string): LessonContent => ({
  nodeId,
  shortDefinitionVi: `${titleVi}: ${purposeVi} Hãy học theo 3 lớp: định nghĩa đơn giản, ví dụ doanh nghiệp, và rủi ro/điểm kiểm soát. Trong đề AI Passport, câu hỏi thường kiểm tra khả năng chọn cách dùng AI phù hợp trong tình huống thực tế.`,
  shortDefinitionJa: `${titleJa}：${purposeJa} 定義、業務での利用例、リスクと対策の3点で整理します。AIパスポートでは実務場面で適切に判断できるかが問われます。`,
  whyImportantVi: `${titleVi} là node trọng tâm vì nó nối kiến thức kỹ thuật với cách dùng trong doanh nghiệp. Nếu hiểu node này, bạn sẽ đọc đề tình huống nhanh hơn: đề đang hỏi mục đích, rủi ro, dữ liệu, hay biện pháp quản trị.`,
  whyImportantJa: `${titleJa}は技術知識とビジネス利用をつなぐ重要ノードです。目的、リスク、データ、ガバナンスのどれを問うているか判断しやすくなります。`,
  examPatternsVi: [`Chọn mô tả đúng nhất về ${titleVi}.`, `Chọn ví dụ ứng dụng đúng trong doanh nghiệp.`, `Chọn rủi ro hoặc biện pháp kiểm soát phù hợp.`, `Phân biệt ${titleVi} với khái niệm gần giống.`],
  examPatternsJa: [`${titleJa}の説明として適切なものを選ぶ。`, `業務での利用例として正しいものを選ぶ。`, `リスクや対策として適切なものを選ぶ。`, `似た概念との違いを問う。`],
  commonMistakesVi: [`Chỉ nhớ tên ${titleVi} nhưng không nhớ ví dụ thực tế.`, `Không gắn ${titleVi} với rủi ro hoặc cách kiểm soát.`],
  commonMistakesJa: [`${titleJa}の名前だけ覚えて具体例を忘れる。`, `リスクや対策とセットで覚えない。`],
  memoryTipVi: memoryVi,
  memoryTipJa: memoryJa,
});

export const aiPassportV12DeepLessons: LessonContent[] = [
  deep('ai-definition', 'AI', '人工知能', 'AI là khái niệm lớn nhất: hệ thống thực hiện việc cần trí tuệ như nhận diện, dự đoán, tạo nội dung và hỗ trợ quyết định.', 'AIは認識・予測・生成・意思決定支援など知的処理を行う広い概念です。', 'AI = ô lớn nhất; ML/DL/GenAI nằm bên trong.', 'AIは一番大きな箱。機械学習・深層学習・生成AIはその中。'),
  deep('machine-learning-ai', 'Machine Learning', '機械学習', 'Machine Learning học quy luật từ dữ liệu thay vì viết luật thủ công.', '機械学習は人がルールをすべて書くのではなく、データから規則性を学びます。', 'Dữ liệu → học quy luật → dự đoán/phân loại.', 'データ → 学習 → 予測・分類。'),
  deep('deep-learning-ai', 'Deep Learning', '深層学習', 'Deep Learning là ML dùng neural network nhiều lớp, mạnh với ảnh, âm thanh, ngôn ngữ.', '深層学習は多層ニューラルネットワークを使う機械学習です。', 'AI ⊃ ML ⊃ DL.', 'AI ⊃ 機械学習 ⊃ 深層学習。'),
  deep('supervised-ai', 'Supervised Learning', '教師あり学習', 'Học từ dữ liệu có đáp án/label đúng để dự đoán nhãn hoặc giá trị.', '正解ラベル付きデータから分類や予測を学びます。', 'Có label = supervised.', '正解ラベルあり = 教師あり。'),
  deep('unsupervised-ai', 'Unsupervised Learning', '教師なし学習', 'Tìm nhóm, cấu trúc hoặc pattern trong dữ liệu không có label.', '正解ラベルのないデータから構造やグループを見つけます。', 'Không label = tìm nhóm/pattern.', 'ラベルなし = 構造を見つける。'),
  deep('regression-ai', 'Regression', '回帰', 'Dự đoán giá trị số liên tục như giá, doanh thu, nhiệt độ.', '価格や売上などの連続値を予測します。', 'Dự đoán số = regression.', '数値予測 = 回帰。'),
  deep('classification-ai', 'Classification', '分類', 'Chọn nhãn/loại cho dữ liệu như spam/không spam hoặc lỗi/không lỗi.', 'データにカテゴリやラベルを付ける予測です。', 'Dự đoán loại = classification.', 'カテゴリ予測 = 分類。'),
  deep('linear-regression-ai', 'Linear Regression', '線形回帰', 'Mô hình dự đoán số bằng quan hệ gần dạng đường thẳng.', '線形関係を使って連続値を予測する方法です。', 'Đường thẳng → số.', '直線 → 数値予測。'),
  deep('logistic-regression-ai', 'Logistic Regression', 'ロジスティック回帰', 'Tên có hồi quy nhưng thường dùng cho phân loại nhị phân bằng xác suất.', '名前は回帰ですが、二値分類でよく使われます。', 'Tên là regression, nhưng thi hay hỏi classification.', '名前は回帰、用途は分類。'),
  deep('decision-tree-ai', 'Decision Tree', '決定木', 'Mô hình ra quyết định bằng các nhánh câu hỏi, dễ hiểu nhưng dễ overfitting.', '条件分岐で判断するモデルで、理解しやすいが過学習しやすいです。', 'Cây quá sâu → học thuộc.', '木が深すぎる → 過学習。'),
  deep('svm-ai', 'SVM', 'サポートベクターマシン', 'Tìm đường ranh giới tốt để tách các nhóm dữ liệu.', 'クラスを分ける境界を見つける方法です。', 'SVM = boundary + margin.', 'SVM = 境界 + マージン。'),
  deep('neural-network-ai', 'Neural Network', 'ニューラルネットワーク', 'Mô hình gồm nhiều nút/lớp tính toán, nền tảng của deep learning.', '多くのノードと層で構成されるモデルで深層学習の基盤です。', 'Nhiều lớp → học pattern phức tạp.', '多層 → 複雑な特徴を学ぶ。'),
  deep('cnn-ai', 'CNN', '畳み込みニューラルネットワーク', 'Neural network mạnh trong xử lý ảnh nhờ học cạnh, hình dạng, texture.', '画像のエッジや形状などを学ぶため画像処理に強いです。', 'CNN = ảnh.', 'CNN = 画像。'),
  deep('rnn-ai', 'RNN', '再帰型ニューラルネットワーク', 'Mô hình xử lý dữ liệu theo chuỗi như văn bản, âm thanh, thời gian.', '文章・音声・時系列など順序データを扱います。', 'RNN = sequence.', 'RNN = 系列。'),
  deep('transformer-ai', 'Transformer', 'Transformer', 'Kiến trúc dùng attention, nền tảng của LLM hiện đại.', 'Attentionを使い、現代のLLMの基盤となる構造です。', 'Transformer = Attention + LLM.', 'Transformer = Attention + LLM。'),
  deep('llm', 'LLM', '大規模言語モデル', 'Mô hình học từ lượng lớn văn bản để tạo/hiểu ngôn ngữ, nhưng có thể sai.', '大量のテキストから学習し言語を扱いますが、誤る場合があります。', 'LLM tiện nhưng phải kiểm chứng.', 'LLMは便利だが検証が必要。'),
  deep('prompt-engineering', 'Prompt Engineering', 'プロンプトエンジニアリング', 'Thiết kế chỉ thị rõ ràng để AI trả lời đúng mục tiêu hơn.', '目的に合う出力を得るために指示を設計することです。', 'Mục tiêu + ngữ cảnh + ràng buộc + format.', '目的 + 文脈 + 制約 + 形式。'),
  deep('hallucination', 'Hallucination', 'ハルシネーション', 'AI tạo câu trả lời nghe hợp lý nhưng sai hoặc không có căn cứ.', 'もっともらしいが誤った情報を生成することです。', 'Nghe hay chưa chắc đúng.', 'もっともらしい = 正しいとは限らない。'),
  deep('rag', 'RAG', '検索拡張生成', 'Kết hợp tìm kiếm tài liệu với LLM để trả lời dựa trên nguồn.', '文書検索と生成を組み合わせて根拠に基づく回答を支援します。', 'RAG = tìm rồi trả lời.', 'RAG = 検索してから生成。'),
  deep('deepfake-ai', 'Deepfake', 'ディープフェイク', 'Nội dung giả bằng AI như ảnh, video, giọng nói giống thật.', 'AIで作られた本物のような偽画像・動画・音声です。', 'Giả nhưng giống thật = cần xác thực.', '本物らしい偽物 = 確認が必要。'),
  deep('data-preprocessing-ai', 'Preprocessing', '前処理', 'Làm sạch, chuẩn hóa và xử lý dữ liệu trước khi huấn luyện.', '学習前にデータを整える作業です。', 'Dữ liệu trước, model sau.', 'データが先、モデルは後。'),
  deep('training-test-data', 'Train/Test Data', '学習データ・テストデータ', 'Training dùng để học; test dùng để kiểm tra trên dữ liệu chưa thấy.', '学習データは学習用、テストデータは未知データでの評価用です。', 'Test data chỉ để kiểm tra.', 'テストデータは評価専用。'),
  deep('overfitting-ai', 'Overfitting', '過学習', 'Model học quá sát training data nên kém với dữ liệu mới.', '学習データに適合しすぎて未知データで性能が下がる状態です。', 'Học thuộc đề cũ → đề mới sai.', '丸暗記 → 新問に弱い。'),
  deep('evaluation-ai', 'Evaluation Metrics', '評価指標', 'Chỉ số đánh giá model như accuracy, precision, recall, F1.', 'Accuracy、Precision、Recall、F1などモデル性能を測る指標です。', 'Chọn chỉ số theo rủi ro.', 'リスクに応じて指標を選ぶ。'),
  deep('bias-fairness', 'Bias & Fairness', 'バイアスと公平性', 'Bias là thiên lệch; fairness là tránh bất lợi không hợp lý cho nhóm người.', '偏りと不公平な影響を避ける考え方です。', 'Dữ liệu lệch → AI lệch.', '偏ったデータ → 偏ったAI。'),
  deep('personal-information-ai', 'Personal Information', '個人情報', 'Dữ liệu có thể nhận diện cá nhân; cần mục đích, đồng ý, bảo vệ.', '個人を識別できる情報で、目的・同意・保護が重要です。', 'Không dán dữ liệu thật vào AI công khai.', '外部AIに個人情報を入れない。'),
  deep('copyright-ai', 'Copyright', '著作権', 'Quyền bảo vệ tác phẩm; AI output vẫn cần kiểm tra quyền sử dụng.', '著作物を保護する権利で、AI出力でも確認が必要です。', 'AI tạo cũng cần kiểm quyền.', 'AI生成物も権利確認。'),
  deep('ai-governance', 'AI Governance', 'AIガバナンス', 'Quy tắc, quy trình, trách nhiệm để dùng AI an toàn và minh bạch.', 'AIを安全・透明に使うためのルールと責任体制です。', 'AI mạnh thì càng cần luật chơi.', '強いAIほどルールが必要。'),
  deep('human-in-the-loop', 'Human in the Loop', '人間参加型', 'Con người kiểm tra/phê duyệt AI trong quyết định quan trọng.', '重要判断で人がAI結果を確認・承認する仕組みです。', 'AI hỗ trợ, người chịu trách nhiệm.', 'AIは支援、人が責任。'),
  deep('ai-project-flow', 'AI Project Flow', 'AIプロジェクトの流れ', 'Bắt đầu từ vấn đề kinh doanh, dữ liệu và KPI trước khi chọn model.', 'モデル選定より前に業務課題・データ・KPIを明確にします。', 'Bài toán trước, model sau.', '課題が先、モデルは後。'),
  deep('roi-ai', 'AI ROI', 'AIの投資対効果', 'Đo lợi ích AI so với chi phí, rủi ro và vận hành.', 'AIの効果をコスト・リスク・運用負荷と比較します。', 'AI tốt = tạo giá trị đo được.', '良いAI = 測定できる価値。'),
];

const scenario = (item: QuizQuestion): QuizQuestion => item;
export const aiPassportV12JapaneseScenarios: QuizQuestion[] = [
  scenario({ id: 'v12-ja-scenario-privacy', domain: 'ai', nodeId: 'personal-information-ai', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về privacy.', questionJa: '社員が顧客名、メールアドレス、購入履歴を含む一覧を外部の生成AIに入力して要約させようとしている。最も適切な対応はどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['個人情報を匿名化・削除し、社内規程と利用可能な環境を確認する', '便利なのでそのまま入力する', 'ファイル名だけ変更すればよい', '社内目的なので確認不要である'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: '個人情報を外部AIにそのまま入力するのはリスクがあります。匿名化、社内規程、利用環境の確認が必要です。' }),
  scenario({ id: 'v12-ja-scenario-copyright', domain: 'ai', nodeId: 'copyright-ai', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về copyright.', questionJa: '生成AIで作成した画像を広告に利用したい。事前に確認すべきこととして最も適切なものはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['利用規約、商用利用の可否、参照画像や既存著作物との類似リスクを確認する', '画像がきれいならよい', 'AI生成物は常に著作権を気にしなくてよい', '作者がいないので確認不要である'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: '生成AIの出力でも、規約や商用利用、既存著作物との類似性を確認する必要があります。' }),
  scenario({ id: 'v12-ja-scenario-rag', domain: 'ai', nodeId: 'rag', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về rag.', questionJa: '社内規程に基づいて最新情報を回答するチャットボットを作りたい。最も適切な構成はどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['RAGで関連文書を検索し、根拠を示して回答する', '文書を使わず毎日ファインチューニングする', '汎用プロンプトだけで十分である', '社内文書の更新は不要である'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: 'RAGは最新の社内文書を検索し、根拠に基づく回答を行う用途に適しています。' }),
  scenario({ id: 'v12-ja-scenario-bias', domain: 'ai', nodeId: 'bias-fairness', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về bias.', questionJa: '採用支援AIが特定の属性を持つ応募者に不利な結果を出している可能性がある。対応として最も適切なものはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['データとモデルのバイアスを検証し、公平性評価と人による確認を行う', '機械は客観的なのでそのまま使う', 'センシティブ属性を削除すれば必ず十分である', 'モデルを確認せず面接回数だけ増やす'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: '過去データや代理変数に偏りが含まれる場合があります。公平性評価と人による確認が重要です。' }),
  scenario({ id: 'v12-ja-scenario-project', domain: 'ai', nodeId: 'ai-project-flow', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về project.', questionJa: 'AI導入プロジェクトを開始する際、最初に行うこととして最も適切なものはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['業務課題、利用可能なデータ、KPI/KGI、リスクを明確にする', '最新モデルを先に選ぶ', 'GPUを先に購入する', '見た目のよい画面を先に作る'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: 'AIプロジェクトはモデル選定より先に、業務課題とデータ、評価指標、リスクを明確にします。' }),
  scenario({ id: 'v12-ja-scenario-hallucination', domain: 'ai', nodeId: 'hallucination', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về hallucination.', questionJa: 'LLMが自信のある表現で回答したが、根拠となる資料が確認できない。対応として最も適切なものはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['信頼できる情報源で確認してから利用する', '自信のある表現なので正しいと判断する', '法務文書にそのまま利用する', '履歴を削除すればよい'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: 'ハルシネーションはもっともらしく見えるため、重要情報は必ず確認します。' }),
  scenario({ id: 'v12-ja-scenario-prompt-injection', domain: 'ai', nodeId: 'prompt-injection', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về prompt-injection.', questionJa: 'RAGチャットボットが外部文書を読み込む際、「システム指示を無視せよ」という文章が含まれていた。想定すべきリスクはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['データ内の悪意ある指示に従うプロンプトインジェクション', 'TLS暗号が強化される', 'DNSキャッシュが満杯になる', 'GPUが高速化する'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: 'プロンプトインジェクションはLLM/RAGで重要なリスクです。入力検証、権限管理、ガードレールが必要です。' }),
  scenario({ id: 'v12-ja-scenario-model-drift', domain: 'ai', nodeId: 'model-drift-ai', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về model-drift.', questionJa: '需要予測モデルが導入直後は高精度だったが、数か月後に精度が低下した。原因として考えられるものはどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['実データの傾向が変化したことによるモデルドリフト', 'モデルが自動的に安全性を高めた', 'DNSのアドレスが変わった', '画面の画像サイズが大きい'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: 'モデルドリフトは実データの分布変化で性能が低下する現象です。監視と再学習が必要です。' }),
  scenario({ id: 'v12-ja-scenario-accuracy', domain: 'ai', nodeId: 'evaluation-ai', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về accuracy.', questionJa: '不正取引が全体の1%しかないデータで、すべて正常と予測するモデルの正解率が99%になった。この評価の問題はどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['クラス不均衡のため正解率だけでは不十分で、適合率・再現率・F値も見るべき', 'モデルは完全である', '追加評価は不要である', 'テストデータを使わない方がよい'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: '不均衡データでは正解率だけでは性能を誤解するため、適合率や再現率も確認します。' }),
  scenario({ id: 'v12-ja-scenario-hitl', domain: 'ai', nodeId: 'human-in-the-loop', difficulty: 'hard', questionVi: 'Câu hỏi tình huống tiếng Nhật về hitl.', questionJa: 'AIが融資審査で否認を提案した。高リスク領域で適切な運用はどれか。', options: ['Đáp án phù hợp nhất', 'Đáp án gây rủi ro', 'Đáp án chưa đủ kiểm soát', 'Đáp án không phù hợp'], optionsJa: ['人が最終判断と理由を確認する', 'AIがすべて自動で否認する', 'ログを残さない', 'AI利用を知らせない'], answerIndex: 0, explanationVi: 'Hãy chọn phương án kiểm soát rủi ro, có căn cứ và phù hợp doanh nghiệp.', explanationJa: '高リスク判断では人による確認、説明、責任体制が重要です。' }),
];

export const examCheatSheet = {
  frequentTerms: [['人工知能','AI','Khái niệm lớn nhất, bao gồm ML/DL/GenAI.'], ['機械学習','Machine Learning','Học quy luật từ dữ liệu.'], ['深層学習','Deep Learning','ML dùng neural network nhiều lớp.'], ['生成AI','Generative AI','Tạo văn bản/ảnh/âm thanh/code.'], ['大規模言語モデル','LLM','Model ngôn ngữ lớn, có thể hallucination.'], ['前処理','Preprocessing','Làm sạch/chuẩn hóa dữ liệu trước khi học.'], ['過学習','Overfitting','Training tốt nhưng dữ liệu mới kém.'], ['ハルシネーション','Hallucination','AI bịa nhưng nghe hợp lý.'], ['個人情報','Personal Information','Không nhập bừa vào AI công khai.'], ['著作権','Copyright','Cần kiểm quyền input/output AI.']],
  confusedPairs: [['AI / ML / DL','AI là ô lớn nhất; ML nằm trong AI; DL nằm trong ML.'], ['教師あり / 教師なし','Có label = supervised; không label, tìm nhóm/pattern = unsupervised.'], ['回帰 / 分類','Dự đoán số = regression; dự đoán nhãn = classification.'], ['CNN / RNN / Transformer','CNN ảnh; RNN chuỗi; Transformer attention/LLM.'], ['Accuracy / Precision / Recall','Accuracy dễ lừa với dữ liệu lệch; precision giảm báo nhầm; recall giảm bỏ sót.'], ['Privacy / Copyright','Privacy bảo vệ người; copyright bảo vệ tác phẩm.'], ['Hallucination / Bias','Hallucination là bịa sai; bias là thiên lệch không công bằng.']],
  memoryFormulas: ['AI ⊃ Machine Learning ⊃ Deep Learning', 'ML project = Problem → Data → Preprocessing → Model → Evaluation → Operation', 'Good AI use = Purpose + Data quality + Risk control + Human review', 'RAG = Retrieve documents → Generate answer → Show evidence', 'Business AI = Use case → KPI/KGI → PoC → Deploy → Monitor'],
  examTraps: ['Không chọn đáp án “dùng test data để training”.', 'Không tin LLM tuyệt đối khi không có nguồn.', 'Không nhập dữ liệu cá nhân/cơ mật vào AI công khai.', 'Không bắt đầu AI project bằng “chọn model mới nhất”.', 'Không dùng accuracy một mình cho dữ liệu lệch lớp.', 'Không nghĩ AI output luôn không có vấn đề bản quyền.', 'Không coi RAG là bảo đảm đúng 100%.'],
  rightWrongExamples: [['Đúng','Dùng RAG cho chatbot nội bộ cần trả lời dựa trên quy định mới nhất.'], ['Sai','Dán danh sách khách hàng thật vào AI công khai để tóm tắt.'], ['Đúng','Dùng human-in-the-loop cho AI hỗ trợ quyết định khoản vay.'], ['Sai','Dùng test data để huấn luyện rồi báo accuracy cao.'], ['Đúng','Kiểm tra terms/license trước khi dùng ảnh AI cho quảng cáo.'], ['Sai','Tin câu trả lời AI vì giọng văn tự tin và trôi chảy.']],
};
