import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';

const q=(nodeId:string, shortDefinitionVi:string, whyImportantVi:string, memoryTipVi:string):LessonContent=>({
  nodeId, shortDefinitionVi, shortDefinitionJa:shortDefinitionVi, whyImportantVi, whyImportantJa:whyImportantVi,
  examPatternsVi:['Phân biệt với khái niệm dễ nhầm','Chọn ứng dụng đúng trong tình huống','Nhận diện rủi ro/bẫy đề thi'],
  examPatternsJa:['類似概念との違い','適切な利用場面','リスク・試験のひっかけ'],
  commonMistakesVi:['Chỉ học thuộc tên mà không hiểu ví dụ','Nhầm tầng khái niệm AI/ML/DL/GenAI','Bỏ qua dữ liệu, rủi ro và con người trong quy trình'],
  commonMistakesJa:['名前だけ暗記する','AI/ML/DL/生成AIを混同する','データ・リスク・人の確認を軽視する'],
  memoryTipVi, memoryTipJa:memoryTipVi,
});

export const aiPassportV35QualityLessons: LessonContent[] = [
  q('ai-definition','AI là lĩnh vực làm cho máy thực hiện tác vụ cần trí tuệ như nhận diện, dự đoán, tạo nội dung hoặc hỗ trợ quyết định.','Đề thi hay hỏi AI khác gì ML/DL/GenAI. Nếu không nắm tầng khái niệm, bạn sẽ nhầm công cụ với phương pháp.','AI là ô lớn nhất: AI ⊃ ML ⊃ Deep Learning; GenAI là nhóm tạo nội dung.'),
  q('machine-learning-ai','Machine Learning là cách cho máy học quy luật từ dữ liệu thay vì viết toàn bộ rule bằng tay.','ML là nền của nhiều câu hỏi về dữ liệu, train/test, overfitting, evaluation và business use case.','ML cần dữ liệu + nhãn/không nhãn + metric; không phải cứ dùng AI là ML.'),
  q('deep-learning-ai','Deep Learning là ML dùng neural network nhiều tầng để học biểu diễn phức tạp từ dữ liệu lớn.','DL thường liên quan CNN/RNN/Transformer, nhận dạng ảnh, ngôn ngữ và mô hình sinh.','Deep = nhiều tầng; mạnh nhưng cần nhiều dữ liệu/tính toán và khó giải thích hơn.'),
  q('supervised-ai','Supervised learning học từ dữ liệu có đáp án đúng, ví dụ nhãn spam/không spam hoặc giá nhà.','Dễ ra câu phân biệt classification/regression và dữ liệu có label hay không.','Có teacher/label thì supervised. Output số liên tục = regression; output lớp = classification.'),
  q('unsupervised-ai','Unsupervised learning tìm cấu trúc trong dữ liệu không có nhãn, ví dụ clustering khách hàng.','Đề hay bẫy giữa phân loại có nhãn và phân cụm không nhãn.','Không có đáp án mẫu; mục tiêu là khám phá pattern.'),
  q('linear-regression-ai','Linear regression dự đoán giá trị số liên tục bằng quan hệ tuyến tính giữa biến đầu vào và đầu ra.','Hay bị nhầm với logistic regression. Linear dùng cho số liên tục, không dùng trực tiếp cho phân lớp.','Regression = dự đoán số; ví dụ doanh thu, nhiệt độ, giá.'),
  q('logistic-regression-ai','Logistic regression thường dùng cho classification nhị phân bằng xác suất thuộc lớp.','Tên có regression nhưng bài thi thường xem là phương pháp classification.','Logistic = xác suất và phân lớp, ví dụ spam/không spam.'),
  q('decision-tree-ai','Decision tree là mô hình ra quyết định bằng chuỗi câu hỏi if/else dạng cây.','Dễ hiểu, dễ giải thích nhưng có thể overfit nếu cây quá sâu.','Cây càng sâu càng dễ nhớ dữ liệu train, cần pruning/giới hạn.'),
  q('svm-ai','SVM tìm ranh giới phân tách dữ liệu sao cho margin giữa các lớp càng lớn càng tốt.','Hay xuất hiện như một thuật toán classification cổ điển bên cạnh tree/logistic.','SVM = tìm đường/siêu phẳng phân tách với margin lớn.'),
  q('neural-network-ai','Neural network gồm các tầng node học trọng số để biến input thành output.','Là nền của deep learning, CNN, RNN, Transformer và GenAI.','Input → layers → output; học bằng điều chỉnh weight.'),
  q('cnn-ai','CNN là neural network mạnh cho dữ liệu dạng lưới như ảnh nhờ convolution filter.','Đề hay hỏi mô hình phù hợp cho image recognition.','CNN = ảnh, filter, đặc trưng cục bộ.'),
  q('rnn-ai','RNN xử lý dữ liệu tuần tự bằng cách giữ thông tin từ bước trước.','Hay được so sánh với Transformer trong xử lý chuỗi/ngôn ngữ.','RNN = sequence theo thời gian, nhưng khó song song hóa hơn Transformer.'),
  q('transformer-ai','Transformer dùng attention để xem phần nào của chuỗi quan trọng khi xử lý ngôn ngữ hoặc dữ liệu tuần tự.','Là nền tảng của LLM và nhiều mô hình GenAI hiện đại.','Attention = chọn phần cần chú ý trong context.'),
  q('data-quality','Data quality là mức độ dữ liệu đầy đủ, chính xác, nhất quán, đại diện và phù hợp mục tiêu.','Dữ liệu kém làm model kém dù thuật toán tốt. Đây là bẫy rất hay gặp trong AI project.','Garbage in, garbage out: dữ liệu xấu → AI sai.'),
  q('data-preprocessing-ai','Data preprocessing là làm sạch, chuẩn hóa, mã hóa, xử lý thiếu dữ liệu và chuẩn bị dữ liệu trước khi train.','Thực tế dự án ML tốn nhiều thời gian ở preprocessing; đề hay hỏi bước này.','Preprocess trước train: clean → transform → split.'),
  q('training-test-data','Training/test split tách dữ liệu học và dữ liệu kiểm tra để đánh giá model trên dữ liệu chưa thấy.','Nếu dùng test data để học sẽ gây data leakage và đánh giá ảo.','Train để học; test để kiểm tra. Không trộn.'),
  q('overfitting-ai','Overfitting là model học quá sát dữ liệu train nên kém trên dữ liệu mới.','Hay xuất hiện trong câu hỏi vì sao train accuracy cao nhưng test accuracy thấp.','Train cao, test thấp = nghĩ tới overfitting.'),
  q('evaluation-ai','Evaluation là đánh giá model bằng metric phù hợp như accuracy, precision, recall, F1, MAE.','Chọn sai metric có thể làm mô hình tưởng tốt nhưng vô dụng trong business.','Classification cần confusion matrix; regression cần sai số số học.'),
  q('llm','LLM là mô hình ngôn ngữ lớn học từ dữ liệu văn bản rất lớn để hiểu và sinh ngôn ngữ tự nhiên.','LLM là trung tâm của GenAI, chatbot, RAG, prompt và hallucination.','LLM giỏi ngôn ngữ nhưng không đảm bảo luôn đúng sự thật.'),
  q('prompt-engineering','Prompt engineering là thiết kế chỉ thị, ngữ cảnh, ví dụ và ràng buộc để model trả lời đúng mục tiêu hơn.','Đề hay hỏi cách giảm sai lệch output mà không cần train lại model.','Prompt tốt = vai trò + mục tiêu + dữ liệu + format + constraint.'),
  q('hallucination','Hallucination là khi AI tạo câu trả lời nghe có vẻ đúng nhưng sai hoặc không có căn cứ.','Đây là rủi ro lớn khi dùng GenAI trong nghiệp vụ, pháp lý, y tế, tài chính.','Không tin output chỉ vì văn phong tự tin; cần nguồn, RAG, review.'),
  q('rag','RAG kết hợp retrieval từ tài liệu bên ngoài với generation để trả lời dựa trên nguồn liên quan.','RAG giảm hallucination và giúp chatbot dùng kiến thức nội bộ mà không cần train lại toàn bộ model.','RAG = search tài liệu trước, rồi LLM trả lời dựa trên tài liệu.'),
  q('multimodal-ai','Multimodal AI xử lý nhiều loại dữ liệu như text, ảnh, âm thanh, video.','Hay ra trong bối cảnh GenAI hiện đại và ứng dụng business.','Multi = nhiều modality; không chỉ text.'),
  q('personal-information-ai','Personal information trong AI là dữ liệu có thể nhận dạng cá nhân trực tiếp hoặc gián tiếp.','Đây là phần ethics/law cực quan trọng khi dùng GenAI và dữ liệu khách hàng.','Không đưa PII vào AI công cộng nếu chưa có căn cứ, policy và bảo vệ phù hợp.'),
  q('copyright-ai','Copyright trong AI liên quan dữ liệu huấn luyện, input đưa vào model và output sinh ra.','Đề hay bẫy: AI tạo ra không có nghĩa là tự do dùng thương mại.','Kiểm license, nguồn dữ liệu, mức tương đồng output và điều khoản dịch vụ.'),
  q('bias-fairness','Bias/Fairness là vấn đề AI đưa ra kết quả bất công với một nhóm người do dữ liệu hoặc thiết kế.','Accuracy toàn cục cao vẫn có thể gây bất công ở nhóm nhỏ; đây là bẫy đề thi quan trọng.','Đánh giá theo nhóm, không chỉ nhìn trung bình toàn bộ.'),
  q('explainable-ai','Explainable AI giúp con người hiểu lý do model đưa ra kết quả.','Quan trọng trong tín dụng, tuyển dụng, y tế và các quyết định ảnh hưởng con người.','Càng rủi ro cao càng cần giải thích và audit.'),
  q('human-in-the-loop','Human-in-the-loop là đặt con người vào quy trình kiểm tra, phê duyệt hoặc can thiệp quyết định AI.','AI hỗ trợ nhưng con người chịu trách nhiệm ở tình huống rủi ro cao.','AI suggest, human decide.'),
  q('ai-governance','AI governance là hệ thống chính sách, quy trình, vai trò và kiểm soát để dùng AI an toàn có trách nhiệm.','Doanh nghiệp cần governance để quản lý privacy, copyright, security, fairness và accountability.','Governance không phải cấm AI; là dùng AI có kiểm soát.'),
  q('ai-project-flow','AI project flow đi từ business problem, data, model, evaluation, deployment đến monitoring.','Nhiều dự án thất bại vì bắt đầu bằng model trước khi rõ bài toán và dữ liệu.','Problem first, data second, model later, monitoring forever.'),
  q('ai-risk-management','AI risk management là nhận diện, đánh giá, giảm thiểu và theo dõi rủi ro AI.','AI có rủi ro hallucination, bias, privacy, copyright, security và vận hành.','Risk = khả năng x impact; cần owner và mitigation.'),
  q('roi-ai','ROI AI là đánh giá lợi ích kinh doanh so với chi phí, rủi ro và vận hành AI.','AI demo hay chưa chắc đáng đầu tư nếu không tạo giá trị đo được.','ROI = value - cost - risk; cần KPI business.'),
];
