import type { QuizQuestion } from '../../features/knowledge-graph/data/quizQuestions';

const j = (item: QuizQuestion) => item;

export const aiPassportJapaneseExamQuiz: QuizQuestion[] = [
  j({ id: 'jexam-001', domain: 'ai', nodeId: 'ai-definition', difficulty: 'basic', questionVi: 'AIの説明として最も適切なものはどれですか。', questionJa: 'AIの説明として最も適切なものはどれですか。', options: ['人間の形をしたロボットだけを指す', '認識・予測・生成など知的な処理を行う技術の総称', '表計算ソフトだけを指す', 'インターネット回線の種類を指す'], optionsJa: ['人間の形をしたロボットだけを指す', '認識・予測・生成など知的な処理を行う技術の総称', '表計算ソフトだけを指す', 'インターネット回線の種類を指す'], answerIndex: 1, explanationVi: 'AIはロボットだけではなく、認識・予測・分類・生成などを含む広い概念です。', explanationJa: 'AIはロボットだけではなく、認識・予測・分類・生成などを含む広い概念です。' }),
  j({ id: 'jexam-002', domain: 'ai', nodeId: 'machine-learning-ai', difficulty: 'basic', questionVi: '機械学習の特徴として正しいものはどれですか。', questionJa: '機械学習の特徴として正しいものはどれですか。', options: ['すべてのルールを人間が手作業で書く', 'データから規則性を学習する', 'データをまったく使わない', '暗号化だけを行う'], optionsJa: ['すべてのルールを人間が手作業で書く', 'データから規則性を学習する', 'データをまったく使わない', '暗号化だけを行う'], answerIndex: 1, explanationVi: '機械学習はデータからパターンや規則性を学習します。', explanationJa: '機械学習はデータからパターンや規則性を学習します。' }),
  j({ id: 'jexam-003', domain: 'ai', nodeId: 'deep-learning-ai', difficulty: 'standard', questionVi: 'AI・機械学習・深層学習の関係として正しいものはどれですか。', questionJa: 'AI・機械学習・深層学習の関係として正しいものはどれですか。', options: ['AI ⊃ 機械学習 ⊃ 深層学習', '深層学習 ⊃ AI ⊃ 機械学習', '機械学習 ⊃ AI ⊃ 深層学習', '3つは関係がない'], optionsJa: ['AI ⊃ 機械学習 ⊃ 深層学習', '深層学習 ⊃ AI ⊃ 機械学習', '機械学習 ⊃ AI ⊃ 深層学習', '3つは関係がない'], answerIndex: 0, explanationVi: 'AIが最も広く、その中に機械学習、さらにその中に深層学習があります。', explanationJa: 'AIが最も広く、その中に機械学習、さらにその中に深層学習があります。' }),
  j({ id: 'jexam-004', domain: 'ai', nodeId: 'supervised-ai', difficulty: 'standard', questionVi: '教師あり学習の例として適切なものはどれですか。', questionJa: '教師あり学習の例として適切なものはどれですか。', options: ['正解ラベル付きの画像から犬・猫を分類するモデルを作る', 'ラベルなしの顧客データをグループ化する', 'ゲーム内で報酬を得ながら行動を学ぶ', 'データを暗号化する'], optionsJa: ['正解ラベル付きの画像から犬・猫を分類するモデルを作る', 'ラベルなしの顧客データをグループ化する', 'ゲーム内で報酬を得ながら行動を学ぶ', 'データを暗号化する'], answerIndex: 0, explanationVi: '教師あり学習は正解ラベル付きデータを使います。', explanationJa: '教師あり学習は正解ラベル付きデータを使います。' }),
  j({ id: 'jexam-005', domain: 'ai', nodeId: 'unsupervised-ai', difficulty: 'standard', questionVi: '教師なし学習の例として適切なものはどれですか。', questionJa: '教師なし学習の例として適切なものはどれですか。', options: ['ラベルなしの購買履歴から似た顧客を分類する', '正解付きデータで迷惑メールを分類する', '人間がすべてのif文を書く', '公開鍵で電子署名を検証する'], optionsJa: ['ラベルなしの購買履歴から似た顧客を分類する', '正解付きデータで迷惑メールを分類する', '人間がすべてのif文を書く', '公開鍵で電子署名を検証する'], answerIndex: 0, explanationVi: '教師なし学習は正解ラベルのないデータから構造やグループを見つけます。', explanationJa: '教師なし学習は正解ラベルのないデータから構造やグループを見つけます。' }),
  j({ id: 'jexam-006', domain: 'ai', nodeId: 'reinforcement-learning', difficulty: 'standard', questionVi: '強化学習に関係が深い用語はどれですか。', questionJa: '強化学習に関係が深い用語はどれですか。', options: ['報酬', '主キー', 'DNS', '著作権'], optionsJa: ['報酬', '主キー', 'DNS', '著作権'], answerIndex: 0, explanationVi: '強化学習ではエージェントが環境内で行動し、報酬をもとに学習します。', explanationJa: '強化学習ではエージェントが環境内で行動し、報酬をもとに学習します。' }),
  j({ id: 'jexam-007', domain: 'ai', nodeId: 'linear-regression-ai', difficulty: 'standard', questionVi: '線形回帰が主に使われる目的はどれですか。', questionJa: '線形回帰が主に使われる目的はどれですか。', options: ['数値を予測する', '画像を暗号化する', '個人情報を匿名化する', 'ネットワークを分割する'], optionsJa: ['数値を予測する', '画像を暗号化する', '個人情報を匿名化する', 'ネットワークを分割する'], answerIndex: 0, explanationVi: '線形回帰は売上や価格など連続値の予測に使われます。', explanationJa: '線形回帰は売上や価格など連続値の予測に使われます。' }),
  j({ id: 'jexam-008', domain: 'ai', nodeId: 'logistic-regression-ai', difficulty: 'hard', questionVi: 'ロジスティック回帰の説明として適切なものはどれですか。', questionJa: 'ロジスティック回帰の説明として適切なものはどれですか。', options: ['主に二値分類の確率予測に使われる', '必ず画像生成に使われる', 'ラベルなしデータのクラスタリング専用である', '暗号方式の一種である'], optionsJa: ['主に二値分類の確率予測に使われる', '必ず画像生成に使われる', 'ラベルなしデータのクラスタリング専用である', '暗号方式の一種である'], answerIndex: 0, explanationVi: '名前に回帰がありますが、実務では二値分類に使われることが多いです。', explanationJa: '名前に回帰がありますが、実務では二値分類に使われることが多いです。' }),
  j({ id: 'jexam-009', domain: 'ai', nodeId: 'classification-ai', difficulty: 'basic', questionVi: '分類の例として適切なものはどれですか。', questionJa: '分類の例として適切なものはどれですか。', options: ['メールが迷惑メールかどうかを判定する', '来月の売上金額を予測する', 'データを圧縮する', '通信を暗号化する'], optionsJa: ['メールが迷惑メールかどうかを判定する', '来月の売上金額を予測する', 'データを圧縮する', '通信を暗号化する'], answerIndex: 0, explanationVi: '分類はデータをカテゴリやラベルに分ける問題です。', explanationJa: '分類はデータをカテゴリやラベルに分ける問題です。' }),
  j({ id: 'jexam-010', domain: 'ai', nodeId: 'regression-ai', difficulty: 'basic', questionVi: '回帰の例として適切なものはどれですか。', questionJa: '回帰の例として適切なものはどれですか。', options: ['住宅価格を予測する', 'メールを迷惑メールかどうか分類する', '利用者を認証する', '著作権を確認する'], optionsJa: ['住宅価格を予測する', 'メールを迷惑メールかどうか分類する', '利用者を認証する', '著作権を確認する'], answerIndex: 0, explanationVi: '回帰は数値の予測に使われます。', explanationJa: '回帰は数値の予測に使われます。' }),
  j({ id: 'jexam-011', domain: 'ai', nodeId: 'cnn-ai', difficulty: 'standard', questionVi: 'CNNが得意とする処理はどれですか。', questionJa: 'CNNが得意とする処理はどれですか。', options: ['画像認識', 'DNS変換', '著作権管理', '会計処理'], optionsJa: ['画像認識', 'DNS変換', '著作権管理', '会計処理'], answerIndex: 0, explanationVi: 'CNNは画像の特徴抽出に強いニューラルネットワークです。', explanationJa: 'CNNは画像の特徴抽出に強いニューラルネットワークです。' }),
  j({ id: 'jexam-012', domain: 'ai', nodeId: 'rnn-ai', difficulty: 'standard', questionVi: 'RNNが扱いやすいデータはどれですか。', questionJa: 'RNNが扱いやすいデータはどれですか。', options: ['時系列や文章のような順序を持つデータ', '静止画像だけ', '公開鍵', '表の主キー'], optionsJa: ['時系列や文章のような順序を持つデータ', '静止画像だけ', '公開鍵', '表の主キー'], answerIndex: 0, explanationVi: 'RNNは系列データの処理に使われます。', explanationJa: 'RNNは系列データの処理に使われます。' }),
  j({ id: 'jexam-013', domain: 'ai', nodeId: 'transformer-ai', difficulty: 'standard', questionVi: 'Transformerの特徴として適切なものはどれですか。', questionJa: 'Transformerの特徴として適切なものはどれですか。', options: ['Attentionを用いて文脈を扱う', 'データベースの正規化だけを行う', 'ネットワーク機器の名称である', 'ウイルス対策ソフトである'], optionsJa: ['Attentionを用いて文脈を扱う', 'データベースの正規化だけを行う', 'ネットワーク機器の名称である', 'ウイルス対策ソフトである'], answerIndex: 0, explanationVi: 'TransformerはAttentionを使い、多くのLLMの基盤です。', explanationJa: 'TransformerはAttentionを使い、多くのLLMの基盤です。' }),
  j({ id: 'jexam-014', domain: 'ai', nodeId: 'data-preprocessing-ai', difficulty: 'standard', questionVi: '前処理の例として適切なものはどれですか。', questionJa: '前処理の例として適切なものはどれですか。', options: ['欠損値の処理やデータ形式の統一を行う', 'テストデータで学習する', '公開鍵を配布する', 'AIの出力を無条件で採用する'], optionsJa: ['欠損値の処理やデータ形式の統一を行う', 'テストデータで学習する', '公開鍵を配布する', 'AIの出力を無条件で採用する'], answerIndex: 0, explanationVi: '前処理はデータを学習に使える状態に整える作業です。', explanationJa: '前処理はデータを学習に使える状態に整える作業です。' }),
  j({ id: 'jexam-015', domain: 'ai', nodeId: 'training-test-data', difficulty: 'standard', questionVi: 'テストデータの使い方として適切なものはどれですか。', questionJa: 'テストデータの使い方として適切なものはどれですか。', options: ['学習済みモデルの評価に使う', 'モデルの学習に直接使う', '常に削除する', '個人情報として公開する'], optionsJa: ['学習済みモデルの評価に使う', 'モデルの学習に直接使う', '常に削除する', '個人情報として公開する'], answerIndex: 0, explanationVi: 'テストデータは学習に使わず、未知データへの性能評価に使います。', explanationJa: 'テストデータは学習に使わず、未知データへの性能評価に使います。' }),
  j({ id: 'jexam-016', domain: 'ai', nodeId: 'overfitting-ai', difficulty: 'standard', questionVi: '過学習の説明として適切なものはどれですか。', questionJa: '過学習の説明として適切なものはどれですか。', options: ['学習データに適合しすぎて未知データに弱くなる', 'データを暗号化する', '画像を圧縮する', '必ず性能が上がる状態'], optionsJa: ['学習データに適合しすぎて未知データに弱くなる', 'データを暗号化する', '画像を圧縮する', '必ず性能が上がる状態'], answerIndex: 0, explanationVi: '過学習では訓練データでは良くてもテストデータで性能が落ちます。', explanationJa: '過学習では訓練データでは良くてもテストデータで性能が落ちます。' }),
  j({ id: 'jexam-017', domain: 'ai', nodeId: 'evaluation-ai', difficulty: 'standard', questionVi: '不均衡データの分類でAccuracyだけを見るリスクは何ですか。', questionJa: '不均衡データの分類でAccuracyだけを見るリスクは何ですか。', options: ['少数クラスを見逃しても高く見えることがある', '必ずモデルが安全になる', '個人情報が自動的に匿名化される', '著作権問題が解決する'], optionsJa: ['少数クラスを見逃しても高く見えることがある', '必ずモデルが安全になる', '個人情報が自動的に匿名化される', '著作権問題が解決する'], answerIndex: 0, explanationVi: 'データが偏っているとAccuracyだけでは性能を正しく判断できません。', explanationJa: 'データが偏っているとAccuracyだけでは性能を正しく判断できません。' }),
  j({ id: 'jexam-018', domain: 'ai', nodeId: 'hallucination', difficulty: 'standard', questionVi: 'ハルシネーションへの適切な対応はどれですか。', questionJa: 'ハルシネーションへの適切な対応はどれですか。', options: ['出力を根拠資料で確認する', 'AIの回答を常に正しいとみなす', '個人情報をすべて入力する', 'ログを残さない'], optionsJa: ['出力を根拠資料で確認する', 'AIの回答を常に正しいとみなす', '個人情報をすべて入力する', 'ログを残さない'], answerIndex: 0, explanationVi: '生成AIの出力は誤りを含むことがあるため、根拠確認が必要です。', explanationJa: '生成AIの出力は誤りを含むことがあるため、根拠確認が必要です。' }),
  j({ id: 'jexam-019', domain: 'ai', nodeId: 'rag', difficulty: 'hard', questionVi: 'RAGの説明として適切なものはどれですか。', questionJa: 'RAGの説明として適切なものはどれですか。', options: ['関連文書を検索してから生成AIに回答させる仕組み', 'AIを使わない暗号方式', '画像だけを圧縮する手法', 'テストデータを学習に使う手法'], optionsJa: ['関連文書を検索してから生成AIに回答させる仕組み', 'AIを使わない暗号方式', '画像だけを圧縮する手法', 'テストデータを学習に使う手法'], answerIndex: 0, explanationVi: 'RAGは検索結果を根拠として生成することで回答品質を高める考え方です。', explanationJa: 'RAGは検索結果を根拠として生成することで回答品質を高める考え方です。' }),
  j({ id: 'jexam-020', domain: 'security', nodeId: 'personal-information-ai', difficulty: 'standard', questionVi: '生成AIに個人情報を入力する場合の注意として適切なものはどれですか。', questionJa: '生成AIに個人情報を入力する場合の注意として適切なものはどれですか。', options: ['利用目的・同意・社内ルールを確認する', '便利なので無条件で入力する', '出力が速ければ問題ない', '暗号化されていれば必ず公開してよい'], optionsJa: ['利用目的・同意・社内ルールを確認する', '便利なので無条件で入力する', '出力が速ければ問題ない', '暗号化されていれば必ず公開してよい'], answerIndex: 0, explanationVi: '個人情報の扱いには目的、同意、管理ルールが必要です。', explanationJa: '個人情報の扱いには目的、同意、管理ルールが必要です。' }),
  j({ id: 'jexam-021', domain: 'security', nodeId: 'copyright-ai', difficulty: 'standard', questionVi: '生成AIの出力を商用利用する場合に必要な考え方はどれですか。', questionJa: '生成AIの出力を商用利用する場合に必要な考え方はどれですか。', options: ['著作権や利用規約を確認する', 'AI出力なので必ず自由に使える', '確認せずに公開してよい', '個人情報保護は関係ない'], optionsJa: ['著作権や利用規約を確認する', 'AI出力なので必ず自由に使える', '確認せずに公開してよい', '個人情報保護は関係ない'], answerIndex: 0, explanationVi: 'AI出力でも著作権・利用規約・類似性確認が必要な場合があります。', explanationJa: 'AI出力でも著作権・利用規約・類似性確認が必要な場合があります。' }),
  j({ id: 'jexam-022', domain: 'security', nodeId: 'bias-fairness', difficulty: 'standard', questionVi: 'AIのバイアス対策として適切なものはどれですか。', questionJa: 'AIのバイアス対策として適切なものはどれですか。', options: ['データの偏りや結果の公平性を確認する', '過去データを無条件に正しいとみなす', '少数派データを必ず削除する', '評価を行わない'], optionsJa: ['データの偏りや結果の公平性を確認する', '過去データを無条件に正しいとみなす', '少数派データを必ず削除する', '評価を行わない'], answerIndex: 0, explanationVi: '過去データには偏りが含まれることがあり、公平性の確認が必要です。', explanationJa: '過去データには偏りが含まれることがあり、公平性の確認が必要です。' }),
  j({ id: 'jexam-023', domain: 'security', nodeId: 'human-in-the-loop', difficulty: 'standard', questionVi: 'Human in the Loop が特に重要な場面はどれですか。', questionJa: 'Human in the Loop が特に重要な場面はどれですか。', options: ['医療・採用・融資など人に大きな影響を与える判断', '背景色を変更するだけの処理', '電卓で単純計算する処理', '画像ファイル名を変更する処理'], optionsJa: ['医療・採用・融資など人に大きな影響を与える判断', '背景色を変更するだけの処理', '電卓で単純計算する処理', '画像ファイル名を変更する処理'], answerIndex: 0, explanationVi: 'リスクが高い判断では人間の確認や責任が重要です。', explanationJa: 'リスクが高い判断では人間の確認や責任が重要です。' }),
  j({ id: 'jexam-024', domain: 'security', nodeId: 'ai-governance', difficulty: 'standard', questionVi: 'AIガバナンスの目的として適切なものはどれですか。', questionJa: 'AIガバナンスの目的として適切なものはどれですか。', options: ['AIを安全かつ責任ある形で利用するためのルールや体制を整える', 'AIの回答をすべて採用する', 'セキュリティ対策を不要にする', '個人情報を自由に共有する'], optionsJa: ['AIを安全かつ責任ある形で利用するためのルールや体制を整える', 'AIの回答をすべて採用する', 'セキュリティ対策を不要にする', '個人情報を自由に共有する'], answerIndex: 0, explanationVi: 'AIガバナンスはルール、責任、監査、リスク管理を含みます。', explanationJa: 'AIガバナンスはルール、責任、監査、リスク管理を含みます。' }),
  j({ id: 'jexam-025', domain: 'security', nodeId: 'prompt-injection', difficulty: 'hard', questionVi: 'プロンプトインジェクションへの対策として適切なものはどれですか。', questionJa: 'プロンプトインジェクションへの対策として適切なものはどれですか。', options: ['入力を無条件に信頼せず、権限やツール利用を制限する', 'ユーザー入力をすべてsystem promptとして扱う', 'ログを残さない', '機密情報をプロンプトに含める'], optionsJa: ['入力を無条件に信頼せず、権限やツール利用を制限する', 'ユーザー入力をすべてsystem promptとして扱う', 'ログを残さない', '機密情報をプロンプトに含める'], answerIndex: 0, explanationVi: 'ユーザー入力でAIが意図しない動作をしないよう、権限や入力検証が必要です。', explanationJa: 'ユーザー入力でAIが意図しない動作をしないよう、権限や入力検証が必要です。' }),
  j({ id: 'jexam-026', domain: 'business', nodeId: 'ai-project-flow', difficulty: 'standard', questionVi: 'AIプロジェクトの進め方として適切な順序はどれですか。', questionJa: 'AIプロジェクトの進め方として適切な順序はどれですか。', options: ['課題設定 → データ確認 → モデル作成 → 評価 → 導入・監視', 'モデル作成 → 課題設定 → データ確認 → 評価', '導入 → データ削除 → 評価なし', 'AIツール選定だけで完了'], optionsJa: ['課題設定 → データ確認 → モデル作成 → 評価 → 導入・監視', 'モデル作成 → 課題設定 → データ確認 → 評価', '導入 → データ削除 → 評価なし', 'AIツール選定だけで完了'], answerIndex: 0, explanationVi: 'AIプロジェクトは目的とデータ確認から始めるのが基本です。', explanationJa: 'AIプロジェクトは目的とデータ確認から始めるのが基本です。' }),
  j({ id: 'jexam-027', domain: 'business', nodeId: 'ai-usecase', difficulty: 'standard', questionVi: 'AI活用を検討するとき最初に確認すべきことはどれですか。', questionJa: 'AI活用を検討するとき最初に確認すべきことはどれですか。', options: ['解決したい業務課題と目的', '流行しているモデル名', '画面の色', '会社のロゴ'], optionsJa: ['解決したい業務課題と目的', '流行しているモデル名', '画面の色', '会社のロゴ'], answerIndex: 0, explanationVi: 'AI導入は技術選定より先に、目的と課題を明確にします。', explanationJa: 'AI導入は技術選定より先に、目的と課題を明確にします。' }),
  j({ id: 'jexam-028', domain: 'business', nodeId: 'roi-ai', difficulty: 'standard', questionVi: 'AI導入のROIを考えるときに含めるべきものはどれですか。', questionJa: 'AI導入のROIを考えるときに含めるべきものはどれですか。', options: ['効果だけでなくデータ整備・運用・監視コストも考える', 'モデル利用料だけを見る', '見た目の新しさだけで判断する', '効果測定をしない'], optionsJa: ['効果だけでなくデータ整備・運用・監視コストも考える', 'モデル利用料だけを見る', '見た目の新しさだけで判断する', '効果測定をしない'], answerIndex: 0, explanationVi: 'AIの費用には開発、データ、運用、監視、リスク対応も含まれます。', explanationJa: 'AIの費用には開発、データ、運用、監視、リスク対応も含まれます。' }),
  j({ id: 'jexam-029', domain: 'business', nodeId: 'ai-monitoring', difficulty: 'standard', questionVi: 'AIモデルを導入した後に必要なことはどれですか。', questionJa: 'AIモデルを導入した後に必要なことはどれですか。', options: ['性能やデータ変化を継続的に監視する', '二度と確認しない', 'テストデータを公開する', 'ログをすべて削除する'], optionsJa: ['性能やデータ変化を継続的に監視する', '二度と確認しない', 'テストデータを公開する', 'ログをすべて削除する'], answerIndex: 0, explanationVi: 'データや環境は変わるため、導入後の監視が必要です。', explanationJa: 'データや環境は変わるため、導入後の監視が必要です。' }),
  j({ id: 'jexam-030', domain: 'ai', nodeId: 'model-drift', difficulty: 'hard', questionVi: 'モデルドリフトの説明として適切なものはどれですか。', questionJa: 'モデルドリフトの説明として適切なものはどれですか。', options: ['時間とともにデータの傾向が変わり、モデル性能が低下すること', 'モデルが必ず高速化すること', '著作権がなくなること', 'データが自動で匿名化されること'], optionsJa: ['時間とともにデータの傾向が変わり、モデル性能が低下すること', 'モデルが必ず高速化すること', '著作権がなくなること', 'データが自動で匿名化されること'], answerIndex: 0, explanationVi: '現実のデータ分布が変化すると、以前のモデルが合わなくなることがあります。', explanationJa: '現実のデータ分布が変化すると、以前のモデルが合わなくなることがあります。' })
];
