import type { ConceptComparison } from '../../features/knowledge-graph/data/conceptComparisons';

export const aiPassportComparisons: ConceptComparison[] = [
  {"id": "ai-ml-dl", "title": "AI vs 機械学習 vs 深層学習", "leftNodeId": "ai-definition", "rightNodeId": "deep-learning-ai", "leftLabel": "AI = khái niệm lớn", "rightLabel": "DL = một phần của ML", "differenceVi": "AI là khái niệm bao trùm. ML là cách AI học từ dữ liệu. DL là ML dùng neural network nhiều lớp.", "differenceJa": "AIは大きな概念、機械学習はデータから学ぶ方法、深層学習は多層ニューラルネットを使う機械学習です。", "examTipVi": "Đề hay hỏi quan hệ bao hàm: AI ⊃ ML ⊃ DL.", "examTipJa": "包含関係「AI ⊃ 機械学習 ⊃ 深層学習」を覚えます。"},
  {"id": "supervised-unsupervised", "title": "教師あり vs 教師なし", "leftNodeId": "supervised-ai", "rightNodeId": "unsupervised-ai", "leftLabel": "Có nhãn đúng", "rightLabel": "Không có nhãn đúng", "differenceVi": "Supervised dùng dữ liệu có label đúng để phân loại/hồi quy. Unsupervised tìm cấu trúc/nhóm trong dữ liệu không label.", "differenceJa": "教師ありは正解ラベル付き、教師なしはラベルなしデータから構造を見つけます。", "examTipVi": "Có đáp án đúng = supervised. Tìm nhóm = unsupervised.", "examTipJa": "正解ラベルあり=教師あり、グループ発見=教師なし。"},
  {"id": "regression-classification", "title": "回帰 vs 分類", "leftNodeId": "regression-ai", "rightNodeId": "classification-ai", "leftLabel": "Dự đoán số", "rightLabel": "Chọn nhóm/lớp", "differenceVi": "Regression dự đoán giá trị số liên tục. Classification dự đoán nhãn/lớp như spam/không spam.", "differenceJa": "回帰は連続値予測、分類はカテゴリ判定です。", "examTipVi": "Giá nhà/điểm số = regression. Spam/không spam = classification.", "examTipJa": "価格・点数=回帰、スパム判定=分類。"},
  {"id": "cnn-rnn-transformer", "title": "CNN vs RNN vs Transformer", "leftNodeId": "cnn-ai", "rightNodeId": "transformer-ai", "leftLabel": "CNN = ảnh, RNN = chuỗi", "rightLabel": "Transformer = attention/LLM", "differenceVi": "CNN mạnh về ảnh, RNN dùng cho chuỗi/thời gian, Transformer dùng attention và là nền tảng LLM.", "differenceJa": "CNNは画像、RNNは系列、TransformerはAttentionを使いLLMの基盤です。", "examTipVi": "CNN=画像、RNN=時系列、Transformer=LLMと覚える.", "examTipJa": "CNN=画像、RNN=時系列、Transformer=LLM。"},
  {"id": "hallucination-bias", "title": "Hallucination vs Bias", "leftNodeId": "hallucination", "rightNodeId": "bias-fairness", "leftLabel": "Thông tin bịa/sai", "rightLabel": "Thiên lệch/không công bằng", "differenceVi": "Hallucination là AI tạo nội dung sai nhưng nghe hợp lý. Bias là dữ liệu/model thiên lệch gây kết quả không công bằng.", "differenceJa": "ハルシネーションはもっともらしい誤情報、バイアスは偏りによる不公平です。", "examTipVi": "Sai thông tin = hallucination. Không công bằng = bias.", "examTipJa": "誤情報=ハルシネーション、不公平=バイアス。"},
  {"id": "privacy-copyright", "title": "Privacy vs Copyright", "leftNodeId": "personal-information-ai", "rightNodeId": "copyright-ai", "leftLabel": "Bảo vệ dữ liệu cá nhân", "rightLabel": "Bảo vệ tác phẩm", "differenceVi": "Privacy liên quan cá nhân và dữ liệu riêng tư. Copyright liên quan quyền tác giả của tác phẩm, dữ liệu học và output AI.", "differenceJa": "プライバシーは個人情報、著作権は著作物や生成物の権利です。", "examTipVi": "Tên/địa chỉ/lịch sử = privacy. Ảnh/văn bản/nhạc/code = copyright.", "examTipJa": "氏名・住所=個人情報、文章・画像・音楽=著作権。"},
];
