import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';

export const aiPassportV52BusinessLessons: LessonContent[] = [
  {
    nodeId: 'ai-project-flow',
    shortDefinitionVi: 'Quy trình dự án AI là chuỗi bước từ xác định vấn đề, thu thập dữ liệu, thử mô hình, đánh giá, triển khai, giám sát và cải thiện liên tục.',
    shortDefinitionJa: 'AIプロジェクトの流れは、課題設定、データ収集、モデル試作、評価、導入、監視、改善を進める一連の工程です。',
    whyImportantVi: 'AI Passport nhấn mạnh AI không bắt đầu từ model mà bắt đầu từ mục tiêu kinh doanh và dữ liệu. Dự án AI cần kiểm chứng lặp lại vì kết quả phụ thuộc dữ liệu thực tế.',
    whyImportantJa: 'AIはモデルからではなく、業務目的とデータから始まります。実データに依存するため、AIプロジェクトは反復的な検証が必要です。',
    examPatternsVi: ['Sắp xếp đúng thứ tự: business problem → data → PoC → evaluation → deployment → monitoring.', 'Hỏi vai trò PoC: kiểm chứng khả thi trước khi triển khai lớn.', 'Hỏi vì sao cần monitoring sau release: dữ liệu thay đổi, drift, lỗi vận hành.'],
    examPatternsJa: ['業務課題 → データ → PoC → 評価 → 導入 → 監視の順序。', 'PoCの役割：本格導入前に実現性を確認する。', 'リリース後監視の理由：データ変化、ドリフト、運用エラー。'],
    commonMistakesVi: ['Bắt đầu bằng chọn model nổi tiếng mà chưa rõ vấn đề cần giải quyết.', 'Xem PoC pass là có thể triển khai ngay không cần đánh giá rủi ro.', 'Quên kế hoạch vận hành, cập nhật dữ liệu và trách nhiệm khi AI sai.'],
    commonMistakesJa: ['課題を明確にせず有名モデル選びから始める。', 'PoC成功だけでリスク評価なしに本番導入する。', '運用、データ更新、AI誤り時の責任を忘れる。'],
    memoryTipVi: 'Mẹo nhớ: AI project = Problem → Data → Model → Check → Run → Monitor.',
    memoryTipJa: '覚え方：AIプロジェクト = 課題 → データ → モデル → 評価 → 運用 → 監視。',
  },
  {
    nodeId: 'human-in-the-loop',
    shortDefinitionVi: 'Human-in-the-loop là thiết kế để con người tham gia kiểm tra, phê duyệt hoặc sửa kết quả AI, nhất là khi quyết định có rủi ro cao.',
    shortDefinitionJa: 'Human-in-the-loopは、AIの結果を人間が確認・承認・修正する仕組みです。特に高リスク判断で重要です。',
    whyImportantVi: 'AI Passport rất coi trọng trách nhiệm, an toàn và đạo đức. AI hỗ trợ ra quyết định, nhưng con người vẫn cần chịu trách nhiệm trong các tình huống quan trọng.',
    whyImportantJa: 'AIパスポートでは責任、安全、倫理が重視されます。AIは意思決定を支援しますが、重要判断では人間の責任が必要です。',
    examPatternsVi: ['Chọn human review cho y tế, tuyển dụng, tín dụng, pháp lý, nội dung nhạy cảm.', 'Hỏi cách giảm rủi ro hallucination/bias: thêm bước kiểm tra con người.', 'Phân biệt automation hoàn toàn với decision support có phê duyệt.'],
    examPatternsJa: ['医療、採用、与信、法務、センシティブ内容で人間確認を選ぶ。', 'ハルシネーションやバイアス低減策として人間確認を入れる。', '完全自動化と、人間承認付き意思決定支援の違い。'],
    commonMistakesVi: ['Cho AI tự động quyết định việc ảnh hưởng quyền lợi con người mà không có cơ chế khiếu nại.', 'Đặt human review hình thức nhưng người kiểm tra không có đủ thông tin.', 'Không ghi log quyết định nên khó truy vết khi có sự cố.'],
    commonMistakesJa: ['人の権利に関わる判断をAIに完全自動化させ、異議申立て手段を用意しない。', '形式的な人間確認で、確認者に十分な情報がない。', 'ログを残さず、問題発生時に追跡できない。'],
    memoryTipVi: 'Mẹo nhớ: rủi ro càng cao → càng cần người kiểm tra trước khi hành động.',
    memoryTipJa: '覚え方：リスクが高いほど、人間確認を前に置く。',
  },
  {
    nodeId: 'ai-stakeholder',
    shortDefinitionVi: 'Stakeholder trong dự án AI là các bên bị ảnh hưởng hoặc tham gia vào hệ thống, gồm người dùng, khách hàng, business owner, data team, pháp chế, bảo mật và người vận hành.',
    shortDefinitionJa: 'AIプロジェクトのステークホルダは、利用者、顧客、業務責任者、データ担当、法務、セキュリティ、運用担当など、関係・影響を受ける人々です。',
    whyImportantVi: 'AI không chỉ là việc của kỹ sư. Đề thi hay hỏi cần phối hợp ai để đảm bảo mục tiêu, dữ liệu, pháp luật, UX, vận hành và trách nhiệm.',
    whyImportantJa: 'AIはエンジニアだけの仕事ではありません。目的、データ、法務、UX、運用、責任のため関係者連携が問われます。',
    examPatternsVi: ['Chọn stakeholder cần tham gia khi xử lý dữ liệu cá nhân: pháp chế/bảo mật/business owner.', 'Hỏi vai trò người dùng cuối trong kiểm chứng usability và phản hồi.', 'Hỏi vì sao cần thống nhất KPI giữa business và data team.'],
    examPatternsJa: ['個人情報を扱う際に法務・セキュリティ・業務責任者を巻き込む。', 'ユーザーが使いやすさやフィードバック確認に関わる理由。', '業務部門とデータ部門でKPIを合わせる必要性。'],
    commonMistakesVi: ['Chỉ hỏi data scientist mà bỏ qua người dùng thực tế.', 'Không có chủ sở hữu nghiệp vụ nên model tối ưu metric kỹ thuật nhưng không tạo giá trị.', 'Bỏ qua pháp chế khi dùng dữ liệu nhạy cảm.'],
    commonMistakesJa: ['データサイエンティストだけで進め、実際の利用者を巻き込まない。', '業務責任者が不在で、技術指標は良いが価値が出ない。', 'センシティブデータ利用で法務確認を省く。'],
    memoryTipVi: 'Mẹo nhớ: AI stakeholder = ai dùng, ai chịu ảnh hưởng, ai chịu trách nhiệm, ai vận hành.',
    memoryTipJa: '覚え方：誰が使う、誰が影響を受ける、誰が責任を持つ、誰が運用する。',
  },
  {
    nodeId: 'ai-audit-log',
    shortDefinitionVi: 'Audit log AI là bản ghi lại dữ liệu, prompt, phiên bản mô hình, kết quả, người thao tác và thời điểm để có thể truy vết khi cần.',
    shortDefinitionJa: 'AI監査ログは、データ、プロンプト、モデル版、出力、操作ユーザー、時刻などを記録し、後から追跡できるようにするものです。',
    whyImportantVi: 'Khi AI sai hoặc gây rủi ro, doanh nghiệp cần biết chuyện gì đã xảy ra. Audit log hỗ trợ giải thích, điều tra, tuân thủ và cải thiện hệ thống.',
    whyImportantJa: 'AIが誤った場合、何が起きたかを確認できる必要があります。監査ログは説明、調査、コンプライアンス、改善に役立ちます。',
    examPatternsVi: ['Chọn audit log để truy vết quyết định AI trong môi trường doanh nghiệp.', 'Hỏi nên ghi gì: input, output, model version, người dùng, thời gian, phê duyệt.', 'Hỏi liên hệ với governance, accountability và incident response.'],
    examPatternsJa: ['企業利用でAI判断を追跡するため監査ログを選ぶ。', '記録項目：入力、出力、モデル版、ユーザー、時刻、承認。', 'ガバナンス、説明責任、インシデント対応との関係。'],
    commonMistakesVi: ['Chỉ lưu output mà không lưu model version/prompt nên không tái hiện được lỗi.', 'Ghi log chứa dữ liệu cá nhân nhưng không kiểm soát quyền truy cập.', 'Không đặt thời hạn lưu trữ và chính sách xóa log.'],
    commonMistakesJa: ['出力だけ保存し、モデル版やプロンプトを残さず再現できない。', '個人情報入りログのアクセス制御をしない。', '保存期間や削除ルールを決めない。'],
    memoryTipVi: 'Mẹo nhớ: Audit log = hộp đen của AI. Có sự cố thì mở ra xem lại đường đi.',
    memoryTipJa: '覚え方：監査ログ = AIのブラックボックス記録。問題時に経緯を見る。',
  },
  {
    nodeId: 'medical-ai',
    shortDefinitionVi: 'AI y tế là ứng dụng AI trong chẩn đoán hỗ trợ, phân tích ảnh y khoa, dự đoán rủi ro bệnh, tối ưu lịch khám và hỗ trợ bác sĩ ra quyết định.',
    shortDefinitionJa: '医療AIは、診断支援、医用画像解析、疾病リスク予測、診療予約最適化、医師の意思決定支援に使われるAIです。',
    whyImportantVi: 'Đây là use case rủi ro cao. AI Passport thường hỏi không nên để AI thay bác sĩ hoàn toàn; cần kiểm chứng, bảo mật dữ liệu bệnh nhân và trách nhiệm chuyên môn.',
    whyImportantJa: '医療は高リスク領域です。AIに完全代替させず、検証、患者データ保護、専門家責任が必要です。',
    examPatternsVi: ['Chọn AI hỗ trợ đọc X-quang/MRI nhưng bác sĩ xác nhận cuối.', 'Hỏi biện pháp bảo vệ dữ liệu y tế cá nhân.', 'Hỏi rủi ro bias nếu dữ liệu huấn luyện không đại diện cho nhóm bệnh nhân.'],
    examPatternsJa: ['X線/MRI読影支援でAIを使い、最終確認は医師が行う。', '医療個人情報の保護策。', '訓練データが患者集団を代表しない場合のバイアスリスク。'],
    commonMistakesVi: ['Viết “AI chẩn đoán thay bác sĩ” trong mọi trường hợp.', 'Bỏ qua giải thích kết quả cho bác sĩ/người bệnh.', 'Dùng dữ liệu bệnh nhân mà không có quản lý mục đích và quyền truy cập.'],
    commonMistakesJa: ['どんな場合もAIが医師に代わって診断すると考える。', '医師や患者への説明可能性を無視する。', '患者データの目的管理・アクセス制御をしない。'],
    memoryTipVi: 'Mẹo nhớ: Medical AI = hỗ trợ bác sĩ, không phải tự ý quyết định thay bác sĩ.',
    memoryTipJa: '覚え方：医療AI = 医師を支援する。勝手に医師を置き換えない。',
  },
  {
    nodeId: 'education-ai',
    shortDefinitionVi: 'AI giáo dục là ứng dụng AI để cá nhân hóa học tập, gợi ý bài ôn, chấm bài hỗ trợ, tạo quiz, phát hiện điểm yếu và hỗ trợ giáo viên.',
    shortDefinitionJa: '教育AIは、学習の個別最適化、復習提案、採点支援、クイズ生成、弱点分析、教師支援に使われるAIです。',
    whyImportantVi: 'Đề thi thường hỏi lợi ích và rủi ro: AI giúp học đúng trình độ nhưng cần tránh thiên vị, bảo vệ dữ liệu học sinh và không thay hoàn toàn giáo viên.',
    whyImportantJa: '利点とリスクが問われます。学習最適化に役立つ一方、バイアス、児童生徒データ保護、教師の役割が重要です。',
    examPatternsVi: ['Chọn adaptive learning để đề xuất nội dung theo năng lực người học.', 'Hỏi rủi ro khi chấm tự động: cần tiêu chí rõ và kiểm tra con người.', 'Hỏi bảo vệ dữ liệu trẻ em/học sinh.'],
    examPatternsJa: ['学習者の理解度に合わせるアダプティブラーニング。', '自動採点のリスク：基準明確化と人間確認。', '児童生徒データの保護。'],
    commonMistakesVi: ['Cho AI quyết định năng lực học sinh mà không có giáo viên xem lại.', 'Dùng dữ liệu học tập cho mục đích khác mà không thông báo.', 'Tạo nội dung học nhưng không kiểm tra độ chính xác.'],
    commonMistakesJa: ['AIだけで学習者能力を決め、教師確認をしない。', '学習データを別目的に使う。', 'AI生成教材の正確性を確認しない。'],
    memoryTipVi: 'Mẹo nhớ: Education AI = cá nhân hóa + hỗ trợ giáo viên + bảo vệ dữ liệu học sinh.',
    memoryTipJa: '覚え方：教育AI = 個別最適化 + 教師支援 + 学習者データ保護。',
  },
  {
    nodeId: 'finance-ai',
    shortDefinitionVi: 'AI tài chính là dùng AI cho phát hiện gian lận, chấm điểm tín dụng, dự báo rủi ro, tư vấn đầu tư hỗ trợ và tự động hóa xử lý hồ sơ.',
    shortDefinitionJa: '金融AIは、不正検知、信用スコアリング、リスク予測、投資助言支援、書類処理自動化などに使われます。',
    whyImportantVi: 'Finance là lĩnh vực nhạy cảm vì ảnh hưởng tiền và quyền lợi khách hàng. Đề thường hỏi fairness, explainability, bảo mật và human review.',
    whyImportantJa: '金融は金銭や顧客権利に影響するため慎重さが必要です。公平性、説明可能性、セキュリティ、人間確認が問われます。',
    examPatternsVi: ['Phát hiện giao dịch bất thường bằng anomaly/fraud detection.', 'Chấm điểm tín dụng cần giải thích và tránh phân biệt đối xử.', 'Bảo vệ dữ liệu tài chính và tuân thủ quy định.'],
    examPatternsJa: ['異常検知・不正検知で不審取引を見つける。', '信用スコアリングでは説明可能性と差別防止が必要。', '金融データ保護と規制遵守。'],
    commonMistakesVi: ['Tự động từ chối khoản vay chỉ theo AI mà không có giải thích/khiếu nại.', 'Dùng biến proxy gây bias, ví dụ khu vực sống thay cho nhóm nhạy cảm.', 'Không giám sát model drift theo thời gian.'],
    commonMistakesJa: ['AIだけで融資拒否し、説明や異議申立てを用意しない。', '居住地域など代理変数で差別的影響を出す。', '時間経過によるモデルドリフトを監視しない。'],
    memoryTipVi: 'Mẹo nhớ: Finance AI = hiệu quả cao nhưng phải giải thích, công bằng và kiểm soát rủi ro.',
    memoryTipJa: '覚え方：金融AI = 効率化できるが、説明・公平性・リスク管理が必須。',
  },
  {
    nodeId: 'manufacturing-ai',
    shortDefinitionVi: 'AI trong sản xuất dùng dữ liệu máy móc, cảm biến và hình ảnh để kiểm tra lỗi, dự đoán bảo trì, tối ưu dây chuyền và giảm lãng phí.',
    shortDefinitionJa: '製造AIは、機械・センサ・画像データを使い、外観検査、予知保全、ライン最適化、廃棄削減に活用されます。',
    whyImportantVi: 'Đây là use case rất dễ ra thi vì liên quan IoT, edge AI, computer vision và predictive maintenance. Cần hiểu cả lợi ích và điều kiện dữ liệu.',
    whyImportantJa: 'IoT、エッジAI、コンピュータビジョン、予知保全と関連し、試験で出やすいユースケースです。',
    examPatternsVi: ['Chọn computer vision/CNN cho kiểm tra ngoại quan sản phẩm.', 'Chọn predictive maintenance khi dự đoán hỏng máy từ sensor.', 'Hỏi lợi ích edge AI: xử lý gần thiết bị, giảm độ trễ, vẫn hoạt động khi mạng yếu.'],
    examPatternsJa: ['製品外観検査でコンピュータビジョン/CNNを選ぶ。', 'センサデータから故障予兆を見つける予知保全。', 'エッジAIの利点：低遅延、現場処理、通信不安定時の動作。'],
    commonMistakesVi: ['Chỉ nhìn accuracy mà không tính chi phí bỏ sót lỗi sản phẩm.', 'Không chuẩn hóa dữ liệu cảm biến từ nhiều máy.', 'Đưa mọi dữ liệu lên cloud dù cần phản ứng thời gian thực tại nhà máy.'],
    commonMistakesJa: ['正解率だけ見て、不良見逃しコストを考えない。', '複数機械のセンサデータ形式を整えない。', 'リアルタイム性が必要なのにすべてクラウド処理にする。'],
    memoryTipVi: 'Mẹo nhớ: Manufacturing AI = nhìn lỗi + nghe sensor + dự đoán hỏng + tối ưu dây chuyền.',
    memoryTipJa: '覚え方：製造AI = 欠陥を見る、センサを読む、故障を予測、ラインを最適化。',
  },
  {
    nodeId: 'marketing-ai',
    shortDefinitionVi: 'AI marketing dùng AI để phân khúc khách hàng, gợi ý sản phẩm, cá nhân hóa nội dung, dự đoán rời bỏ và tối ưu chiến dịch quảng cáo.',
    shortDefinitionJa: 'マーケティングAIは、顧客セグメント、商品推薦、コンテンツ個別化、解約予測、広告最適化に使われます。',
    whyImportantVi: 'AI Passport hay hỏi business value của AI. Marketing là ví dụ dễ hiểu nhưng cần chú ý privacy, consent và tránh cá nhân hóa quá mức gây phản cảm.',
    whyImportantJa: 'AIの業務価値を問う問題で出やすい領域です。一方でプライバシー、同意、過度な個別化への配慮が必要です。',
    examPatternsVi: ['Chọn recommendation system cho gợi ý sản phẩm/nội dung.', 'Chọn customer segmentation hoặc churn prediction cho chiến dịch giữ chân.', 'Hỏi rủi ro dùng dữ liệu cá nhân không đúng mục đích.'],
    examPatternsJa: ['商品・コンテンツ推薦でレコメンドシステムを選ぶ。', '顧客セグメントや解約予測で施策を最適化。', '個人データの目的外利用リスク。'],
    commonMistakesVi: ['Gửi nội dung cá nhân hóa mà không tôn trọng opt-out.', 'Tối ưu click nhưng làm giảm trải nghiệm hoặc gây spam.', 'Nhầm correlation với nguyên nhân khi phân tích chiến dịch.'],
    commonMistakesJa: ['オプトアウトを尊重せず個別化メッセージを送る。', 'クリックだけ最適化し、体験悪化やスパム化を招く。', '施策分析で相関と因果を混同する。'],
    memoryTipVi: 'Mẹo nhớ: Marketing AI = đúng khách hàng, đúng nội dung, đúng thời điểm, nhưng phải đúng quyền riêng tư.',
    memoryTipJa: '覚え方：マーケAI = 適切な顧客・内容・タイミング。ただしプライバシーも適切に。',
  },
  {
    nodeId: 'public-sector-ai',
    shortDefinitionVi: 'AI hành chính/công là dùng AI trong dịch vụ công như chatbot hướng dẫn thủ tục, phân loại hồ sơ, dự báo nhu cầu, tối ưu giao thông hoặc hỗ trợ phòng chống thiên tai.',
    shortDefinitionJa: '公共分野のAIは、行政手続き案内チャットボット、書類分類、需要予測、交通最適化、防災支援などに使われます。',
    whyImportantVi: 'Lĩnh vực công ảnh hưởng nhiều người nên cần minh bạch, công bằng, accessibility và giải thích. Đề hay hỏi không được để AI gây phân biệt đối xử hoặc loại trừ người yếu thế.',
    whyImportantJa: '公共分野は多くの人に影響するため、透明性、公平性、アクセシビリティ、説明が重要です。差別や排除を避ける必要があります。',
    examPatternsVi: ['Chọn AI chatbot để giảm tải hỏi đáp thủ tục nhưng vẫn có kênh con người.', 'Hỏi fairness khi AI hỗ trợ phân bổ phúc lợi/dịch vụ.', 'Hỏi quản lý dữ liệu công dân và minh bạch thuật toán.'],
    examPatternsJa: ['手続き案内チャットボットで問い合わせ負荷を下げ、人間窓口も残す。', '福祉・サービス配分支援で公平性を確認。', '市民データ管理とアルゴリズム透明性。'],
    commonMistakesVi: ['Chỉ tối ưu hiệu quả hành chính mà bỏ qua người không dùng được công nghệ.', 'Tự động từ chối dịch vụ công không có giải thích/khiếu nại.', 'Dùng dữ liệu công dân vượt mục đích ban đầu.'],
    commonMistakesJa: ['行政効率だけを重視し、デジタルに弱い人を置き去りにする。', '説明や異議申立てなしに公共サービスを自動拒否する。', '市民データを当初目的外に利用する。'],
    memoryTipVi: 'Mẹo nhớ: Public AI = tiện lợi cho dân, nhưng phải công bằng, minh bạch và có kênh hỗ trợ người thật.',
    memoryTipJa: '覚え方：公共AI = 便利にするが、公平・透明・人間窓口が必要。',
  }
];
