import type { KnowledgeEdgeData, KnowledgeNodeData } from '../../features/knowledge-graph/types';

type NodeSeed = Omit<KnowledgeNodeData, 'examples' | 'keywords' | 'prerequisites' | 'related'> & {
  examples?: string[];
  keywords?: string[];
  prerequisites?: string[];
  related?: string[];
};

const node = (seed: NodeSeed): KnowledgeNodeData => ({
  examples: [],
  keywords: [],
  prerequisites: [],
  related: [],
  ...seed,
});

export const aiPassportNodes: KnowledgeNodeData[] = [
  node({ id: 'ai-passport', labelJa: 'AIパスポート', labelVi: 'AI Passport', labelEn: 'AI Passport', category: 'root', level: 'root', importance: 'high', summaryVi: 'Kỳ thi nền tảng để hiểu AI, dữ liệu, machine learning, generative AI, đạo đức, pháp luật và ứng dụng AI trong kinh doanh.', summaryJa: 'AI、データ、機械学習、生成AI、倫理、法務、ビジネス活用を広く学ぶ基礎試験です。', examPointVi: 'Nhìn tổng quan theo 4 trục: AI basics → Data/ML → Generative AI → Ethics/Law/Business.', examPointJa: 'AI基礎、データ・機械学習、生成AI、倫理・法務・ビジネス活用の流れで押さえます。', keywords: ['AIパスポート', '生成AI', '機械学習', '倫理'] }),
  node({ id: 'ai-basics', labelJa: 'AI基礎', labelVi: 'Nền tảng AI', labelEn: 'AI Basics', category: 'ai', level: 'major', importance: 'high', summaryVi: 'Các khái niệm gốc như AI, machine learning, deep learning, suy luận và nhận diện mẫu.', summaryJa: 'AI、機械学習、深層学習、推論、パターン認識などの基本概念です。', examPointVi: 'Hay hỏi quan hệ AI > ML > DL và khác biệt giữa học máy với lập trình truyền thống.', examPointJa: 'AI、機械学習、深層学習の包含関係と、従来のプログラミングとの違いが重要です。', keywords: ['AI', '機械学習', '深層学習'] }),
  node({ id: 'data-ml', labelJa: 'データと機械学習', labelVi: 'Dữ liệu & Machine Learning', labelEn: 'Data and Machine Learning', category: 'database', level: 'major', importance: 'high', summaryVi: 'Dữ liệu, tiền xử lý, chia train/test, mô hình học máy và đánh giá kết quả.', summaryJa: 'データ、前処理、訓練・テスト分割、モデル、評価を扱います。', examPointVi: 'Nhớ dữ liệu quyết định chất lượng AI; không dùng test data để training.', examPointJa: 'AIの品質はデータに大きく依存します。テストデータを学習に使わないことが重要です。', keywords: ['データ', '前処理', '学習データ', '評価'] }),
  node({ id: 'generative-ai', labelJa: '生成AI', labelVi: 'AI tạo sinh', labelEn: 'Generative AI', category: 'ai', level: 'major', importance: 'high', summaryVi: 'AI tạo văn bản, ảnh, âm thanh, video hoặc code dựa trên dữ liệu đã học.', summaryJa: '学習したデータをもとに、文章・画像・音声・動画・コードなどを生成するAIです。', examPointVi: 'Hay hỏi LLM, prompt, hallucination, deepfake, copyright và rủi ro sử dụng.', examPointJa: 'LLM、プロンプト、ハルシネーション、ディープフェイク、著作権、利用リスクが頻出です。', keywords: ['生成AI', 'LLM', 'プロンプト', 'ハルシネーション'] }),
  node({ id: 'ai-ethics-law', labelJa: 'AI倫理・法務', labelVi: 'Đạo đức & pháp luật AI', labelEn: 'AI Ethics and Law', category: 'security', level: 'major', importance: 'high', summaryVi: 'Các rủi ro về quyền riêng tư, bias, công bằng, trách nhiệm, bản quyền và bảo mật khi dùng AI.', summaryJa: 'AI利用におけるプライバシー、バイアス、公平性、責任、著作権、セキュリティの考え方です。', examPointVi: 'Câu hỏi thường là “trường hợp này có rủi ro gì?” và “biện pháp phù hợp là gì?”.', examPointJa: '「どのようなリスクか」「適切な対応は何か」を問う問題が多いです。', keywords: ['倫理', '個人情報', '著作権', 'バイアス'] }),
  node({ id: 'business-ai', labelJa: 'AIビジネス活用', labelVi: 'Ứng dụng AI trong kinh doanh', labelEn: 'AI Business Use', category: 'business', level: 'major', importance: 'high', summaryVi: 'Cách doanh nghiệp dùng AI để cải thiện nghiệp vụ, tự động hóa, phân tích dữ liệu và tạo giá trị.', summaryJa: '業務改善、自動化、データ分析、価値創出にAIを活用する考え方です。', examPointVi: 'Nhớ AI phải gắn với mục tiêu, dữ liệu, vận hành, rủi ro và đánh giá hiệu quả.', examPointJa: 'AI活用は目的、データ、運用、リスク、効果測定とセットで考えます。', keywords: ['DX', '業務改善', '自動化', 'ROI'] }),

  node({ id: 'ai-definition', labelJa: '人工知能', labelVi: 'Trí tuệ nhân tạo', labelEn: 'Artificial Intelligence', reading: 'じんこうちのう', category: 'ai', level: 'topic', importance: 'high', summaryVi: 'AI là kỹ thuật để máy tính thực hiện các tác vụ cần trí tuệ như nhận diện, dự đoán, suy luận và tạo nội dung.', summaryJa: '認識、予測、推論、生成など知的な処理をコンピュータで行う技術です。', examPointVi: 'AI là khái niệm lớn, bao gồm machine learning và deep learning.', examPointJa: 'AIは大きな概念で、その中に機械学習や深層学習が含まれます。', keywords: ['人工知能', '認識', '予測', '推論'] }),
  node({ id: 'machine-learning-ai', labelJa: '機械学習', labelVi: 'Machine Learning', labelEn: 'Machine Learning', reading: 'きかいがくしゅう', category: 'ai', level: 'topic', importance: 'high', summaryVi: 'Máy học quy luật từ dữ liệu để phân loại, dự đoán hoặc phát hiện mẫu.', summaryJa: 'データから規則性を学び、分類・予測・パターン発見を行う技術です。', examPointVi: 'Nhớ supervised, unsupervised, reinforcement learning và overfitting.', examPointJa: '教師あり、教師なし、強化学習、過学習を区別します。', keywords: ['教師あり学習', '教師なし学習', '強化学習'] }),
  node({ id: 'deep-learning-ai', labelJa: '深層学習', labelVi: 'Deep Learning', labelEn: 'Deep Learning', reading: 'しんそうがくしゅう', category: 'ai', level: 'topic', importance: 'high', summaryVi: 'Deep learning dùng neural network nhiều lớp để học đặc trưng phức tạp từ dữ liệu.', summaryJa: '多層ニューラルネットワークで複雑な特徴を学習する方法です。', examPointVi: 'CNN, RNN, Transformer đều thuộc deep learning.', examPointJa: 'CNN、RNN、Transformerは深層学習の代表例です。', keywords: ['ニューラルネットワーク', 'CNN', 'RNN', 'Transformer'] }),
  node({ id: 'supervised-ai', labelJa: '教師あり学習', labelVi: 'Học có giám sát', labelEn: 'Supervised Learning', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Học từ dữ liệu có nhãn/đáp án đúng, dùng cho phân loại hoặc hồi quy.', summaryJa: '正解ラベル付きデータから学習し、分類や回帰に使われます。', examPointVi: 'Classification và regression là hai ví dụ tiêu biểu.', examPointJa: '分類と回帰が代表例です。', keywords: ['ラベル', '分類', '回帰'] }),
  node({ id: 'unsupervised-ai', labelJa: '教師なし学習', labelVi: 'Học không giám sát', labelEn: 'Unsupervised Learning', category: 'ai', level: 'detail', importance: 'medium', summaryVi: 'Học từ dữ liệu không có nhãn để tìm nhóm, cấu trúc hoặc mẫu ẩn.', summaryJa: '正解ラベルのないデータからグループや構造を見つけます。', examPointVi: 'Clustering là ví dụ hay gặp.', examPointJa: 'クラスタリングが代表例です。', keywords: ['クラスタリング', 'ラベルなし'] }),
  node({ id: 'reinforcement-learning', labelJa: '強化学習', labelVi: 'Học tăng cường', labelEn: 'Reinforcement Learning', category: 'ai', level: 'detail', importance: 'medium', summaryVi: 'Agent học bằng thử-sai trong môi trường để tối đa hóa phần thưởng.', summaryJa: 'エージェントが環境で試行錯誤し、報酬を最大化するように学習します。', examPointVi: 'Nhớ từ khóa agent, environment, reward.', examPointJa: 'エージェント、環境、報酬がキーワードです。', keywords: ['エージェント', '環境', '報酬'] }),
  node({ id: 'linear-regression-ai', labelJa: '線形回帰', labelVi: 'Hồi quy tuyến tính', labelEn: 'Linear Regression', reading: 'せんけいかいき', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Dự đoán giá trị số bằng quan hệ gần giống đường thẳng.', summaryJa: '直線的な関係を用いて数値を予測する方法です。', examPointVi: 'Dự đoán số liên tục, khác logistic regression dùng cho phân loại.', examPointJa: '連続値予測に使います。ロジスティック回帰は分類で使われます。', keywords: ['回帰', '数値予測'] }),
  node({ id: 'logistic-regression-ai', labelJa: 'ロジスティック回帰', labelVi: 'Hồi quy logistic', labelEn: 'Logistic Regression', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Dự đoán xác suất thuộc một lớp, thường dùng cho phân loại nhị phân.', summaryJa: 'あるクラスに属する確率を扱い、二値分類によく使われます。', examPointVi: 'Tên là regression nhưng hay dùng cho classification.', examPointJa: '「回帰」という名前ですが分類でよく使われます。', keywords: ['確率', '分類'] }),
  node({ id: 'decision-tree-ai', labelJa: '決定木', labelVi: 'Cây quyết định', labelEn: 'Decision Tree', reading: 'けっていぎ', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Phân loại/dự đoán bằng các câu hỏi dạng nhánh điều kiện.', summaryJa: '条件分岐を木構造で表して判断するモデルです。', examPointVi: 'Dễ giải thích, nhưng có thể overfit nếu cây quá sâu.', examPointJa: '説明しやすい一方、木が深いと過学習しやすいです。', keywords: ['木構造', '条件分岐', '過学習'] }),
  node({ id: 'svm-ai', labelJa: 'SVM', labelVi: 'SVM', labelEn: 'Support Vector Machine', category: 'ai', level: 'detail', importance: 'medium', summaryVi: 'Tìm ranh giới phân chia dữ liệu sao cho khoảng cách giữa các nhóm lớn nhất.', summaryJa: 'データを分ける境界を見つけ、マージンを大きくする分類手法です。', examPointVi: 'Nhớ hình ảnh “đường chia nhóm”.', examPointJa: '分類境界とマージンのイメージで覚えます。', keywords: ['分類', '境界', 'マージン'] }),
  node({ id: 'neural-network-ai', labelJa: 'ニューラルネットワーク', labelVi: 'Mạng nơ-ron', labelEn: 'Neural Network', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Mô hình gồm nhiều lớp node có trọng số để học quan hệ phi tuyến phức tạp.', summaryJa: '重みを持つ層を重ねて、複雑な非線形関係を学習するモデルです。', examPointVi: 'Là nền tảng của deep learning.', examPointJa: '深層学習の基盤です。', keywords: ['重み', '層', 'ニューロン'] }),
  node({ id: 'cnn-ai', labelJa: 'CNN', labelVi: 'CNN', labelEn: 'Convolutional Neural Network', category: 'ai', level: 'detail', importance: 'medium', summaryVi: 'Neural network mạnh về xử lý ảnh nhờ convolution.', summaryJa: '畳み込みを使い、画像認識に強いニューラルネットワークです。', examPointVi: 'CNN = hình ảnh.', examPointJa: 'CNNは画像認識に強いと覚えます。', keywords: ['画像', '畳み込み'] }),
  node({ id: 'rnn-ai', labelJa: 'RNN', labelVi: 'RNN', labelEn: 'Recurrent Neural Network', category: 'ai', level: 'detail', importance: 'medium', summaryVi: 'Neural network dùng cho dữ liệu chuỗi như văn bản, âm thanh, thời gian.', summaryJa: '文章、音声、時系列など順序を持つデータに使われます。', examPointVi: 'RNN = dữ liệu có thứ tự/thời gian.', examPointJa: 'RNNは時系列・系列データに強いと覚えます。', keywords: ['時系列', '系列データ'] }),
  node({ id: 'transformer-ai', labelJa: 'Transformer', labelVi: 'Transformer', labelEn: 'Transformer', category: 'ai', level: 'detail', importance: 'high', summaryVi: 'Kiến trúc dùng attention, nền tảng của nhiều LLM và generative AI hiện đại.', summaryJa: 'Attentionを用いるモデルで、多くのLLMや生成AIの基盤です。', examPointVi: 'Liên hệ LLM, attention, ChatGPT.', examPointJa: 'LLM、Attention、ChatGPTとの関係で理解します。', keywords: ['Attention', 'LLM', '生成AI'] }),

  node({ id: 'data-quality', labelJa: 'データ品質', labelVi: 'Chất lượng dữ liệu', labelEn: 'Data Quality', category: 'database', level: 'topic', importance: 'high', summaryVi: 'Độ chính xác, đầy đủ, nhất quán và phù hợp của dữ liệu dùng cho AI.', summaryJa: 'AIに使うデータの正確性、完全性、一貫性、適切性です。', examPointVi: 'Dữ liệu sai hoặc lệch sẽ làm AI sai; garbage in, garbage out.', examPointJa: 'データが悪いとAIの結果も悪くなります。Garbage in, garbage outです。', keywords: ['正確性', '完全性', '一貫性'] }),
  node({ id: 'data-preprocessing-ai', labelJa: '前処理', labelVi: 'Tiền xử lý dữ liệu', labelEn: 'Data Preprocessing', reading: 'ぜんしょり', category: 'database', level: 'topic', importance: 'high', summaryVi: 'Làm sạch, chuẩn hóa, xử lý thiếu dữ liệu và biến đổi dữ liệu trước khi học máy.', summaryJa: '欠損値処理、正規化、変換など、学習前にデータを整える作業です。', examPointVi: 'Thực tế ML thường tốn rất nhiều thời gian ở preprocessing.', examPointJa: '実際のMLでは前処理に多くの時間がかかります。', keywords: ['欠損値', '正規化', '外れ値'] }),
  node({ id: 'training-test-data', labelJa: '学習データ・テストデータ', labelVi: 'Train/Test data', labelEn: 'Training and Test Data', category: 'database', level: 'topic', importance: 'high', summaryVi: 'Training data dùng để học; test data dùng để đánh giá model sau khi học.', summaryJa: '学習データはモデルの学習に使い、テストデータは評価に使います。', examPointVi: 'Không dùng test data để training vì sẽ đánh giá sai.', examPointJa: 'テストデータを学習に使うと正しく評価できません。', keywords: ['学習データ', 'テストデータ', '評価'] }),
  node({ id: 'overfitting-ai', labelJa: '過学習', labelVi: 'Overfitting', labelEn: 'Overfitting', reading: 'かがくしゅう', category: 'database', level: 'topic', importance: 'high', summaryVi: 'Model khớp quá sát dữ liệu học và dự đoán kém trên dữ liệu mới.', summaryJa: '学習データに過度に適合し、未知データへの性能が悪くなる状態です。', examPointVi: 'Hay hỏi nguyên nhân: model quá phức tạp, dữ liệu ít, học quá sát training data.', examPointJa: 'モデルが複雑すぎる、データが少ない、学習データに合わせすぎる場合に起きます。', keywords: ['汎化性能', '訓練データ', '未知データ'] }),
  node({ id: 'evaluation-ai', labelJa: '評価指標', labelVi: 'Chỉ số đánh giá', labelEn: 'Evaluation Metrics', category: 'database', level: 'topic', importance: 'high', summaryVi: 'Các chỉ số như accuracy, precision, recall, F1 để đánh giá model phân loại.', summaryJa: 'Accuracy、Precision、Recall、F1などでモデルを評価します。', examPointVi: 'Nhớ precision = dự đoán positive đúng bao nhiêu; recall = tìm được positive thật bao nhiêu.', examPointJa: 'PrecisionとRecallの意味を区別します。', keywords: ['Accuracy', 'Precision', 'Recall', 'F1'] }),
  node({ id: 'bias-variance', labelJa: 'バイアス・バリアンス', labelVi: 'Bias / Variance', labelEn: 'Bias and Variance', category: 'database', level: 'detail', importance: 'medium', summaryVi: 'Bias cao dễ underfit, variance cao dễ overfit.', summaryJa: 'バイアスが高いと未学習、バリアンスが高いと過学習になりやすいです。', examPointVi: 'Dùng để hiểu vì sao model đơn giản/quá phức tạp đều có vấn đề.', examPointJa: 'モデルが単純すぎる・複雑すぎる問題を理解します。', keywords: ['未学習', '過学習', '汎化'] }),

  node({ id: 'llm', labelJa: '大規模言語モデル', labelVi: 'Mô hình ngôn ngữ lớn', labelEn: 'Large Language Model', reading: 'だいきぼげんごモデル', category: 'ai', level: 'topic', importance: 'high', summaryVi: 'Model AI học từ rất nhiều văn bản để hiểu và tạo ngôn ngữ tự nhiên.', summaryJa: '大量のテキストから学習し、自然言語を理解・生成するモデルです。', examPointVi: 'LLM là nền tảng của ChatGPT, chatbot, tóm tắt, dịch, hỗ trợ viết code.', examPointJa: 'ChatGPT、チャットボット、要約、翻訳、コード支援の基盤です。', keywords: ['LLM', '自然言語処理', 'ChatGPT'] }),
  node({ id: 'prompt-engineering', labelJa: 'プロンプトエンジニアリング', labelVi: 'Prompt engineering', labelEn: 'Prompt Engineering', category: 'ai', level: 'topic', importance: 'high', summaryVi: 'Thiết kế câu lệnh/yêu cầu để AI tạo kết quả đúng, rõ và an toàn hơn.', summaryJa: 'AIから適切な出力を得るために指示文を工夫する技術です。', examPointVi: 'Prompt tốt cần mục tiêu, bối cảnh, điều kiện, format output và ví dụ nếu cần.', examPointJa: '目的、文脈、条件、出力形式、例を明確にします。', keywords: ['プロンプト', '指示', '出力形式'] }),
  node({ id: 'hallucination', labelJa: 'ハルシネーション', labelVi: 'Hallucination', labelEn: 'Hallucination', category: 'security', level: 'topic', importance: 'high', summaryVi: 'AI tạo thông tin nghe có vẻ đúng nhưng thực ra sai hoặc không có căn cứ.', summaryJa: 'AIがもっともらしいが誤った情報を生成する現象です。', examPointVi: 'Biện pháp: kiểm chứng nguồn, không dùng AI output làm sự thật tuyệt đối.', examPointJa: '対策は、根拠確認、出典確認、人間によるレビューです。', keywords: ['誤情報', '検証', '出典'] }),
  node({ id: 'deepfake-ai', labelJa: 'ディープフェイク', labelVi: 'Deepfake', labelEn: 'Deepfake', category: 'security', level: 'topic', importance: 'high', summaryVi: 'AI tạo ảnh/video/âm thanh giả giống thật, có thể gây lừa đảo và misinformation.', summaryJa: '本物のような偽画像・動画・音声をAIで作る技術です。', examPointVi: 'Rủi ro: giả mạo, lừa đảo, danh dự, tin giả, xác thực nội dung.', examPointJa: 'なりすまし、詐欺、名誉毀損、偽情報のリスクがあります。', keywords: ['偽動画', 'なりすまし', '誤情報'] }),
  node({ id: 'rag', labelJa: 'RAG', labelVi: 'RAG', labelEn: 'Retrieval-Augmented Generation', category: 'ai', level: 'topic', importance: 'medium', summaryVi: 'Kỹ thuật cho LLM tham khảo tài liệu bên ngoài trước khi trả lời để giảm sai lệch.', summaryJa: '外部情報を検索して参照しながら生成することで、回答の信頼性を高める方法です。', examPointVi: 'RAG liên quan giảm hallucination và dùng tri thức nội bộ doanh nghiệp.', examPointJa: 'ハルシネーション低減や社内ナレッジ活用と関連します。', keywords: ['検索', '外部知識', '生成AI'] }),
  node({ id: 'multimodal-ai', labelJa: 'マルチモーダルAI', labelVi: 'AI đa phương thức', labelEn: 'Multimodal AI', category: 'ai', level: 'topic', importance: 'medium', summaryVi: 'AI xử lý nhiều loại dữ liệu như văn bản, ảnh, âm thanh, video cùng lúc.', summaryJa: 'テキスト、画像、音声、動画など複数の形式を扱うAIです。', examPointVi: 'Nhớ multi-modal = nhiều dạng input/output.', examPointJa: 'マルチモーダルは複数形式の入出力と覚えます。', keywords: ['画像', '音声', '動画', 'テキスト'] }),

  node({ id: 'personal-information-ai', labelJa: '個人情報', labelVi: 'Thông tin cá nhân', labelEn: 'Personal Information', category: 'security', level: 'topic', importance: 'high', summaryVi: 'Dữ liệu có thể xác định cá nhân như tên, địa chỉ, số điện thoại, lịch sử dùng dịch vụ.', summaryJa: '氏名、住所、電話番号、利用履歴など個人を識別できる情報です。', examPointVi: 'Không nhập thông tin cá nhân/bí mật công ty vào AI công cộng nếu chưa được phép.', examPointJa: '許可なく個人情報や機密情報を公開AIに入力しないことが重要です。', keywords: ['個人情報保護', 'プライバシー'] }),
  node({ id: 'copyright-ai', labelJa: '著作権', labelVi: 'Bản quyền', labelEn: 'Copyright', category: 'security', level: 'topic', importance: 'high', summaryVi: 'Quyền bảo vệ tác phẩm như văn bản, hình ảnh, âm nhạc, chương trình; AI output cũng cần chú ý quyền sử dụng.', summaryJa: '文章、画像、音楽、プログラムなどの著作物を保護する権利です。AI出力の利用にも注意が必要です。', examPointVi: 'Không mặc định rằng nội dung AI tạo ra luôn dùng thương mại được.', examPointJa: 'AI生成物を無条件に商用利用できるとは限りません。', keywords: ['著作物', '学習データ', '商用利用'] }),
  node({ id: 'bias-fairness', labelJa: 'バイアスと公平性', labelVi: 'Bias và công bằng', labelEn: 'Bias and Fairness', category: 'security', level: 'topic', importance: 'high', summaryVi: 'AI có thể học thiên lệch từ dữ liệu và tạo kết quả không công bằng với một nhóm người.', summaryJa: 'AIはデータの偏りを学習し、特定の集団に不公平な結果を出す可能性があります。', examPointVi: 'Biện pháp: kiểm tra dữ liệu, đánh giá fairness, human review.', examPointJa: 'データ確認、公平性評価、人間のレビューが重要です。', keywords: ['偏り', '公平性', '差別'] }),
  node({ id: 'explainable-ai', labelJa: '説明可能AI', labelVi: 'AI có thể giải thích', labelEn: 'Explainable AI', category: 'security', level: 'topic', importance: 'medium', summaryVi: 'AI có thể giải thích lý do đưa ra dự đoán/quyết định, giúp tăng tin cậy và kiểm soát.', summaryJa: 'AIの判断理由を説明できるようにする考え方です。', examPointVi: 'Quan trọng trong lĩnh vực cần trách nhiệm như y tế, tài chính, tuyển dụng.', examPointJa: '医療、金融、採用など説明責任が必要な分野で重要です。', keywords: ['説明責任', '透明性'] }),
  node({ id: 'human-in-the-loop', labelJa: 'Human in the Loop', labelVi: 'Con người trong vòng kiểm soát', labelEn: 'Human in the Loop', category: 'security', level: 'topic', importance: 'high', summaryVi: 'Con người kiểm tra, phê duyệt hoặc can thiệp vào quá trình AI để giảm rủi ro.', summaryJa: 'AIの結果を人間が確認・承認・修正する運用です。', examPointVi: 'AI không nên tự quyết định trong tình huống rủi ro cao nếu không có kiểm soát.', examPointJa: '高リスク領域では人間の確認が重要です。', keywords: ['人間の確認', '承認', 'リスク管理'] }),
  node({ id: 'ai-governance', labelJa: 'AIガバナンス', labelVi: 'Quản trị AI', labelEn: 'AI Governance', category: 'business', level: 'topic', importance: 'high', summaryVi: 'Quy tắc, quy trình, trách nhiệm và kiểm soát để AI được dùng an toàn và có trách nhiệm.', summaryJa: 'AIを安全かつ責任ある形で利用するためのルール、体制、責任、監査の仕組みです。', examPointVi: 'Gắn với policy, risk management, audit, accountability.', examPointJa: '方針、リスク管理、監査、説明責任と関連します。', keywords: ['方針', '監査', '責任'] }),

  node({ id: 'ai-usecase', labelJa: 'AI活用事例', labelVi: 'Use case AI', labelEn: 'AI Use Cases', category: 'business', level: 'topic', importance: 'high', summaryVi: 'Các ứng dụng như chatbot, dự báo nhu cầu, phát hiện gian lận, phân tích khách hàng, tự động hóa văn phòng.', summaryJa: 'チャットボット、需要予測、不正検知、顧客分析、業務自動化などの活用例です。', examPointVi: 'Câu hỏi thường hỏi use case nào phù hợp với AI nào.', examPointJa: 'どの業務にどのAI活用が適切かが問われます。', keywords: ['チャットボット', '需要予測', '不正検知'] }),
  node({ id: 'ai-project-flow', labelJa: 'AIプロジェクトの流れ', labelVi: 'Quy trình dự án AI', labelEn: 'AI Project Flow', category: 'business', level: 'topic', importance: 'high', summaryVi: 'Xác định vấn đề, thu thập dữ liệu, tiền xử lý, học model, đánh giá, triển khai, giám sát.', summaryJa: '課題設定、データ収集、前処理、学習、評価、導入、監視の流れです。', examPointVi: 'Không bắt đầu bằng model; phải xác định mục tiêu và dữ liệu trước.', examPointJa: 'いきなりモデルを作るのではなく、目的とデータを確認します。', keywords: ['課題設定', 'データ収集', '評価', '運用'] }),
  node({ id: 'ai-risk-management', labelJa: 'AIリスク管理', labelVi: 'Quản lý rủi ro AI', labelEn: 'AI Risk Management', category: 'business', level: 'topic', importance: 'high', summaryVi: 'Xác định và kiểm soát rủi ro như sai thông tin, rò rỉ dữ liệu, bias, pháp lý, an toàn vận hành.', summaryJa: '誤情報、情報漏えい、バイアス、法務、運用安全などのリスクを管理します。', examPointVi: 'Luôn gắn AI với kiểm chứng, log, review, quyền truy cập và policy.', examPointJa: '検証、ログ、レビュー、アクセス制御、方針とセットで考えます。', keywords: ['リスク', '監視', 'レビュー'] }),
  node({ id: 'roi-ai', labelJa: '費用対効果', labelVi: 'Hiệu quả đầu tư AI', labelEn: 'AI ROI', category: 'business', level: 'topic', importance: 'medium', summaryVi: 'Đánh giá AI có tạo giá trị so với chi phí triển khai, vận hành, dữ liệu và rủi ro không.', summaryJa: 'AI導入のコストに対して、どれだけ効果や価値があるかを評価します。', examPointVi: 'AI không phải lúc nào cũng nên dùng; phải xét mục tiêu và hiệu quả.', examPointJa: 'AIを使えばよいとは限らず、目的と効果を確認します。', keywords: ['ROI', '効果測定', 'コスト'] }),
];

const edge = (item: KnowledgeEdgeData) => item;

export const aiPassportEdges: KnowledgeEdgeData[] = [
  edge({ id: 'ai-passport-ai-basics', source: 'ai-passport', target: 'ai-basics', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ai-passport-data-ml', source: 'ai-passport', target: 'data-ml', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ai-passport-generative-ai', source: 'ai-passport', target: 'generative-ai', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ai-passport-ethics', source: 'ai-passport', target: 'ai-ethics-law', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ai-passport-business', source: 'ai-passport', target: 'business-ai', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'basics-ai-def', source: 'ai-basics', target: 'ai-definition', relation: 'belongs_to', labelVi: 'khái niệm', labelJa: '概念' }),
  edge({ id: 'ai-def-ml', source: 'ai-definition', target: 'machine-learning-ai', relation: 'belongs_to', labelVi: 'bao gồm', labelJa: '含む' }),
  edge({ id: 'ml-dl', source: 'machine-learning-ai', target: 'deep-learning-ai', relation: 'belongs_to', labelVi: 'bao gồm', labelJa: '含む' }),
  edge({ id: 'ml-supervised', source: 'machine-learning-ai', target: 'supervised-ai', relation: 'belongs_to', labelVi: 'loại', labelJa: '種類' }),
  edge({ id: 'ml-unsupervised', source: 'machine-learning-ai', target: 'unsupervised-ai', relation: 'belongs_to', labelVi: 'loại', labelJa: '種類' }),
  edge({ id: 'ml-reinforcement', source: 'machine-learning-ai', target: 'reinforcement-learning', relation: 'belongs_to', labelVi: 'loại', labelJa: '種類' }),
  edge({ id: 'supervised-linear', source: 'supervised-ai', target: 'linear-regression-ai', relation: 'example_of', labelVi: 'ví dụ', labelJa: '例' }),
  edge({ id: 'supervised-logistic', source: 'supervised-ai', target: 'logistic-regression-ai', relation: 'example_of', labelVi: 'ví dụ', labelJa: '例' }),
  edge({ id: 'supervised-tree', source: 'supervised-ai', target: 'decision-tree-ai', relation: 'example_of', labelVi: 'ví dụ', labelJa: '例' }),
  edge({ id: 'supervised-svm', source: 'supervised-ai', target: 'svm-ai', relation: 'example_of', labelVi: 'ví dụ', labelJa: '例' }),
  edge({ id: 'dl-nn', source: 'deep-learning-ai', target: 'neural-network-ai', relation: 'requires', labelVi: 'dựa trên', labelJa: '基盤' }),
  edge({ id: 'dl-cnn', source: 'deep-learning-ai', target: 'cnn-ai', relation: 'example_of', labelVi: 'mô hình', labelJa: 'モデル' }),
  edge({ id: 'dl-rnn', source: 'deep-learning-ai', target: 'rnn-ai', relation: 'example_of', labelVi: 'mô hình', labelJa: 'モデル' }),
  edge({ id: 'dl-transformer', source: 'deep-learning-ai', target: 'transformer-ai', relation: 'example_of', labelVi: 'mô hình', labelJa: 'モデル' }),
  edge({ id: 'data-quality-pre', source: 'data-ml', target: 'data-quality', relation: 'requires', labelVi: 'cần', labelJa: '必要' }),
  edge({ id: 'data-preprocess', source: 'data-ml', target: 'data-preprocessing-ai', relation: 'requires', labelVi: 'cần', labelJa: '必要' }),
  edge({ id: 'data-split', source: 'data-ml', target: 'training-test-data', relation: 'requires', labelVi: 'cần', labelJa: '必要' }),
  edge({ id: 'data-overfit', source: 'training-test-data', target: 'overfitting-ai', relation: 'related_to', labelVi: 'liên quan', labelJa: '関連' }),
  edge({ id: 'data-eval', source: 'data-ml', target: 'evaluation-ai', relation: 'requires', labelVi: 'đánh giá', labelJa: '評価' }),
  edge({ id: 'overfit-biasvariance', source: 'overfitting-ai', target: 'bias-variance', relation: 'related_to', labelVi: 'liên quan', labelJa: '関連' }),
  edge({ id: 'gen-llm', source: 'generative-ai', target: 'llm', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'gen-prompt', source: 'generative-ai', target: 'prompt-engineering', relation: 'used_in', labelVi: 'dùng', labelJa: '使う' }),
  edge({ id: 'gen-hallucination', source: 'generative-ai', target: 'hallucination', relation: 'related_to', labelVi: 'rủi ro', labelJa: 'リスク' }),
  edge({ id: 'gen-deepfake', source: 'generative-ai', target: 'deepfake-ai', relation: 'related_to', labelVi: 'rủi ro', labelJa: 'リスク' }),
  edge({ id: 'gen-rag', source: 'llm', target: 'rag', relation: 'used_in', labelVi: 'giảm sai', labelJa: '低減' }),
  edge({ id: 'gen-multimodal', source: 'generative-ai', target: 'multimodal-ai', relation: 'related_to', labelVi: 'liên quan', labelJa: '関連' }),
  edge({ id: 'ethics-personal-info', source: 'ai-ethics-law', target: 'personal-information-ai', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ethics-copyright', source: 'ai-ethics-law', target: 'copyright-ai', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ethics-bias', source: 'ai-ethics-law', target: 'bias-fairness', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ethics-xai', source: 'ai-ethics-law', target: 'explainable-ai', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'ethics-hitl', source: 'ai-ethics-law', target: 'human-in-the-loop', relation: 'used_in', labelVi: 'kiểm soát', labelJa: '管理' }),
  edge({ id: 'ethics-governance', source: 'ai-ethics-law', target: 'ai-governance', relation: 'used_in', labelVi: 'quản trị', labelJa: 'ガバナンス' }),
  edge({ id: 'business-usecase', source: 'business-ai', target: 'ai-usecase', relation: 'belongs_to', labelVi: 'gồm', labelJa: '含む' }),
  edge({ id: 'business-flow', source: 'business-ai', target: 'ai-project-flow', relation: 'requires', labelVi: 'quy trình', labelJa: '流れ' }),
  edge({ id: 'business-risk', source: 'business-ai', target: 'ai-risk-management', relation: 'requires', labelVi: 'rủi ro', labelJa: 'リスク' }),
  edge({ id: 'business-roi', source: 'business-ai', target: 'roi-ai', relation: 'requires', labelVi: 'đánh giá', labelJa: '評価' }),
];
