import type { LessonContent } from '../../features/knowledge-graph/data/lessonContent';

const lesson = (item: LessonContent) => item;

export const aiPassportLessons: LessonContent[] = [
  lesson({ nodeId: 'ai-passport', shortDefinitionVi: 'AI Passport kiểm tra khả năng hiểu AI ở mức nền tảng: khái niệm, dữ liệu, mô hình, generative AI, rủi ro và ứng dụng.', shortDefinitionJa: 'AIパスポートは、AIの基礎概念、データ、モデル、生成AI、リスク、活用を確認する試験です。', whyImportantVi: 'Đây là bản đồ gốc. Nếu nắm được cấu trúc 5 nhóm lớn, bạn sẽ học các thuật ngữ AI ít bị rối.', whyImportantJa: '全体の入口です。5つの大分類を押さえると、AI用語を整理して学習できます。', examPatternsVi: ['Hỏi AI/ML/DL khác nhau thế nào.', 'Hỏi rủi ro khi dùng generative AI.', 'Hỏi dữ liệu và tiền xử lý trong dự án ML.', 'Hỏi AI dùng cho nghiệp vụ nào phù hợp.'], examPatternsJa: ['AI・機械学習・深層学習の関係。', '生成AI利用時のリスク。', '機械学習におけるデータと前処理。', '業務に適したAI活用。'], commonMistakesVi: ['Chỉ học thuật toán mà bỏ qua đạo đức/pháp luật.', 'Nhầm generative AI với toàn bộ AI.', 'Nghĩ AI output luôn đúng.'], commonMistakesJa: ['アルゴリズムだけ学び、倫理・法務を軽視する。', '生成AIをAI全体と混同する。', 'AI出力を常に正しいと思う。'], memoryTipVi: 'AI Passport = AI basics + Data/ML + Generative AI + Ethics/Law + Business.', memoryTipJa: 'AIパスポート = AI基礎 + データ/ML + 生成AI + 倫理/法務 + ビジネス。' }),
  lesson({ nodeId: 'machine-learning-ai', shortDefinitionVi: 'Machine Learning là cách để máy học quy luật từ dữ liệu thay vì con người viết từng luật bằng tay.', shortDefinitionJa: '機械学習は、人がルールをすべて書くのではなく、データから規則性を学ぶ方法です。', whyImportantVi: 'Nhiều câu thi hỏi các loại học máy, dữ liệu có nhãn/không nhãn, và cách đánh giá model.', whyImportantJa: '教師あり・教師なし・強化学習、ラベルの有無、評価方法がよく問われます。', examPatternsVi: ['教師あり = có đáp án/nhãn.', '教師なし = không có nhãn, tìm nhóm.', '強化学習 = agent học bằng reward.'], examPatternsJa: ['教師あり = 正解ラベルあり。', '教師なし = ラベルなしで構造を見つける。', '強化学習 = 報酬で学習。'], commonMistakesVi: ['Nhầm classification với clustering.', 'Dùng test data để train.', 'Bỏ qua tiền xử lý dữ liệu.'], commonMistakesJa: ['分類とクラスタリングを混同する。', 'テストデータを学習に使う。', '前処理を軽視する。'], memoryTipVi: 'ML học theo câu: dữ liệu gì → nhãn có không → học gì → đánh giá ra sao.', memoryTipJa: 'MLは「データ → ラベル有無 → 学習内容 → 評価」で覚えます。' }),
  lesson({ nodeId: 'data-preprocessing-ai', shortDefinitionVi: 'Tiền xử lý là bước làm sạch và chuẩn bị dữ liệu trước khi đưa vào mô hình.', shortDefinitionJa: '前処理は、モデルに入力する前にデータを整える作業です。', whyImportantVi: 'Trong thực tế, phần lớn thời gian ML dùng để xử lý dữ liệu. Đề thi hay hỏi dữ liệu thiếu, chuẩn hóa, dữ liệu lệch.', whyImportantJa: '実務では前処理に多くの時間がかかります。欠損値、正規化、偏りが問われます。', examPatternsVi: ['欠損値処理 = xử lý dữ liệu thiếu.', '正規化 = đưa thang đo về chuẩn.', '外れ値 = giá trị bất thường.'], examPatternsJa: ['欠損値処理。', '正規化。', '外れ値対応。'], commonMistakesVi: ['Nghĩ chỉ cần model tốt là đủ.', 'Không kiểm tra dữ liệu đầu vào.', 'Nhầm preprocessing với evaluation.'], commonMistakesJa: ['モデルだけ良ければよいと思う。', '入力データを確認しない。', '前処理と評価を混同する。'], memoryTipVi: 'Garbage in, garbage out: dữ liệu bẩn → AI sai.', memoryTipJa: 'Garbage in, garbage out：悪いデータなら悪い結果。' }),
  lesson({ nodeId: 'generative-ai', shortDefinitionVi: 'Generative AI là AI tạo nội dung mới như văn bản, ảnh, âm thanh, video hoặc code.', shortDefinitionJa: '生成AIは、文章、画像、音声、動画、コードなど新しいコンテンツを生成するAIです。', whyImportantVi: 'Đây là phần rất thời sự. Đề hay hỏi LLM, prompt, hallucination, deepfake, copyright và sử dụng an toàn.', whyImportantJa: 'LLM、プロンプト、ハルシネーション、ディープフェイク、著作権、安全な利用が頻出です。', examPatternsVi: ['Prompt tốt cần mục tiêu và điều kiện rõ.', 'AI có thể hallucinate.', 'Output cần kiểm chứng và chú ý bản quyền.'], examPatternsJa: ['良いプロンプトは目的と条件が明確。', 'AIはハルシネーションを起こす。', '出力は検証し、著作権に注意する。'], commonMistakesVi: ['Tin toàn bộ câu trả lời AI.', 'Nhập thông tin cá nhân/công ty vào AI công cộng.', 'Dùng ảnh/nhạc AI tạo mà không kiểm tra quyền.'], commonMistakesJa: ['AI回答を全て信じる。', '個人情報や機密情報を入力する。', '権利確認せず生成物を使う。'], memoryTipVi: 'Generative AI mạnh nhưng cần 3 bước: chỉ dẫn rõ → kiểm chứng → quản lý rủi ro.', memoryTipJa: '生成AIは「明確な指示 → 検証 → リスク管理」で使います。' }),
  lesson({ nodeId: 'hallucination', shortDefinitionVi: 'Hallucination là khi AI tạo thông tin nghe hợp lý nhưng sai hoặc không có căn cứ.', shortDefinitionJa: 'ハルシネーションは、AIがもっともらしいが誤った情報を生成する現象です。', whyImportantVi: 'Đề thường hỏi cách giảm rủi ro: kiểm chứng nguồn, human review, RAG hoặc giới hạn phạm vi sử dụng.', whyImportantJa: '出典確認、人間の確認、RAG、利用範囲の制限が対策として問われます。', examPatternsVi: ['Không dùng AI output làm bằng chứng duy nhất.', 'Cần kiểm chứng nguồn.', 'Có thể dùng RAG để tham khảo tài liệu nội bộ.'], examPatternsJa: ['AI出力だけを根拠にしない。', '出典確認を行う。', 'RAGで外部情報を参照する。'], commonMistakesVi: ['Nhầm hallucination với bias.', 'Nghĩ model mới thì không hallucinate.', 'Không yêu cầu nguồn.'], commonMistakesJa: ['ハルシネーションとバイアスを混同する。', '新しいモデルなら誤りがないと思う。', '根拠を確認しない。'], memoryTipVi: 'Hallucination = “nghe rất thật nhưng phải kiểm tra”.', memoryTipJa: 'ハルシネーション = 「本当らしいが確認が必要」。' }),
  lesson({ nodeId: 'ai-ethics-law', shortDefinitionVi: 'Đạo đức và pháp luật AI là các nguyên tắc để AI được dùng công bằng, an toàn, minh bạch và có trách nhiệm.', shortDefinitionJa: 'AI倫理・法務は、AIを公平・安全・透明・責任ある形で使うための考え方です。', whyImportantVi: 'AI Passport không chỉ hỏi kỹ thuật mà còn hỏi trách nhiệm xã hội, dữ liệu cá nhân, bản quyền và bias.', whyImportantJa: 'AIパスポートでは技術だけでなく、社会的責任、個人情報、著作権、バイアスも問われます。', examPatternsVi: ['個人情報 không nhập bừa vào AI.', 'Bias gây kết quả không công bằng.', 'Copyright cần kiểm tra dữ liệu học và output.', 'Human review quan trọng ở lĩnh vực rủi ro cao.'], examPatternsJa: ['個人情報を安易に入力しない。', 'バイアスは不公平な結果につながる。', '著作権に注意する。', '高リスク領域では人間の確認が重要。'], commonMistakesVi: ['Chỉ xem AI là công cụ tiện lợi.', 'Bỏ qua quyền riêng tư.', 'Không xác định ai chịu trách nhiệm khi AI sai.'], commonMistakesJa: ['AIを便利ツールとしてだけ見る。', 'プライバシーを軽視する。', 'AIが誤った場合の責任を考えない。'], memoryTipVi: 'AI an toàn = dữ liệu đúng + mục đích rõ + con người kiểm tra + trách nhiệm rõ.', memoryTipJa: '安全なAI = 良いデータ + 明確な目的 + 人間確認 + 責任明確。' }),
  lesson({ nodeId: 'ai-project-flow', shortDefinitionVi: 'Dự án AI bắt đầu từ vấn đề kinh doanh, sau đó mới đến dữ liệu, model, đánh giá, triển khai và giám sát.', shortDefinitionJa: 'AIプロジェクトは課題設定から始まり、データ、モデル、評価、導入、監視へ進みます。', whyImportantVi: 'Đề hay hỏi thứ tự đúng và việc không nên làm: bắt đầu bằng model khi chưa có mục tiêu/dữ liệu.', whyImportantJa: '正しい順序や、目的・データなしにモデル作成から始めないことが問われます。', examPatternsVi: ['Xác định mục tiêu trước.', 'Kiểm tra dữ liệu có đủ/đúng không.', 'Đánh giá model bằng test data.', 'Triển khai xong vẫn cần monitoring.'], examPatternsJa: ['目的を先に決める。', 'データの量・質を確認する。', 'テストデータで評価する。', '導入後も監視する。'], commonMistakesVi: ['Nhảy thẳng vào thuật toán.', 'Không đo hiệu quả sau triển khai.', 'Không chuẩn bị vận hành/risk.'], commonMistakesJa: ['いきなりアルゴリズムを選ぶ。', '導入後の効果測定をしない。', '運用やリスクを考えない。'], memoryTipVi: 'AI project = Problem → Data → Model → Evaluate → Deploy → Monitor.', memoryTipJa: 'AIプロジェクト = 課題 → データ → モデル → 評価 → 導入 → 監視。' }),
];

export const getAiLessonContent = (nodeId: string): LessonContent | undefined => aiPassportLessons.find((lesson) => lesson.nodeId === nodeId);
