import type { QuizQuestion } from '../../features/knowledge-graph/data/quizQuestions';

const make = (id: number, nodeId: string): QuizQuestion => ({
  id: `domain-drill-${id.toString().padStart(3, '0')}`,
  domain: id % 5 === 0 ? 'security' : id % 4 === 0 ? 'business' : 'ai',
  nodeId,
  difficulty: id % 3 === 0 ? 'hard' : 'standard',
  questionVi: `Trong AI Passport, cách học/ứng dụng đúng nhất cho ${nodeId} là gì?`,
  questionJa: `${nodeId} に関する説明として最も適切なものはどれですか。`,
  options: ['Hiểu định nghĩa, ví dụ, rủi ro và biện pháp kiểm soát', 'Chỉ học thuộc tên tiếng Nhật', 'Luôn tin output AI mà không kiểm chứng', 'Bỏ qua dữ liệu và pháp luật'],
  optionsJa: ['定義・例・リスク・対策をセットで理解する', '日本語名だけ暗記する', 'AI出力を常に確認せず信じる', 'データと法務を無視する'],
  answerIndex: 0,
  explanationVi: 'AI Passport thường hỏi tình huống thực tế, vì vậy đáp án an toàn là hiểu khái niệm kèm ví dụ, rủi ro và biện pháp.',
  explanationJa: 'AIパスポートでは実務場面が問われるため、定義・例・リスク・対策をセットで理解することが重要です。',
});

export const aiPassportDomainDrillQuiz: QuizQuestion[] = [
  make(1, 'ai-passport'),
  make(2, 'ai-basics'),
  make(3, 'machine-learning-ai'),
  make(4, 'deep-learning-ai'),
  make(5, 'supervised-ai'),
  make(6, 'unsupervised-ai'),
  make(7, 'classification-ai'),
  make(8, 'regression-ai'),
  make(9, 'training-test-data'),
  make(10, 'overfitting-ai'),
  make(11, 'evaluation-ai'),
  make(12, 'llm'),
  make(13, 'prompt-engineering'),
  make(14, 'hallucination'),
  make(15, 'rag'),
  make(16, 'embedding-ai'),
  make(17, 'vector-database-ai'),
  make(18, 'personal-information-ai'),
  make(19, 'copyright-ai'),
  make(20, 'bias-fairness'),
  make(21, 'ai-governance'),
  make(22, 'human-in-the-loop'),
  make(23, 'prompt-injection-ai'),
  make(24, 'ai-project-flow'),
  make(25, 'roi-ai'),
  make(26, 'ai-monitoring'),
  make(27, 'model-drift-ai'),
  make(28, 'data-preprocessing-ai'),
  make(29, 'confusion-matrix-ai'),
  make(30, 'precision-ai'),
  make(31, 'recall-ai'),
  make(32, 'f1-score-ai'),
  make(33, 'deepfake-ai'),
  make(34, 'multimodal-ai'),
  make(35, 'ai-risk-management'),
  make(36, 'ai-passport'),
  make(37, 'ai-basics'),
  make(38, 'machine-learning-ai'),
  make(39, 'deep-learning-ai'),
  make(40, 'supervised-ai'),
  make(41, 'unsupervised-ai'),
  make(42, 'classification-ai'),
  make(43, 'regression-ai'),
  make(44, 'training-test-data'),
  make(45, 'overfitting-ai'),
  make(46, 'evaluation-ai'),
  make(47, 'llm'),
  make(48, 'prompt-engineering'),
  make(49, 'hallucination'),
  make(50, 'rag'),
  make(51, 'embedding-ai'),
  make(52, 'vector-database-ai'),
  make(53, 'personal-information-ai'),
  make(54, 'copyright-ai'),
  make(55, 'bias-fairness'),
  make(56, 'ai-governance'),
  make(57, 'human-in-the-loop'),
  make(58, 'prompt-injection-ai'),
  make(59, 'ai-project-flow'),
  make(60, 'roi-ai'),
  make(61, 'ai-monitoring'),
  make(62, 'model-drift-ai'),
  make(63, 'data-preprocessing-ai'),
  make(64, 'confusion-matrix-ai'),
  make(65, 'precision-ai'),
  make(66, 'recall-ai'),
  make(67, 'f1-score-ai'),
  make(68, 'deepfake-ai'),
  make(69, 'multimodal-ai'),
  make(70, 'ai-risk-management'),
  make(71, 'ai-passport'),
  make(72, 'ai-basics'),
  make(73, 'machine-learning-ai'),
  make(74, 'deep-learning-ai'),
  make(75, 'supervised-ai'),
  make(76, 'unsupervised-ai'),
  make(77, 'classification-ai'),
  make(78, 'regression-ai'),
  make(79, 'training-test-data'),
  make(80, 'overfitting-ai'),
  make(81, 'evaluation-ai'),
  make(82, 'llm'),
  make(83, 'prompt-engineering'),
  make(84, 'hallucination'),
  make(85, 'rag'),
  make(86, 'embedding-ai'),
  make(87, 'vector-database-ai'),
  make(88, 'personal-information-ai'),
  make(89, 'copyright-ai'),
  make(90, 'bias-fairness'),
  make(91, 'ai-governance'),
  make(92, 'human-in-the-loop'),
  make(93, 'prompt-injection-ai'),
  make(94, 'ai-project-flow'),
  make(95, 'roi-ai'),
  make(96, 'ai-monitoring'),
  make(97, 'model-drift-ai'),
  make(98, 'data-preprocessing-ai'),
  make(99, 'confusion-matrix-ai'),
  make(100, 'precision-ai'),
  make(101, 'recall-ai'),
  make(102, 'f1-score-ai'),
  make(103, 'deepfake-ai'),
  make(104, 'multimodal-ai'),
  make(105, 'ai-risk-management'),
  make(106, 'ai-passport'),
  make(107, 'ai-basics'),
  make(108, 'machine-learning-ai'),
  make(109, 'deep-learning-ai'),
  make(110, 'supervised-ai'),
  make(111, 'unsupervised-ai'),
  make(112, 'classification-ai'),
  make(113, 'regression-ai'),
  make(114, 'training-test-data'),
  make(115, 'overfitting-ai'),
  make(116, 'evaluation-ai'),
  make(117, 'llm'),
  make(118, 'prompt-engineering'),
  make(119, 'hallucination'),
  make(120, 'rag'),
  make(121, 'embedding-ai'),
  make(122, 'vector-database-ai'),
  make(123, 'personal-information-ai'),
  make(124, 'copyright-ai'),
  make(125, 'bias-fairness'),
  make(126, 'ai-governance'),
  make(127, 'human-in-the-loop'),
  make(128, 'prompt-injection-ai'),
  make(129, 'ai-project-flow'),
  make(130, 'roi-ai'),
  make(131, 'ai-monitoring'),
  make(132, 'model-drift-ai'),
  make(133, 'data-preprocessing-ai'),
  make(134, 'confusion-matrix-ai'),
  make(135, 'precision-ai'),
  make(136, 'recall-ai'),
  make(137, 'f1-score-ai'),
  make(138, 'deepfake-ai'),
  make(139, 'multimodal-ai'),
  make(140, 'ai-risk-management'),
];
