import type { StudyPathPhase } from '../../features/knowledge-graph/data/studyPath';

export const aiPassportStudyPath: StudyPathPhase[] = [
  {
    id: 'ai-path-01-overview',
    titleVi: '1. Bức tranh tổng quan AI Passport',
    titleJa: '1. AIパスポート全体像',
    goalVi: 'Hiểu AI Passport gồm những mảng nào và nên học theo thứ tự nào.',
    goalJa: 'AIパスポートの全体構造と学習順序を理解します。',
    nodeIds: ['ai-passport', 'ai-basics', 'ai-definition', 'ai-literacy', 'data-ml', 'generative-ai', 'ai-ethics-law', 'business-ai'],
  },
  {
    id: 'ai-path-02-ml-foundation',
    titleVi: '2. Nền tảng Machine Learning',
    titleJa: '2. 機械学習の基礎',
    goalVi: 'Nắm AI/ML/DL, ba loại học máy, classification/regression và các model cơ bản.',
    goalJa: 'AI/ML/DL、学習方法、分類・回帰、代表モデルを理解します。',
    nodeIds: ['machine-learning-ai', 'deep-learning-ai', 'supervised-ai', 'unsupervised-ai', 'reinforcement-learning', 'classification-ai', 'regression-ai', 'linear-regression-ai', 'logistic-regression-ai', 'decision-tree-ai', 'svm-ai', 'clustering-ai'],
  },
  {
    id: 'ai-path-03-data',
    titleVi: '3. Dữ liệu và tiền xử lý',
    titleJa: '3. データと前処理',
    goalVi: 'Hiểu vì sao dữ liệu quyết định chất lượng AI: thu thập, làm sạch, chia train/test, feature.',
    goalJa: 'データの品質、収集、クレンジング、分割、特徴量を理解します。',
    nodeIds: ['data-quality', 'data-collection-ai', 'data-preprocessing-ai', 'data-cleaning-ai', 'missing-value-ai', 'outlier-ai', 'normalization-ai-data', 'standardization-ai', 'feature-engineering-ai', 'label-encoding-ai', 'one-hot-ai', 'training-test-data', 'data-split-ai', 'validation-data-ai', 'test-data-leakage-ai'],
  },
  {
    id: 'ai-path-04-evaluation',
    titleVi: '4. Đánh giá model và lỗi dễ gặp',
    titleJa: '4. モデル評価と落とし穴',
    goalVi: 'Biết chọn chỉ số đánh giá và nhận diện overfitting, data leakage, class imbalance.',
    goalJa: '評価指標、過学習、データリーク、クラス不均衡を理解します。',
    nodeIds: ['evaluation-ai', 'model-validation-ai', 'cross-validation-ai', 'overfitting-ai', 'bias-variance', 'confusion-matrix-ai', 'accuracy-ai-metric', 'precision-ai', 'recall-ai', 'f1-score-ai', 'auc-ai', 'mean-squared-error-ai', 'class-imbalance'],
  },
  {
    id: 'ai-path-05-deep-learning',
    titleVi: '5. Deep Learning và các kiến trúc quan trọng',
    titleJa: '5. 深層学習と重要アーキテクチャ',
    goalVi: 'Phân biệt Neural Network, CNN, RNN, Transformer và attention.',
    goalJa: 'ニューラルネット、CNN、RNN、Transformer、Attentionを区別します。',
    nodeIds: ['neural-network-ai', 'loss-function-ai', 'gradient-descent-ai', 'epoch-ai', 'batch-size-ai', 'cnn-ai', 'computer-vision', 'object-detection', 'image-classification', 'rnn-ai', 'time-series-ai', 'transformer-ai', 'attention-ai', 'self-attention'],
  },
  {
    id: 'ai-path-06-generative-ai',
    titleVi: '6. Generative AI / LLM / Prompt',
    titleJa: '6. 生成AI・LLM・プロンプト',
    goalVi: 'Học phần rất hay ra thi: LLM, token, prompt, hallucination, RAG, multimodal.',
    goalJa: 'LLM、トークン、プロンプト、ハルシネーション、RAG、マルチモーダルを学びます。',
    nodeIds: ['generative-ai', 'llm', 'foundation-model', 'pretrained-model', 'token-ai', 'context-window-ai', 'prompt-engineering', 'prompt-template-ai', 'system-prompt-ai', 'zero-shot-ai', 'few-shot-ai', 'chain-of-thought-ai', 'temperature-ai', 'hallucination', 'fact-check-ai', 'rag', 'retrieval-ai', 'embedding-ai', 'vector-database-ai', 'semantic-search-ai', 'multimodal-ai'],
  },
  {
    id: 'ai-path-07-nlp-cv-usecases',
    titleVi: '7. NLP / Computer Vision / ứng dụng',
    titleJa: '7. NLP・画像認識・活用例',
    goalVi: 'Nhận biết ví dụ ứng dụng AI trong ngôn ngữ, ảnh, âm thanh, dự báo và gợi ý.',
    goalJa: '言語、画像、音声、予測、推薦のAI活用例を理解します。',
    nodeIds: ['natural-language-processing', 'nlp-tokenization', 'morphological-analysis', 'sentiment-analysis', 'text-classification', 'ocr-ai', 'speech-recognition-ai', 'text-to-speech-ai', 'recommendation-system-ai', 'forecasting-ai', 'demand-forecasting-ai', 'anomaly-detection-ai', 'fraud-detection-ai', 'predictive-maintenance', 'chatbot-ai'],
  },
  {
    id: 'ai-path-08-ethics-law',
    titleVi: '8. Đạo đức, pháp luật, privacy, copyright',
    titleJa: '8. 倫理・法務・個人情報・著作権',
    goalVi: 'Học các rủi ro bắt buộc phải nhớ khi dùng AI trong công ty.',
    goalJa: '企業でAIを使うときの必須リスクを理解します。',
    nodeIds: ['ai-ethics-law', 'personal-information-ai', 'purpose-limitation-ai', 'consent-ai', 'data-minimization-ai', 'anonymization-ai', 'pseudonymization-ai', 'copyright-ai', 'copyright-training-data', 'copyright-output-ai', 'license-ai', 'trade-secret-ai', 'confidential-info-ai', 'bias-fairness', 'sampling-bias', 'ai-fairness-check', 'explainable-ai', 'ai-transparency', 'ai-explainability-report'],
  },
  {
    id: 'ai-path-09-risk-security',
    titleVi: '9. Rủi ro AI và bảo mật',
    titleJa: '9. AIリスクとセキュリティ',
    goalVi: 'Nắm hallucination, deepfake, prompt injection, rò rỉ thông tin và attack vào model.',
    goalJa: 'ハルシネーション、ディープフェイク、プロンプトインジェクション、情報漏えい、AI攻撃を学びます。',
    nodeIds: ['ai-risk-management', 'deepfake-ai', 'voice-cloning-ai', 'fake-news-ai', 'image-generation-risk', 'prompt-injection-ai', 'data-leakage-ai', 'ai-phishing-risk', 'ai-security-attack', 'adversarial-example', 'adversarial-attack-ai', 'poisoning-attack-ai', 'model-inversion-ai', 'membership-inference-ai', 'human-in-the-loop'],
  },
  {
    id: 'ai-path-10-business-operation',
    titleVi: '10. Business, governance, vận hành AI',
    titleJa: '10. ビジネス・ガバナンス・運用',
    goalVi: 'Biết cách triển khai AI có mục tiêu, KPI, PoC, vận hành, monitoring và ROI.',
    goalJa: '目的、KPI、PoC、運用、監視、ROIを含むAI導入を理解します。',
    nodeIds: ['ai-project-flow', 'ai-problem-framing', 'ai-requirement-definition', 'ai-feasibility-check', 'ai-kpi-design', 'ai-poC', 'ai-usecase', 'ai-service-design', 'business-ai', 'roi-ai', 'ai-cost-risk-ai', 'ai-governance', 'ai-guideline-company', 'ai-literacy-training', 'ai-vendor-management', 'ai-contract-ai', 'ai-quality-assurance', 'mlops-ai', 'ai-production-operation', 'ai-monitoring', 'model-drift-ai', 'data-drift-ai', 'concept-drift-ai', 'ai-retraining'],
  },
];
