import type { KnowledgeNodeData } from '../../features/knowledge-graph/types';
type Level = 'root' | 'major' | 'topic' | 'detail';
type Importance = 'high' | 'medium' | 'low';
const n = (id:string, vi:string, en:string, level:Level, importance:Importance='high', prerequisites:string[]=[]):KnowledgeNodeData => ({
  id, labelJa: vi, labelVi: vi, labelEn: en, category:'management', level, importance,
  summaryVi:`${vi}: kỹ năng BrSE quan trọng để kết nối khách hàng Nhật và team phát triển.`,
  summaryJa:`${vi} はBrSEに必要な重要スキルです。`,
  examPointVi:`Cần hiểu mục đích, output cần tạo, lỗi giao tiếp dễ xảy ra và cách phòng tránh.`,
  examPointJa:`目的、成果物、認識齟齬の防止方法を確認します。`,
  examples:[], keywords:[vi,en], prerequisites, related:[],
});

export const brseNodes = [
  n('brse','BrSE総論 / Tổng quan BrSE','Bridge System Engineer','root','high',[]),
  n('brse-role','BrSEの役割','BrSE Role','major','high',['brse']),
  n('communication','日越コミュニケーション','Communication','major','high',['brse']),
  n('japanese-business','ビジネス日本語','Business Japanese','topic','high',['communication']),
  n('keigo','敬語','Keigo','topic','medium',['japanese-business']),
  n('hou-ren-sou','報連相','HouRenSou','topic','high',['communication']),
  n('meeting','会議運営','Meeting Facilitation','topic','high',['communication']),
  n('agenda','アジェンダ','Meeting Agenda','detail','medium',['meeting']),
  n('minutes','議事録','Meeting Minutes','topic','high',['meeting']),
  n('decision-log','決定事項管理','Decision Log','topic','high',['minutes']),
  n('qa-management','Q&A管理','Q&A Management','topic','high',['communication']),
  n('stakeholder','ステークホルダー管理','Stakeholder Management','topic','medium',['communication']),
  n('conflict-resolution','認識齟齬対応','Conflict Resolution','topic','high',['communication']),
  n('customer-negotiation','顧客折衝','Customer Negotiation','topic','high',['stakeholder']),
  n('escalation','エスカレーション','Escalation','topic','medium',['conflict-resolution']),
  n('requirement-definition','要件定義','Requirement Definition','major','high',['brse']),
  n('requirement-analysis','要求分析','Requirement Analysis','topic','high',['requirement-definition']),
  n('business-flow','業務フロー','Business Flow','topic','high',['requirement-definition']),
  n('current-flow','現行フロー','Current Flow','detail','medium',['business-flow']),
  n('to-be-flow','To-Beフロー','To-Be Flow','detail','medium',['business-flow']),
  n('use-case','ユースケース','Use Case','topic','medium',['requirement-definition']),
  n('user-story','ユーザーストーリー','User Story','topic','medium',['requirement-definition']),
  n('acceptance-criteria','受入基準','Acceptance Criteria','topic','high',['requirement-definition']),
  n('scope-management','スコープ管理','Scope Management','topic','high',['requirement-definition']),
  n('out-of-scope','スコープ外','Out of Scope','detail','medium',['scope-management']),
  n('non-functional-requirement','非機能要件','Non-functional Requirement','topic','high',['requirement-definition']),
  n('performance-requirement','性能要件','Performance Requirement','detail','medium',['non-functional-requirement']),
  n('security-requirement','セキュリティ要件','Security Requirement','detail','medium',['non-functional-requirement']),
  n('availability-requirement','可用性要件','Availability Requirement','detail','medium',['non-functional-requirement']),
  n('spec-reading','仕様書読解','Specification Reading','topic','high',['requirement-definition']),
  n('requirement-review','要件レビュー','Requirement Review','topic','high',['requirement-definition']),
  n('basic-design','基本設計','Basic Design','major','high',['requirement-definition']),
  n('screen-design','画面設計','Screen Design','topic','high',['basic-design']),
  n('screen-item-definition','画面項目定義','Screen Item Definition','topic','high',['screen-design']),
  n('screen-transition','画面遷移','Screen Transition','topic','high',['screen-design']),
  n('ui-rule','UIルール','UI Rule','detail','medium',['screen-design']),
  n('api-design','API設計','API Design','topic','high',['basic-design']),
  n('api-spec','API仕様書','API Specification','topic','high',['api-design']),
  n('request-response','リクエスト/レスポンス','Request Response','detail','medium',['api-design']),
  n('error-code','エラーコード','Error Code','detail','medium',['api-design']),
  n('db-design','DB設計','DB Design','topic','medium',['basic-design']),
  n('db-item-definition','DB項目定義','DB Item Definition','topic','high',['db-design']),
  n('erd-brse','ER図','ER Diagram','topic','medium',['db-design']),
  n('external-interface','外部IF','External Interface','topic','medium',['basic-design']),
  n('batch-design','バッチ設計','Batch Design','topic','medium',['basic-design']),
  n('detailed-design','詳細設計','Detailed Design','major','high',['basic-design']),
  n('sequence-diagram','シーケンス図','Sequence Diagram','topic','medium',['detailed-design']),
  n('state-diagram','状態遷移図','State Transition','topic','medium',['detailed-design']),
  n('processing-detail','処理詳細','Processing Detail','topic','high',['detailed-design']),
  n('exception-handling-design','例外処理設計','Exception Handling Design','topic','medium',['detailed-design']),
  n('review','レビュー','Review','major','high',['basic-design']),
  n('review-perspective','レビュー観点','Review Perspective','topic','high',['review']),
  n('design-review','設計レビュー','Design Review','topic','high',['review']),
  n('code-review','コードレビュー','Code Review','topic','medium',['review']),
  n('review-comment','レビュー指摘','Review Comment','topic','medium',['review']),
  n('implementation-support','実装サポート','Implementation Support','major','medium',['detailed-design']),
  n('developer-question','開発者質問対応','Developer Q&A','topic','high',['implementation-support']),
  n('test-planning','テスト計画','Test Planning','major','high',['basic-design']),
  n('test-design','テスト設計','Test Design','topic','high',['test-planning']),
  n('test-case','テストケース','Test Case','topic','high',['test-design']),
  n('unit-test-brse','単体テスト','Unit Test','topic','medium',['test-planning']),
  n('integration-test','結合テスト','Integration Test','topic','medium',['test-planning']),
  n('system-test','総合テスト','System Test','topic','medium',['test-planning']),
  n('uat','受入テスト','UAT','topic','high',['test-planning']),
  n('test-evidence','テストエビデンス','Test Evidence','topic','high',['test-case']),
  n('defect-management','不具合管理','Defect Management','major','high',['test-planning']),
  n('bug-report','不具合報告','Bug Report','topic','high',['defect-management']),
  n('reproduction-steps','再現手順','Reproduction Steps','detail','high',['bug-report']),
  n('expected-actual','期待結果/実際結果','Expected vs Actual','detail','high',['bug-report']),
  n('severity-priority','重要度/優先度','Severity Priority','topic','medium',['defect-management']),
  n('root-cause','原因分析','Root Cause Analysis','topic','medium',['defect-management']),
  n('change-request','仕様変更','Change Request','major','high',['scope-management']),
  n('change-request-sheet','仕様変更依頼書','Change Request Sheet','topic','medium',['change-request']),
  n('impact-analysis','影響調査','Impact Analysis','topic','high',['change-request']),
  n('estimation','見積もり','Estimation','topic','high',['impact-analysis']),
  n('approval-flow','承認フロー','Approval Flow','topic','medium',['change-request']),
  n('schedule-management','進捗管理','Schedule Management','major','high',['brse']),
  n('wbs','WBS','WBS','topic','medium',['schedule-management']),
  n('milestone','マイルストーン','Milestone','topic','medium',['schedule-management']),
  n('risk-management-brse','リスク管理','Risk Management','topic','high',['schedule-management']),
  n('issue-management','課題管理','Issue Management','topic','high',['schedule-management']),
  n('status-report','進捗報告','Status Report','topic','high',['schedule-management']),
  n('delay-report','遅延報告','Delay Report','topic','high',['status-report']),
  n('release-management','リリース管理','Release Management','topic','medium',['schedule-management']),
  n('release-judgement','リリース判定','Release Judgement','topic','high',['release-management']),
  n('rollback-plan','切り戻し計画','Rollback Plan','topic','medium',['release-management']),
  n('operation-handover','運用引き継ぎ','Operation Handover','topic','medium',['release-management']),
  n('offshore-dev','オフショア開発','Offshore Development','major','high',['brse']),
  n('handover','引き継ぎ','Handover','topic','medium',['offshore-dev']),
  n('translation-quality','翻訳品質','Translation Quality','topic','high',['communication']),
  n('ambiguity-control','曖昧表現の制御','Ambiguity Control','topic','high',['communication']),
  n('backlog-management','バックログ管理','Backlog Management','topic','medium',['schedule-management']),
  n('ticket-writing','チケット作成','Ticket Writing','topic','high',['backlog-management']),
  n('definition-of-done','完了条件','Definition of Done','topic','high',['acceptance-criteria']),
  n('production-incident','本番障害対応','Production Incident','topic','high',['release-management']),
  n('incident-report','障害報告書','Incident Report','topic','high',['production-incident']),
  n('postmortem','再発防止策','Postmortem','topic','medium',['incident-report']),
];
