import type { StudyPathPhase } from '../../features/knowledge-graph/data/studyPath';

export const brseStudyPath: StudyPathPhase[] = [
  { id:'brse-path-1', titleVi:'BrSE nền tảng', titleJa:'BrSE Basic', goalVi:'Vai trò, giao tiếp, tiếng Nhật business.', goalJa:'Vai trò, giao tiếp, tiếng Nhật business.', nodeIds:['brse','brse-role','communication','japanese-business','keigo','hou-ren-sou','meeting','agenda','minutes','decision-log','qa-management','stakeholder','conflict-resolution','customer-negotiation','escalation','translation-quality','ambiguity-control'] },
  { id:'brse-path-2', titleVi:'Requirement', titleJa:'Requirement', goalVi:'要件定義, 業務フロー, scope, 非機能要件.', goalJa:'要件定義, 業務フロー, scope, 非機能要件.', nodeIds:['requirement-definition','requirement-analysis','business-flow','current-flow','to-be-flow','use-case','user-story','acceptance-criteria','definition-of-done','scope-management','out-of-scope','non-functional-requirement','performance-requirement','security-requirement','availability-requirement','spec-reading','requirement-review'] },
  { id:'brse-path-3', titleVi:'Basic Design', titleJa:'Basic Design', goalVi:'基本設計, 画面, API, DB, 外部IF.', goalJa:'基本設計, 画面, API, DB, 外部IF.', nodeIds:['basic-design','screen-design','screen-item-definition','screen-transition','ui-rule','api-design','api-spec','request-response','error-code','db-design','db-item-definition','erd-brse','external-interface','batch-design'] },
  { id:'brse-path-4', titleVi:'Detailed Design / Review', titleJa:'Detailed Design and Review', goalVi:'詳細設計, diagrams, review, implementation support.', goalJa:'詳細設計, diagrams, review, implementation support.', nodeIds:['detailed-design','sequence-diagram','state-diagram','processing-detail','exception-handling-design','review','review-perspective','design-review','code-review','review-comment','implementation-support','developer-question'] },
  { id:'brse-path-5', titleVi:'Test / Defect', titleJa:'Test and Defect', goalVi:'Test plan, testcase, UAT, bug report, root cause.', goalJa:'Test plan, testcase, UAT, bug report, root cause.', nodeIds:['test-planning','test-design','test-case','unit-test-brse','integration-test','system-test','uat','test-evidence','defect-management','bug-report','reproduction-steps','expected-actual','severity-priority','root-cause'] },
  { id:'brse-path-6', titleVi:'Change / Estimation', titleJa:'Change and Estimation', goalVi:'仕様変更, impact, estimation, approval.', goalJa:'仕様変更, impact, estimation, approval.', nodeIds:['change-request','change-request-sheet','impact-analysis','estimation','approval-flow'] },
  { id:'brse-path-7', titleVi:'Project Management', titleJa:'Project Management', goalVi:'WBS, risk, issue, report, release.', goalJa:'WBS, risk, issue, report, release.', nodeIds:['schedule-management','wbs','milestone','risk-management-brse','issue-management','status-report','delay-report','backlog-management','ticket-writing','release-management','release-judgement','rollback-plan','operation-handover'] },
  { id:'brse-path-8', titleVi:'Offshore / Incident', titleJa:'Offshore and Incident', goalVi:'Offshore, handover, incident, postmortem.', goalJa:'Offshore, handover, incident, postmortem.', nodeIds:['offshore-dev','handover','production-incident','incident-report','postmortem'] },
];
